### ISSUE TITLE
Username dropdown unselectable on "submission" page

### ISSUE THREAD

**Issue by adamchainz** [pretalx/pretalx#1005]
## Current Behavior

On the submission page, when I hover over my name, I see the dropdown. But when I try move the mouse to it, it passes over a void area, closing the dropdown.

![cannae-select](https://user-images.githubusercontent.com/857609/92919449-6d6dc100-f428-11ea-9534-1761b99337f8.gif)

## Expected Behavior

I can move to the dropdown

## Your Environment

Djangocon EU 2020 site
Firefox 80
macOS

**Comment by rixx** [comment]
This is resolved (by moving to GitHub style dropdowns) in the current development version. The next release will probably come out in September, but I can't make more specific promises. FWIW, the links, in order, are

- https://cfp.2020.djangocon.eu/porto/me/submissions/
- https://cfp.2020.djangocon.eu/porto/me/mails/
- https://cfp.2020.djangocon.eu/porto/me/

**Comment by adamchainz** [comment]
Thanks. Forgot to say they were still working from the home page.
