### ISSUE TITLE
documentation: widget not showing

### ISSUE THREAD

**Issue by ligi** [pretalx/pretalx#1008]
## Current Behavior

on this site: https://docs.pretalx.org/user/event/widget.html
the widget is not showing - just a spinner

## Expected Behavior

widget should show

## Steps to Reproduce

1. open the site

## Context

on the console I see:

"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

seems this returns a 404 now: https://docs.pretalx.org/user/event/undefinedschedule/widget/v2.json

which seems the root cause of the problem

**Comment by rixx** [comment]
Fixed, thank you.
