### ISSUE TITLE
Talks once publicly visible stay visible

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#1011]
## Current Behavior

When you accept a talk and schedule it, there will be a public link. If you then change its state back to "submitted" the talk is still publicly visible under that URL.

## Expected Behavior

I'm not sure. I just wanted to report that issue in case someone has a good idea. The problem is that going back to "submitted" also has other implications. E.g. should it also be removed from the schedule?

## Steps to Reproduce

1. Change a talk to "confirmed"
2. Schedule that talk
3. Change the talk back to "submitted"

## Your Environment

* Version used: current `HEAD`
* Environment name and version (e.g. Chrome 39, python 3.5): Independent of Browser. Python 3.8.
* Operating System and version (desktop or mobile): Debian, Desktop.
* Link to your instance, if in production:

**Comment by rixx** [comment]
If you release a new schedule version, the talk will be removed. This is to make sure that schedule versions are as static as possible, and to make use of the versioning pretalx provides. This is especially relevant for users of the API and the exports, who assume that talks do not change within the same schedule version.

**Comment by vmx** [comment]
Thanks for the quick reply! I just tried it, it works. I think that workflow makes sense.
