### ISSUE TITLE
Track / "Space" Descriptions header reads "Session Format Descriptions"

### ISSUE THREAD

**Issue by marcwalsh** [pretalx/pretalx#1021]
## Current Behavior
When clicking the i button next to the drop-down to select a Track / Space in the CFP form the header of the popup reads "Session Format Descriptions"

![Screenshot 2020-10-21 at 13 55 55](https://user-images.githubusercontent.com/30226684/96722633-7fd30700-13a5-11eb-8fbc-ca686876bccc.png)

## Expected Behavior
The heading should read "Track / Space Descriptions" 

## Steps to Reproduce

1. Go https://www.pretalx.com/mozfest/cfp 
2. Start submitting a proposal
3. Click the i next to the dropdown for Spaces
4. See the error in the heading

**Comment by rixx** [comment]
That seems to be a bug specific to the en_Mozilla locale. I'll fix it shortly. Thank you for pointing it out!
