### ISSUE TITLE
500 server error when adding new review criteria

### ISSUE THREAD

**Issue by marcwalsh** [pretalx/pretalx#1026]
## Current Behavior
When adding a piece of review criteria into the MozFest 2021 sections I'm getting a 500 error.

## Expected Behavior
I am able to add a new piece of criteria to the review system

## Steps to Reproduce

1. Go to https://pretalx.com/orga/event/mozfest-2021/settings/review/
2. Add a new review criteria
3. Press Save
4. See 500 error

**Comment by rixx** [comment]
Closed in pretalx 2.0
