### ISSUE TITLE
Feature Request: Configure when feedback form is available

### ISSUE THREAD

**Issue by Kunsi** [pretalx/pretalx#1036]
## Problem you are facing
We used pretalx to collect feedback about our talks. We noted the feedback form is only available after a talk has ended according to the schedule. However (as usual) most of the talks were actually a bit shorter, but the feedback form was not yet available.

## Possible Solution
Provide an option to allow feedback while a talk is still running. Enabling Feedback after 50% of talk time would be enough for us.

**Comment by rixx** [comment]
I think we can just make all feedback forms available once the talk has started, without adding yet another setting. Thank you for the suggestion!
