### ISSUE TITLE
Password reset link missing from invitation page

### ISSUE THREAD

**Issue by omercnet** [pretalx/pretalx#1048]
## Current Behavior
Password reset link does not appear on team invitation page

## Expected Behavior
The invitation page should should RESET PASSWORD under the login portion

## Steps to Reproduce

1. Invite an existing user to team

## Context

When inviting a user to a team, if they already have a user but need a password reset they have no clear path to reset their own password

## Your Environment

* Version used: 2.1.1
* Environment name and version (e.g. Chrome 39, python 3.5): N/A
* Operating System and version (desktop or mobile): N/A
* Link to your instance, if in production: https://cfp.bsidestlv.com

![image](https://user-images.githubusercontent.com/639682/106394460-62cabd00-6405-11eb-9b70-8efe76b61494.png)

**Comment by rixx** [comment]
Password reset links currently exist within the scope of an event, while invites exist within the scope of an orgnizer. A fix would include adding a new password reset URL (not scoped to events), adjust the password reset page and its form, and then change the "common/auth.html" template. I'll happily accept pull requests.

**Comment by omercnet** [comment]
There’s already a generic reset url, why not just use that? That’s how I
solved it for now, directed users to /orga/reset

**Comment by rixx** [comment]
Ah, in that case the part about creating the view doesn't have to happen – the general authentication template will still have to know in which scope to show the reset URL, though, as it isn't only in use in the organiser area.

I suppose as a hotfix we can use the organiser reset link for now, as we don't have any cross-event pages for non-organisers. I'm pretty sure this decision will come back to bite us.
