### ISSUE TITLE
Make bug reporting URL a configurable setting

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#1054]
## Problem you are facing

Bug reports from self-hosted instanced get opened on the main pretalx issue tracker. In self-hosted instances problems are often configuration related (especially if it's a 500 error) and not really a bug in pretalx. Ideally those self-hosted instances have their own issue tracker/a place to report bugs, which can then be triaged there and once it is confirmed that it is an actual bug, it can be reported back to pretalx.

## Possible Solution

Add a setting in the settings file (not through the UI) to specify your own bug tracker.

If that's an OK solution I'm happy to work on that myself.

## Context

Bugs have been opened here and I feel bad as those are related to a self-hosted instance that likely has some configuration issue.

**Comment by rixx** [comment]
I'm starting to think that the bug tracker idea wasn't all that clever, to be honest, and I'm going to remove it again.

I thought about making the 500 page text configurable, but then you'd have to deal with translations in settings, and nobody wants that. I suppose the best solution would be a generic 500 page, and you can optionally add a link via the settings. If you want to work on that (aka if a custom link is worth the trouble for you), feel free to do so!

**Comment by vmx** [comment]
I think removing it from deployed versions makes sense. Ideally people then just contact conference organisers directly and they can then investigate in there own systems and do a proper bug report.
