### ISSUE TITLE
View tags in list view (the review talks list view)

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1059]
## Problem you are facing

You have to click through to a review to see tags

## Possible Solution

A line with the first x (3?) tags under the title would work, or an extra column. Sorting by tag would be super useful. 

## Context

We use tagging to group talks, but it is currently only a partial solution.

**Comment by rixx** [comment]
Tags have been shown in a (collapsible, as of today) extra column for a while now. Not terrible pretty, but we'll take it for now.
