### ISSUE TITLE
White image on transparent background becomes "all-white" in the preview

### ISSUE THREAD

**Issue by magamig** [pretalx/pretalx#1061]
## Problem you are facing

When I upload a white image with transparent background, the image becomes "all-white" in the preview.

## Possible Solution

Add a checkered grid background below the transparent images.

## Context

<img width="338" alt="Screenshot 2021-02-23 at 19 33 09" src="https://user-images.githubusercontent.com/8484196/108890516-f874f900-760d-11eb-9a63-9da685a8500b.png">

**Comment by ilmiddin17** [comment]
Can I contribute  this issue?
