### ISSUE TITLE
Create new organizer, when registrating on https://pretalx.com/p/try with existing mail-address 

### ISSUE THREAD

**Issue by saschafoerster** [pretalx/pretalx#1063]
As an agency we have lots of different official event organizers to handle. So it would be great to either be able to create new organizers in the backend to to use https://pretalx.com/p/try to create new organizers, when using an existing account. (this is the behavior of Pretix on the setup-page): https://pretix.eu/about/de/setup

**Comment by rixx** [comment]
Done.
