### ISSUE TITLE
Error on /foss4g-2021-academic/submit/f3Tpgw/profile/

### ISSUE THREAD

**Issue by tinko92** [pretalx/pretalx#1083]
## Current Behavior
I tried to save a submission and went through all steps, using a recently created account. In the final step I got an error 500. My profile shows no submissions. The abstract contains markdown, which renders as expected in the preview, and non-ascii characters (because authors with non-ascii-names are cited). No image was uploaded in any of the steps.

## Expected Behavior
I expect my submission to be saved and viewable in my profile.

## Steps to Reproduce
Everything was described in Current behavior.

## Context
I'm trying to save an abstract for submission.

## Your Environment
Arch Linux and Firefox 87 (result for Chrome 89 was the same)

**Comment by rixx** [comment]
Thank you for the report. I'll wait for Foss4G administrators to chime in with error logs, otherwise I won't be able to pin the error down.

**Comment by gvarela1981** [comment]
Hi @rixx Ihere is the error log for this particular issue.
I see a CSRF error after submit, some 5 minutes after 500-error but other only 1 minute after a previous 500 error, I think it's a very short time for session expires.

@tinko92 this is a very well detail issue report, thank you for that.
As I understand there's a non-ASCII name on citation, is that correct ?
We found some issues on non-UTF8 character on title and description, can it be a name causing troubles to process this submittion ?
We can also see CSRF error right after your submission, previous CSRF errors and turn out to be on client side. Have you ckeck your cookies configuration ?

Here is the log

[PRETIX-issue1083.txt](https://github.com/pretalx/pretalx/files/6251538/PRETIX-issue1083.txt)

**Comment by rixx** [comment]
For some reason your log doesn't appear to include tracebacks, so I'm afraid this will be pretty impossible to debug.
