### ISSUE TITLE
Show avatar image upload size limit in help text

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1084]
This leads to confusion for submitters, so we should have a size hint for image fields.

**Comment by AthinaDavari** [comment]
@rixx , me and my colleague @NataliaKat want to contribute to this issue.  

The changes we want to make are:
1.	In src/pretalx/static/cfp/scss/_layout.scss file, we will change #event-logo. To be more specific, we will add max height to this rule and delete the rule height:auto. We will also delete width: 100%.
2.	We will add a help text in two parts of the of the software: event’s settings (events' logo) and in new event’s form (step 4 : logo). The help text will we like this: “If the image is taller than x px, it will automatically be adjusted to x px.”.  (The suggested max height is 150 px.)

These changes will also satisfy issue #1082.

We are first time contributors and we want to contribute as part of Applied Software Engineering university course. We would like to make further contributions, so any help or suggestion is welcome.

**Comment by rixx** [comment]
Sorry for not responding earlier, I was away – your efforts are very appreciated! Happy to have your contributions, and ping me whenever you have any questions or want any help.
