### ISSUE TITLE
Encoding problem on send proposal ("Incorrect string value: '\\xE2\\x80\\x8B\\xE2\\x80\\x8B...' for column 'abstract' at row 1")

### ISSUE THREAD

**Issue by Delawen** [pretalx/pretalx#1085]
## Current Behavior

When trying to send proposals with "non-western" characters like `ý ě`, Pretalx returns a 500 error. 

The log shows something like:

```
ERROR 2021-03-29 23:21:28,396 django.request log Internal Server
Error: /$url/submit/$ID/profile/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py",
line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py",
line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py",
line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py",
line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py",
line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value:
'\\xE2\\x80\\x8B\\xE2\\x80\\x8B...' for column 'abstract' at row 1")
```

## Expected Behavior

Best case scenario: process the encoding right, escape whatever needs to escape and accept the proposal.
Second best case scenario: Provide an error that is not a 500 error so people can at least know how to modify their proposal to send it.

## Steps to Reproduce

1. Deployed a 2.1.1 Pretalx with a database defined in docker as
```  db:
    image: mysql:5
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ************
      MYSQL_USER: ************
      MYSQL_PASSWORD: ************
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
```
2. Create an event that accepts proposals
3. Send a proposal with characters like `ý ě`
4. Pretalx will show a 500 error
![imagen](https://user-images.githubusercontent.com/726590/112949186-3ac3b580-9139-11eb-9532-a86d60a0fa9b.png)

## Context

This is preventing many proposals from being digested and sent to Pretalx.

## Your Environment

* Version used: 2.1.1 using the pretalx/standalone image
* Environment name and version (e.g. Chrome 39, python 3.5): Not related to the browser
* Operating System and version (desktop or mobile): Both
* Link to your instance, if in production: callforpapers.2021.foss4g.org
* Full docker-compose file
 ```  version: '2'
services:
  pretalx:
    image: pretalx/standalone:2.1.1
    container_name: pretalx
    restart: unless-stopped
    depends_on:
      - redis
      - db
    ports:
      - "8080:80"
    volumes:
    [...]

  db:
    image: mysql:5
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
    [....]
    environment:
      MYSQL_DATABASE: ************
      MYSQL_USER: ************
      MYSQL_PASSWORD: ************
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes:
     [.........]

volumes:
  pretalx-db:
  pretalx-data:
  pretalx-redis:

```

**Comment by Delawen** [comment]
I guess playing with the encoding of the MySQL database could fix this, but I still think something on Pretalx side should prevent the error from getting that far/should warn the user how to work around the encoding.

**Comment by rixx** [comment]
This looks like a problem with your database encoding. Are you sure it is utf8mb4 on all sides?

pretalx cannot (with reasonable effort) stop you from using an unsupported encoding in the database. 

Moving this to a discussion, since it's a setup problem with the particular MySQL/Docker combination.
