### ISSUE TITLE
Unable to schedule talk across midnight

### ISSUE THREAD

**Issue by stblassitude** [pretalx/pretalx#1087]
## Current Behavior

When a talk begins before midnight, but ends after midnight, an exclamation icon is shown "the room is not available", even though the room is available up until midnight on the first day, and from midnight on the following day.

## Expected Behavior

The availability of the room is computed correctly; if it is available both directly before and after midnight, the room is available for that event.

## Steps to Reproduce

1. Create a multi-day schedule, and make a room available on the first day until midnight, and from midnight on the following day.
2. Schedule a talk to begin before midnight, but extend past it.
3. Observe the error message in the schedule editor.

## Context

This makes it impossible to add talks or other events that cross the day boundary. There appears to be no work-around.

## Your Environment

pretalx.c3voc.de

**Comment by stblassitude** [comment]
If a correct computation of the availability cannot easily implemented, a nice alternative might be to move the end of the day from midnight to a configurable time, say 4 or 6 am. This is the typical way broadcast planning software works (the end of the day is usually 4 or 5 am).

**Comment by rixx** [comment]
> This makes it impossible to add talks or other events that cross the day boundary.

You can still do this, even if you're shown a warning.

**Comment by stblassitude** [comment]
I can? The published schedule did not include those events. What do I need to do?

**Comment by rixx** [comment]
Events are included if they have been confirmed by the speakers, or set to "confirmed" by the organisers. Warnings on the schedule release page don't have anything to do with that.

**Comment by stblassitude** [comment]
Huh, I could swear that the only thing I changed was the scheduling. Going across midnight: warning and not included in the public schedule, moving them so they don't cross the boundary -> included in public schedule after publishing.

**Comment by stblassitude** [comment]
Speaker availability also leads to events not being published in the public schedule, unless I'm looking at the wrong things.

**Comment by rixx** [comment]
I'm very sure that warnings have literally no impact on visibility of talks, and that pretalx supports talks that cross day boundaries – an example would be [here](https://talks.mrmcd.net/2019/schedule/).

**Comment by rixx** [comment]
The bug that leads to a warning being shown when crossing any availability boundary (not midnight-specific) has been fixed in 175be817a26df73e54d16f3a013df8de05bf0672.
