### ISSUE TITLE
Error on /foss4g-2021-academic/submit/VfZVfq/profile/

### ISSUE THREAD

**Issue by vicksunNigeria** [pretalx/pretalx#1088]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by vmx** [comment]
I forwarded it to the FOSS4G team.

**Comment by gvarela1981** [comment]
Testing this URL I've found no error.

![imagen](https://user-images.githubusercontent.com/9384999/113458278-3670f400-93e8-11eb-9620-55e4420d6cc6.png)

@vicksunNigeria  can you provide us with more information about your issue ?
We've seen people having troubles uploading their proposal with large images, or non-UTF8 text on title or Description

@vmx 
I also found some URLs as failed in log wich are working fine right now
Testing on Firefox 87.0 (64-bit) over Ubuntu Desktop 20.04.2 LTS

ERROR 2021-03-31 14:13:46,380 django.request log Internal Server Error: /foss4g-2021-academic/submit/KXdP6U/profile/
ERROR 2021-03-31 14:23:39,916 django.request log Internal Server Error: /foss4g-2021-academic/submit/KXdP6U/profile/
WARNING 2021-03-31 14:23:55,859 django.request log Not Found: /orga/event/foss4g2021/
ERROR 2021-03-31 14:26:47,068 django.request log Internal Server Error: /foss4g-2021-academic/submit/1NCuGf/profile/

ERROR 2021-03-31 14:37:04,217 django.request log Internal Server Error: /foss4g-2021-academic/submit/5IYB68/profile/
ERROR 2021-03-31 14:37:37,812 django.request log Internal Server Error: /foss4g-2021-academic/submit/5IYB68/profile/
ERROR 2021-03-31 14:45:14,391 django.request log Internal Server Error: /foss4g-2021-academic/submit/5IYB68/profile/
ERROR 2021-03-31 14:54:16,072 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/new
ERROR 2021-03-31 14:57:47,962 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 14:58:10,531 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT/
ERROR 2021-03-31 15:00:47,397 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:03:54,200 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:04:48,655 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:05:11,159 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:05:31,091 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:09:25,078 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:11:03,725 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT//favicon.ico
ERROR 2021-03-31 15:11:43,182 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT/

ERROR 2021-03-31 15:12:16,923 django.request log Internal Server Error: /orga/event/foss4g-2021-academic/submissions/ZQK7AT/

WARNING 2021-03-31 15:26:29,937 django.request base Method Not Allowed (POST): /orga/event/foss4g-2021-academic/submissions/ZQK7AT/speakers/add

ERROR 2021-03-31 20:14:46,608 django.request log Internal Server Error: /foss4g-2021-academic/submit/VfZVfq/profile/

**Comment by rixx** [comment]
Images might be a problem, I'll look into that. Other than that, I'm afraid without tracebacks, there's nothing to be done here.
