### ISSUE TITLE
talk preview uses <code> instead of <pre> for triple-ticks

### ISSUE THREAD

**Issue by clarkevans** [pretalx/pretalx#1090]
## Current Behavior

When building your proposal, the Preview works lovely.  You can include, for example, HTML code within triple ticks, and it's shown as you expect.  However, when you look at a proposal via "Share", content within triple-ticks does not render properly.  Instead of wrapping the block in a `<pre>` it uses `<code>` which is incorrect.

## Expected Behavior

On the "Share" link page, HTML markup within a triple-ticks should be escaped so that it's rendered by the browser using triple tickets.  

## Steps to Reproduce

1.  Create a proposal, use triple-ticks with raw HTML inside.
2.  Notice that if you move to the "Preview" tab, it renders properly.
3.  Save the proposal, then click "Share".  Open that link.
4.  The shared proposal link doesn't render properly.

## Context

This bug prevents you from using HTML code examples within your proposal without manually escaping less-than and ampersand. This bug is affecting at least one JuliaCon 2021 proposal ("HypertextLiteral : performant string interpolation for HTML/SVG").

**Comment by rixx** [comment]
Triple backticks are generally supported, but apparently they currently only work in blocks without newlines, and (as you noted) always renders `code` tags.

**Comment by rixx** [comment]
fixed.

**Comment by clarkevans** [comment]
That was fast.  Thank you so, so much.
