### ISSUE TITLE
"Your Score" is picking up number of reviews in the presence of "independent score"

### ISSUE THREAD

**Issue by vchuravy** [pretalx/pretalx#1095]
## Current Behavior

For JuliaCon 2021 some reviewers are reporting that they see a "Your Score" of `1` without having voted on the proposal.
It seems to me that it picked up the column for current number of reviews and not the caclulcation for the overall score. This might be an issue with having an "Independent Score".

![Screenshot 2021-04-07 at 17 44 09](https://user-images.githubusercontent.com/145258/113895180-b4d9e700-9796-11eb-8e9c-227dc32c9fe1.png)

## Expected Behavior

It should list the "Independent Score", "Your Score" and probably "number of reviews"

cc: @crstnbr

**Comment by rixx** [comment]
Thank you for the detailed report! It was very helpful in fixing the issue.
