### ISSUE TITLE
Error on /foss4g2021/submit/PMI7EP/profile/

### ISSUE THREAD

**Issue by fipeto** [pretalx/pretalx#1099]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by fipeto** [comment]
Dears, I got this error twice while trying to submit a proposal for the foss4G presentation track.
![image](https://user-images.githubusercontent.com/20887674/115202134-c27c5e80-a0fe-11eb-98a2-8c736b331553.png)

**Comment by vmx** [comment]
I've forwarded it to the FOSS4G team.

**Comment by Delawen** [comment]
Can you send an email to info@foss4g.org with the data you are sending on the form? We need more data to be able to debug it.

**Comment by fipeto** [comment]
thanks Maria, sending it immediately. nothing special on the data - tried to re-size the images, tried different browsers, different time-frame, still the same error message.
