### ISSUE TITLE
user_submission_confirm.html template contains no timezone information

### ISSUE THREAD

**Issue by fghaas** [pretalx/pretalx#1102]
## Current Behavior

In the [user_submission_confirm](https://github.com/pretalx/pretalx/blob/master/src/pretalx/cfp/templates/cfp/event/user_submission_confirm.html) template, the speaker does not get any explicit information as to what timezone the calendar being shown is in. This is somewhat confusing, particularly in online events where the organizers may have chosen to communicate all scheduling information in UTC, or when speakers span multiple timezones.

## Expected Behavior

The user_submission_confirm.html template should be explicit about the timezone that applies to the calendar being shown.

## Steps to Reproduce

1. Submit talk and get it accepted.
2. Receive message asking speaker to confirm.
3. Open confirmation page.
4. Observe that there is no information concerning the applicable timezone.

## Context

I ran into this when trying to confirm a talk for DjangoCon Europe 2021. It took a bit of back-and-forth with the organizers to ascertain what timezone I am confirming my slot in. In this case the conference is being organized [from Portugal](https://2021.djangocon.eu/about/credits/) (which, at the time of the conference, is on UTC+1), but the organizers have informed me that the calendar is meant to be read as CEST (UTC+2). That ambiguity could be removed if the timezone (and a UTC offset) were included in the confirmation page.

## Your Environment

* Version used: Unsure (assuming this refers to the pretalx version)
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 87.0, 64bit
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS, desktop
* Link to your instance, if in production: https://cfp.2021.djangocon.eu/ (not "my" instance in the sense that I do not control this instance; it's just where I saw this behavior)

**Comment by fghaas** [comment]
I realize that this _may_ be a duplicate of #924, but I did look at the current state of the template and it doesn't seem to include the information I was hoping for.

**Comment by rixx** [comment]
Thank you for the report! We already generated the correct help text and just failed to display it. Fixed now and will be included in the next release.

**Comment by fghaas** [comment]
Sweet, thanks!
