### ISSUE TITLE
Error on /orga/event/foss4g2021/submissions/VAX8RE/

### ISSUE THREAD

**Issue by Codrina** [pretalx/pretalx#1103]
## Current Behavior
When trying to open a proposal to do its review, I get a 500 error. 

## Expected Behavior
Open the proposal, without showing authors/speakers, allowing me to enter my comments and assign a rating.  

## Steps to Reproduce

1. login with reviewer account (codrina@geo-spatial.org)
2. click on 'proposals'

## Context
As part of the program committee, I wanted to start reviewing proposal received. I know that others reviewers did it, as I can see there are 393 reviews done. 
 
## Your Environment

* Environment name and version (e.g. Chrome 39, python 3.5): Version 90.0.4430.85 (Official Build) (x86_64), Firefox 88.0 (64-bit)
* Operating System and version (desktop or mobile): macOS Catalina, iPAD Air 4th gen - 14.4.2

**Comment by vmx** [comment]
I've let the FOSS4G team know about this issue.

**Comment by rixx** [comment]
Thank you! Feel free to re-open with further information.
