### ISSUE TITLE
Dupliclate Accept emails generated for submission with multiple speakers

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#1111]
## Current Behavior
If a submission has e.g. 3 speakers, then when it is accepted, it seems that 3 copies of the emails are generate for each speaker (i.e. 9 emails total would be sent)

## Expected Behavior
Each speaker should get exactly acceptance email, no matter how many  speakers are on the talk

## Steps to Reproduce

1.  Create an event
2. Assign multiple speakers to it
3. Change it's status to accepted
4. Look in outbox, and notice that there are too many emails there and that they are mostly duplicates

## Context

I wanted to send acceptance emails, and not overly spam attendees.
I knew this was happening but chose to send them anyway, because its too hard to go and delete emails from the giant queue if they are duplicates. Not when there are over 700 in the queue.

## Your Environment

* Version used: how do i find this out?
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 88.0.1
* Operating System and version (desktop or mobile): Mac, Desktop
* Link to your instance, if in production: https://pretalx.com/orga/event/juliacon2021

If you have the ability to check on the JuliaCon instance, then you can see the mass of duplicates for this speaker
https://pretalx.com/orga/event/juliacon2021/speakers/1022/

**Comment by rixx** [comment]
Thank you for the report! I'll be looking into fixing it asap.

> I knew this was happening but chose to send them anyway, because its too hard to go and delete emails from the giant queue if they are duplicates.

For what it's worth, you can always get in touch with pretalx support to fix issues like this. That's what support is there for.
