### ISSUE TITLE
form not valid when editing a submission in a track with access code?

### ISSUE THREAD

**Issue by xhub** [pretalx/pretalx#1114]
## Current Behavior

When a user wished to edit a submission in a track with access code, the editing is silently failing: clicking on "Save" does not yield any error, the page content are as desired, but no change are actually recorded. The only indication (to the trained eye) is that there is no "Your changes have been saved." banner at the top.

Further investigation leads to the form being invalid. In the method `post` of the `SubmissionsEditView` object, a call to `form.is_valid()` returns `False`. The error reported by `form.errors` is
```
<ul class="errorlist"><li>track<ul class="errorlist"><li>Select a valid choice. That choice is not one of the available choices.</li></ul></li></ul>
```
This leads to a call to `return self.form_invalid(form)`.

## Expected Behavior

The "Save" action yields a record of the changes. This works with the talks in the one publicly accessible track. Those can successfully update their submission. The same is expected for a submission in a track that required an access code.

## Steps to Reproduce

1. Log in
2. Go to "My submission". Select a submission in a track with access code
3. Edit the title or abstract 
4. Click on "Save".

## Context

Due to the global situation, a conference was postponed by a year. We wish to give the attendee an opportunity to edit their title/abstract. With this bug, this is now not possible for a majority of them.

## Your Environment

* Version used: v1.1.2
* Environment name and version (e.g. Chrome 39, python 3.5): python 3.6, many browsers (safari, chrome)
* Operating System and version (desktop or mobile): desktop
* Link to your instance, if in production:

**Comment by rixx** [comment]
Debugged privately, can't reproduce the original error. For future reference, this occurs when an event

- makes tracks mandatory, and
- there are no tracks available for the proposal being edited.

In this case, it was because all tracks were protected by access codes, but no access codes were connected to the proposals.
