### ISSUE TITLE
Session image not constrained in talk page

### ISSUE THREAD

**Issue by doegox** [pretalx/pretalx#1115]
Hello
We have the issue that large images uploaded by speakers as session image and displayed in their talk page on the right of the talk description weren't constrained in size and could go way over it.
One possible fix we did locally is to add `width="100%"` to the `img` on this line:
https://github.com/pretalx/pretalx/blob/70ff61d08fcc8c5912aebb86d24c60044c6291dc/src/pretalx/agenda/templates/agenda/talk.html#L66

**Comment by rixx** [comment]
Thank you for your report!

This issue has been fixed in development in 3a3a14267b7a72cb2ed369da83382088f1072010, the fix will be included in the next release.

**Comment by doegox** [comment]
Great! Thanks for your fast and efficient handling!
