### ISSUE TITLE
Error: This schedule-related page is non-public. Only organisers can see it.

### ISSUE THREAD

**Issue by logankilpatrick** [pretalx/pretalx#1122]
## Current Behavior

I am getting the following message: "This schedule-related page is non-public. Only organisers can see it." but when I open the same link: https://pretalx.com/juliacon2021/featured/ in a private browser, I see the content from that page. 

## Expected Behavior

I would not expect to see that warning message.

## Steps to Reproduce

1. go to https://pretalx.com/juliacon2021/featured/ as a logged in admin 
2. go to https://pretalx.com/juliacon2021/featured/ without being logged in 

## Your Environment

* Version used: Unknown
* Environment name and version (e.g. Chrome 39, python 3.5): Safari 
* Operating System and version (desktop or mobile): Desktop
* Link to your instance, if in production: https://pretalx.com/juliacon2021/featured/

**Comment by rixx** [comment]
Thank you for the report! Bug is fixed and fix is live 🎉
