### ISSUE TITLE
Possibility to extend validity of links for user generation

### ISSUE THREAD

**Issue by kuhball** [pretalx/pretalx#1124]
## Current Behavior
If proposals are created manually all the speakers get links to create accounts. These links are only valid for 24 hours. 

## Expected Behavior
It would be nice to have the possibility the extend the validity of the links to create the user account hence speakers are busy and won't always read their mail within the next 24 hours. 

## Context
We are using pretalx mostly to gather informations from the artist in a central location and keeping information organized for new people. 

## Your Environment

* Version used: 2.1.1

**Comment by rixx** [comment]
We should do that, for sure. I'll close it as extension of #554, which is about the same thing from a slightly different point of view.
