### ISSUE TITLE
Talk slot start/end times use different timezones

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#1145]
## Current Behavior

Slot start/end times use different timezones

## Expected Behavior

Slot start/end times use same timezones. 

## Steps to Reproduce

1. Look at talks/submissions API 
2. See strange

   ```
            "slot": {
                "room": {
                    "en": "Education"
                },
                "start": "2021-09-10T13:30:00+10:00",
                  "end": "2021-09-10T04:00:00Z"
            },
   ```

  Formatting changed so the different timezones (+10:00 vs Z) are visible.
3. Don't notice until attendee/speaker tells you
4. See strange

<img width="989" alt="Screen Shot 2021-08-02 at 12 18 56 pm" src="https://user-images.githubusercontent.com/813732/127795948-473dabf3-2811-4900-a893-066b5b6a0dda.png">

## Context

We were just alerted to this on our website, as our own code takes the pretalx data and makes a nice program. Our issues occurred when our auto-updater changed all our end-times https://github.com/pyconau/2021-website/runs/3187241468?check_suite_focus=true 

The pretalx schedule is fine though. Our code currently presumes the data from pretalx is consistent with respect to date formatting, hence the issue. 

### Conjecture follows

I think this is related to 613f1c5df50a5e9ecafc8f4b39e3be20c0e0e0ad as this is the only change from around that time. 

It might be that the `real_end` doesn't take into account timezone settings, or something of the like

## Your Environment

Hosted pretalx

**Comment by glasnt** [comment]
FYI we've fixed this on our end by coercing timezones manually, but should still be addressed upstream

https://github.com/pyconau/2021-website/pull/82

**Comment by rixx** [comment]
Damn, I'm sorry this happened! Fix is live now – I was sure all times were cast to event time through the API serialiser.

**Comment by glasnt** [comment]
All good! Thanks for the quick fix <3
