### ISSUE TITLE
Error on /iclave11/cfp

### ISSUE THREAD

**Issue by ewittenberg** [pretalx/pretalx#1152]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
I'll need details (error logs) from the iclave11 sys admins – leaving this issue open for a bit to see if we can get any details.

**Comment by rixx** [comment]
Actually, after looking at it, apparently the entire pretalx instance is not working at the moment. This isn't a pretalx bug, more likely an update issue or something like that. Please get in touch with the organisers.
