### ISSUE TITLE
Maybe I just don't understand?  Some emails don't go out, others do.

### ISSUE THREAD

**Issue by mraugh** [pretalx/pretalx#1164]
## Current Behavior
Presenters seeking to change or reset their password do not get any email allowing them to do that.  But emails sent out through the Mails|Send Email function work fine, and I can send mail from the server command line via Postfix and that works.  So why are password reset emails not working?

## Expected Behavior
Mail is mail is mail; if one works, they all should work.

## Steps to Reproduce

1. An existing user forgets their password
2. They click "Reset Password" and enter their email
3. The email never arrives

## Context

This is making it difficult to get class proposals, since presenters from last year cannot get a password reset

## Your Environment

* Version 2.1.1
* Various browsers and OSes on the user side
* Server is Ubuntu 20.04, with python 3.8.10 
* https://pretalx.charmedhypno.org is the instance

**Comment by rixx** [comment]
This isn't a support channel – please start discussions for support questions in the future.

Password reset emails don't use event email configurations, rather, they use the global email configuration from the pretalx.cfg (or environment variables). I would guess that at your instance, the email settings are not configured correctly. Please refer to our [documentation](https://docs.pretalx.org/administrator/configure.html#the-mail-section) for further information.

**Comment by rixx** [comment]
Apparently, you ran into the same issue a year ago in #1020.
