### ISSUE TITLE
Too long placeholder text for 'Session Types' input when adding a new question

### ISSUE THREAD

**Issue by mnojek** [pretalx/pretalx#1167]
## Current Behavior
Too long placeholder text for a 'Session Types' input when adding a new question. The placeholder does not fit the input width and displays weirdly. Also, the input does not look like it's a select input (there is no arrow that suggests it). 

![image](https://user-images.githubusercontent.com/7412964/133121515-3ea6fafa-25e4-4ad8-ab5d-2643aa8bb73e.png)

## Expected Behavior
The placeholder text should be short or none. There should be an arrow inside the input to suggest that field type is select input.

## Steps to Reproduce

1. Go to `CfP` -> `Questions` and click `Add a new question`.
2. Scroll down to see `Session Types` field.

## Your Environment

* Version used: pretalx.com
* Environment name and version: Google Chrome 93.0.4577.63
* Operating System and version (desktop or mobile): MS Windows 10 Home

**Comment by rixx** [comment]
Apparently changes in Chrome 93 led to calculation of input width at the wrong time.

**Comment by mnojek** [comment]
Wow, thanks Tobias for quick response with fixes.
Unfortunately, I think this fix introduced a new bug:

![image](https://user-images.githubusercontent.com/7412964/133157007-aed8697e-62be-4353-8767-20f6fc23687e.png)

Now I can select multiple values instead of 1 and they are displayed in a weird way.

**Comment by rixx** [comment]
You were always able to select multiple values; that's why there wasn't a downard arrow.

As for the display issue, you may have to hard-reload the page to get rid of some caching. It looks perfectly fine to me: 
![2021-09-13T23:27+02:00](https://user-images.githubusercontent.com/2657547/133158784-f139a0f1-c0d9-42ef-afed-220bbb05db2b.png)

**Comment by mnojek** [comment]
Yes, you're right. I tried in incognito and it looks fine now. Thanks!
