### ISSUE TITLE
Strange display of dropdown when editing CfP

### ISSUE THREAD

**Issue by mnojek** [pretalx/pretalx#1168]
## Current Behavior
There is a strange behavior when using empty dropdowns while editing CfP. The empty dropdown shows a short empty element which covers the new modal that is opened after clicking the select input. 

![image](https://user-images.githubusercontent.com/7412964/133122768-84163a6a-2313-4044-a0e7-20bae41e35fa.png)

## Expected Behavior
The strange empty element should not be displayed at all, only the modal should appear.

## Steps to Reproduce
1. Go to any event
2. Go to `CfP` -> `Editor`
3. Click on the empty dropdown input, e.g. 'Language' or 'Session Type'
4. The issue appears only when clicking inside the input, not the whole clickable element

## Your Environment

* Version used: pretalx.com
* Environment name and version: Google Chrome 93.0.4577.63
* Operating System and version (desktop or mobile): MS Windows 10 Home

**Comment by rixx** [comment]
Can't reproduce on the same Google Chrome version, but I'll add a workaround that will make the field generally unselectable.
