### ISSUE TITLE
Option to disable feedback to speakers

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#1171]
## Current Behavior

The public schedule for talks that have occurred has a 'anonymous feedback form' that appears after the talk was presented

## Expected Behavior

I was only notified of this feature after our event, and wanted to disable it. Which I couldn't. 

## Steps to Reproduce

1. Enter data for a talk
2. Schedule it in the past
3. View the public listing
4. See feedback form
5. Fail to locate any setting to disable this

## Workaround

Our event is over and we don't need the schedule listing any more, so we hid the entire thing. 

## Context

We weren't sure if the feedback form would be sending 'anonymous' feedback to speakers. Our event has a conduct team that helps ensure speaker and attendee safety, and we patrol our in person and online spaces when our events are virtual. We cannot commit such resources after an event, so we disable video upload comments. This is another possible vector. 

We also weren't sure if there was an automatic email to speakers that happened, but going by previous issues this wasn't implemented.

## Your Environment

Hosted pretalx.

**Comment by rixx** [comment]
There's no automatic email sent to speakers, but disabling feedback should be a feature regardless!
