### ISSUE TITLE
Email sending confusion

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1178]
## Current Behavior

The new new compose email editor does away with manual emails, which I found super useful :-(

![image](https://user-images.githubusercontent.com/95874/135073023-a3a45943-e492-4efe-b5d4-f2f69fa7e4f9.png)

## Expected Behavior

No recipient groups selected should result in zero emails sent, but actually sends to all proposals

## Steps to Reproduce

1. Don't select any recipient groups
2. Preview email 
3. See "Roughly 56 emails will be generated."

## Context

I'd like to be able to send a test email to a specific person, or failing that event admins (not reviewers)

**Comment by rixx** [comment]
Yes, we disabled the sending of individual emails, at least for now – it was a tradeoff between offering proper email templates and placeholders, and allowing arbitrary addressees. Sending emails with placeholders like {session_title} was our most heavily requested feature, so we prioritised that.

The next step will be to add a general toggle – to send proposal-based emails vs person-based emails. We're working on that at the moment!

**Comment by plaindocs** [comment]
I still find it pretty odd that the default when no group selected is *everyone*, instead of *nobody*.

**Comment by rixx** [comment]
Sending an email to nobody would be fairly useless, though? How would that be a usecase?

If you select only one proposal or one track etc, only that group will receive an email. But when *nothing* is selected and you try to send an email, pretalx does its best to actually let you send an email.

**Comment by plaindocs** [comment]
Riiight, I guess if you state it like, I kinda agree.

BUT if you're coming from the previous interface, where you _could_ send to a single address, and you keep on going down the form not finding what you want, but still write the email anyway :-D
