### ISSUE TITLE
Specifying the date for event creation can only work without zeros

### ISSUE THREAD

**Issue by Lukas2112** [pretalx/pretalx#1179]
## Current behaviour
When creating events, I can only specify a start and end date in the format d.m.yy and not in dd.mm.yyyy - Europe/Berlin has been selected as the Locate.

## Expected behaviour
Either it makes no difference between d.m.yy and dd.mm.yyyy or a corresponding note in the creation mask.

## Steps to Reproduce

1. Pretalx deployment with docker
2. Event creation
3. Setting a start and end date

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
Yeah, this is a vaild issue, but I'm afraid it would be much too complex to fix – localised inputs are hard, and we rely on libraries to handle them for us. Once we re-write the frontend, this may get fixed in the process, but until then, unless somebody else provides a fix, it's here to stay.

**Comment by Lukas2112** [comment]
Okay, thanks for your feedback. A note about this fact might still be useful, I guess.
