### ISSUE TITLE
Error on /foss4g2021/me/

### ISSUE THREAD

**Issue by srvsingh1962** [pretalx/pretalx#1180]

**Comment by rixx** [comment]
Couls you please provide any details? Did this happen when you just accessed the page? Did you attempt an update? Which data did you attempt to change? Which browser did you use? etc.

**Comment by srvsingh1962** [comment]
Hi,

I faced the error when there was one emoji in bio which cause some error in
saving it. I removed it and resolved that.

With regards,
Sourav Singh

**Comment by rixx** [comment]
Emoji are definitely supported in pretalx – this is probably a problem with the Foss4G pretalx instance. Please get in touch with their organisers/administrators!

**Comment by srvsingh1962** [comment]
Sure, will do that.
