### ISSUE TITLE
"Plugins" settings option is only shown to superadmins

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1218]
## Current Behavior

The "plugins" settings option in the menu bar is only shown to superadmins, however inputting a direct link (like https://talks.seibert-media.net/orga/event/tools4agileteams2021/settings/plugins) works fine.

## Expected Behavior

"Plugins" setting is also shown to users with "manage events" or similar permission.

**Comment by rixx** [comment]
This was fixed in a75ca408.

**Comment by fkusei** [comment]
Oh, nice, so it's just pending a release then. Wonderful to hear.
