### ISSUE TITLE
Cannot filter submissions by multiple states in API

### ISSUE THREAD

**Issue by AetherUnbound** [pretalx/pretalx#1232]
## Current Behavior
When I try to use the API to retrieve submissions across multiple states, only submissions for one state are returned.

Example command: 
```
$ curl -X GET \
  'https://pretalx.com/api/events/[event]/submissions?state=accepted&state=confirmed' \
  -H 'Authorization: Token [redacted]' \
  -H 'content-type: application/json'
```

## Expected Behavior

I would expect this to return talks which fall in both states, since the UI allows multiple states through the same parameters. E.g.: https://pretalx.com/orga/event/[event]/submissions/?q=&state=accepted&state=confirmed

## Steps to Reproduce

1. Set up an event with submissions in different states
2. Try to query across multiple states using the `state` parameter several times
3. Observe that only submissions from a single state are returned.

## Context

I'm hoping to provide a list of submissions to our AV team and not all submissions are in the same state.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production: https://pretalx.com/orga/event/pycascades-2022

**Comment by rixx** [comment]
Sounds like a cool feature, and easy enough to add – thanks for proposing it!

**Comment by rixx** [comment]
Feature is live in production. We should probably revisit this for other endpoints and fields at some point.

**Comment by AetherUnbound** [comment]
Sweet, thanks a ton!
