### ISSUE TITLE
Add federation of the events via AcitivityPub

### ISSUE THREAD

**Issue by hfte** [pretalx/pretalx#1241]
Could pretalx become a part of the fediverse? At least one way. Mobilizon users or instance admins could follow a pretalx conference.

**Comment by rixx** [comment]
I'm fairly sure the current plugin system is good enough to write a Fediverse plugin for pretalx. If you run into issues with that, feel free to open issues for specific missing hooks – we would be glad to add them. :)

(Making pretalx-core be a Fediverse node would be wildly out of scope, of course, but this is basically the textbook case for a plugin.)
