### ISSUE TITLE
submission start time gets cleared by javascript

### ISSUE THREAD

**Issue by saerdnaer** [pretalx/pretalx#1243]
## Current Behavior

after loading an event, e.g. https://pretalx.c3voc.de/orga/event/rc3-2021-gehacktes-from-hell/submissions/FUUQ8S/ the javascript modifies the begin time field:
* in chrome (macos)  the field gets cleared,
* in firefox (ubuntu) writes the day -1 hour, e.g. 2021-12-25T23:00:00+01:00

screenshot from chrome:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/40266/147395141-711fcc6e-948b-4baf-a0a1-8919bd46b3de.png">

https://user-images.githubusercontent.com/40266/147395177-2baa2d54-0dc2-409d-9d57-dd2c8e256156.mov

## Expected Behavior

the existing value shoud not be modified

## Steps to Reproduce

1. open an existing event in firefox 95.0.2 auf Ubuntu 21.10, der standard "Mozilla Firefox Snap for Ubuntu, canonical-002 - 1.0"
2. try to edit any field e.g. the description
3. save

now the beginning is set to the day before at 23:00

## Your Environment

* Version used: 2.3.0
* Environment name and version: chrome 96
* Operating System and version (desktop or mobile): macOS
* Link to your instance, if in production: https://pretalx.c3voc.de/

## User Environment `@flo_h` 

firefox 95.0.2 auf Ubuntu 21.10, der standard "Mozilla Firefox Snap for Ubuntu, canonical-002 - 1.0"

**Comment by rixx** [comment]
Included in v2.3.1
