### ISSUE TITLE
Individual talk ics empty

### ISSUE THREAD

**Issue by stblassitude** [pretalx/pretalx#1247]
## Current Behavior

The iCal file for an individual talk is practically empty:

https://pretalx.c3voc.de/rc3-2021-chaosstudiohamburg/talk/FTBBTL.ics
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//pretalx//pretalx.c3voc.de//FTBBTL
END:VCALENDAR
```

The full calendar https://pretalx.c3voc.de/rc3-2021-chaosstudiohamburg/schedule/export/schedule.ics is missing this event, too.

## Expected Behavior

The iCal file should contain the date and time for the talk.

## Steps to Reproduce

1. Download and inspect/import the iCal file

I've noticed that the talk has no end time (listed as "13:30–"). I'll try and update the talk to see if that fixed the iCal.

## Your Environment

n/a

**Comment by stblassitude** [comment]
This is weird. The data for the talk looks OK to me: starts at 13:30, ends at 14:15, length 45 minutes. Not sure why the end time would be missing. I'll try moving it in the schedule back and forth to trigger updates to all the fields.

**Comment by stblassitude** [comment]
Moving the talk five minutes and back fixed the entries, apparently. The export now looks correct.

**Comment by rixx** [comment]
Probably occurs because the schedule is created by way of plugin. Going to make some changes to make sure fallback values are used.
