### ISSUE TITLE
End time before start time

### ISSUE THREAD

**Issue by cketti** [pretalx/pretalx#1248]
## Current Behavior
Apparently it's possible to enter an end time that lies before the start time.

## Expected Behavior

Don't allow the user to create an event with a end time that lies before the start time.

## Steps to Reproduce

Sorry, no idea. All I have is this screenshot sent to me. Note that the end date is the day before the start date.

![image](https://user-images.githubusercontent.com/218061/147601816-f05d5e99-deb5-44f4-9a07-43088b336776.png)

## Context

This lead to a problem in the XML version of the rC3 schedule. The duration value was negative, throwing off (at least) one consumer of this file, namely [EventFahrplan](https://github.com/EventFahrplan/EventFahrplan).

## Your Environment

If necessary I'm sure @saerdnaer can provide details.

**Comment by rixx** [comment]
This is only possible as of the bugfix version released yesterday, where we had to disable some checks to get around browser timezone parsing idiocy. I'll push a fix blocking changes like these, but I'm not sure this is in itself enough to justify another bugfix release.
