### ISSUE TITLE
Bug adding review scoring

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1253]
On hosted pretalx I copied a previous event, and was surprised that the review scores were not copied.

When attempting to add new scores manually they were truncated and did not save. Second attempt the same, but third did result in a longer text field and I was able to save the score.

> I will fight to make sure this talk is included in the program.

![image](https://user-images.githubusercontent.com/95874/148350163-fa49f62a-71f0-4eee-bcc5-3875d892e840.png)

First two tries not working and third succeeding seems consistent behaviour.

**Comment by rixx** [comment]
Thanks for reporting this bug! From the description, I'd assume some browser shenanigans – Firefox is particularly good at secretly caching hidden (or non-existant) form fields and absolutely ruining form inputs like that. Just to help reproduce the issue, which browser are you using?

**Comment by plaindocs** [comment]
Sorry for not mentioning earlier!

![image](https://user-images.githubusercontent.com/95874/148398544-6a637488-c6f7-4c74-9dcf-397f0ebb1bb4.png)

**Comment by rixx** [comment]
Still not sure what was going on there, but we copy/create review scores and phases on event copy, now.
