### ISSUE TITLE
Per-reviewer emails

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1254]
## Current Behavior

After opening and closing #1178 (which I understand) I'm back with a new issue. 
I've two reviewers in a team, including myself. 

## Expected Behavior

I can send them email

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/95874/148397176-a24462d6-b349-44e0-a2cf-08e322f15f4b.png)

## Context

I'm actually using reviewers as a way to send test emails here, because I'm having some trouble with a 3rd party SMTP provider, but also for the actual email content when I get around to updating it.

**Comment by rixx** [comment]
Ah, yes, with the recent change in email sending, emails are currently only possible based on proposals, not on individuals. We're working to make that possible again, see also #1244. I'll remove the option to avoid misleading users in the meantime, and it will be added again once we introduce the switcher between "per-person" emails and "per-proposal" emails.

**Comment by plaindocs** [comment]
:tada:
