### ISSUE TITLE
CFP editor confirmation UI

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1255]
## Current Behavior

![image](https://user-images.githubusercontent.com/95874/148574861-2488371c-a66f-40d2-9cfc-5375bd9535f9.png)

## Expected Behavior

A confirmation dialog box where I can see it so I don't lose changes. :-p 

## Steps to Reproduce

1. In the CFP editor, click question text to change it.
2. 
3.
4.

## Your Environment

Firefox 95.0.2 (64-bit) on Linux Fedora.

**Comment by rixx** [comment]
Could you expand? I understand that "Unsaved configuration changes! [Save now]" is not terribly specific, but it pops up as soon as you change something, and it's always visible (cannot scroll out of view), and I don't quite see how listing the details with a confirmation dialog would improve over a simple save button.

**Comment by plaindocs** [comment]
@rixx I apologize for all of my curt bug reports. <3

The save button is fine, I just expect it closer to the modal. First time round I didn't see the button at all, clicked outside the shaded area because there "was no other option", and was surprised that my changes were not saved.

**Comment by rixx** [comment]
Putting the save button into the pop-up would force you to save for every single change, instead of being able to make several changes in a row and finally saving them. I'm not sure that would be an improvement … it's sometimes nice to see changes in all in one place to see if they work together.

**Comment by plaindocs** [comment]
Gotcha. I didn't even realize you could do that, so would have made changes one at a time anyway.
Don't suppose you can float it to the last field changed? 

Anyhow, I'll remember this now, at least until next time, so we can close if you don't consider it a bug.

**Comment by rixx** [comment]
Closing for now, will keep in mind that hte UI will need a refresh once all the other UI refreshes are done.
