### ISSUE TITLE
Email templates do not take timezone into account

### ISSUE THREAD

**Issue by AetherUnbound** [pretalx/pretalx#1258]
## Current Behavior

It appears that when composing an arbitrary email, the `{session_start_time}` placeholder does not take into account the event's timezone.

## Expected Behavior

When I generate emails with a `{session_start_time}`, I expect the templated time to reflect the session's start time in the timezone the event is set in.

## Steps to Reproduce

1. Create an event with a non-UTC time zone
1. Create a submission with a scheduled time
1. Compose an email with `{session_start_time}`
1. Observe that the email in the Outbox shows the start time as UTC rather than the local timezone
1.

## Context

![image](https://user-images.githubusercontent.com/10214785/148864308-58e0dd31-dc83-454f-94e2-2c7cae610337.png)
![image](https://user-images.githubusercontent.com/10214785/148864334-e7c64cbe-6f90-475f-9f24-76444bbd0c67.png)
![image](https://user-images.githubusercontent.com/10214785/148864406-875c3413-052b-4585-9f38-e5f744d3b2ca.png)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
Thank you for the bug report! The fix is rolled out on pretalx.com
