### ISSUE TITLE
use local date format in HTML export

### ISSUE THREAD

**Issue by gislars** [pretalx/pretalx#1272]
## Current Behavior

The HTML export pages for speaker and talks show the date in YYYY-MM-DD format even when time zone is set to Europe/Berlin

## Expected Behavior

The HTML export pages should use the local date format. For Europe/Berlin it is DD-MM-YYYY

## Steps to Reproduce

1.  configure a conference and set time zone to Europe/Berlin
2. configure a program an do an HTML export
3. look at talk page (pretalx.com/conference_name/talk/talkid), the second line is showing the date YYYY-MM-DD
![Bildschirmfoto vom 2022-02-22 21-41-23](https://user-images.githubusercontent.com/402166/155218923-3acdac1a-526b-40e6-afbd-76366457c213.png)
4. or look at the speaker page (pretalx.com/conference_name/speaker/speakerid), the first column of the talk table contains the date with format MM-DD
![Bildschirmfoto vom 2022-02-22 22-02-35](https://user-images.githubusercontent.com/402166/155218919-f052e989-8be7-4498-b66b-adf6a2030d8e.png)

## Context

I couldn't find a setting to configure a date format for HTML export. If there is one, please let me know. I was looking at open/closed issues regarding date format, but I couldn't finde anything related. 

At other exported pages the date format is correct, like at the overview page pretalx.com/conference_name/schedule/

## Your Environment

* Version used: hosted at pretalx.com
* Link to your instance, if in production: https://pretalx.com/fossgis2022

**Comment by rixx** [comment]
As far as I can tell, this issue is **not** specific to the HTML export.
