### ISSUE TITLE
Error on /conference2022/

### ISSUE THREAD

**Issue by tebeka** [pretalx/pretalx#1279]
## Current Behavior
Submitting a talk, I get "CSRF error".

## Expected Behavior
Proposal submitted.

## Steps to Reproduce

1. Fill a proposal
2. Click "Submit"
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome 99.0.4844.51 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Linux, desktop
* Link to your instance, if in production:

**Comment by rixx** [comment]
Could you please provide a link to the event in question? This sounds like it's probably a problem with the instance setup, and nothing we can fix on our end.

**Comment by tebeka** [comment]
https://cfp.pycon.org.il/

**Comment by rixx** [comment]
Please get in touch with the administrator team, and ask them to look at the error logs.

If that doesn't work, they can re-open this issue with further details.
