### ISSUE TITLE
Error on /workshop2022/submit/W8QIRR/questions/

### ISSUE THREAD

**Issue by dinbav** [pretalx/pretalx#1303]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
Could you please provide details, such as the event you were trying to create a proposal for?
