### ISSUE TITLE
404 if file name contains special chars

### ISSUE THREAD

**Issue by Rufus125** [pretalx/pretalx#1304]
## Current Behavior
https://pretalx.linuxtage.at/glt22/talk/YGGRCU/
click on file töst
https://pretalx.linuxtage.at/media/glt22/submissions/YGGRCU/resources/t%C3%B6stfile_Ja8S1It.txt
404 Not Found

## Expected Behavior
Being able to see/download the file

## Steps to Reproduce

1. In a submission, click on add another resource
2. set any description for the resource
3. upload a file that contains special characters like öäü
4. Try to download it

## Your Environment

* Link to your instance, if in production:
https://pretalx.linuxtage.at/glt22/talk/YGGRCU/

**Comment by crablab** [comment]
I have tested this locally and I believe this has now been fixed, although not yet released. 

Perhaps you could test locally from the latest on main and confirm? 👍

**Comment by rixx** [comment]
Yup, seems to work alright. Might also be a configuration problem, I don't think we've touched that code in ages.
