### ISSUE TITLE
Order of tracks changes after editing a track

### ISSUE THREAD

**Issue by navlisilvan** [pretalx/pretalx#1305]
## Current Behavior
Arter you edit a track (Name, Description, Colour)  the order of the Tracks will be different afterwards. 

## Expected Behavior
The order of the tracks stay in order of creation or sorted by first letter

## Steps to Reproduce

1. In Backend under CfP - Tracks: Create a few tracks.
2. Change the colour/Description or name of one
3. You will see the tracks will be in a different order afterwards
4.

## Context
We want to have sorted tracks: Beginner/Intermediate/Advanced. It will be confusing if the order would not be in this order.
Adding a number at the beginning (for sorting for first "letter" doesn´t help)

## Your Environment

* Version used: i think the current one but didn´t know wher to find out
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 99.0.1
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your instance, if in production: https://workshops.acronia.de bzw. https://workshops.acrolotl.de/orga/

**Comment by johanvdw** [comment]
I think a position field should be added to tracks, similar to how this is done for room.

https://github.com/pretalx/pretalx/blob/main/src/pretalx/schedule/models/room.py#L51C17-L57

This way tracks can be sorted any way, without relying on implicit behaviour.
