### ISSUE TITLE
Speakers calendar constraints not saved from attendance confirmation page

### ISSUE THREAD

**Issue by doegox** [pretalx/pretalx#1307]
## Current Behavior

When a speaker follows the mailed link to xxxx/me/submissions/XXXXXX/confirm and fills the calendar then press "Confirm", his choices are not saved.

When he enters his profile xxxx/me,  edit the calendar and press "Save", the calendar is properly saved.

## Expected Behavior

Calendar editions should be saved from the /confirm pages as well

## Steps to Reproduce

1. Get acceptande email, click on link -> .../confirm
2. Add choices to the calendar on /confirm webpage
3. Press Confirm
4. Visit /me and see calendar didn't get saved

## Your Environment

* Version used: 2.3.1
* Environment name and version (e.g. Chrome 39, python 3.5): Brave 1.37.116 (Chromium: 100.0.4896.127).
* Operating System and version (desktop or mobile): Debian Testing
* Link to your instance, if in production: https://cfp.pass-the-salt.org/ (python3.7 in venv, pretalx 2.3.1 from pip)

**Comment by rixx** [comment]
Wow, that's quite the bug. Thank you for reporting it!
