### ISSUE TITLE
Auto crop of speaker fotos  - croppes to the top part of the picture

### ISSUE THREAD

**Issue by navlisilvan** [pretalx/pretalx#1317]
## Current Behavior
In the List of all Speaker the Picture of them are auto croped to the upper part of the foto. 

## Expected Behavior
Best would be to not crop it but if necessary maybe crop to the middle or let choose. 

## Context

https://workshops.acronia.de/acronia-2022/speaker/ 
there many Fotos are cropped weird and there is space under it so that a crop is not necessary.

**Comment by rixx** [comment]
Not cropping is not exactly an option – I've seen speaker images that were like 500px high for 100px width, those would not even fit hte box without cropping.
