### ISSUE TITLE
Show session and speaker images on click in overlay/lightbox

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1324]
Currently, session images and speaker avatars either can't be opened at all or open in a new tab, neither of which is great. A lightbox/overlay on click would be great.

Low-priority, but nice-to-have.

**Comment by Muxsidov** [comment]
![demo_con](https://user-images.githubusercontent.com/56025069/194547908-c4b1d42b-7ada-4f27-90b9-54dbd8d976bb.png)

When I click to avatar of the user (Silhouette in this case) lightbox/overlay should pop up, right? I believe it is done with CSS, am I right?

**Comment by rixx** [comment]
Exactly, when a user clicks/taps a speaker avatar or a session image, the image should open in a lighbox or overlay kind of display.

A CSS-only solution would be great!
