### ISSUE TITLE
json export doesn't contain time_zone_name

### ISSUE THREAD

**Issue by aNullValue** [pretalx/pretalx#1334]
## Current Behavior

When viewing frab-compatible XML, attribute schedule->conference->time_zone_name exists and is set to a logical value. But when viewing frab-compatible JSON, no such attribute exists. 

(Same problem with "generator" name and version not being in the json, and speaker biography not being in XML, but one problem per request I suppose. )

## Expected Behavior

Having identical information in both file formats.

## Steps to Reproduce

1. View https://scheduler.hope.net/new-hope/schedule/export/schedule.xml
2. View https://scheduler.hope.net/new-hope/schedule/export/schedule.json
3. Observe missing "time_zone_name" value anywhere in the json file.

## Context

I'm trying to process only the JSON file, to get as much info as possible. I intend to use it as a sync-source connected to the conference management software that powers HackerTracker (a conference app for smartphones). 

## Your Environment

HOPE appears to be running pretalx 2.3.1, the latest release. I'm just attempting to consume the XML and JSON files. I am not affiliated with HOPE.

**Comment by saerdnaer** [comment]
Actually frab includes the time zone name in the JSON version...

https://fahrplan.events.ccc.de/rc3/2020/Fahrplan/schedule.json / https://frab.cccv.de/en/rc3/public/schedule.json
```
{
"schedule": {
  "version": "1.7",
  "base_url": "https://fahrplan.events.ccc.de/rc3/2020/Fahrplan/",
  "conference": {
    "acronym": "rc3",
    "title": "Remote Chaos Experience",
    "start": "2020-12-27",
    "end": "2020-12-30",
    "daysCount": 4,
    "timeslot_duration": "00:10",
    "time_zone_name": "Europe/Berlin",
    …
```

I also started to create a JSON schema at https://github.com/voc/schedule/tree/master/validator/json , but of course `time_zone_name` is still missing there... because I was thinking about additional attributes like color, keywords, etc. – c.f. https://github.com/voc/streaming-website/blob/master/docs/config-schema.json#L76-L102

I think we (aka CCC / VOC) should decouple the format binding to frab, and simply provide some a python package (e.g. `voctosched`) containing the XSD, JSON-Schema and maybe even Python data models…

**Comment by rixx** [comment]
I'm happy to integrate whatever the community decides on. We might move the frab exporters to a plugin at that point, if there's significant overhead – it's easier for the community to maintain then, and events can decide if they want/need the often confusing "frab exporters" in their export list. 

Until then, I'll be happy to keep up on request, like in this issue, but I won't be able to proactively monitor frab. Case in point: your second example is not accessible without an account, and automating the monitoring of the JSON format (via parsing it into a schema and then alerting when the schema changes) seems like *far* too much effort, unless somebody else sets it up.

**Comment by saerdnaer** [comment]
> Case in point: your second example is not accessible without an accoun
 Ah, sorry I should have clarified that – it's actually the same content=example, but the latter might include more update to date changes.
 
Just for the sake of completeness: I added `time_zone_name` to https://github.com/voc/schedule/blob/master/validator/json/schema.json and will think about a process. We had an ticket about this new attribute at https://github.com/frab/schedule.xml/pull/2#issue-700628688 – but the pretalx checkbox was checked to early without checking that both schedule `xml` AND `json`

**Comment by rixx** [comment]
```
jsonschema.exceptions.ValidationError: 'Europe/Berlin' does not match '^[A-Z][a-z+]/[A-Z][a-z+]$'
```

I'd suggest permitting more than two letters per timezone part :wink: 

Requiring the slash is also rough, because it doesn't allow "UTC" as timezone label. Is there a reason for specifying the timezone string to this degree?

**Comment by rixx** [comment]
Let's continue the conversation over in the PR above – I'll merge that once pretalx complies with your JSON schema. Once it is merged, we'll have tests that check that a) our export complies with the schema, and b) that our version of the schema is up to date (same as with the schedule xsd).
