### ISSUE TITLE
Explain how to add a custom domain

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1339]
The help text for the `custom_domain` setting contains a mention of a CNAME record, but we should still make sure to also explain custom domains in more detail in the user documentation, and link to this documentation in the help text.

Rough content collection for the user docs:

- Set a CNAME record (future safe, ddos mitigation etc)
- You need a full domain, no sub-paths (cfp., schedule., programme., …)
- You can use the same domain for multiple events
- pretalx will redirect the root url to the most current public event
- this also means that if there is no public event at all, the root url will show a 404

**Comment by dilbarov03** [comment]
Hi, I'm a first time contributor. Should we add some text to the documentation?

**Comment by rixx** [comment]
Sadly we don't have real user documentation or a manual at the moment, so the text to be added would be in the configuration interface, which could link to the documentation in the future. Or you could create the necessary documentation page and do both!

**Comment by Muxsidov** [comment]
I am a first time contributor. So, what I understood is I should add that a user should point a CNAME (I do not know what it is) to the pretalx domain(which is https://pretalx.com/p/about/, right?) to this [documentation/page](https://docs.pretalx.org/en/latest/user/index.html)
  using [Sphinx](https://www.sphinx-doc.org/en/master/)?

**Comment by rixx** [comment]
Thank you for offering to help with this issue! However, I think explaining what a CNAME is to you first, and having you add an explanation to the users, would be a bit like a game of telephone. The other issue you commented on is probably better suited as a first time issue – I answered your questions there, too :)
