### ISSUE TITLE
Check emails for broken / empty links

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1343]
## Current Behavior

Pretalx let's you compose  and send emails with empty linkt `[Test text]()...

## Expected Behavior

A warning before you send.

Yes, I'm doubling down on preventing human error, why do you ask? :-p

**Comment by rixx** [comment]
If you have any other things that we should warn email senders about: Now it's easy to add warnings!

**Comment by plaindocs** [comment]
<3
