### ISSUE TITLE
[Django 5] Update to Django 5.0, plus form improvements

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1348]
With Django 5.0, we will have custom form rendering via form and field based templates. It's finally time to remove django-bootstrap4. This issue lists the steps to be taken once that time comes, and which improvements we can then fold into Django, hopefully.

## Migration

We'll need a simple form renderer of our own for the default pretalx form. I think the other forms, we can handle with separate one-off templates, eg for the filter forms.

```python
class PretalxFormRenderer(DjangoTemplates):
    form_template_name = "pretalx/common/form/form.html"
    formset_template_name = "pretalx/common/form/formset.html"
```

Next steps are

- [x] Writing form.html, formset.html and field.html
- [x] Removing all mentions of bootstrap4
- [x] Might make sense to also provide a light wrapper template for the standard organizer form (including form tags, submit buttons etc), as we replicate that one a lot. Or move onto more standardised CRUD templates in general, [neapolitan](https://github.com/carltongibson/neapolitan) style?
- [ ] Use proper custom widgets for our special fields (availability, patterns, colours)
- [x] Consider using form.media for those special widgets
- [x] For a lighter general css package, possibly just include form css when `form or has_form`?#

## Cool things to do

… now that forms are under our control.

- [x] Prevent page reload with unsaved changes. In the CfP flow, we could even prompt users to save as draft instead?
- [ ] Save/reload form inputs to localstorage
- [x] Use `inputmode=email` on email inputs, etc
- [ ] enterkeyhint
- [ ] Use autofocus on pure login pages
- [x] Use auto-expanding textareas – I think we tried this, and then updates to i18nfield (in the organiser area) and markdown preview (cfp area) broke it? [edit: we'll get this in [pure css soon](https://caniuse.com/?search=field-sizing)]
- [x] Don't use scroll wheels on number inputs
- [x] Use JS form submits (with native fallback of course) for nicer rendering and loading experience. Has to deal with failure states of course, but we can do that by pointing out the auto-save (see above)
- [ ] Submit with control-enter
- [ ] Scroll to errors (we can even just render this script if `{{ form.errors }}`

[Here](https://austingil.com/build-html-forms-right-user-experience/) is the source for most of these, usually with implementation snippets.

More resources:

- [good inputs for mobile](https://css-tricks.com/better-form-inputs-for-better-mobile-user-experiences/#aa-a-quick-detour-into-date-types)
- [Django 5.0 goodies (by Mariusz!)](https://fly.io/django-beats/new-goodies-in-django-50/)
- [Release Notes](https://docs.djangoproject.com/en/dev/releases/5.0/)

**Comment by Valodim** [comment]
It would also be really nice to use individual `<form>`s for login and registration where they are on the same page. This allows password managers to perform a much better job of detecting those

**Comment by rixx** [comment]
Completely separate problem and should go into a separate issue.

**Comment by Valodim** [comment]
Oh, sorry about that. The "cool things we could do" list seemed like a match :) I'll open a separate issue
