### ISSUE TITLE
Adress text is not properly alligned

### ISSUE THREAD

**Issue by Muxsidov** [pretalx/pretalx#1349]
## Current Behavior
The adress lines have come on top of each other: 

![image](https://user-images.githubusercontent.com/56025069/189337342-9d1f685f-7ae0-4d86-8851-93b657da2043.png)

"Mühlenbecker Weg 1
16515 Oranienburg"

## Expected Behavior
"16515 Oranienburg"
Should be in a new and seperate line.
## Steps to Reproduce

1.
2.
3.
4.

## Context

I am afraid that this might be quite uncomfortable for user to see such disarray in a web site.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

P. S. This is my first issue report so please excuse and correct my mistakes.

**Comment by rixx** [comment]
Oh great, this seems to be a Chrome-vs-Firefox issue. Love those.

**Comment by rixx** [comment]
Thanks for pointing this out! Should be fixed now. (Looks a bit stupid on Firefox, but better than being unreadable on Chrome, for sure).

**Comment by Muxsidov** [comment]
> Thanks for pointing this out! Should be fixed now. (Looks a bit stupid on Firefox, but better than being unreadable on Chrome, for sure).

Hey, I had couple of questions for you. I wrote to info@pretalx.com but no one replied yet, how do I get familiar with this code? I wanted to tackle other small issues however I don't know where to start.

**Comment by rixx** [comment]
I didn't see your email to info@pretalx.com, it had gotten caught in the spam filter. However, this is a better place to discuss contributions, in any case!

pretalx is written in Django, so if you're not familiar with that, it may be best to work through a Django tutorial first. Next up you should complete our [development setup](https://docs.pretalx.org/developer/setup.html) and make sure everything works – poke a bit around to become familiar with pretalx.

 Then, when you want to tackle an issue and don't know where to start (ideally after searching the code base for related terms), feel free to just leave a comment on that issue and ask for advice!

(In this case, you got unlucky: the frontpage of pretalx is part of a custom pretalx plugin, so you had no way to fix this issue!)
