### ISSUE TITLE
Perform safety check when editing email templates 

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1350]
dfb5a161 added safety checks for empty links when composing emails. We should try and add a similar preview+warning system when people are editing regular templates.

**Comment by khodjiyev2o** [comment]
hi @rixx wanted to contribute to the project ,but as i am a junior ,needed some help .I have run the project locally and it is okey.Wanted to work on this issue.Can you clarify more details ?

**Comment by khodjiyev2o** [comment]
or can you suggest me any issue that i can work on ?

**Comment by rixx** [comment]
So this issue is probably on the upper end of "good first issue" – it basically asks you to add the email preview we have for simple email composition to the email template editor. Once that is done, you can also apply the change in the linked commit, which adds extra warnings on empty links.

Alternatively, you could also look into #1311 or #1324.
