### ISSUE TITLE
Changes in duration do not reflect on Start/End Time

### ISSUE THREAD

**Issue by momorientes** [pretalx/pretalx#1364]
### Problem and impact

When a submission is already scheduled, and therefore has a start and end date/time set, and the duration is updated, the end time isn't updated accordingly, thus showing up wrong in the schedule.

### Expected behaviour

The end-time should be increased/decreased to match start+duration

### Steps to reproduce

1. Create a submission with default duration.
2. Schedule the presentation
3. Increase the duration of the presentation by 30min 

### Version

hosted

**Comment by rixx** [comment]
Hmm, the time should be updated when a new schedule version is released. Could you try/check that?

**if** that works, then it's intended: Schedule versions are meant to be static, so any changes will only show up in the next version.
