### ISSUE TITLE
Django 4.1 update documentation issue

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#1368]
Once we have updated to Django 4.0 (#1235), Django 4.1 is up next. This issue collects relevant actions to be taken:

- [Adam's Postgres ID migration command](https://adamj.eu/tech/2022/10/21/migrate-postgresql-ids-serial-identity-django-4.1/)

**Comment by husanIbragimov** [comment]
`python -m pip install -U Django`

**Comment by rixx** [comment]
I'm afraid, @husanIbragimov, updating to a new Django version is not as simple as that. Please don't drive-by comment like that.
