### ISSUE TITLE
Room choice by the speaker

### ISSUE THREAD

**Issue by wargreen** [pretalx/pretalx#1381]
### Problem and impact

Ask to the speakers there need and put there proposal to each room can be :

- Obvious, if it need drill and hammer => workbench // Mic and quiet => studio // Videoprojector and chair => conf room
- Complicated, if the speaker don't know exactly what's in each place, and can't grab all the tools with him.

### Proposed solution / feature

It will be useful if we can ask to the speaker to choose the best place for his proposal, with the tools in place.
We have already a good description of each room. Maybe add a picture ?

### Context or examples

We organize an [hacker] meet and popular university with multiple topic as software, electronic, biology, music... and maybe another kind.
Our place have multiple rooms, as biology lab, workbench, computer desk, 2D/3D print and serigraphy...
Each topic have his place, and it's easier to explain what's in each place (tools or equipement) than ask for all the need and put it in the right place.

**Comment by rixx** [comment]
I'm sorry, but room self-selection is currently out of scope for pretalx, as we do not have a model of selecting a room without also selecting a time. We may revisit this at a later time (see also the discussion at #1382 ).

For the time being, you can use custom questions ("choice" or "multiple choice") to ask speakers for their room preferences or requirements.

**Comment by wargreen** [comment]
Thank you for the time :)

Maybe another view can work, for our usage at least :
Have a "prefered" room question, with a list of the rooms and some information.
For us, it is even a better solution !

Add a new custom question add a "clone" of the data and can cause errors... Because mistake between chair and keyboard.
