### ISSUE TITLE
Portuguese (Portugal) translation

### ISSUE THREAD

**Issue by davidmgvaz** [pretalx/pretalx#1384]
### Problem and impact

Is it possible to start a Portuguese (Portugal) translation?

I can contribute to this translation myself, just need it to be setup in https://translate.pretalx.com/.

**Comment by rixx** [comment]
[Here](https://translate.pretalx.com/projects/pretalx/pretalx/pt_PT/) you go!

**Comment by davidmgvaz** [comment]
100% portuguese translated ;)
