### ISSUE TITLE
'crispy_forms_tags' is not a registered tag library.

### ISSUE THREAD

**Issue by UweKrause** [pretalx/pretalx#1393]
### Problem and impact

When trying to install, pretalx shows an error message.

When following the steps in the [documentation](https://docs.pretalx.org/administrator/installation.html), at a fresh ubuntu (22.04.1 LTS "jammy")  at step 5 the command `python -m pretalx rebuild` shows an error message:
```
517 static files copied to '/var/pretalx/static', 1011 post-processed.
Compressing... Invalid template django_filters/rest_framework/crispy_form.html: 'crispy_forms_tags' is not a registered tag library. Must be one of:
bootstrap4
cache
compress
copyable
formset_tags
html_signal
i18n
jquery_tags
l10n
orga_edit_link
rest_framework
review_score
rich_text
rules
static
times
tz
url_replace
xmlescape
done
Compressed 37 block(s) from 381 template(s) for 1 context(s).
```

I now try to just continue with the installation.
If I don't update this issue I
a) rage-quitted, or
b) managed to get it running 

### Steps to reproduce

1.
2.
3.
4.

### Operating system, dependency versions

Ubuntu 22.04.1 LTS

### Version

v2.3.1

**Comment by rixx** [comment]
This is not an error, just a warning. It originates with two of our dependencies interacting in an unfortunate way and cannot be trivially resolved on our end, see encode/django-rest-framework#5463 and django-compressor/django-compressor#881.
