### ISSUE TITLE
Differences between Markdown preview and rendered Markdown

### ISSUE THREAD

**Issue by jomo** [pretalx/pretalx#1395]
### Problem and impact

Pretalx seems to use a client-side, JavaScript Markdown renderer for the previews which differs from the one used for rendering the actual public profile.

While the difference may or may not be considered a bug in either Markdown renderer, I think it is more important to use the same renderer for both cases. Otherwise the idea of a preview becomes a bit pointless.

### Expected behaviour

The preview shown to the user and the rendered page should look the same.

### Steps to reproduce

1. Navigate to your speaker profile
2. Enter
```markdown
- #️⃣ foo
```
into about field
4. Preview looks good
5. Public speaker page looks broken

### Link

https://pretalx.c3voc.de

**Comment by rixx** [comment]
In the future, please provide more detailed bug reports – "broken" and "good" are not particularly helpful descriptions and make it much harder to work on issues like this.

For future reference, in this case, "good" means 
![2022-12-21T23:06:50+01:00](https://user-images.githubusercontent.com/2657547/209011361-e1db4c6f-5e85-4a66-86be-0a3563a700a3.png) and "broken" means 
![2022-12-21T23:06:58+01:00](https://user-images.githubusercontent.com/2657547/209011399-e0a6d07e-716d-45b8-b345-c43a1cc62125.png).

I consider this a bug in the Python markdown renderer we're using – please report the bug upstream, as resolving the problem on our end isn't feasible.

(Using the "same renderer" would increase the server load while potentially decreasing security, as the only solution would be to render every preview server-side. I don't think this is in the cards for us right now – I don't really want to provide the world with an open markdown renderer endpoint, and neither do I want the delay, traffic and ickyness of embedding HTML received from the server.)
