### ISSUE TITLE
Allow to add custom fields to Rooms

### ISSUE THREAD

**Issue by wslyvh** [pretalx/pretalx#1396]
### Problem and impact

Room information is currently limited to title, description and speaker notes.

### Proposed solution / feature

Ideally, I’d like to add custom fields to have more flexibility as to what kind of information can be added to rooms.

### Context or examples

This could be similar to questions and answers on sessions. Although all information will (likely) be added by organizers.

The kind of information that would be useful to add to rooms would be, e.g. 

- venue info 
We’ve used pretalx’s room info for creating a venue map and navigator. So useful fields could be, floor nr, room nr, navigation info.

- live-streaming info
Live-streams are often setup per room. So possible fields YouTube endpoint, video player url, embedded video, etc. This should allow for flexibility to have multiple/different streams.

**Comment by rixx** [comment]
Sorry, but custom fields are currently way out of scope for pretalx. Organisers using pretalx, on average, are not set up to configure custom fields, and adding this feature would increase both the software maintenance burden and the support burden for fairly small gain.

Rooms are very much second class citizens in pretalx right now – we only very recently added a way to display additional room information in the frontend, and even so it's not well-integrated imo. Custom fields would raise questions about API expectations, especially with the upcoming writable API, as well as UI concerns.

I'd be willing to entertain a plugin API proposal that would make it easier for plugins to add model extensions, if somebody were to write the proposal and commit to providing the plugin API, but even there I can't commit to merging such a PR right now. An issue such as this is very likely to require either a committed developer or external funding.

**Comment by wslyvh** [comment]
The reason I described it as custom fields is for flexibility. 
I also assumed that some of the code from session's questions & answers could be re-used.
But I fully understand the added complexity. For limited benefits.

What are your thoughts on adding a few more fixed fields instead? I'd like to propose the following
- Room Rr
- Floor 
- (External) Url

All of these optional. 
The first 2 are useful for venue navigation. Especially for big events/venues.
The last one would be useful for different use-cases. E.g. a live-streaming url or navigation instructions.

**Comment by rixx** [comment]
All of these fields, again, come with odd sets of expectations: are they visible in the frontend? If so, how? Etc.

I don't quite see what having a number and a floor would improve over the current "description" field, which is more flexible (some venues will also need to detail the building number, or the wing, or …). As you can see with our [demo schedule](https://pretalx.com/democon/schedule/) ("Magenta room"), pretalx can now show this information to attendees, and I struggle to see an improvement in more fields.

The URL field, in particular, would make organisers expect that this URL is somehow visible to attendees, when we have no current place to make it visible at all.

**Comment by wslyvh** [comment]
My thinking was that more dedicated fields for each would allow for better navigation and filtering options.
I get your point that this should get reflected in the front-end as well somewhere.

For context, we have built a custom App in which we use these kind filtering options to create a venue navigator, with maps of the layout, floors, etc. I think for the Pretalx front-end, we could do similar by creating a 4th 'venue' (or 'location') page/tab, next to 'schedule', 'sessions' and 'speakers' that would display more detailed room info.
