### ISSUE TITLE
Allow to add custom fields to sessions

### ISSUE THREAD

**Issue by wslyvh** [pretalx/pretalx#1397]
### Problem and impact

As an organizer we’d like to add more information to sessions as current fields are limited or available for speakers to view/edit

### Proposed solution / feature

We’d like to use Pretalx as single source of truth for our entire event and production flow. 

### Context or examples

Similar to #1396 but for sessions. Maybe an extension to questions and answers would suffice. But these questions should only get answered/edited by organizers.

Some examples of fields:
- Urls or fields for additional resources, links, reading materials, slides (no uploads)
- YouTube video url 
- other video/embedded urls 
- Internal comments or feedback (not shown to speakers)

**Comment by rixx** [comment]
Sorry, but custom fields are currently way out of scope for pretalx. Organisers using pretalx, on average, are not set up to configure custom fields, and adding this feature would increase both the software maintenance burden and the support burden for fairly small gain.

Features like these need support in the frontend and the backend, and can't just be generic custom fields. Let me illustrate with your examples:

- Related links need to be displayed in the frontend, and are actually a composite field (title and link). This feature, btw, **already exists** in the form of resources (which can be either a link or a file upload).
- Video URLs need to be frontend supported: just adding a custom field and calling it "youtube video url" doesn't cut it – you'll want to be able to show actual embeds. This feature **already exists** in the form of the pretalx-youtube plugin.
- The same goes for the next point – other embeds **already exist** in the form of the vimeo plugin and the media-ccc-de plugin.
- First off, an internal notes field **already exists**, as well as a full-featured feedback and review system. More importantly, creating such a field makes API promises (not delivering this field in the public API or to authenticated users who do not have the matching access rights, ie. not to speakers, but to reviewers!) that are very hard to build in a generic fashion. Users, when creating a generic field, would also have to be able to select access rights, display method, display place and many other factors (title, identifier, help text, email integration, etc)

I'd be willing to entertain a plugin API proposal that would make it easier for plugins to add model extensions, if somebody were to write the proposal and commit to providing the plugin API, but even there I can't commit to merging such a PR right now. An issue such as this is very likely to require either a committed developer or external funding.

**Comment by wslyvh** [comment]
Thanks for your detailed feedback!

As also discussed on #1396
I assumed that some of the code from session's questions & answers could be re-used.
But I fully understand the added complexity. 

Your examples are helpful though and would likely solve (some of) our needs.
- are the composite title/link fields for resources introduced in a specific version? It seems our (self-hosted) instance only allows for file uploads, with a description. 
- I do believe that something like optional video urls (even without embeds) would be useful. It also sounds like this is something that could be solved using above composite fields tho. So not too much of a concern.
I'll have a look into the mentioned plug-ins as well.
- Regarding internal notes, are you referring to the session's review system? I'm not sure that would be useful for our case, but maybe that's my lack of understanding of it. What we'd like to do is add speakers telegram handles. For most speakers, this is private info and should be handled similarly as someone's email address. Only specific roles / organizing team should be able to view this. But there might be other/better ways to solve this?

**Comment by wslyvh** [comment]
Got it. 

I see there are a few other features and improvements on the next' release notes that would be useful.
If we'd like to experiment with the development version, I assume we can use the main branch, correct? 

Also curious if there's a planning for next release yet? Is there a release schedule or progress tracker?

**Comment by rixx** [comment]
> If we'd like to experiment with the development version, I assume we can use the main branch, correct?

Yes. You can find instructions on how to install it in the administrator / update section of our docs.

> Also curious if there's a planning for next release yet? Is there a release schedule or progress tracker?

Neither a schedule nor a progress tracker – I was meaning to release the next major version by the end of 2022, but didn't get the big schedule editor rewrite done in time. I'll *probably* release the next major version once that's done (tracking at #1340).

pretalx development is mostly subject to sponsoring/commissions or me having some free time (rare). I've actually managed to secure funding for a writable API, so depending on the time frames involved, it might be that the next major release will *also* include the writable API, in which case I'd expect a release in late July or late September (no development time in August).

**Comment by wslyvh** [comment]
Good to know. Thank you! And appreciate all the work!
