### ISSUE TITLE
Team invite link - account creation fails

### ISSUE THREAD

**Issue by loelkes** [pretalx/pretalx#140]
Hello,

if I invite someone and he creates an account, the server gives an error page, but the account exists but is not inside a team and the invitation link is still there.  Where can I see the logs from pretalx, i've followed the default install guide.

**Comment by rixx** [comment]
Log files are located at `/var/pretalx-data/logs/pretalx.log` or a similar location. Feel free to post the tracebacks here or send them via mail if you prefer that.

**Comment by loelkes** [comment]
This is what i got. 

> ERROR 2017-09-18 13:08:17,585 django.request exception Internal Server Error: /orga/invitation/fntwijg8sp9wysag66uj
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/src/pretalx/orga/views/settings.py", line 191, in get_context_data
    invitation_token=self.kwargs.get('code'),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
pretalx.person.models.permission.DoesNotExist: EventPermission matching query does not exist.

**Comment by rixx** [comment]
Ah, huh, I thought this was tested, but apparently a recent change introduced an error. I just pushed a fix, the test will come in later.

The demo instance seems to be working again, too, so if you'd prefer to use that, ping me per mail with an event name. :)

**Comment by loelkes** [comment]
Thank you <3

I got the setup up and running, thanks for the offer :)

**Comment by loelkes** [comment]
![screen shot 2017-09-21 at 11 16 29](https://user-images.githubusercontent.com/231909/30688456-7e61df4a-9ebe-11e7-96ce-ee6f43f9b501.png)

The event name is cut out because it's not public yet. If i replace the link by hand (it should not be localhost) everything else works. I can try to look at the code but just wanted to leave this here in case some else stumbles across it.

**Comment by rixx** [comment]
The current settings file format is undocumented because it is only as old as about a week, but …

You'll either need a `~/.pretalx.cfg` or `/etc/pretalx.cfg` with at least:

```
[site]
url = https://my.url
```

This will then resolve the links correctly etc.

You can also add in a database section if you do not want to use sqlite:

```
[database]
backend = {{ pretalx_database_backend }}
name = {{ pretalx_database_name }}
user = {{ pretalx_database_user }}
password = {{ pretalx_database_password }}
host = {{ pretalx_database_host }}
port = {{ pretalx_database_port }}
```

**Comment by loelkes** [comment]
OK. The initial problem from the issue seems resolved and works here.

**Comment by rixx** [comment]
I'll keep the issue open until the fix has its test. Thank you for reporting!
