### ISSUE TITLE
Python client for pretalx

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#1415]
### Problem and impact

Using the rest API is nice, but having python methods to do the things is better (or at least, I prefer it). We had a discussion about that in the before times (https://github.com/pretalx/pretalx/issues/773) and forgot about it.  As hack.lu will come back this year, and we're planing to use pretalx again, I thought it is a good time to bump this one up again.

### Proposed solution / feature

I have this code as a baseline from 2019, but will probably rewrite it next time I need to automate something: https://github.com/CIRCL/pypretalx

Would you still be interested in moving this repo to pretalx? Not immediately, as I'm not sure the code is even working, but in the next few months, maybe?

**Comment by rixx** [comment]
If there is working code, then we can definitely talk about it! It basically comes down to how maintainable the code is, and if there's any of you who would be willing to do active maintenance on it. (Caveat that pretalx is getting a writable API this year, hopefully, so complexity in a client will go up.)

I'm closing this issue, just for repository maintenance, but feel free to ping me here or via email once you think the code is ready, and I'll be happy to take a look!

**Comment by Rafiot** [comment]
All good, I'll get this code to something usable (at least for me at first), and we can discuss again when it's there.
