### ISSUE TITLE
Limit the times for when a speaker can select their availability

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1418]
### Problem and impact

If you have an event which is supposed to run between 16:00 and 21:00, you can not limit speakers to only add their availability in that time range. This allows speakers to enter availabilities which are nowhere near the event times, thus creating unneeded opportunities for scheduling, especially if the "wrong" availabilities are only noticed after accepting the talks.

### Proposed solution / feature

Pretalx should offer some sort of time selection to limit the upper and lower bounds for selecting availability.

This could be done by combining the room availabilities (meaning you can only be available if atleast one room is available too) or simply adding a 'time' value to the event start and end times.

### Context or examples

As discussed in #1362

**Comment by rixx** [comment]
I'm more inclined to grouping room availability here, because start and end times will be annoying for multi-day events (plus we don't need to change the data).

Sadly, this will run up against our use of a fairly old version of the js library (and updates looked *really* annyoing to get right).
