### ISSUE TITLE
Moment Timezone database seems out of date

### ISSUE THREAD

**Issue by sparunakian** [pretalx/pretalx#1421]
### Problem and impact

In the schedule availability widget, if you set a new time slot and save, the time slot is offset. It seems the problem occurs if the event is in a timezone with a DST and the event is in a DST and you are not (or vice-versa).

Updating the timezone definition in the Moment Timezone library fixes the issue. Given the filename (moment-timezone-with-data-2012-2022.js), it seems that the database doesn't cover 2023 and beyond.

I can try to provide a MR next week if useful.

### Expected behaviour

The time slot should stay at the same slot after saving.

### Steps to reproduce

1. Create an event in a timezone with a DST (Europe/Paris in my case)
2. If the timezone is not in DST, create the event in DST.
3. Got to a schedule availability widget for a speaker or a room.
4. Add a time slot, save and the time slot is offset.

### Browser (software, desktop or mobile?) and version

Firefox Desktop 109.0.1

### Version

2.3.1 and main

**Comment by rixx** [comment]
Thanks! I was about to sit down and figure out what's going on with the wonky timezones.

**Comment by sparunakian** [comment]
Thank you for the quick fix!
