### ISSUE TITLE
Submitted + not pending

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1428]
### Problem and impact

I'd like to sort proposals that aren't pending. 

![image](https://user-images.githubusercontent.com/95874/218139078-19d4c517-1f3b-486e-9286-a09ef34c8f31.png)

Not counting the 4 withdrawn talks there are 81, which -65 rejected pending and -13 accepted pending, leaves 3. I'd like to be able to select those three, with `Submitted and not pending`

**Comment by rixx** [comment]
I'm confused: is the "exclude pending" checkbox not exactly what you want?
![2023-03-28T00:41:26+02:00](https://user-images.githubusercontent.com/2657547/228083120-be72ea75-3237-4c85-93c8-4a02aec0f1e1.png)

**Comment by plaindocs** [comment]
Looks like it should, although it isn't immediately clear to me whether that excludes all pending or only pending with the selected states. But I don't think I have that check box either in the Review view or the Proposal view?

**Comment by rixx** [comment]
My screenshot is from the proposal list – it's true that it's not there in the review list, mostly due to space constraints. 

This search box will exclude all pending states from the search – I think everything else would be within the realm of an "advanced search", #1183

**Comment by plaindocs** [comment]
So what am I missing here? 

![image](https://user-images.githubusercontent.com/95874/228204207-63140f06-a6f1-4ace-b583-ff5e55c17f88.png)

**Comment by rixx** [comment]
The checkbox only appears once you've selected a proposal state to filter for. It's currently not possible to exclude all pending proposals in general.

**Comment by plaindocs** [comment]
Aah, fascinating. Thank you!
