### ISSUE TITLE
Wrong results of submission endpoint in case of multiple state filters

### ISSUE THREAD

**Issue by FlorianWilhelm** [pretalx/pretalx#1429]
### Problem and impact

When the [submission endpoint](https://docs.pretalx.org/api/resources/submissions.html#endpoints) is queried using multiple state filters the returned results of the pagination are inconsistent. The `count` doesn't equal the number of returned results after resolving the pagination. 

The screenshot shows that in case of specifying a single state the results are as expected but querying for `accepted` or `confirmed` returns the correct total `count` but a wrong result set.

### Expected behaviour

It should be consistent. `count` should always specify the number of returned results ofter resolving the pagination. 

### Steps to reproduce

1. Query the endpoint
2. Look at `count` and the number of returned results
3. Note that they are different

### Screenshots

![image](https://user-images.githubusercontent.com/3184072/219609210-f2e802ce-b952-45bf-9946-b05c886f967c.png)

### Browser (software, desktop or mobile?) and version

pytanis to query the endpoint

**Comment by rixx** [comment]
Sorry, cannot reproduce. I ran the following script against (presumably) your event, and it printed "88" three times:

```python
import os, requests

proposals = []
count = 0
headers = {
    "content-type": "application/json",
    "Authorization": f"Token {os.environ.get('PRETALX_TOKEN')}",
}
url = f"https://pretalx.com/api/events/{os.environ.get('PRETALX_EVENT')}/submissions/?state=accepted&state=confirmed"

while url:
    response = requests.get(url, headers=headers).json()
    count = response["count"]
    proposals += response["results"]
    url = response["next"]

print(count)
print(len(proposals))
print(len({p["code"] for p in proposals}))
```

**Comment by FlorianWilhelm** [comment]
Sorry, my bad and thanks for this demo code. I found a quite subtle bug in Pytanis where list parameters like `state=["submitted", "accepted"]` are swallowed during the page resolution.
