### ISSUE TITLE
selecting availability on touchscreen devices it is very hard

### ISSUE THREAD

**Issue by navlisilvan** [pretalx/pretalx#1438]
### Problem and impact

When registering as a speaker with a touchscreen device (tablet/mobile phone), it is very hard, almost impossible to select the availability. Many speakers doesn´t manage this.

### Expected behaviour

Some way to make it easier to select availability via touchscreen device. 

### Steps to reproduce

1. try to select speaker availability via touchscreen device. 
2.
3.
4.

### Browser (software, desktop or mobile?) and version

Chrome on mobile phone

### Operating system, dependency versions

Android

**Comment by rixx** [comment]
Updated the calendar library from v3 to v6, which ought to help with the mobile capabilities, hopefully. If not, there's really nothing we can do without trying to build an entire calendar library of our own.
