### ISSUE TITLE
Rename "Track" 

### ISSUE THREAD

**Issue by navlisilvan** [pretalx/pretalx#1439]
### Problem and impact

We use Pretalx as a workshop planning tool for a sports event.
As "tracks" we use the levels of difficulty. there was Confusion several times, because the term "track" is less useful for us and a "level" is more helpful.
All teachers have to choose the level when they register for the workshop. 

### Proposed solution / feature

It would be nice if you can define the term "track" somewhere.

**Comment by rixx** [comment]
I'm sorry, arbitrary renaming of UI components is currently out of scope for pretalx, as this is not a trivial problem, particularly considering translations support, and the fact that words occur in many places (such as help texts, error messages and so on), where they'd also need to be changed.

(It's true that a nearly-stupid search-and-replace would work for this in English, but we *do* try to support other languages appropriately, too.)
