### ISSUE TITLE
Users in Team list is sorted randomly?

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1440]
### Problem and impact

When adding a new user to a team, the pending invite gets added to the bottom of the list.

After the user accepted the invite, the newly created user gets moved to a seemingly random position. For example, i just added two users, one was added at the last position (just before the pending invites), but the second user was added on the fifth-last position.

This makes it very difficult to see which users actually exist if you have very large teams.

### Expected behaviour

Team User list should be sorted alphabetically. Ideally, the table header is clickable, so the user can choose if the list should be sorted by name or by email.

### Steps to reproduce

1.
2.
3.
4.

### Version

git 7c3f8861a0ced94ffb4745c071a6ca3359dc1047

**Comment by rixx** [comment]
Just a note: I would not consider this a bug. It's an inconvenience, and certainly bad UI, but not a bug as such. Particularly "make all the table headers clickable for arbitrary sorting, but remember to keep all the invites at the bottom of the table always" is very much a feature request.
