### ISSUE TITLE
"Secret public link" does not respect event domain

### ISSUE THREAD

**Issue by bonzini** [pretalx/pretalx#1446]
### Problem and impact

Despite setting up a special domain name for an event, the "secret public links" for proposals show the domain name from pretalx.cfg.

### Expected behaviour

Domain name for events is respected throughout.

### Steps to reproduce

1. Create an event
2. Set a custom domain name for the event
3. Create the proposal
4. Look for the "secret public link" under the links dropdown.

### Link

/orga/event/NAME/submissions/CODE/

### Version

2.3.1

**Comment by bonzini** [comment]
The same link is also sent when inviting a co-speaker.

**Comment by rixx** [comment]
Agreed that this isn't great, but it should also not be a problem in practice, as pretalx knows to redirect to event domains, at least in `main`.

(Also I see that you're running 2.3.1 – there has been a security release since then that is highly recommended to install.)

**Comment by rixx** [comment]
Actually, cannot reproduce on `main`: Both on organiser pages and on the speaker page providing the link and the generated email, the correct link is used in pretalx-main / pretalx.com.
