### ISSUE TITLE
When duration field is configured to be mandatory, change help text accordingly

### ISSUE THREAD

**Issue by ligi** [pretalx/pretalx#1447]
### Problem and impact

I see an error when no input is given for the duration

### Expected behaviour

it should use the default length if no input is given like stated in the hint next to the input field

### Steps to reproduce

1.
2.
3.
4.

### Screenshots

![image](https://user-images.githubusercontent.com/111600/225642083-570ee193-67d3-4797-b74d-1186267c8211.png)
![pretalx_problem](https://user-images.githubusercontent.com/111600/225642616-e26f5d2b-2b0e-4be9-811c-cc692a5be831.png)

### Browser (software, desktop or mobile?) and version

brave

**Comment by rixx** [comment]
Impossible to help without knowing details – Your screenshot shows a page where the duration is marked as mandatory, as indicated by the missing "Optional" below the label. Requiring the input of a non-optional field is correct behaviour. Normally, the duration field is not required: 
![2023-03-16T23:05:23+01:00](https://user-images.githubusercontent.com/2657547/225763169-4d2f6d20-adaf-41ea-9caf-0aa31975e3c8.png)

To re-open, please provide a minimum of context as asked for by the issue form:

- Which page is this on? CfP submission? Submission edit?
- What is your permission context – speaker, organiser?
- Which pretalx instance / version is this?
- If you have organiser permissions: Have you set "Duration" to be "required"?

**Comment by ligi** [comment]
I would still consider this a bug then - at least the hint text. It states "Leave empty for default duration" - but in case of having this field mandatory this is not an option. So I think this should be reopened ..

**Comment by ligi** [comment]
- Which page is this on? CfP submission? Submission edit?
 CfP submission
- What is your permission context – speaker, organiser?
 organizer - but can test with speaker only - guess it will also happen then
- Which pretalx instance / version is this?
will query this - or can I see it in the interface somewhere?
- If you have organiser permissions: Have you set "Duration" to be "required"?
 happens when "requred" - it behaves correctly when "optional"

**Comment by rixx** [comment]
I agree that the text could be phrased better to accommodate mandatory texts, then, though that is more of a UI issue than a bug. Thank you for providing further context.

**Comment by ligi** [comment]
thanks for reopening - yea more like a UI issue - just felt like a bug on the first encounter.
