### ISSUE TITLE
"Review" is ambiguously used for both feedback and the process of accepting talk submissions

### ISSUE THREAD

**Issue by MikkCZ** [pretalx/pretalx#1449]
### Problem and impact

The term _review_ is used in pretalx in two places - to describe the feedback process from the attendees/visitors to speakers, but also in the context of accepting/rejecting talk proposal submissions by the organization team.

The ambiguity is especially notable during localization process, and given how gettext works, there might even be the same string used for both feature, which is limiting the flexibility for locales to translate the terms differently. Which is Czech for example there is no single words that would fit in both contexts without actually increasing the ambiguity even compared to English.

### Expected behaviour

I am not a native English speaker, but it would be nice to have two different terms for these two contexts. One solution that I think would be acceptable is to just go with _feedback_/_to provide feedback_ instead of _review_ in the context of giving a post-event feedback from attendees to the speakers.

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
I'd be happy to use clearer wording here – however, "feedback" would be just as ambiguous, as pretalx supports *post-event* feedback under that name.

Maybe we ought to rename the page to "preview"? As that's what it is, in the end.

**Comment by rixx** [comment]
If I'm not mistaken, the double meaning was only in a single place (I hope?), because I really tried to make sure that it's always "review" for organiser reviewers and "feedback" for attendees.
