### ISSUE TITLE
Tests are failing both locally and in Github Actions

### ISSUE THREAD

**Issue by MikkCZ** [pretalx/pretalx#1452]
### Problem and impact

https://github.com/pretalx/pretalx/actions/runs/4389337240 - broken by https://github.com/pretalx/pretalx/commit/52b674b93960d73a2c05eea80058726009508fbd

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
Please don't open an extra issue for failing checks. The failure in itself are the action item; additional open issues aren't necessary.
