### ISSUE TITLE
Markdown Docs Guide not working as expected

### ISSUE THREAD

**Issue by Rufus125** [pretalx/pretalx#1458]
### Problem and impact

https://docs.pretalx.org/en/latest/user/markdown.html
1. 
* First item
* Second item which is too long to
  fit in a line
* Third item

does not show bullet points:

First item

Second item which is too long to fit in a line

Third item

2.
Look at [this](https://pretalx.com). 

translates to only text:
Look at this.

No Link under "this"

3.
Also, another question: is it possible to indent bullet points?

* first level
  * second level

like here on Github?

### Steps to reproduce

1.
2.
3.
4.

### Link

https://docs.pretalx.org/en/latest/user/markdown.html

### Browser (software, desktop or mobile?) and version

Browser, chromium based

**Comment by rixx** [comment]
![2023-03-28T12:26:43+02:00](https://user-images.githubusercontent.com/2657547/228207823-e59c6e11-03be-4c71-a5c1-96eed6fa929d.png)
