### ISSUE TITLE
Widget does not auto-adjust format to list when there are more than two rooms

### ISSUE THREAD

**Issue by MikkCZ** [pretalx/pretalx#1464]
### Problem and impact

When the schedule is to wide to fit into the page, it starts overflowing the page, instead of correctly changing the layout to "list" as it's actually implemented in the code.

### Expected behaviour

When the 3 rooms don't horizontally fit into the window, the format automatically changes to "list", or the parent element gains `overflow-x: auto`.

### Steps to reproduce

STR:
1. Have a schedule with 3 or more rooms.
2. Add widget to a page (arbitrary).
3. Load the page with the widget.
4. Start shrinking the browser window horizontally.

### Link

https://openalt.gitlab.io/openalt-cz/program/#

**Comment by MikkCZ** [comment]
The issue is here

https://github.com/pretalx/pretalx/blob/f26a6581dfe34b1b8847f40f6cbd41cceb51c903/src/pretalx/static/agenda/js/pretalx-schedule.js#L16284-L16286

where it always counts two rooms. The correct code would probably be

```js
    showGrid() {
      // if we can't fit two rooms together, switch to list
      const minimalRequiredWidth = (78 + this.schedule.rooms * 316);
      return this.scrollParentWidth > minimalRequiredWidth && this.format !== 'list';
    },
```

Another part of the problem (but way smaller) is that the code only takes into account the width of the body, not the parent element.

https://github.com/pretalx/pretalx/blob/f26a6581dfe34b1b8847f40f6cbd41cceb51c903/src/pretalx/static/agenda/js/pretalx-schedule.js#L16455-L16457

I am not familiar with the shadow DOM, but I assume there is a way to get the DOM element where the shadow root is rendered ([maybe something like this?](https://stackoverflow.com/questions/25339932/get-shadow-root-host-element)) and read `.offsetWidth` on that element instead of `document.body`.

**Comment by MikkCZ** [comment]
@rixx I haven't found the original source code for the widget, only `pretalx-schedule.js` and its minified "brother" next to it, but not how to update them. Where is the original source code and how to compile it, please?

**Comment by MikkCZ** [comment]
Btw. I prepared a temporary workaround for us before this gets fixed in Pretalx. I haven't deployed it yet, so the link above still reproduces the issue. The workaround is to add the following snippet to the page.

```html
<script>
  /* workaround for https://github.com/pretalx/pretalx/issues/1464 */
  function _updatePretalxScheduleFormat(minimalRequiredWidth) {
    if (document.body.offsetWidth > minimalRequiredWidth) {
      document.querySelector('pretalx-schedule').setAttribute('format', 'grid');
    } else {
      document.querySelector('pretalx-schedule').setAttribute('format', 'list');
    }
  }

  fetch('https://talks.openalt.cz/pretalx-test-event/schedule/widget/v2.json')
    .then((response) => response.json())
    .then((data) => {
      const minimalRequiredWidth = 78 + (data.rooms.length * 316);
      _updatePretalxScheduleFormat(minimalRequiredWidth);
      window.addEventListener('resize', () => {
        _updatePretalxScheduleFormat(minimalRequiredWidth);
      }, true);
    });
</script>
```

**Comment by MikkCZ** [comment]
FYI I attempted to add `overflow-x: scroll` to prevent breaking the whole layout while allowing the grid layout to still be used. But adding that either to `pretalx-schedule` or it's parent day navigation (`bunt-tabs days`) - they just do nothing then.

**Comment by rixx** [comment]
> Where is the original source code and how to compile it, please?

`pretalx-schedule` lives at [pretalx/schedule](/pretalx/schedule).

**Comment by MikkCZ** [comment]
I have no prior experience with Vue.js, but I managed to patch the code including calculating the size from the parent element instead of the HTML body. Hopefully it does not break any existing functionality.

**Comment by rashfael** [comment]
Having a grid schedule overflow horizontally and only switching to the list view when 2 rooms wouldn't fit is by design.
We wan't grid schedules to scroll horizontally.
"2 rooms wide" is the responsive breakpoint we chose for small screens.

**Comment by MikkCZ** [comment]
Thank you for the explanation. As the value was hard-coded and not computed in widget, I assumed it was some shortcut during development, but I see it's on purpose.

There is another issue with the widget, and that its overflow behavior. For example on https://installfest.cz/if22/program.html (same happens with the current version of Pretalx) when you reduce the width of the window to 900px or less, and scroll the page vertically, you'll the whole page is scrolled, not just the widget, and the layout of the page does not actually account for that. I.e. the widget does not honor the parent element size restrictions.

![obrazek](https://user-images.githubusercontent.com/3941344/233845362-f7a75f30-fe97-4bd1-9d62-e4e58b474989.png)

What's the most interesting is it's fixable by adding `overflow-x: auto` to a parent element, in which the widget is embedded, but it only works form DevTools after the widget is rendered. If I make it direct part of the CSS and then the widgets gets rendered into such element, the date navigation on click stops working.

I can probably provide a better test case inside the schedule repository directly, if you'd like.

**Comment by rashfael** [comment]
The widget tries not to create its own scrollbars and will either track the global scrollbars or the nearest overflowing parent. Depending on what layout is desired, it's up the host page to provide scrollbars. We can probably do a better job explaining this in the docs.

That only adding `overflow` via devtools is working sounds like a css load order problem, but if you think that's a problem with the widget itself, please open a new issue.
