### ISSUE TITLE
Authors to be notified about changes to their submission

### ISSUE THREAD

**Issue by bsipocz** [pretalx/pretalx#1465]
### Problem and impact

When organizers changes e.g. the "Session type" for a submission, authors gets no notification about it. E.g. submission as a talk get accepted as a poster still gets the "accepted" status, and no indication whatsoever that it's not the same submission any more that the authors proposed.

This can be viewed either as a bug or a missing feature, from the user's POV I'm more inclined toward the bug. 

- history shows that the organizers modified the submission, but there is no way to diff it with the original
- it would be useful to have more fine-grained statuses, e.g. `accepted-with-modifications` would tick all the boxes for the scenario above

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
pretalx is *very* rarely sending out emails without direct organiser oversight – I don't think that this is something we will change. The only email that is sent without organiser input is the "we received your proposal" email, at the moment.

I think this problem should be covered by introducing better history display (re: #400 ).
