### ISSUE TITLE
Provided fonts lack glyphs from extended Latin set

### ISSUE THREAD

**Issue by oskar456** [pretalx/pretalx#1473]
### Problem and impact

When running pretalx instance with Czech translation, some glyphs of the font Titillium are not provided by the web application and get replaced by some alternative. This makes the pretalx interface unnecessary ugly. See screenshot with character `ě` being substituted.

Both fonts are available with extended Latin glyphs. It just seem that those have been stripped from the `woff` files served by the frontend.

### Steps to reproduce

1. Use a computer without fonts Titillium or Muli installed.
2. Open pretalx admin interface.
3. Switch to Czech language
4. See all `ě`s, `ř`s and similar characters substituted from a different font.

### Screenshots

<img width="173" alt="Screenshot 2023-04-28 at 10 40 01" src="https://user-images.githubusercontent.com/816717/235100148-2a899e5d-3af1-41dd-935c-a2beb883d49b.png">

### Browser (software, desktop or mobile?) and version

Chrome on macOS

### Version

main branch as of 2023-04-28

**Comment by rixx** [comment]
> Oh my #1240. :cry: 

I'm afraid I don't quite understand what you mean by this. Like stated in that discussion, there is a tracking issue at #1242. pretalx is open source – contributions to that end are welcome.

**Comment by benabraham** [comment]
@rixx Thank you for your quick reaction and adding at least the latin extended set font.

To explain: that was just an expression of emotions that the discussion in #1240 made me feel about possibilty of changing anything soon enough.

I’m probably to much of a designer and frontend dev to understand the importance of the need to block so many things that would make my work easier and feel frustrated about it.
