### ISSUE TITLE
Work with short talks

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#148]
Short talks (shorter than 25-30 minutes) have two problems:

- [ ] In the scheduling view, you cannot see the title of the submission you are positioning
- [x] In the agenda view, you cannot see it either

I think the best way to handle the scheduling view would be to show it on hover, since having proportional display there is really important.

In the agenda view, though, we should consider showing always at least one line of text. But this introduces the problem of positioning visually (but not actually) overlapping talks in the agenda view.

**Comment by luto** [comment]
![image](https://user-images.githubusercontent.com/2158203/31535516-a2d522bc-affb-11e7-9cd2-189b02809687.png)

This can also be a problem for talks >= 30 minutes, if they have a long enough title / speaker list.
