### ISSUE TITLE
OGP metadata contain invalid local domain

### ISSUE THREAD

**Issue by raoulb** [pretalx/pretalx#1481]
### Problem and impact

In the exported schedule html files, at least one OGP URL points to `testserver` which is obviously wrong.

Example: `<meta property="og:url" content="http://testserver/myeventname/schedule/">` where I replaced the event name by `myeventname` only.

Note that I've set the html export URL to a custom value with host and path part.
See also #1480, I found this during investigation of the other issue.

### Expected behaviour

An URL pointing to the correct resource, having the configured host part.

### Version

v2.3.2

**Comment by rixx** [comment]
Fixed in 44f5d9e.
