### ISSUE TITLE
Merged Schedule Presentation of multiple Events

### ISSUE THREAD

**Issue by margau** [pretalx/pretalx#1488]
### Problem and impact

For GPN21, we have two events: One for the CFP (Talks and Workshops), and one for the lounge act.
This is useful, as we have multiple separate teams managing those, and an entirely different workflow.

However, we have the need to show the resulting schedules together to conference visitors.

### Proposed solution / feature

Ideally, we have a "merged schedule presentation", which combines the latest schedule releases of both/all selected events, and presents it together via HTML/JSON/XML to the user.

This issue is primarily intended to check if this is feasible, and, if yes, we'd try to develop this for GPN21.

**Comment by rixx** [comment]
I'd be tentatively down to merge a feature like that, though it would maybe better to first develop it as a plugin as proof of work – merging plugins back into pretalx is pretty easy, and it makes it easier for whoever is building this to experiment with UI approaches.

(That said, if somebody already has a fully-formed idea how to implement this, we can also skip the plugin step. Consider though, that merging the data is the easy part, and discoverability in pretalx, as well as access right  management to multiple events and proper update handling with two sources is the harder part.)

**Comment by rixx** [comment]
Closing until there is a) more demand, b) a clearer sense of permissions handling, or c) proof of work as a plugin, as there hasn't been much demand for this in the past year. Happy to re-open when any of the above happens!
