### ISSUE TITLE
Flapping review link button on submissions page

### ISSUE THREAD

**Issue by riotbib** [pretalx/pretalx#1497]
### Problem and impact

The button for copying the review link on the submissions page is flapping for me.

### Expected behaviour

The button shouldn't flap, but copy the review link to the clipboard.

### Steps to reproduce

1. Go on the submissons page under `/$EVENT/me/submissions/`.
2. Hover over the review link button.
3. The button flaps.

### Screenshots

https://github.com/pretalx/pretalx/assets/43172581/3fec83b4-18fb-4abe-87ff-567778c7e3c2

### Browser (software, desktop or mobile?) and version

Mozilla Firefox 113.0.2 (64-bit)

### Operating system, dependency versions

macOS Ventura 13.2.1 (22D68)

**Comment by rixx** [comment]
Tried with Firefox and Chrome, and cannot reproduce, sorry.
