### ISSUE TITLE
Unconfirmed events appear on speaker profile page

### ISSUE THREAD

**Issue by raoulb** [pretalx/pretalx#1498]
### Problem and impact

When releasing a public schedule, accepted but not (yet) confirmed events do not appear on the schedule view (which is correct) but get listed on the profile page (`/speaker/*`) of a speaker (which is obviously wrong). This happens if the speaker profile page is public because there are other (confirmed, hence visible) events from the same person.

### Expected behaviour

Do not show unconfirmed events in public schedules, independent of the view (`/schedule/*`, `/talk/*`, `/speaker/*`).

### Version

v2.3.2

**Comment by rixx** [comment]
Yikes, no idea how this got through for *years*. Thank you for reporting!
