### ISSUE TITLE
Inconsistent talk numbers

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1499]
### Problem and impact

I want an indication of how many submissions there are :-p,m with consistent treatment of withdrawn and cancelled

### Expected behaviour

- https://pretalx.com/orga/event/ shows 60 
- https://pretalx.com/orga/event/most-recent-event/ shows 55 (edited url)

I think the second number is "more correct", unless you're showing a detailed view also showing totals of withdrawn and cancelled.

I've got vague memories of a third place, but can't find that, so probs ignore. 

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
Will be deployed during Sunday's maintenance window.

**Comment by plaindocs** [comment]
:sparkles: thanks! :sparkles:
