### ISSUE TITLE
Bleach is deprecrated

### ISSUE THREAD

**Issue by mweinelt** [pretalx/pretalx#1502]
### Problem and impact

The upstream announced that the library is deprecated and recommends consumer to look elsewhere for a replacement.

### Expected behaviour

Security relevant libraries consumed should be supported.

### Steps to reproduce

https://github.com/pretalx/pretalx/blob/bd7c792588fbdfb0aa7f4aab4e468d59964b2bf8/src/setup.py#L97

### Screenshots

n/a

### Link

https://github.com/mozilla/bleach/issues/698

### Version

2.3.2/master

**Comment by rixx** [comment]
> Security relevant libraries consumed should be supported.

Bleach explicitly will continue to add security fixes, updates for new Python versions, and even bug fixes for really bad bugs. It's in the issue you linked.

I'm of course happy to merge a contribution that replaces our use of `bleach` with something else that provides an equivalent set of features and APIs, if you have something in mind that you'd like to see in pretalx, but until then, we'll stick with bleach.
