### ISSUE TITLE
"all day" availability does not work when limiting availability by room availability

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1504]
### Problem and impact

When limiting the availability speakers can enter in the CfP, the bar below the title of the time selector is white, indicating the speaker can click that to indicate they are available for all times on that day.

However, clicking on the bar simply does nothing.

### Expected behaviour

The bar should either be greyed out, indicating it cannot be clicked, or (better) just select all available times during that day.

### Steps to reproduce

1. Create a new proposal
2. During creation of the speaker profile, click the bar between the date display and the time selector
3. Nothing happens.

### Link

https://talks.seibert-media.net/tools4agileteams-2023/cfp

### Browser (software, desktop or mobile?) and version

Firefox and Chrome atleast, but i believe this is not client specific

### Version

git d80da6245984097959919344ec1fad9770b3bde8

**Comment by alangecker** [comment]
Got the same issue. It seems like the availability gets constrained to 00:00-23:59 to say that the full day is available, but fullcalendar then creating a one minute unavailability range (23:59 till 00:00, see screenshot)  and, as far as  I understand it, only offers the full day bar on days without any unavailability.

So even though the full day is available, the bar doesn't work.

![grafik](https://github.com/pretalx/pretalx/assets/10246027/199baaf8-84fe-4252-8d61-03463c156db5)

I wonder why this is rather an issue with full calendar than pretalx?

**Comment by rixx** [comment]
It's probably an issue at the intersection of the two.

**Comment by rixx** [comment]
Ah, it is not – we use FullCalendar's `constraint` feature for this, which can only operate on weekdays (not dates), so what we pass is

```js
constraints = [
	{
		daysOfWeek: 4,
		startTime: "00:00",
		endTime: "23:59"
	}
]
```

Which is bad and should change anyway, but I haven't as yet found a way to make it work. Technically, FullCalendar supports constraints that are more sensible, as I've tried in 5cca010d, (see [documentation](https://fullcalendar.io/docs/eventConstraint)), but I can't get it to work. If any of you have the time to play with that commit and see what needs to change to make the stupid thing cooperate, I'd be more than thankful.

As an alternative, I hate to say it, but we could also do the inverse: Create a lot of constraints that are **not** allowed, and place them and set `overlap: false`, as in [this demo](https://codepen.io/pen?editors=001). I'm fairly sure that might actually work? All that would be needed is the `invert` code for availabilities …

**Comment by rixx** [comment]
Just FYI: my next two weeks are extremely busy, so I'll likely be unable to address this issue before then. If either of you two (or anybody else) has the time to

- a) try my branch and see if I'm missing something obvious with FullCalendar, and bring it from half-working to fully working, or
- b) pursue my second suggestion of blocking out time rather than allowing it,

I'd definitely find the time to look at and merge a PR.
