### ISSUE TITLE
Assign talks by track to particular reviewers

### ISSUE THREAD

**Issue by dariagrudzien** [pretalx/pretalx#1505]
### Problem and impact

When trying to assign talks to reviewers in the UI, currently I need to select them title by title. This is tedious and error-prone at scale.

### Proposed solution / feature

Ideally, on the `/reviews/assign/` page I'd like to be able to select a whole track and assign it to a particular reviewers. This should work in addition to assigning individual proposals.

### Context or examples

We have 3 different tracks and reviewers who specialize in some of them. I wish I could review full tracks like this:
Reviewer 1 - tracks A & B
Reviewer 2 - track B
Reviewer 3 - tracks A & C
Reviewer 4 - all tracks

Hope this makes sense.

**Comment by rixx** [comment]
You can simply add reviewers to teams that are limited by track. That's not the same as an assignment, but it will only permit them to see proposals in their tracks, and is a much easier way to map reviewers to groups of proposals.
