### ISSUE TITLE
Don't require Event end time

### ISSUE THREAD

**Issue by FloorD** [pretalx/pretalx#1511]
### Problem and impact

We're using Pretalx for our conferences, but we're also running a semi-regular meetup. For the meetup we'd love to have an always-open call for papers/speakers, to open it up for people that are not in our immediate networks. Right now there's no way of doing that, except for having the end time/submission deadline some time far far away in the future - which isn't a very elegant solution.

![Screenshot (661)](https://github.com/pretalx/pretalx/assets/1087213/acdc3fa4-7f69-4544-b29c-f372465df8e7)

### Proposed solution / feature

By not making event dates and submission deadlines required, we could achieve this and use Pretalx for all events - conferences and meetups.

**Comment by rixx** [comment]
Sorry, this is out of scope for pretalx for now. We would have to make significant changes to our schedule display and schedule editor to support ongoing events that would span weeks or months. Neither the schedule editor nor the schedule display is equipped for this kind of thing.

(Even if we chose to support this, I assume we would have "sub events" with a shared CfP or something like that – but that would be a major change and would require sponsoring or outside contributions.)

Closing as out of scope, might re-open if we find support for the idea or our focus changes.
