### ISSUE TITLE
use of global_settings for content_locale options prevents settings from being applied

### ISSUE THREAD

**Issue by stuebinm** [pretalx/pretalx#1514]
### Problem and impact

When adding a new language to LANGUAGES_INFORMATION in `settings.py`, the new language does not show up in the Content Language menu under `/orga/event/<name>/settings/`, as the `choices` of the `content_locales` multiple choice field is set to `global_settings.LANGUAGES`, not `settings.LANGUAGES`.

(I am opening this as an issue and not a PR since I'm unfamiliar with django, and I assume there may well be a good reason to do it this way which I do not know — but afaict, [use of global_settings seems to be discouraged](https://docs.djangoproject.com/en/4.2/topics/settings/#using-settings-in-python-code); if there's interest, I can open a PR for removing its use from pretalx)

### Expected behaviour

Conference organisers should be able to set the new language as a possible language for submissions in the event's settings.

### Steps to reproduce

1. add a new language to `LANGUAGES_INFORMATION` in `settings.py`
2. run `python manage.py runserver` (e.g. with the example event)
3. go to `http://127.0.0.1:8000/orga/event/democon/settings/`as an admin/organiser
4. the newly-defined language cannot be set as a possible choice in the "Content languages" field

**Comment by rixx** [comment]
pretalx does not support adding new languages by users manually adding them to `settings.py`, sorry. Please either provide a PR to add a language to pretalx, or add your language as a plugin language.

**Comment by rixx** [comment]
To elaborate: You *cannot* replace `global_settings.LANGUAGES` with `settings.LANGUAGES` here, as that would restrict available content locales to only languages pretalx is available in. This is not what we want – there are plenty of languages that we don't have the bandwidth to maintain a translation for, but that people still want to offer in a language select dropdown for the proposal content language.

Just to make sure I'm understanding you correctly: you're adding a new language that is not a "usual" language (ie that is not a part of Django) **and** you're not adding it via a plugin locale, and istead choosing to patch pretalx itself? (The choices collection already respects plugin locales and adds those to the list, after all!)

Good thing it's a Friday night, so I added support for odd patched-in languages (but please consider using plugin locales).

**Comment by stuebinm** [comment]
> Just to make sure I'm understanding you correctly: you're adding a new language that is not a "usual" language (ie that is not a part of Django) and you're not adding it via a plugin locale, and istead choosing to patch pretalx itself? (The choices collection already respects plugin locales and adds those to the list, after all!)

Yes (the context for this was: an event needs support for sign languages in submissions. Since those (usually) don't have a standard writing system that the interface could possibly be translated into, it seemed odd to also have them show up in the 'available languages' menu for the event's interface. There's some further hackery I did to make that work, but I considered that to not be relevant for most deployments, and only reported the above, which appeared to me to be a bug)

**Comment by rixx** [comment]
I'd always prefer for non-fork solutions to be found to problems like this, but in any case, I hope the patch I committed earlier today helps.
