### ISSUE TITLE
Availability calendar broken: e.start.format is not a function

### ISSUE THREAD

**Issue by alangecker** [pretalx/pretalx#1519]
### Problem and impact

In the speaker edit view I get the following error due to e.start being a `Date` (is there a `Moment` expected) and leading to the availability calendar being unresponsive to any attempts to create a new availability.

`TypeError: e.start.format is not a function`
![grafik](https://github.com/pretalx/pretalx/assets/10246027/0b4e431c-205e-4b05-bcc7-a9f077bae0db)

### Steps to reproduce

I'm currently not able to narrow down whats needed for a reproducible setup. If people have difficulties to reproduce it, I could investigate it further

### Version

https://github.com/pretalx/pretalx/commit/1b47902b5a4753efce7b5481f7e9ce74bc74dc6c

**Comment by rixx** [comment]
Only occurred when the user was in a timezone with 0 offset to UTC.
