### ISSUE TITLE
Makes proposal title and additional speakers from step 1 optional

### ISSUE THREAD

**Issue by ChAoSUnItY** [pretalx/pretalx#1522]
### Problem and impact

Currently my team on [ocftw/oscvpass](https://github.com/ocftw/OSCVPass) are working on using pretalx to organize the applications for open source contribution. There are several fields such as `proposal title` and `additional speakers` are unused and we would like to remove them, however, in current implementation, it seems that they are not able to be marked as `Do not ask`.

### Proposed solution / feature

Idealy, we would like to see that  `proposal title` and `additional speakers` are able to be optional.

Since the first one must exists in order to render on the proposal entry list, I would like to see that the proposal name could be replaced with other questions, e.g. contribution repository's name.

**Comment by rixx** [comment]
You can already hide the "additional speakers" field, as well as the recording opt-out: 
![2023-07-14T17:54:19+02:00](https://github.com/pretalx/pretalx/assets/2657547/6bc75687-0217-4888-b178-47962b21ab33)


Titles will never become optional, as pretty much all parts of pretalx rely on there being a talk title. In fact, it's one of the very few non-nullable fields in the Submission model. If having empty titles is a requirement for you, I'm sorry, but you'd have to fork pretalx, make the field nullable and figure out all the places where a title is assumed as a given. If you get it to work in your fork, and the maintenance impact isn't too big, we can talk about merging it back.

(I can see a future development of pretalx where there will be a hidden/automatically generated title, but that future is not now, as the added maintenance burden far outweighs the use imo.)

**Comment by ChAoSUnItY** [comment]
I see, thanks for your reply. But I still have one more question, is there any release schedule for the next major version?

**Comment by rixx** [comment]
No, there is no release schedule.

**Comment by rixx** [comment]
Update: there is a release schedule! The next version, a major release with many new features, will be out by the end of August.
