### ISSUE TITLE
Make questions exportable & importable

### ISSUE THREAD

**Issue by ChAoSUnItY** [pretalx/pretalx#1528]
### Problem and impact

We're currently making a seasonal CfP that heavily depends on questions, which will seasonally restart. However, currently it seems documentation doesn't provide any reliable way to save this high repeatability work.

### Proposed solution / feature

Ideally, introducing a way to export & import questions could save time on copy pasting questions from previous season.

**Comment by rixx** [comment]
I'm not sure if you mean "questions" or "answers to questions", so I'll answer both:

## Exporting and importing questions

Questions cannot currently be exported or imported at all, and this is not expected to change until the API rewrite. However, when you create a new event, you can choose to copy an old event's data, which will copy questions to the new event. As that is your described use case, that should do the job.

## Exporting and importing question answers

You can export question answers via the export functions of proposals and speakers, depending on what the question is targeting, plus also via the API.


You can import question answers. This is not documented, as it was a one-off implementation for a paying customer, and not in line with how a consistent API behaves. This will also change with the API rewrite. Until then, you can `POST` to the `/answers/` endpoint. You can query the endpoint to see the expected format; the required data fields are `question` (ID of the question you're creating an answer for), any of `review`/`submission`/`person` (depending on the question type; the related object), and `answer`. Note that this is not available for questions with selectable options (choice/multiple choice).

Once we are rewriting the API to be fully writable, importing question answers via the API will be possible, too.

**Comment by rixx** [comment]
As an addition for people who come across this issue: As of now (and to be released in v2024.01), pretalx can import question *options* (for select/multi-select questions) from text and JSON files.
