### ISSUE TITLE
Mark problematic talk slots in orga scheduling view

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#153]
Problematic/conflicting talks should be marked (orange border?) visibly in the schedule editing view, and show the problem on hover (maybe a warning sign to hover on). The issues should also be listed in a pre-release view appearing when trying to release a schedule with active issues.

The implementation of this concept is discussed in #214, this issue tracks the front-end side of things.

**Comment by rixx** [comment]
This is especially relevant for the barcamp mode, as it does help the participants directly.

**Comment by MacLemon** [comment]
Maybe even have a default time-buffer that a speaker cannot be expected to meet when rushing from one room to the next because tearing down the speaker's laptop, packing up, physically moving in a potentially large area or building, and setting everything up again may take quite some time.

**Comment by rixx** [comment]
A simple version of this is now implemented, more detailed checks will come with #214.
