### ISSUE TITLE
Make login/registration page password manager friendly

### ISSUE THREAD

**Issue by Valodim** [pretalx/pretalx#1534]
### Problem and impact

The login and registration forms are both on the same page, and share a `<form>` element. That's not a technical issue per se, but throws off the login form detection algorithms of password managers since they'd have to distinguish different sets of inputs for different purposes.

(It's also semantically less nice markup than it could be, but that alone certainly wouldn't be worth any effort :shrug:)

![image](https://github.com/pretalx/pretalx/assets/27813/648e6b71-fff7-4553-b55b-bbea1620ea3a)

### Proposed solution / feature

Use two separate `<form>` elements for the login and registration forms

### Context or examples

pretalx logins are bound to events thus fairly short lived by nature, so it's particularly convenient to have a quick signup/login process.

**Comment by jfowl** [comment]
It may already/also help password managers (including in-browser ones) to use the proper `autocomplete` parameters on the inputs:

`autocomplete="username"`
`autocomplete="new-password"`
`autocomplete="current-password"`

- https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values

**Comment by rixx** [comment]
Alright, let's see if using the correct autocomplete hints will maybe fix the password manager problem.

**Comment by Valodim** [comment]
As developer of a password manager, I'll say that it's unlikely. Groups of fields with distinct semantics within the same `<form>` will always yield mixed results at best.

Worth mentioning also, that the autocomplete hints are not nearly reliable enough to take for granted - the web is messy, and whatever assumptions you make about them, there will be a page that breaks that intentionally or not. For that reason they are only used as an input to form matching heuristics, not fully relied upon.

Anyways, I'll check if this helped in our case when I see this shipped, and possibly reopen if it didn't. Thanks!

**Comment by rixx** [comment]
Sounds good – thanks! I suppose we can also pull this apart into two HTML forms while keeping the single Django form. How would we indicate which form is which in that case, though? What would help the password manager decide which form is which, if autocomplete hints don't work?

**Comment by Valodim** [comment]
If there are two forms, both of them will be straightforward to detect for what they are :)

**Comment by nicornk** [comment]
Just ran into this issue today that I signed up on an cfp invite link, generated my password in 1Password and 1Password was not able to auto fill the password into neither of the three password fields. I had to manually open 1P, copy the password and paste it twice into the password and confirm password field.

Safari on iOS correctly displayed my username and proposed to auto fill but after clicking the fields remain empty

**Comment by rixx** [comment]
If it is true that using two separate forms on the same page would be enough to fix this problem, then #2301 is the fix in question.
