### ISSUE TITLE
OOM when trying to upload very large profile images

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1540]
### Problem and impact

A speaker tried submitting a talk, which required them uploading a profile picture. They tried uploading a `1484751` bytes (~1.4MB) JPEG image, which is sized 5082x6265 pixels in dimension. Pretalx then tried to resize the image, which lead to the worker process consuming over 3GB of RAM, which in turn resulted in the kernel OOM-killing the worker.

When trying the upload in my local development instance, i get the following log (but no OOM, since there's about 10GB of free RAM available):
```
DEBUG 2023-07-27 12:28:22,498 rules predicates Testing (can_change_submissions | (is_reviewer & can_view_speaker_names))
DEBUG 2023-07-27 12:28:22,499 rules predicates   can_change_submissions = True
DEBUG 2023-07-27 12:28:22,499 rules predicates   (can_change_submissions | (is_reviewer & can_view_speaker_names)) = True
DEBUG 2023-07-27 12:28:22,502 rules predicates Testing can_change_submissions
DEBUG 2023-07-27 12:28:22,502 rules predicates   can_change_submissions = True
DEBUG 2023-07-27 12:28:22,518 PIL.TiffImagePlugin TiffImagePlugin tag: PhotometricInterpretation (262) - type: short (3) - value: b'\x00\x02'
DEBUG 2023-07-27 12:28:22,518 PIL.TiffImagePlugin TiffImagePlugin tag: ImageDescription (270) - type: string (2) Tag Location: 34 - Data Location: 146 - value: b'                               \x00'
DEBUG 2023-07-27 12:28:22,518 PIL.TiffImagePlugin TiffImagePlugin tag: Make (271) - type: string (2) Tag Location: 46 - Data Location: 178 - value: b'SONY\x00'
DEBUG 2023-07-27 12:28:22,518 PIL.TiffImagePlugin TiffImagePlugin tag: Model (272) - type: string (2) Tag Location: 58 - Data Location: 184 - value: b'ILCE-7RM3\x00'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: Orientation (274) - type: short (3) - value: b'\x00\x01'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: XResolution (282) - type: rational (5) Tag Location: 82 - Data Location: 194 - value: b'\x00\x00\x01,\x00\x00\x00\x01'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: YResolution (283) - type: rational (5) Tag Location: 94 - Data Location: 202 - value: b'\x00\x00\x01,\x00\x00\x00\x01'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: ResolutionUnit (296) - type: short (3) - value: b'\x00\x02'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: Software (305) - type: string (2) Tag Location: 118 - Data Location: 210 - value: b'Adobe Photoshop CC (Macintosh)\x00'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: DateTime (306) - type: string (2) Tag Location: 130 - Data Location: 242 - value: b'2021:01:12 12:30:17\x00'
DEBUG 2023-07-27 12:28:22,519 PIL.TiffImagePlugin TiffImagePlugin tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x01\x06'
DEBUG 2023-07-27 12:28:26,013 rules predicates Testing can_change_submissions
DEBUG 2023-07-27 12:28:26,013 rules predicates   can_change_submissions = True
[27/Jul/2023 12:28:26] "POST /orga/event/democon/speakers/UXYHP9/ HTTP/1.1" 302 0
```
I have attached a [dmesg.log](https://github.com/pretalx/pretalx/files/12183532/dmesg.log) containing the complete kernel log of the OOM in the production system. So far, i have not been able to reproduce this in our test environment nor in my local development setup.

I do have access to the original image that the speaker tried uploading, but i won't post it here unless explicitely asked for to protect their privacy.

### Expected behaviour

Uploading large profile pictures should not lead to pretalx OOMing.

### Operating system, dependency versions

python 3.10.6 - ubuntu 22.04

### Version

git d80da6245984097959919344ec1fad9770b3bde8

**Comment by rixx** [comment]
Yeah, I'm afraid fixing this is out of scope for pretalx, apart from waiting for Pillow updates. It's planned to eventually make image processing fully async, so that this failure wouldn't be blocking – but then again, in that case, pretalx would continue to serve an image will full metadata tags, which isn't a good idea either.
