### ISSUE TITLE
Time in Program Editor mismatches Frontend Time

### ISSUE THREAD

**Issue by td00** [pretalx/pretalx#1541]
### Problem and impact

When planning a schedule with the program editor and looking at it in the submissions planning, the time is mismatched by an hour.

### Expected behaviour

The time in the program / scheduling editor and the actual time matches

### Steps to reproduce

1. set a time via program editor
2. click on the schedule item you just scheduled
3. see the time difference

(also tested switching the timezone from UTC to Europe/Berlin on the host)

### Screenshots

Time presented in `/<eventslug>/schedule/v/wip/#`
![schedule_wip](https://github.com/pretalx/pretalx/assets/10527500/04f00a43-1a39-4944-9ce3-3a2b941f0ba6)

Time presented in `/orga/event/<eventslug>/schedule/?`
![schedule_edit](https://github.com/pretalx/pretalx/assets/10527500/11f136af-9661-4ef1-abd8-fd706268fe77)

Time presented in `/orga/event/<eventslug>/submissions/<subid>/`
![submission](https://github.com/pretalx/pretalx/assets/10527500/77f181dc-0e03-4874-b77a-0d2cb2475194)

### Link

/orga/event/<eventslug>/schedule/?

### Operating system, dependency versions

dockerized

### Version

v2.3.2

**Comment by rixx** [comment]
Yup, known issue in v2.3.2 / any currently released version. See also #1444, #1468, #1421. Next release is hopefully coming within a week.

**Comment by rixx** [comment]
To add: your options are to live with it for a week (though as you're running Docker, I have *no* idea if the next release will run on Docker immediately), or to run on `main`.

**Comment by rixx** [comment]
Update: sorry, the release will be delayed after all. I had hoped to be done before CCCamp, and I *kinda* am, but don't have enough time for testing and polish to feel comfortable with a new release rn. Will be out by the end of the month (ideally a few days after CCCamp ends, but let's say end of August just to be safe.)
