### ISSUE TITLE
Make `pretalx init` also work in a non-interactive mode

### ISSUE THREAD

**Issue by lorenzleutgeb** [pretalx/pretalx#1551]
### Problem and impact

When trying to package pretalx (see https://github.com/ngi-nix/ngipkgs/issues/2) we wanted to automate/script invocations of `pretalx init`. We used [`expect`](https://wiki.tcl-lang.org/page/Expect), which is quite brittle and cumbersome.

### Proposed solution / feature

Ideally, `pretalx init` should take parameters or read environment variables as an alternative to user interaction via writing prompts to standard output and reading from standard input.

I looked at https://github.com/pretalx/pretalx/blob/3cd043beb880c628707f8060341e33c63f2f7e6b/src/pretalx/common/management/commands/init.py and noted:

It is good, that `organiser_name` and `organiser_slug` are both read via `get_nonempty`, and it would be rather straight forward to add a parameter to `get_nonempty` that acts as the environment variable that should be used instead (if present), e.g. `organiser_name = get_nonempty(_('...'), 'PRETALX_INIT_ORGANISER_NAME')`.

It is good that [Django's `createsuperuser`](https://docs.djangoproject.com/en/4.2/ref/django-admin/#createsuperuser)  offers a [`--no-input`](https://docs.djangoproject.com/en/4.2/ref/django-admin/#cmdoption-createsuperuser-noinput) flag, causing the command to read arguments from the environment variables `DJANGO_SUPERUSER_*`.

This leads to my proposal to add a `--no-input` flag to `pretalx init`, which will in turn cause `superuser` to also be called with `--no-input`, and additionally interpreting `PRETALX_INIT_*` if defined.

I am willing to contribute an implementation, if confirmed by a maintainer.

**Comment by rixx** [comment]
Great suggestion, any your offered PR would be very much appreciated. (Bonus points if you add the  env vars to the [docs](https://docs.pretalx.org/administrator/commands.html#python-m-pretalx-init), but I'll do it if you won't – would be very happy to get this in before the end-of-August release!

**Comment by DeMiro5001** [comment]
Hello
I followed https://docs.pretalx.org/administrator/commands/#init
```
The init command allows you to create a superuser and an organiser. It is useful to give you all the tools to start configuring pretalx in the web interface. Please run this command once in the beginning. You can abort the command at any time, and it will not write anything to the database.

With the --noinput flag, this command will not prompt you interactively on standard input, but will instead read from the environment. This is especially useful for automating invocations of this command. For the first phase (creation of a superuser), set the environment variables DJANGO_SUPERUSER_EMAIL and DJANGO_SUPERUSER_PASSWORD ([see also the documentation of the non-interactive mode of the corresponding Django command](https://docs.djangoproject.com/en/stable/ref/django-admin/#createsuperuser)). For the second phase (creation of an organiser), set the environment variables PRETALX_INIT_ORGANISER_NAME and PRETALX_INIT_ORGANISER_SLUG.
```

But I couldn't get it to work.

I have defined an .env file : 
```
PRETALX_INIT_ADMIN_EMAIL="__EMAIL__"
PRETALX_INIT_ADMIN_USER="__ADMIN__"
PRETALX_INIT_ADMIN_PASSWORD="__PASSWORD__"
PRETALX_INIT_ORGANISER_NAME="__ORGANISER_NAME__"
PRETALX_INIT_ORGANISER_SLUG="__ORGANISER_SLUG__"
```
I also tried :  
```
DJANGO_SUPERUSER_EMAIL="__EMAIL__"
DJANGO_SUPERUSER_PASSWORD="__PASSWORD__"
```

I tried running running with `--noinput`, I get `CommandError: You must use --email with --noinput`. And if I use `--noinput --email "email@domain.fr"`, I get `__main__.py init: error: unrecognized arguments: --email "email@domain.fr"`
```
python3 -m pretalx init --noinput --email "email@domain.fr"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.1                                                       ┃
┃ ┃  ┌─·──╮  ┃  Settings:  pretalx.cfg                                                  ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)                                         ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/log/pretalx                                             ┃
┃ ┃  └─┘     ┃  Python:    /var/www/pretalx/venv/bin/python3                            ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /var/www/pretalx/venv/lib/python3.11/site-packages/pretalx   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
/var/www/pretalx/venv/lib/python3.11/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
usage: __main__.py init [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH]
                        [--traceback] [--no-color] [--force-color] [--skip-checks] [--noinput]
__main__.py init: error: unrecognized arguments: --email "email@domain.fr"
```

```
python3 -m pretalx init --noinput                                 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.1                                                       ┃
┃ ┃  ┌─·──╮  ┃  Settings:  pretalx.cfg                                                  ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)                                         ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/log/pretalx                                             ┃
┃ ┃  └─┘     ┃  Python:    /var/www/pretalx/venv/bin/python3                            ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /var/www/pretalx/venv/lib/python3.11/site-packages/pretalx   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
/var/www/pretalx/venv/lib/python3.11/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)

Welcome to pretalx! This is my initialization command, please use it only once.
You can abort this command at any time using C-c, and it will save no data.

Let's get you a user with the right to create new events and access every event on this pretalx instance.
CommandError: You must use --email with --noinput.
```

Not sure what am I missing.
Thank you

**Comment by rixx** [comment]
I added another patch that improves error messages on missing env variables further. Please try again with this version. I’m fairly sure that your environment variables are not present in the Django process. I have confirmed manually (again) that the command works with the environment variables present by running 

```bash
PRETALX_INIT_ORGANISER_SLUG=testorg01 PRETALX_INIT_ORGANISER_NAME=testorg01 DJANGO_SUPERUSER_EMAIL=admin@example.org DJANGO_SUPERUSER_PASSWORD=password python manage.py init --noinput`
```

You said you run `source .env` – does your env file set variables or does it export them? If you want them to be available to other processes, you have to export them (either explicitly or by changing your shell mode along the lines of `set -o allexport` or whatever the shell you uses prefers).

**Comment by DeMiro5001** [comment]
The error message is much clearer and the command works as intended.
Thanks a lot for your help
