### ISSUE TITLE
Add room property if room is recorded or not

### ISSUE THREAD

**Issue by saerdnaer** [pretalx/pretalx#1571]
### Problem and impact

As of now the schedule does not really give much information about if a room has actually recordings/streaming abilities or not. Speakers can set a 'do not record' flag on an individual submission, but as participant of a conference it's highly intransparent which are the "real" lecture rooms and which aren't.

### Proposed solution / feature

We should add a boolean or dropdown field on the room model and expose this information via according icons / legend in the schedule matrix + APIs

**Comment by rixx** [comment]
"boolean or drop-down field" seems like the sticking point here: There are so many ways to model this information, and there is very little data on what the organisers want or need. Off the top of my head, here are some options:

- `Room.can_be_recorded`
- `Room.can_be_streamed`, `Room.can_be_recorded`
- `Room.has_{…}` for microphone, camera, projector, livestream, etc
- `Room.equipment` with a list of devices/setup

Any option other than the first will be hard to impossible to display in the schedule in any meaningful way.

**Comment by johnjohndoe** [comment]
If I don't misunderstand the `recording` attribute is related: https://github.com/voc/schedule/blob/0d45ead981768eaf29cd943f0acec68ffabc6077/validator/xsd/schedule.xml.xsd#L89

**Comment by rixx** [comment]
The `recording` attribute is set on events (in VOC parlance; that'd be sessions/submissions/talks in pretalx). This issue is about adding recording potential information on the room / location level.
