### ISSUE TITLE
Scheduling cards are broken for characters outside Latin-1

### ISSUE THREAD

**Issue by oskar456** [pretalx/pretalx#1577]
### Problem and impact

When generating scheduling cards PDF, all characters outside ISO Latin-1 are replaced by a black box.

### Expected behaviour

Resonable full glyph set should be supported.

### Steps to reproduce

1. Put a text outside Latin-1 anywhere in author name, talk title, abstract or talk type.
2. Use Print Cards feature.
3. Download a broken PDF.

### Screenshots

<img width="420" alt="broken_card_example" src="https://github.com/pretalx/pretalx/assets/816717/2213f697-d7fa-4268-b074-f45ebfb306a7">

### Browser (software, desktop or mobile?) and version

Not relevant

### Operating system, dependency versions

Debian Bullseye running Python 3.9, reportlab 3.6.13

### Version

2.3.2

**Comment by rixx** [comment]
Looks like we'd have to ship our own fonts / make sure they are available in the system, then point reportlab at them.
