### ISSUE TITLE
mail output composition : select all speakers of a room

### ISSUE THREAD

**Issue by vincent-lucy** [pretalx/pretalx#1581]
### Problem and impact

In the use case where a room is unavailable or relocated, it could be very convenient to send a mail to all speekers of this room

**Comment by rixx** [comment]
The current workaround would be to move the talks from the old to a new room – that way, emails to all those speakers would be generated, and additionally, the audience could also see the change in the changelog.

However, for other cases, such as actual information regarding the room itself, I do think this would be a good idea. However, as we're not currently permitting mails to speakers directly, I'll add this request to #1244, for when speaker emails are getting implemented.
