### ISSUE TITLE
mail output composition : select all speakers of a day

### ISSUE THREAD

**Issue by vincent-lucy** [pretalx/pretalx#1582]
### Problem and impact

If something unexpected arrives at a special day, the events of this day could be canceled or moved: in that situation it could be very useful to prevent all the speakers involved *that* day

**Comment by rixx** [comment]
As we're not currently permitting mails to speakers directly (only per-proposal, which wouldn't make a ton of sense here), I'll add this request to #1244, for when speaker emails are getting implemented.
