### ISSUE TITLE
`static_dir` does not apply to fonts

### ISSUE THREAD

**Issue by lorenzleutgeb** [pretalx/pretalx#1585]
### Problem and impact

In packaging pretalx with Nix, a clear separation between static files (`STATIC_ROOT`) and the package (`PACKAGE_DIR`) is enforced. After running `pretalx rebuild` all files from `static.dist` are moved to a location that called "static output". The pretalx package (`*.py` files, ...) go into another location that called "default output". This means that `PACKAGE_DIR/static` will be empty, and all static files will be in `STATIC_ROOT`.

Doing that, creates the issue that fonts cannot be loaded: `reportlab.pdfbase.ttfonts.TTFError: Can't open file "mulish-v12-latin-ext-regular.ttf"`

Leaving `PACKAGE_DIR/static/fonts` untouched (but still removing all other subdirectories of `PACKAGE_DIR/static`) works around this problem. The relevant downstream commit is https://github.com/ngi-nix/ngipkgs/pull/54/commits/89af01904ea4ab43b82bf8a6495d310c8382de1e

<details>
<summary>However, this leads to duplicated files:</summary>
<pre>
$ shasum result-static/fonts/* result/lib/python3.10/site-packages/pretalx/static/fonts/* | sort
2affce5a063d34fc744bc8ff4b6b5c86467d6f37  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-regular.ttf
2affce5a063d34fc744bc8ff4b6b5c86467d6f37  result-static/fonts/mulish-v12-latin-ext-regular.77e10c973d96.ttf
2affce5a063d34fc744bc8ff4b6b5c86467d6f37  result-static/fonts/mulish-v12-latin-ext-regular.ttf
2b34b32ba7b10a8a5b5e4975297081d66f1259f1  result-static/fonts/mulish-v12-latin-ext-regular.77e10c973d96.ttf.gz
2b34b32ba7b10a8a5b5e4975297081d66f1259f1  result-static/fonts/mulish-v12-latin-ext-regular.ttf.gz
320811cfb42cdcab1204e23705d78c4f771ad37e  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-700.woff2
320811cfb42cdcab1204e23705d78c4f771ad37e  result-static/fonts/mulish-v12-latin-ext-700.8383c3d85e91.woff2
320811cfb42cdcab1204e23705d78c4f771ad37e  result-static/fonts/mulish-v12-latin-ext-700.woff2
3a80654b0c3218a240dee2ec9cdab7ff9f54a940  result-static/fonts/titillium-web-v17-latin-ext-600.2f5c4da2290e.ttf.br
3a80654b0c3218a240dee2ec9cdab7ff9f54a940  result-static/fonts/titillium-web-v17-latin-ext-600.ttf.br
52e7e46fa9bbd8fc4b19bae875028eee0721f359  result-static/fonts/titillium-web-v17-latin-ext-600.2f5c4da2290e.ttf.gz
52e7e46fa9bbd8fc4b19bae875028eee0721f359  result-static/fonts/titillium-web-v17-latin-ext-600.ttf.gz
53d6db227478f23398b88e3ac70459b3298f4ed7  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-regular.woff
53d6db227478f23398b88e3ac70459b3298f4ed7  result-static/fonts/mulish-v12-latin-ext-regular.82441db23d19.woff
53d6db227478f23398b88e3ac70459b3298f4ed7  result-static/fonts/mulish-v12-latin-ext-regular.woff
545f40106e6442130573d5fef2beec03cf4125c6  result-static/fonts/mulish-v12-latin-ext-italic.06ac9bf69334.ttf.gz
545f40106e6442130573d5fef2beec03cf4125c6  result-static/fonts/mulish-v12-latin-ext-italic.ttf.gz
60cfff531fdb1614d4e76060309eae1a1ae771af  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-700italic.woff2
60cfff531fdb1614d4e76060309eae1a1ae771af  result-static/fonts/mulish-v12-latin-ext-700italic.0285418739c7.woff2
60cfff531fdb1614d4e76060309eae1a1ae771af  result-static/fonts/mulish-v12-latin-ext-700italic.woff2
68aeba12a917628ca7eb10b2049747e0d0c52ce8  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-italic.woff
68aeba12a917628ca7eb10b2049747e0d0c52ce8  result-static/fonts/mulish-v12-latin-ext-italic.02cda471be11.woff
68aeba12a917628ca7eb10b2049747e0d0c52ce8  result-static/fonts/mulish-v12-latin-ext-italic.woff
6a857b0d9c8fd269888b6c31ab5d7f43433d8fce  result-static/fonts/mulish-v12-latin-ext-italic.06ac9bf69334.ttf.br
6a857b0d9c8fd269888b6c31ab5d7f43433d8fce  result-static/fonts/mulish-v12-latin-ext-italic.ttf.br
90fbb3d6555181bebb9a6e466e57a2cb9abae005  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-italic.ttf
90fbb3d6555181bebb9a6e466e57a2cb9abae005  result-static/fonts/mulish-v12-latin-ext-italic.06ac9bf69334.ttf
90fbb3d6555181bebb9a6e466e57a2cb9abae005  result-static/fonts/mulish-v12-latin-ext-italic.ttf
9273efaf59db131ac8cf23f3f6b42c66629af829  result/lib/python3.10/site-packages/pretalx/static/fonts/titillium-web-v17-latin-ext-700.woff2
9273efaf59db131ac8cf23f3f6b42c66629af829  result-static/fonts/titillium-web-v17-latin-ext-700.b2f72c965b95.woff2
9273efaf59db131ac8cf23f3f6b42c66629af829  result-static/fonts/titillium-web-v17-latin-ext-700.woff2
9f065d772e2391d8335934c68acef67c3fcd2b8a  result/lib/python3.10/site-packages/pretalx/static/fonts/titillium-web-v17-latin-ext-600italic.woff2
9f065d772e2391d8335934c68acef67c3fcd2b8a  result-static/fonts/titillium-web-v17-latin-ext-600italic.b239a10f596e.woff2
9f065d772e2391d8335934c68acef67c3fcd2b8a  result-static/fonts/titillium-web-v17-latin-ext-600italic.woff2
ac474e1dc2d8b1eba525307cf822f9a6cea77d0d  result/lib/python3.10/site-packages/pretalx/static/fonts/titillium-web-v17-latin-ext-600.ttf
ac474e1dc2d8b1eba525307cf822f9a6cea77d0d  result-static/fonts/titillium-web-v17-latin-ext-600.2f5c4da2290e.ttf
ac474e1dc2d8b1eba525307cf822f9a6cea77d0d  result-static/fonts/titillium-web-v17-latin-ext-600.ttf
ad50c0dd6d8fed173cab08b486e508d8e063a5e6  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-regular.woff2
ad50c0dd6d8fed173cab08b486e508d8e063a5e6  result-static/fonts/mulish-v12-latin-ext-regular.f8e96c6d54f2.woff2
ad50c0dd6d8fed173cab08b486e508d8e063a5e6  result-static/fonts/mulish-v12-latin-ext-regular.woff2
d4a6f81d4f9013380d4776938eafbe524ef27d25  result/lib/python3.10/site-packages/pretalx/static/fonts/titillium-web-v17-latin-ext-600.woff2
d4a6f81d4f9013380d4776938eafbe524ef27d25  result-static/fonts/titillium-web-v17-latin-ext-600.ba4ebbf930dd.woff2
d4a6f81d4f9013380d4776938eafbe524ef27d25  result-static/fonts/titillium-web-v17-latin-ext-600.woff2
da261e89959df941fa01b4c438e9068e862e999a  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-700.woff
da261e89959df941fa01b4c438e9068e862e999a  result-static/fonts/mulish-v12-latin-ext-700.451f34afbc7f.woff
da261e89959df941fa01b4c438e9068e862e999a  result-static/fonts/mulish-v12-latin-ext-700.woff
e0cb9ce8aafcaa9283c2ee8b5119240edaedc457  result/lib/python3.10/site-packages/pretalx/static/fonts/titillium-web-v17-latin-ext-700italic.woff2
e0cb9ce8aafcaa9283c2ee8b5119240edaedc457  result-static/fonts/titillium-web-v17-latin-ext-700italic.059366840be6.woff2
e0cb9ce8aafcaa9283c2ee8b5119240edaedc457  result-static/fonts/titillium-web-v17-latin-ext-700italic.woff2
e7af6e2afdd70b4ab8c5957d9175ffda2f45f783  result-static/fonts/mulish-v12-latin-ext-regular.77e10c973d96.ttf.br
e7af6e2afdd70b4ab8c5957d9175ffda2f45f783  result-static/fonts/mulish-v12-latin-ext-regular.ttf.br
e9f5d6feed8ac6e1c8455253c6aa585c04dc5c8b  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-italic.woff2
e9f5d6feed8ac6e1c8455253c6aa585c04dc5c8b  result-static/fonts/mulish-v12-latin-ext-italic.82d3a2194c94.woff2
e9f5d6feed8ac6e1c8455253c6aa585c04dc5c8b  result-static/fonts/mulish-v12-latin-ext-italic.woff2
eb624b41d87418154adeda29723fbd082e5f2fe4  result/lib/python3.10/site-packages/pretalx/static/fonts/mulish-v12-latin-ext-700italic.woff
eb624b41d87418154adeda29723fbd082e5f2fe4  result-static/fonts/mulish-v12-latin-ext-700italic.e473338d2965.woff
eb624b41d87418154adeda29723fbd082e5f2fe4  result-static/fonts/mulish-v12-latin-ext-700italic.woff
</pre>
</details>

Since for other kinds of static files, the behavior is different, I believe that the line https://github.com/pretalx/pretalx/blob/c9194be722ec98c4100180236c51ab1ca54d3094/src/pretalx/orga/views/cards.py#L24 should not refer to `PACKAGE_DIR`, but to `STATIC_ROOT`.

### Expected behaviour

Fonts should not be required in `PACKAGE_DIR`, but only in `STATIC_ROOT/fonts`.

### Steps to reproduce

1. Run `pretalx rebuild`.
2. Delete `PACKAGE_DIR/static/fonts`
3. Observe errors about fonts not being found.

### Operating system, dependency versions

NixOS

### Version

2023.1.3

**Comment by rixx** [comment]
Deleting part of the package (or making it inaccessible) is not a supported way to run pretalx at the moment.

There's a reason we need to use the actual packaged files here: the files under `STATIC_ROOT` are not guaranteed to be accessible. Well, first off, they are named dynamically, as django usually adds a hash to the filename for cache invalidation purposes, so we'd have to look the names up with the `static` templatetag in the first place. But they are also not guaranteed to be in the filesystem at all – you can get Django to collect files into S3 or basically arbitrary filesystem-alike interfaces, which reportlab cannot read.

I changed the code in 820866b4 to use `finders.find()` rather than paths relying on `PACKAGE_DIR`, which is the correct thing to do in the first place, but if `finders.find()` reports an inaccessible directory on your system, I'm afraid that's an unsupported use case.
