### ISSUE TITLE
Dev setup fails on db migrations

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#1590]
### Problem and impact

I try to setup a dev environment. Following the steps at https://docs.pretalx.org/developer/setup.html fails at the 

    python manage.py migrate 

step. It fails with:

```console
 Applying event.0034_fix_language_codes...╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/vmx/src/python/pretalx/pretalx/env/lib/python3.11/site-packages/django/apps/config.py:235  │
│ in get_model                                                                                     │
│                                                                                                  │
│   232 │   │   else:                                                                              │
│   233 │   │   │   self.apps.check_apps_ready()                                                   │
│   234 │   │   try:                                                                               │
│ ❱ 235 │   │   │   return self.models[model_name.lower()]                                         │
│   236 │   │   except KeyError:                                                                   │
│   237 │   │   │   raise LookupError(                                                             │
│   238 │   │   │   │   "App '%s' doesn't have a '%s' model." % (self.label, model_name)           │
│                                                                                                  │
│ ╭──────────────── locals ─────────────────╮                                                      │
│ │    model_name = 'SpeakerInformation'    │                                                      │
│ │ require_ready = True                    │                                                      │
│ │          self = <AppConfigStub: person> │                                                      │
│ ╰─────────────────────────────────────────╯                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'speakerinformation'
…
```

And a much longer traceback.

### Expected behaviour

I'd expect that `python manage.py migrate` passes.

### Steps to reproduce

1. Use current main (https://github.com/pretalx/pretalx/commit/7ecf37dc31f2ec4ab9ca47d150c474da95eb7539).
2. Follow the steps from https://docs.pretalx.org/developer/setup.html
3. The `python manage.py migrate` step fails.

What works for me:

5. `rm -Rf data`
6. `git checkout 7f7c4ea1bbb02a5a81571d84e4f9703bc6e23d71` (https://github.com/pretalx/pretalx/commit/7f7c4ea1bbb02a5a81571d84e4f9703bc6e23d71)
7. `python manage.py migrate` passes.

When `rm -Rf data` and going to the next commit https://github.com/pretalx/pretalx/commit/0c190fccc927263ef398edf3d9deaeb2ac4028a8, it fails again.

### Operating system, dependency versions

Debian testing

### Version

https://github.com/pretalx/pretalx/commit/7ecf37dc31f2ec4ab9ca47d150c474da95eb7539

**Comment by rixx** [comment]
Failure was due to a migration with underspec'd dependencies. Fixed and added tests for this.
