### ISSUE TITLE
Email not logged to stdout in dev mode

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#1591]
### Problem and impact

I try to use the public voting plugin. In order to actually try to vote, you need to see the email that is sent.

### Expected behaviour

I can read the email on stdout.

### Steps to reproduce

1. Setup pretalx including the demo conf.
2. Run the dev server via `python manage.py runserver`
3. Go to "Mails" in the UI.
4. Press "Send" on one of the emails.
5. The only log output I get is:
```console
INFO 2023-09-28 00:10:07,930 celery.app.trace trace Task pretalx.common.mail.mail_send_task[2421f456-ef5e-41ce-8ef1-867edd40bcf0] succeeded in 0.0001394780119881034s: None
[28/Sep/2023 00:10:07] "GET /orga/event/democon/mails/85/send HTTP/1.1" 302 0
DEBUG 2023-09-28 00:10:08,046 rules predicates Testing can_change_submissions
DEBUG 2023-09-28 00:10:08,046 rules predicates   can_change_submissions = True
DEBUG 2023-09-28 00:10:08,055 rules predicates Testing can_change_event_settings
DEBUG 2023-09-28 00:10:08,055 rules predicates   can_change_event_settings = True
DEBUG 2023-09-28 00:10:08,689 rules predicates Testing ((can_change_submissions | can_change_event_settings) | is_reviewer)
DEBUG 2023-09-28 00:10:08,689 rules predicates   can_change_submissions = True
DEBUG 2023-09-28 00:10:08,689 rules predicates   (can_change_submissions | can_change_event_settings) = True
DEBUG 2023-09-28 00:10:08,690 rules predicates   ((can_change_submissions | can_change_event_settings) | is_reviewer) = True
DEBUG 2023-09-28 00:10:08,690 rules predicates Testing can_change_submissions
DEBUG 2023-09-28 00:10:08,690 rules predicates   can_change_submissions = True
DEBUG 2023-09-28 00:10:08,690 rules predicates Testing (is_administrator | can_change_teams)
DEBUG 2023-09-28 00:10:08,690 rules predicates   is_administrator = True
DEBUG 2023-09-28 00:10:08,691 rules predicates   (is_administrator | can_change_teams) = True
DEBUG 2023-09-28 00:10:08,691 rules predicates Testing (can_change_submissions | (is_reviewer & can_view_speaker_names))
DEBUG 2023-09-28 00:10:08,691 rules predicates   can_change_submissions = True
DEBUG 2023-09-28 00:10:08,691 rules predicates   (can_change_submissions | (is_reviewer & can_view_speaker_names)) = True
[28/Sep/2023 00:10:08] "GET /orga/event/democon/mails/outbox/ HTTP/1.1" 200 207323
[28/Sep/2023 00:10:09] "GET /static/CACHE/css/main.c8176c4a565a.css HTTP/1.1" 200 666509
```
I don't see anything of the email itself.

### Operating system, dependency versions

Debian testing

### Version

Slightly older main https://github.com/pretalx/pretalx/commit/7f7c4ea1bbb02a5a81571d84e4f9703bc6e23d71

**Comment by rixx** [comment]
How did you set up your emails for local development? Did you follow the [developer documentation for working with emails](https://docs.pretalx.org/developer/setup.html#working-with-mails)?

**Comment by vmx** [comment]
Yes. I didn't touch any of the email setting and assumed it to be the default to log to stdout, or am I misunderstanding the docs?

I then also tried hard to make sure that `DEBUG` is set. I think it was already set as I saw `debug` level logs.

**Comment by rixx** [comment]
Does the alternative setup mentioned in the docs work? It seems to me that at the cost of only an additional shell, that would solve your immediate problem of not seeing emails, right?

**Comment by rixx** [comment]
Cannot reproduce: I set up an entirely new event and can see emails in the console.

Are you trying to send emails to a @localhost or @example.org address? Those get filtered out by the email sending logic.

**Comment by rixx** [comment]
I suppose we might as well allow emails to `@localhost` and `@example.org` if we are running in `DEBUG` mode.

**Comment by vmx** [comment]
I just tried to reproduce it from scratch and already picked up the fix you just pushed. I can confirm that it now works. And indeed, I was sending to `@example.org`. Thanks a lot for the quick turnaround time for all the bugs I've reported!
