### ISSUE TITLE
Plugin hook for sent email

### ISSUE THREAD

**Issue by Kunsi** [pretalx/pretalx#1594]
### Problem and impact

For tracking communication with speakers it would be really nice if sent emails would get imported automatically into some sort of ticket system. Due to the many ticket systems available, i don't think it is suitable to add such functionality directly into pretalx.

Instead, pretalx should have a plugin hook so plugins can get notified of sent emails, and then take care of importing those emails into the ticket system of choice.

### Proposed solution / feature

In my opinion, it would be best to implement this somewhere in `common.mail.mail_send_task()`, because that's the only place (i could find) that knows of all mails and is running in celery.

**Comment by rixx** [comment]
Definitely a cool idea!

I don't think we want to use `mail_send_task()` though – this is used for non-event mails as well as things like password resets and automated confirmation emails ("we have received your proposal"). I think putting something into `QueuedMail.send()` however sounds sensible. We'd need to check and see if we want to call this only if the `QueuedMail` object has an `id` (aka if it's still accessible for users after the fact), but we could also let the plugin handle this check.

As signals run synchronously, it'd probably be **very highly recommended** for any receiving signal to call a task asynchronously (as not to block email sending), but other than that, I don't really see any problems with this.
