### ISSUE TITLE
Review page limits only 25 submissions

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1607]
### Problem and impact

I noticed that the review dashboard page show only 25 submissions, without any pagination. If I change https://github.com/pretalx/pretalx/blob/main/src/pretalx/orga/views/review.py#L36 to eg paginate_by: 200 all my submissions do show correctly. Looks like the None logic is not working as expected.

### Version
We are using git sha: 7ecf37dc31f2ec4ab9ca47d150c474da95eb7539

**Comment by rixx** [comment]
That was fixed in 92018fd6. If you do not use a release, please check the current main branch before opening bug reports, as chances are good that old bugs have been fixed (introduced 4 weeks ago, fixed 3 weeks ago, in this case).
