### ISSUE TITLE
Add hero image per talk

### ISSUE THREAD

**Issue by naltatis** [pretalx/pretalx#1612]
### Problem and impact

Would be nice if you could add an image to each talk. This image would be shown on the talks detail page.

I've tried doing this via the description, but as explained here https://github.com/pretalx/pretalx/issues/1539 this is not possible right now.

### Proposed solution / feature

A dedicated image field per talk. Editable by the organizer (and speaker?).

### Context or examples

NooK Lübeck has Midjourney generated hero images for each talk, which, I think, is a really cool idea and makes the schedule more fun to explore and remember:
https://2023.nook-luebeck.de/talks/ueber-taschenmonster-und-bills-pc/

**Comment by rixx** [comment]
Sessions already can have images. If you want to change the way these images are displayed, please clarify.
![2023-10-26T12:22:38+02:00](https://github.com/pretalx/pretalx/assets/2657547/c902cd5a-45c4-4fd0-8c9c-9ba1f0281b54)

**Comment by naltatis** [comment]
Oh, sorry. I've missed this setting in the configuration. Problem solved, thanks 💚
