### ISSUE TITLE
Possibility to request a code of conduct on account creation

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1623]
### Problem and impact

We added a question to ask whether speakers agree to the CoC. For the initial submitter this works well, but if you add a second speaker, you can basically ignore the field.

![image](https://github.com/pretalx/pretalx/assets/868434/73319220-b051-4ae3-a2f4-6fb34284c34d)

I think ideally it should be possible to have a similar question already asked at account creation.

**Comment by rixx** [comment]
Account creation is, currently, not event specific. Indeed, accounts are created *for* users when they are invited, and they just populate the account with information. I agree that this isn't ideal, but I think we will fold this in with #554, which I edited a bit to reflect this problem.
