### ISSUE TITLE
Email reply-to/from

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1625]
### Problem and impact

While checking the latest commits, I noticed that the reply-to field was removed.
I think that's a pity, I'm actually using it, and I was about to open a PR to make sure we can use a signal for it:

https://github.com/pretalx/pretalx/commit/572bee2eced34c0f2951350a5b9d3858e84eede5

Our usecase: we have a lot of tracks, so we want to make sure people with issues mail to the track responsible (which we supply from a [plugin](https://github.com/FOSDEM/pretalx-integration/blob/master/devroom-settings/devroom_settings/signals.py#L47-L69)) 

If reply-to stays removed, as an alternative, would it be possible to template out _from_ instead?

**Comment by rixx** [comment]
Okay, so getting dinged for a change **the exact minute** I merge the containing pull request is new. Speak of turn-around times.

So, first off: the field has only been removed from the UI – you're still free to use it in your plugin, and the pretalx email backend still supports setting reply_to and bcc parameters.

There has been a requested feature to use "sender identities" (a combination of name, Reply-To, and other settings) to distinguish different emails/senders. I feel like more technical fields like Reply-To and Bcc are better off in a feature like that than in the already-cluttered email form. I'll revert the commit for now and figure out some way to hide the fields in the form, I suppose, though admittedly I resent the added effort and visual clutter even so.

As for your other requests / approaches: You will not be able to set the From: address any time soon. Letting users set arbitrary, non-vetted From: addresses is a great way to ruin the originating email server's spam score forever, and to leave users confused and angry at bouncing emails. (And yes, I know that means we should have actual email address verification. I know.)
Also re: the commit you linked: I don't think templating of email addresses is going to happen at any point. Template variables are purposefully meant to contain human-readable text, not variables. If you really need message-dependent Reply-To addresses, I'd recommend that you write your own email backend – you can find some discussion on related topics and caveats in #1596
