### ISSUE TITLE
Links/Resources not asked for during submission + missing from review

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1633]
### Problem and impact

Compared to our previous conference management system, reviewers complained that almost no links were present when reviewing proposals.

While reviewing the issue I noticed 3 things:
1) When submitting, the option to add resources is not presented
2) If you go back and edit a submission you can add resources, but it it may not be apparent for new users that this can also be used to add links to the project
3) Even if you add a link this way, it will not show up in the review page. 

We could add a question asking for links, but that does not seem ideal: links could than be specified in different locations and what if a submitter wants to add several links. I think it would be better that resources are part of the normal submission process (with clear indication that their content will be public and can contain links), and that they are shown during the review phase.

A small disclaimer, these were noticed on our fork https://github.com/johanvdw/pretalx/commits/fosdem_2024 - sorry for the noise if these are fixed in the master branch, I've not yet checked that.

**Comment by rixx** [comment]
Relevant to #1316, too.

**Comment by rixx** [comment]
Resources are now part of the review view – the other aspect of this issue will be resolved via #1316.
