### ISSUE TITLE
Add speaker data when exporting proposals

### ISSUE THREAD

**Issue by olblak** [pretalx/pretalx#1640]
### Problem and impact

When building a conference agenda, we like to export proposals to a csv file that we can use in a solution like Google Sheet, Libreoffice calc, etc...

This allows to quickly visualize the consequence of changing various parameters like the length of each presentation,etc...

And I would like to also export speaker information associated to each talk proposal

### Proposed solution / feature

I would like to export speaker information associated to each talk proposal

**Comment by rixx** [comment]
You can include speaker names and speaker IDs in your export already.

For more complex data, the simple Excel/CVS export is the wrong place: One talk can have multiple speakers, after all, so if each talk is a row, you'd have to have separate columns for "speaker 1 name", "speaker 1 additional data A", "speaker 2 name", "speaker 2 additional data A" etc. For purposes like these, please use the API instead.

**Comment by olblak** [comment]
Thanks for the suggestion. I'll look into that next time
