### ISSUE TITLE
schedule fails to display when localstorage is disabled.

### ISSUE THREAD

**Issue by stef** [pretalx/pretalx#1644]
### Problem and impact

i want to see the fireshonks23 fahrplan, but all i see is an infinite spinner, this is due to schedule.js throwing a TypeError when trying to access localstorage. since this is globally disabled in the browser by setting `dom.storage.enabled` to false, fixing this would mean that all the other tabs with those mean surveillance capitalistic pigs would do bad things with their tentacles to my browser, me and my rights...

### Expected behaviour

schedule displays without needing any localstorage

### Steps to reproduce

1. start firefox
2. got about:config
3. set `dom.storage.enabled` to false
4. go to https://pretalx.c3voc.de/fireshonks23/schedule/
5. enjoy the wonderful sight of a spinner

### Browser (software, desktop or mobile?) and version

firefox 120.0.1

**Comment by rashfael** [comment]
Feel free to enjoy the [nojs UI](https://pretalx.c3voc.de/fireshonks23/schedule/nojs) or the ASCII printout via `curl https://pretalx.c3voc.de/fireshonks23/schedule/`.

**Comment by stef** [comment]
TIL. wow. mind blown. awesome. geekgasming.

**Comment by rixx** [comment]
Note that you probably want to use `curl https://pretalx.c3voc.de/fireshonks23/schedule/\?format=list` since FireShonks is a single track conference :)

**Comment by stef** [comment]
let me respectfully disagree with this "not planned" i do think it is a bug, and it violates user expectations. graceful degradation and possibly a redirect to the nojs version is better than an infinite spinner.

**Comment by rixx** [comment]
You're of course free to provide a pull request providing a more graceful error message. But I'm afraid that disagreeing with this decision *without* a contribution is not going to change anything: we simply don't have the bandwidth to guard against every way users may change, limit or break their JavaScript interpreter. The moment you go to `about:config` to change the way your browser works, you're accepting that you're going to break things.

This is a single-maintainer project, so we pretty much need to pick our battles – we already provide multiple no-JS fallbacks, and that's the limit of our maintenance capabilities.

**Comment by stef** [comment]
fair enough. thanks!
