### ISSUE TITLE
Error 404 on schedule

### ISSUE THREAD

**Issue by amasson84** [pretalx/pretalx#1653]
### Problem and impact

When clicking on Schedule in the orga/event, the schedule does not appear and I if I look in the console I have two 404 errors for :
*  ./src/main.js
* ./@vite/client

### Expected behaviour

The schedule should appear here, only the buttons New release and action are present.

### Steps to reproduce

1. Open an event
2. Define room 
3. Click on Schedule
4.

### Screenshots

![image](https://github.com/pretalx/pretalx/assets/37930258/06d9fb78-8c39-4b64-884e-3486f9e2f480)
![image](https://github.com/pretalx/pretalx/assets/37930258/59f6d07b-a13e-46db-b113-30a86d1f3097)
![image](https://github.com/pretalx/pretalx/assets/37930258/699d0ae6-c6ed-49a8-a21a-fc4ea789c581)

### Browser (software, desktop or mobile?) and version

firefox, brave desktop

### Operating system, dependency versions

macos sillicon m2

### Version

2023.1.3

**Comment by rixx** [comment]
This is covered in the [developer docs](https://docs.pretalx.org/developer/setup.html#run-the-development-server).
