### ISSUE TITLE
css files getting 404 errors

### ISSUE THREAD

**Issue by zunder1990** [pretalx/pretalx#1655]
### Problem and impact

We made our CFP open today and now we are getting 404 errors on the css files 
https://speakers.southeastlinuxfest.org/southeast-linux-fest-2024/
I ran an update steps just to make sure including regen css files. 
https://docs.pretalx.org/administrator/maintenance.html

All CSS is set to default.
any points would be nice.

the two files that I am getting 404 errors are found /var/pretalx/data/media/southeast-linux-fest-2024 and owned by the pretalx user.

### Steps to reproduce

1.
2.
3.
4.

### Screenshots

![image](https://github.com/pretalx/pretalx/assets/11825392/4172afe2-b050-4811-863d-bfad624c14a6)
![image](https://github.com/pretalx/pretalx/assets/11825392/040cd803-3371-4a8a-b2eb-ec6c0df6c496)

### Operating system, dependency versions

Debian 11.7

### Version

pretalx v2023.1.3

**Comment by rixx** [comment]
Sounds like you're not exposing your media files correctly – check the example NGINX settings file. You have to expose the media directory on the `/media` HTTP path.
