### ISSUE TITLE
Adding talk image after submission

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1668]
### Problem and impact

Unless I'm terribly mislooking, there does not seem to be an option to add an image to a submission after you submitted it, or to remove it, either as an organiser or as a submitter.

That's a bit weird, I think you should be able to update this at any point.

Note we use a [slightly older fork](https://github.com/pretalx/pretalx/discussions/1637) from master. If this was addressed recently, sorry for the noise, but I'd be interested to see which commits fixed it.

**Comment by rixx** [comment]
Cannot reproduce, neither in the organiser area nor as the speaker:

![2024-02-01T09:02:28+01:00](https://github.com/pretalx/pretalx/assets/2657547/193b4308-0f67-4838-b193-9f27555ebb61)
![2024-02-01T09:02:57+01:00](https://github.com/pretalx/pretalx/assets/2657547/0927fd56-98ee-4c41-99b9-04ad03f17ddd)

I don't believe this form has changed recently. The availability of the field depends on the session field being asked for in the CfP (either "Ask, but do not require input" or "Ask and require input").

**Comment by johanvdw** [comment]
Ok,thanks, it was indeed a configuration issue. I did check, but must have somehow still missed it.
