### ISSUE TITLE
User interface can trigger 500 error when changing proposal state 

### ISSUE THREAD

**Issue by nicorikken** [pretalx/pretalx#1669]
### Problem and impact

Changing a proposal state, say from _confirmed_ to _withdrawn_ it opens a separate page to confirm.
On that page you can also use the dropdown again to change the state. If doing so and submittng..
![image](https://github.com/pretalx/pretalx/assets/7458098/e905f1eb-d3cc-4e2f-b805-820358559341)

Selecting from the dropdown:
![image](https://github.com/pretalx/pretalx/assets/7458098/a87d0e6f-037b-4b4c-916b-8147494e18ed)

I got a 500 error, but that might have a different reason. In any case it is a strange place to have another dropdown.

Impact low, maybe some user confusion or denial of service risk.  

### Expected behaviour

No dropdown button, doesn't make sense.

### Steps to reproduce

1. Open an existing proposal 
2. Change state from confirmed to withdrawn
3. On the new page to confirm, make a similar change in the dropdown
4. Commit ('Do it')
5. See a 500 error page (in my situation)

### Link

https://pretalx.fosdem.org/orga/event/fosdem-2024/submissions/<id>/withdraw?next=/orga/event/fosdem-2024/submissions/<id>/%3F

### Version

Couldn't find the version unfortunately

**Comment by rixx** [comment]
Cannot reproduce:

1. Click "withdrawn" in the drop-down
2. On the confirmation page, instead click "withdrawn in the drop-down again"
3. Click "confirm"
4. Get redirected to the confirmation page again, now asking you to confirm that you're changing the status from "withdrawn" to "withdrawn"

I agree that 4) isn't the greatest UI, but I can't reproduce the error. Happy to re-open with added information for a repro, or server error logs.
