### ISSUE TITLE
Default ordering of sent emails

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1673]
### Problem and impact

By default, sent mails are ordered  from old to new. That does not seem a logical choice: I think that in most cases you are most interested in which mails were recently sent, so I'd rather sort them from new to old by default.

An other option would be storing the previous sort order in the session/cookie, so a user will immediately see what he prefers.

**Comment by rixx** [comment]
Actually, I can't reproduce that – just went to an event's sent emails that I had never looked at before, and they were sorted newest-first. Same for a demo event that I can actually share a screenshot for:

![2024-02-08T10:52:34+01:00](https://github.com/pretalx/pretalx/assets/2657547/834983d6-805f-4fa5-aecd-8dd6dd68e7d0)

The code lists `default_sort_field = "-sent"`, which seems correc.t
