### ISSUE TITLE
Speaker page always reports as changed

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1674]
### Problem and impact

When I open a speaker profile, eg http://localhost:8000/orga/event/fosdem-2024/speakers/LBHD3Y/ and switch to another page, eg click a link to a proposal the browser will always report the page as being changed, even if nothing was touched.

Eg this box in firefox
![image](https://github.com/pretalx/pretalx/assets/868434/8fedb71e-086d-4889-88ec-b57a98970095)

### Expected behaviour

If nothing is changed, it should not be reported as 'changed'.

### Browser (software, desktop or mobile?) and version

Firefox 115.6

### Operating system, dependency versions

linux

### Version

master

**Comment by rixx** [comment]
Are you sure you're running the latest pretalx version? You reported running on `master`, which we don't have, but I vividly remembering this being an issue when the "are you sure?" dialog was first introduced, and having fixed that later. (And I cannot, in fact, reproduce the problem in either dev or on pretalx.com).

**Comment by rixx** [comment]
Found it: the fix should be in 039bfd1d657bce766e6a3334c212209e04f46ad5, so nearly three months old.
