### ISSUE TITLE
Timezone Selection sorted or searchable

### ISSUE THREAD

**Issue by turbotimon** [pretalx/pretalx#1681]
### Problem and impact

When i create a new event, it is hard to find the right Timezone, because the list is not sorted nor searchable

![image](https://github.com/pretalx/pretalx/assets/57718207/7c85ffa2-facc-4537-85d4-4a272f730d50)

### Proposed solution / feature

- Make it searchable
- Or make it at least sorted (so e.g. all "Europe/..." or all "America/..." are together)

(Btw, new to pretalx an already love it!)

**Comment by rixx** [comment]
This is already implemented, both in event creation and event edit:

![2024-02-12T10:11:43+01:00](https://github.com/pretalx/pretalx/assets/2657547/1bd97f86-3587-4521-849d-593cc1cea50b)

Added in b2ce55bfd  for event edit and 0fe8b984c  for the wizard, introduced a day after the last release. Will be part of v2024.1.0.
