### ISSUE TITLE
Infinite Loop in all screens

### ISSUE THREAD

**Issue by freqq68** [pretalx/pretalx#1684]
### Problem and impact

Hello to all !

I perform an instalation of pretix, and I have something I don't know how it appends... 
In my screenshot you can see an big loop that appear on all pages, mobile, checkout etc...

![image](https://github.com/pretalx/pretalx/assets/4027268/c18810be-7b51-41b8-8d67-8d870835e9d7)

Do you know why ? It seem's a slideshow ? 
Thank's

### Steps to reproduce

1.
2.
3.
4.

### Screenshots

![image](https://github.com/pretalx/pretalx/assets/4027268/a8f071f1-bd03-4d31-b755-a97c90459f2a)
![image](https://github.com/pretalx/pretalx/assets/4027268/ec79c0e5-026d-4926-9c43-6cc7a768ae04)

**Comment by freqq68** [comment]
Hello,

I confirm that is it a Slideshow.

**Comment by rixx** [comment]
You're talking about [pretix](/pretix/pretix), not pretalx.
