### ISSUE TITLE
Tooltip on submission overview breaks usability

### ISSUE THREAD

**Issue by pascoda** [pretalx/pretalx#1687]
### Problem and impact

When trying to copy the review link from the speaker's submission overview, the tooltip (Review-Link kopieren) keeps popping up/does not go away. This keeps me from clicking the button to actually copy the review link.

### Expected behaviour

Tooltip should disappear again to make button clickable.

### Steps to reproduce

1. Be a speaker
2. submit proposal
3. try to share proposal from submission overview page
4. fail.

### Screenshots

![grafik](https://github.com/pretalx/pretalx/assets/6959763/3eb191b8-259c-4b3f-8050-607945677064)

### Link

https://fahrplan.eh21.easterhegg.eu

### Browser (software, desktop or mobile?) and version

Firefox 122.0.1

### Operating system, dependency versions

Windows 10 22H2

**Comment by rixx** [comment]
Cannot reproduce in dev or on pretalx.com, neither on Firefox 124 (known to work since at least Firefox 11x) or on Google Chrome. Possibly a problem with the local setup – please contact the administrators of the instance, as they can either fix the problem or provide further details here.
