### ISSUE TITLE
reject button is shown for confirmed submissions

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#169]
## Current Behavior

1. Create a submission
2. accept and confirm it
3. press the "reject" button
4. receive the following exception:
>SubmissionError at /orga/event/pw17/submissions/QJXKSB/reject
> Submission must be submitted or accepted not confirmed to be rejected.

## Possible Solution

Choose either one, I'll code up a PR:
a) Hide the reject button. This means that there is not a single button except for Delete shown. Mabye add a "unconfirm"-button?
b) [allow submissions](https://github.com/pretalx/pretalx/blob/master/src/pretalx/submission/models/submission.py#L38-L46) to switch from `CONFIRMED` to `REJECTED`.

In addition it would probably be smart to automatically generate a list of shown buttons based on `SubmissionStates.valid_next_states`, so you can't reach invalid states via the user interface.

**Comment by rixx** [comment]
a) with an unconfirm button sounds like a good idea.
