### ISSUE TITLE
Reordering tracks/rooms more easily

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1690]
### Problem and impact

When a large number of tracks or rooms is present, reordering them using the current interface is quite painful or even unworkeable (we used sql). Eg FOSDEM 2024 had 67 tracks. You don't want to press 60 up if you want to add another track on the top of the list

![image](https://github.com/pretalx/pretalx/assets/868434/dfa91006-574a-4360-b40c-0bcbe1afd610)

Some options I see:
* show the ordering number and make it editable (not very nice)
* a move below dropdown instead of the up down arrows, where you could specify the new position
* but ideally i think would be a 'drag and drop' handle instead of the up/down arrows.

The same issue exists for rooms, so we should probably use the same ui for both.

**Comment by rixx** [comment]
Yeah, I'd def want a drag'n'drop solution here. Notoriously annoying to build, but really should have done that ages ago. Happy to take contributions!

(Note: I want to get away from using jQuery, so preferably, the implementation would be in vanilla JS)
