### ISSUE TITLE
schedule.xml export / persons node missing

### ISSUE THREAD

**Issue by johnjohndoe** [pretalx/pretalx#1694]
### Problem and impact

The _schedule.xml_ exported by version _2024.2.0.dev0_ is not containing any `person` nodes.

``` xml
<event guid="5f049ba4-500a-5aa1-b04d-91b0d8ec97ad" id="39029">
	<room>Hörsaal 1 (Audimax 1)</room>
	<title>Hinweiskarten Starkregengefahren: OpenData für die bundesweite Klimawandelanpassung</title>
	<subtitle/>
	<type>Vortrag</type>
	<date>2024-03-20T14:50:00+01:00</date>
	<start>14:50</start>
	<duration>00:20</duration>
	<abstract>Infolge des Klimawandels ...</abstract>
	<slug>fossgis2024-39029-hinweiskarten-starkregengefahren-opendata-fr-die-bundesweite-klimawandelanpassung</slug>
	<track>Praxisberichte</track>
	<logo>/media/fossgis2024/submissions/F9Q3RK/Wasserh%C3%B6hen_22UWZcR.jpg</logo>
	<language>de-formal</language>
	<description>Die bei Starkregenereignissen...</description>
	<recording>
		<license/>
		<optout>false</optout>
	</recording>
	<links/>
	<attachments/>
	<url>https://pretalx.com/fossgis2024/talk/F9Q3RK/</url>
	<feedback_url>https://pretalx.com/fossgis2024/talk/F9Q3RK/feedback/</feedback_url>
</event>
```

### Expected behaviour

``` xml
<event guid="5f049ba4-500a-5aa1-b04d-91b0d8ec97ad" id="39029">
	<room>Hörsaal 1 (Audimax 1)</room>
	<title>Hinweiskarten Starkregengefahren: OpenData für die bundesweite Klimawandelanpassung</title>
	<subtitle/>
	<type>Vortrag</type>
	<date>2024-03-20T14:50:00+01:00</date>
	<start>14:50</start>
	<duration>00:20</duration>
	<abstract>Infolge des Klimawandels ...</abstract>
	<slug>fossgis2024-39029-hinweiskarten-starkregengefahren-opendata-fr-die-bundesweite-klimawandelanpassung</slug>
	<track>Praxisberichte</track>
	<logo>/media/fossgis2024/submissions/F9Q3RK/Wasserh%C3%B6hen_22UWZcR.jpg</logo>
	<persons>
		<person guid="062a3282-7689-5ffa-81fa-8282457f960c">Lukas Wimmer</person>
	</persons>
	<language>de-formal</language>
	<description>Die bei Starkregenereignissen...</description>
	<recording>
		<license/>
		<optout>false</optout>
	</recording>
	<links/>
	<attachments/>
	<url>https://pretalx.com/fossgis2024/talk/F9Q3RK/</url>
	<feedback_url>https://pretalx.com/fossgis2024/talk/F9Q3RK/feedback/</feedback_url>
</event>
```

### Steps to reproduce

1. Visit https://pretalx.com/fossgis2024/schedule/export/schedule.xml

### Link

https://pretalx.com/fossgis2024/schedule/export/schedule.xml

### Version

2024.2.0.dev0

**Comment by Masterart666** [comment]
![Uploading Logo_Default_A.png…]()

**Comment by Masterart666** [comment]
Hi

**Comment by Masterart666** [comment]
> ### Problem and impact
> The _schedule.xml_ exported by version _2024.2.0.dev0_ is not containing any `person` nodes.
> 
> ```
> <event guid="5f049ba4-500a-5aa1-b04d-91b0d8ec97ad" id="39029">
> 	<room>Hörsaal 1 (Audimax 1)</room>
> 	<title>Hinweiskarten Starkregengefahren: OpenData für die bundesweite Klimawandelanpassung</title>
> 	<subtitle/>
> 	<type>Vortrag</type>
> 	<date>2024-03-20T14:50:00+01:00</date>
> 	<start>14:50</start>
> 	<duration>00:20</duration>
> 	<abstract>Infolge des Klimawandels ...</abstract>
> 	<slug>fossgis2024-39029-hinweiskarten-starkregengefahren-opendata-fr-die-bundesweite-klimawandelanpassung</slug>
> 	<track>Praxisberichte</track>
> 	<logo>/media/fossgis2024/submissions/F9Q3RK/Wasserh%C3%B6hen_22UWZcR.jpg</logo>
> 	<language>de-formal</language>
> 	<description>Die bei Starkregenereignissen...</description>
> 	<recording>
> 		<license/>
> 		<optout>false</optout>
> 	</recording>
> 	<links/>
> 	<attachments/>
> 	<url>https://pretalx.com/fossgis2024/talk/F9Q3RK/</url>
> 	<feedback_url>https://pretalx.com/fossgis2024/talk/F9Q3RK/feedback/</feedback_url>
> </event>
> ```
> 
> ### Expected behaviour
> ```
> <event guid="5f049ba4-500a-5aa1-b04d-91b0d8ec97ad" id="39029">
> 	<room>Hörsaal 1 (Audimax 1)</room>
> 	<title>Hinweiskarten Starkregengefahren: OpenData für die bundesweite Klimawandelanpassung</title>
> 	<subtitle/>
> 	<type>Vortrag</type>
> 	<date>2024-03-20T14:50:00+01:00</date>
> 	<start>14:50</start>
> 	<duration>00:20</duration>
> 	<abstract>Infolge des Klimawandels ...</abstract>
> 	<slug>fossgis2024-39029-hinweiskarten-starkregengefahren-opendata-fr-die-bundesweite-klimawandelanpassung</slug>
> 	<track>Praxisberichte</track>
> 	<logo>/media/fossgis2024/submissions/F9Q3RK/Wasserh%C3%B6hen_22UWZcR.jpg</logo>
> 	<persons>
> 		<person guid="062a3282-7689-5ffa-81fa-8282457f960c">Lukas Wimmer</person>
> 	</persons>
> 	<language>de-formal</language>
> 	<description>Die bei Starkregenereignissen...</description>
> 	<recording>
> 		<license/>
> 		<optout>false</optout>
> 	</recording>
> 	<links/>
> 	<attachments/>
> 	<url>https://pretalx.com/fossgis2024/talk/F9Q3RK/</url>
> 	<feedback_url>https://pretalx.com/fossgis2024/talk/F9Q3RK/feedback/</feedback_url>
> </event>
> ```
> 
> ### Steps to reproduce
> 1. Visit https://pretalx.com/fossgis2024/schedule/export/schedule.xml
> 
> ### Screenshots
> _No response_
> 
> ### Link
> https://pretalx.com/fossgis2024/schedule/export/schedule.xml
> 
> ### Browser (software, desktop or mobile?) and version
> _No response_
> 
> ### Operating system, dependency versions
> _No response_
> 
> ### Version
> 2024.2.0.dev0
