### ISSUE TITLE
Serving statics in production

### ISSUE THREAD

**Issue by dionzand** [pretalx/pretalx#1695]
### Problem and impact

In debug mode all my statics are served correctly, but in production mode the statics are not served correctly to the "public" area of the website. The "organizers" area is still working correctly.

### Steps to reproduce

1. When debug = True, static files are served correctly
2. When debug = False, static files are not served to public area of website

### Screenshots

![publicarea](https://github.com/pretalx/pretalx/assets/105492790/77b05d9d-67f9-4023-9519-0919b2fe43df)
![organizersarea](https://github.com/pretalx/pretalx/assets/105492790/a9a14985-ffbf-41a1-853e-2d88b76d2b75)

**Comment by dionzand** [comment]
I tried it with a new event and apparently this only happens when I specify a custom colour for the event, so I think it has something to do with the regenerate_css..? Any tips on how I can troubleshoot this? Thanks!

**Comment by dionzand** [comment]
I am sorry, I was too quick with opening an issue. I solved it by adding the static location to the nginx virtual host.

**Comment by FFricke** [comment]
I got the same problem. I use the docker version and got the mappings of the static directory in the docker-compose and the pretalx.conf wrong
