### ISSUE TITLE
System info not availible in frontend

### ISSUE THREAD

**Issue by matebitte** [pretalx/pretalx#1707]
### Problem and impact

Bug reports as a user would be a lot easier, if the detected OS, browser and (most import) the running pretalx version would be visible to admin users under https://pretalx.example.com/orga/admin

**Comment by rixx** [comment]
![2024-03-06T13:12:53+01:00](https://github.com/pretalx/pretalx/assets/2657547/4c6aab07-0af9-4f8b-8af8-20e80851aabd)
this was implemented in 7ecf37d, five months ago, so hereby you know that you're not on the latest pretalx version :)
