### ISSUE TITLE
Unable to send emails

### ISSUE THREAD

**Issue by rhandorf** [pretalx/pretalx#1713]
### Problem and impact

When the system tries to send email addresses, the following error is presented.

DEBUG 2024-03-12 19:37:56,491 rules predicates   (can_change_submissions & can_edit_mail) = True
ERROR 2024-03-12 19:37:56,614 celery.app.trace trace Task pretalx.common.mail.mail_send_task[2f4e3fd6-5bee-43dc-bd79-075f8060bba4] ra
Traceback (most recent call last):
  File "/home/pretalx/.local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/pretalx/.local/lib/python3.6/site-packages/pretalx/common/mail.py", line 98, in mail_send_task
    email.attach_alternative(inline_css(html), "text/html")
  File "/home/pretalx/.local/lib/python3.6/site-packages/inlinestyler/utils.py", line 17, in inline_css
    converter.perform(document, html_message, '', encoding=encoding)
  File "/home/pretalx/.local/lib/python3.6/site-packages/inlinestyler/converter.py", line 30, in perform
    matching = CSSRelSelector.evaluate(document)
AttributeError: 'CSSSelector' object has no attribute 'evaluate

### Expected behaviour

Being able to send email.

### Steps to reproduce

1. Install the latest pretalx
2. Attempt to have the system generate an email message.
3.
4.

### Browser (software, desktop or mobile?) and version

Chrome/FF

**Comment by rixx** [comment]
> ### Operating system, dependency versions
> _No response_
> ### Version
> _No response_

We put these fields into our issue form for a reason – it's very hard to help people without the required information.

Your stack trace shows that you're running Python 3.6, which has been end of life for over two years. Please update your pretalx, including your system requirements, up to current versions. If you're still running into problems, you could try opening a discussion – or, if this issue still occurs, and you're sure that you've found a bug, then please open a new, *complete* bug report.
