### ISSUE TITLE
UI: Selection of state: not all states are shown

### ISSUE THREAD

**Issue by Rufus125** [pretalx/pretalx#1718]
### Problem and impact

When I am filtering talks and get a very short list, not all states are shown in the selection box:
<img width="498" alt="image" src="https://github.com/pretalx/pretalx/assets/5963362/d6f1c4aa-df6d-40c1-b199-07c8410e9d9e">
When I scroll down, I see the whole list.

### Expected behaviour

The list is not "hidden"

### Steps to reproduce

1.
2.
3.
4.

### Link

https://pretalx.linuxtage.at/orga/event/glt24/submissions/?q=&submission_type=56

### Browser (software, desktop or mobile?) and version

Chrome

### Operating system, dependency versions

Win10

### Version

v2023.1.3

**Comment by mridubhatnagar** [comment]
@rixx can I work on this?

**Comment by rixx** [comment]
sure!

**Comment by mridubhatnagar** [comment]
> @mridubhatnagar Just wanted to check in if this is going alright for you, or if you need any help getting set up.

@rixx sorry for delayed response. 

I did try to clone the project on my local and then tried to reproduce the given issue. 
But, I wasn't able to reproduce it. Also, I am on linux operating system. Not sure if this issue is OS and browser specific.

**Comment by rixx** [comment]
@mridubhatnagar Hmm, can you show a screenshot of the issue not showing up for you? Shouldn't depend on anything, any correctly-working browser should be showing this problem.

**Comment by rixx** [comment]
Huh, can confirm – either the original browser was odd (though I recall seeing this issue!), or something else resolved it incidentally in the past months. Thank you for reporting this issue fixed – I know this kind of thing can be a bit frustrating, but knowing that this issue can be closed is still very helpful!

**Comment by Rufus125** [comment]
Hey @rixx , @mridubhatnagar !
I still see the same problem! Comparing our screenshots: I can see that I filtered the session types and my list contains 3 entries compared to 1.
Another example:
![image](https://github.com/pretalx/pretalx/assets/5963362/9252a09b-1174-4360-9112-ed973509fe5a)

**Comment by rixx** [comment]
@Rufus125 Regardless, I can confirm that this problem does not occur in the current `main` branch. Please allow for some time in order for fixes to a) land in a release and b) the release to be installed on your server. If the problem still occurs with the (not yet released) v2024.2.0 release, please let us know.

**Comment by Rufus125** [comment]
Ah, I see. Thanks!
