### ISSUE TITLE
Date Indicator Glitches

### ISSUE THREAD

**Issue by Nachtpfoetchen** [pretalx/pretalx#1722]
### Problem and impact

When I scroll rapidly up and down in firefox the date indicator gets glitchy and might indicate another date then the listed events are happening.

### Expected behaviour

It not being glitchy and show the date for the current displayed events

### Steps to reproduce

1. scroll a lot around
2. wait until it glitches
3.
4.

### Screenshots

![Screenshot_20240330_101903](https://github.com/pretalx/pretalx/assets/47748053/8615a6a6-c963-451e-bf7a-c0dae566d593)
![grafik](https://github.com/pretalx/pretalx/assets/47748053/91f17e57-a37b-4d06-ad02-436ec3534523)

### Link

https://fahrplan.eh21.easterhegg.eu/eh/schedule/#2024-03-30

### Browser (software, desktop or mobile?) and version

Firefox-esr 115.9.1
Chromium 123.0.6312.86

### Operating system, dependency versions

debian bookworm 12.5

**Comment by rixx** [comment]
Can't reproduce – maybe my wild scrolling is too slow, but I tried my best. Will of course still happily merge a PR fixing the issue.
