### ISSUE TITLE
'Reviewers can see other reviews' setting doesn't seem to have any effect 

### ISSUE THREAD

**Issue by skryukova** [pretalx/pretalx#1723]
### Problem and impact

My event has 2 phases: Review & Selection. Review phase is currently active, but setting 'Reviewers can see other reviews' to 'Never' or 'After reviewing proposals' does not seem to have any effect.
 

### Expected behaviour

I was expected reviewers not to be able to see other reviews on proposals, ever (until the next phase Selection kicks in)

### Steps to reproduce

1. CFP for the event is active, the review is currently in the 'Review' phase.
2. The Review phase has Never setting in the 'Reviewers can see other reviews'
3. All reviewers seem to be able to see scores and reviews of other reviewers. 
4. The setting was originally set to 

### Browser (software, desktop or mobile?) and version

Google Chrome

**Comment by rixx** [comment]
pretalx always applies the broadest possible permissions it can apply – if you have more permissions than *just* reviewer permissions, you'll always be able to access additional data. The "can see other reviews" permission is only applied to people who are *just* reviewers, i.e. who don't have permissions in addition to the reviewer permission.

**Comment by skryukova** [comment]
I understand that. However, my team members who are not administrators, and only have "reviewer" permissions are still able to see the reviews by other people. 

For example, user with just "Is a reviewer" checkbox checked, can still see every review, every score. They are just not able to see the names of the other reviewers or average score.

If I add "Can work with and change proposals" to that role, the users can also see the names of the other reviewers and the average scores. 

That does not seem like an intended behavior to me.

**Comment by rixx** [comment]
I cannot reproduce this bug at all. I created a new user, and added them to a team with exactly just the reviewer permission. The review phase is configured like this: 
![2024-04-02T18:02:30+02:00](https://github.com/pretalx/pretalx/assets/2657547/4dfb60c5-3d90-4866-8a72-d935f605cbcf)

The review user is not able to see any reviews, neither before nor after submitting their review – they see only their own review:

![2024-04-02T18:03:34+02:00](https://github.com/pretalx/pretalx/assets/2657547/c982ec80-908a-42a2-9aea-f22d3390b9a8)

In contrast, the organiser user can see this new review as well as all other reviews:

![2024-04-02T18:04:19+02:00](https://github.com/pretalx/pretalx/assets/2657547/29294b68-d880-4c62-bb22-0c663e5171d6)

If changing the setting has no effect at all, then one of these must be true:

- your reviewers are part of some team that grants them additional permissions
- you're not in the review phase that you think you're in
- you're running different code than the current release or current development branch (though I don't think we had a bug related to this in ages)

It's impossible to know what's going on without further information, sorry – I hope showing a complete configuration/reproduction in my screenshots above is helpful in figuring out what's going on.
