### ISSUE TITLE
allow scheduling of "pending accepted" talks

### ISSUE THREAD

**Issue by margau** [pretalx/pretalx#1730]
### Problem and impact

When i'm planning an event/designing a schedule, I don't want to finally already accept a talks (so that speakers could see the accepted state after login), but already try out how everything fits in the schedule editor. Currently, pending accepted proposals don't show up in the schedule editor.

### Proposed solution / feature

We could make pending accepted talks show up in the schedule editor, or make this configurable.
This would however require the availability of "Start" and "End" time, which is not currently available for talks in "pending accepted" state.
Maybe there is another option?

**Comment by rixx** [comment]
Thank you again for requesting and building this!
