### ISSUE TITLE
Gravitar checkbox should stay checked

### ISSUE THREAD

**Issue by jidanni** [pretalx/pretalx#1736]
### Problem and impact

Editing our profile a second time shows the Gravitar button has oddly become unchecked.

Yes, there is a certain logic involved. But I would just keep it checked, once the user has checked it.

![Screenshot 2024-04-06 13 09 30](https://github.com/pretalx/pretalx/assets/1230959/3f392680-8b5b-469b-ad63-6974c7438112)

That way each time he goes to Edit My Profile, he needn't think "huh, didn't I tell it to use my Gravitar?"

Yes even if lower down it says it is indeed using it.

**Comment by rixx** [comment]
I don't see how this would violate the TOS of Automattic, who (as far as I can tell) do not have separate TOS for Gravatar. If, however, you can point out where pretalx violates the TOS of Gravatar/Automattic, I'd of course stop doing so immediately and disable our Gravatar integration! As that's a topic of legal bearing, please contact [info at pretalx.com](mailto:info@pretalx.com) for further discussion.
