### ISSUE TITLE
Flashing link

### ISSUE THREAD

**Issue by jidanni** [pretalx/pretalx#1737]
### Problem and impact

On https://pretalx.com/sotm2024/me/submissions/ I put my mouse upon this "chain" icon,
![Screenshot 2024-04-06 22 44 45](https://github.com/pretalx/pretalx/assets/1230959/76bb4b03-1e32-4faf-9184-52933869b352)
and some balloon kept on flashing, about two times a second.

**Comment by rixx** [comment]
Cannot reproduce (tried Firefox 125 and Chrome 122).
