### ISSUE TITLE
Sessions and Speakers overview numbers not updating on Dashboard

### ISSUE THREAD

**Issue by timothymamo** [pretalx/pretalx#1741]
### Problem and impact

When withdrawing a session and/or speaker from the confirmed sessions (for example when a speaker has to withdraw their session after accepting and confirming), the values of `Sessions` and `Speakers` on the `Dashboard` page are not updated. The number of speakers and sessions within the appropriate pages show the correct number.

### Expected behaviour

The number of Sessions and Speakers on the Dashboard page show the correct number of session and speakers as in the Speakers and Sessions pages

### Steps to reproduce

1. Accept and confirm sessions and speakers
2. Confirm sessions and speakers on Dashboard page are equivalent to that within Sessions and Speakers page
3. Withdraw a session
4. Sessions and speakers on Dashboard are different to those within 

### Screenshots

Correct number of sessions being shown in the `Sessions` page
<img width="1709" alt="Screenshot 2024-04-10 at 11 00 29" src="https://github.com/pretalx/pretalx/assets/65859835/5e77632b-7e25-4b51-afec-b72f23699965">

Correct number of speakers being shown in the `Speakers` page
<img width="1710" alt="Screenshot 2024-04-10 at 11 01 46" src="https://github.com/pretalx/pretalx/assets/65859835/bcda3dd3-2795-4886-b3da-ad2a2cd442ee">

Incorrect number of sessions and speakers on the `Dashboard` page
<img width="1709" alt="Screenshot 2024-04-10 at 11 10 08" src="https://github.com/pretalx/pretalx/assets/65859835/80b7fc83-d8df-4acd-8322-771109614085">

### Browser (software, desktop or mobile?) and version

Firefox 124.0.1

### Operating system, dependency versions

macOS 14.4.1

**Comment by rixx** [comment]
Hmm, I'd give even odds that the dashboard numbers are based on public speakers; that is, they would update when the schedule reflects the change in proposal status.

**Comment by timothymamo** [comment]
Ahhh yes seems to be the case. I hadn't released a new schedule after withdrawing one of the speakers/sessions. I've now released a new version of the schedule and the numbers have been updated appropriately on the `Dashboard` page to sync with those on the `Speakers` and `Sessions` page.

For our conference our "source of truth" (so to speak) with regards to program for attendees is going to be on devopsdays.org, which is managed in a different way (at least for now). Would be nice to have the numbers sync with the relevant pages rather than the schedule, but its a minimal issue, so happy to have this closed if you see fit

**Comment by rixx** [comment]
Yeah, closing for now – I def agree that we need to settle on a central definition of what constitutes a session as compared to a proposal, but I think that's a big effort best left for another time. Definitely welcome to have the current convention documented here, so thank you for opening this issue!
