### ISSUE TITLE
Unable to move questions up or down

### ISSUE THREAD

**Issue by skryukova** [pretalx/pretalx#1743]
### Problem and impact

When trying to move per speaker questions up or down, nothing appears to happen. The UI does display `The order has been updated.` message, but nothing changes on the screen. Refreshing the screen also shows original order.

The CFP is closed, and we are in the review process. I was trying to add a few questions for the "accepted" speakers to fill out.

Looking at the Network panel in the Dev Tools, I see that calls to the backend endpoints result in `302 Found` 

### Steps to reproduce

1. Create CFP with several "per speaker" questions
2. After CFP closes, create new question.
3. Try to move the original or new questions up or down in the list.

### Browser (software, desktop or mobile?) and version

Google Chrome

**Comment by rixx** [comment]
> Link
> No response

These fields exist for a reason: without knowing which instance *or* which pretalx version bug reports refer to, this maximises the work we get to do to reproduce the bug or figure out what's going on.

**Comment by rixx** [comment]
For reference, this is a bug that was fixed in 3aab65e, and knowing if the bug occurred on pretalx.com or in development or on a self-hosted instance would have narrowed it down quite a bit.
