### ISSUE TITLE
Heroku/Dokku deployment compatibility

### ISSUE THREAD

**Issue by strugee** [pretalx/pretalx#1748]
### Problem and impact

Heroku and Dokku are both platform-as-a-service systems that make deploying stuff really easy. It would be great if Pretalx could be deployed using one of these systems.

### Proposed solution / feature

I'm already working on this in a downstream fork - mostly I'm filing this issue to see if you would take patches upstream to make it work.

**Comment by rixx** [comment]
Hmm, I don't think this would be a good thing to include in the pretalx repository, as files like that wouldn't be maintained, and would be frustrating to run into for users hoping for an easy setup solution.

However! I do think it's cool to have something like that around. What do you think about documenting the setup / writing the required files, and then linking the result (be it a fork or a repo or a blog post, etc) in the [Deployment section of the Community Tools wiki page](https://github.com/pretalx/pretalx/wiki/Community-Tools#deployment)? That way, people could find help easily, but at the same time, it would be clearly signposted that there's no official support …
