### ISSUE TITLE
add tooltip explaning do-not-record icon

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#176]
In the public schedule view do-not-record is currently shown as a 🚫 symbol. This should but clear to many people, but maybe not to all. We could add a tooltip to make it clearer in a non-intrusive way.

**Comment by rixx** [comment]
We already have the hover CSS tooltip and the regular html tooltip. We should probably add this information to either of these, not add a third one. :wink:

**Comment by tabascoeye** [comment]
@luto: agree to close this after #184 was merged?

**Comment by rixx** [comment]
Definitely a closed issue :)
