### ISSUE TITLE
"Send mail to speakers" link is wrong

### ISSUE THREAD

**Issue by paulmelis** [pretalx/pretalx#1771]
### Problem and impact

When viewing a submission, there's a `Send email` button at the top of the page and a `Send mail to speakers` button at the bottom. 

The top button links to `.../mails/compose/sessions/?submissions=<id>`, while the bottom button links to `.../mails/compose/sessions/?submission=<id>`. Note the `submissions` versus `submission`. 

The latter causes the proposal filter to be empty, and I got bitten by this yesterday by accidentally sending an e-mail to all our speakers, while I intended to address only a single proposal.

Btw, if these two buttons are intended to do the exact same thing then I suggest to also give them the exact same label, to avoid confusion.

### Expected behaviour

Apply the correct proposal filter on the Email editor page being linked to.

### Browser (software, desktop or mobile?) and version

Firefox 125.0.3, Chromium 125.0.6442

### Version

2024.1.0 I believe (I don't manage the instance)

**Comment by rixx** [comment]
I'll remove the email button at the bottom, as that's pretty non-standard and in a weird position anyways. The one at the top will show up on every proposal sub-page, too, which is nice and consistent.
