### ISSUE TITLE
pretalx-schedule widget: settings bar stretches width of content causing horizontal scrollbar

### ISSUE THREAD

**Issue by beinardus** [pretalx/pretalx#1772]
### Problem and impact

When just using the example on https://docs.pretalx.org/user/event/widget/, and resize the window, so that it does not have abundant horizontal space, the "settings" bar doesn't size to fit into the container, resulting in a horizontal scrollbar and the time-zone button is rendered half outside the viewport. Also the containers of the events in the right most column are not fully visible.
See attached screen shot (`scrollbar.png`). This effect disappears when the "settings" bar is not rendered (by setting `display:none`). See second screen shot (`no-scrollbar.png`), where there is no horizontal scrollbar and plenty space to show the content.

### Expected behaviour

A horizontal scollbar should be the last resort. There is no need for one in this case.
Diving a bit deeper in the problem shows that there is a difference in the original `schedule/src/App.vue` where the width of the "settings" bar is determined bij a calculation where room for a scrollbar (?) is taken into account:
line 331: `width: min(calc(100vw - 36px), var(--schedule-max-width))`
And te widget (`pretalx/src/pretalx/static/agenda/js/pretalx-schedule.js`):
line 20164: `width:var(--schedule-max-width)`

### Steps to reproduce

Easy to check from the Google DevTools by disabling the rendering of the "settings" div by adding the attribute: `style="display:none"`

### Screenshots

![scrollbar](https://github.com/pretalx/pretalx/assets/46429579/a79f7cc6-19c1-4e23-ba87-5ab371528f9c)
![no-scrollbar](https://github.com/pretalx/pretalx/assets/46429579/2c8f1da3-42bb-48d7-a048-9253197f982e)

### Link

https://docs.pretalx.org/user/event/widget/

### Browser (software, desktop or mobile?) and version

Chrome desktop / Chrome mobile

### Operating system, dependency versions

Windows 11 / Android

**Comment by rixx** [comment]
The size of the schedule widget depends on its scrollparent. I agree that this wasn't looking very flattering in our docs atm, should be fixed now.
