### ISSUE TITLE
Locale only partially applied, mostly English fallback loaded

### ISSUE THREAD

**Issue by almereyda** [pretalx/pretalx#1773]
### Problem and impact

In running pretalx in a declarative and immutable environment https://github.com/pretalx/pretalx-docker/pull/64 a regression regarding using the language code to set the locale has emerged.

When setting the `PRETALX_LANGUAGE_CODE` to `de` or any other locale than `en`, most of the language strings are not translated in the generated HTML.

<details><summary>The generated HTML. (snippet)</summary>
<p>

```html
<div class="submit-group panel">
    <span></span>
    <span>
        <button
            type="submit" class="btn btn-success btn-lg"
            value="profile"
            name="form"
        >
            <i class="fa fa-check"></i>
            Speichern
        </button>
    </span>
</div>

        </fieldset>
    </form>
    <form method="post" class="password-input-form">
        <input type="hidden" name="csrfmiddlewaretoken" value="3hXcUnEzUliWouTxFO152AKct9Vs5xINVNYIdJ1Rlu8VNQiA4m5LBjCf0SjhrtHw">
        <fieldset class="m-2">
            <legend>Login settings</legend>
            <script src="[/static/vendored/zxcvbn.095d5364dae4.js](view-source:https://pretalx.allmende.io/static/vendored/zxcvbn.095d5364dae4.js)"></script>
<script src="[/static/common/js/password_strength.04222154cb10.js](view-source:https://pretalx.allmende.io/static/common/js/password_strength.04222154cb10.js)"></script>
            <div class="form-group row"><label class="col-md-3 col-form-label" for="id_email">E-mail</label><div class="col-md-9"><input type="email" name="email" value="yala@allmende.io" maxlength="254" class="form-control" placeholder="E-mail" title="Your email address will be used for password resets and notification about your event/proposals." required id="id_email">
    <small class="form-text text-muted">Your email address will be used for password resets and notification about your event/proposals.</small>

</div></div>
<div class="form-group row"><label class="col-md-3 col-form-label" for="id_old_password">Password (current)</label><div class="col-md-9"><input type="password" name="old_password" class="form-control" placeholder="Password (current)" title="" required id="id_old_password"></div></div>
<div class="form-group row"><label class="col-md-3 col-form-label" for="id_password">Neues Passwort<br><span class="optional">Optional</span></label><div class="col-md-9"><input type="password" name="password" class="form-control password_strength" placeholder="Neues Passwort" title="">
        <div class="password-progress">
            <div class="password-progress-bar progress">
                <div class="progress-bar progress-bar-warning password_strength_bar"
                     role="progressbar"
                     aria-valuenow="0"
                     aria-valuemin="0"
                     aria-valuemax="4">
                </div>
            </div>
            <p class="text-muted password_strength_info hidden">
                <span style="margin-left:5px;">
                    This password would take <em class="password_strength_time"></em> to crack.
                </span>
            </p>
        </div>
        </div></div>
<div class="form-group row"><label class="col-md-3 col-form-label" for="id_password_repeat">New password (again)<br><span class="optional">Optional</span></label><div class="col-md-9"><input type="password" name="password_repeat" class="form-control password_confirmation" placeholder="New password (again)" title="" data-confirm-with="password">
        <div class="hidden password_strength_info">
            <p class="text-muted">
                <span class="label label-danger">Warning</span>
                <span>Your passwords don't match.</span>
            </p>
        </div>
        </div></div>
            
<div class="submit-group panel">
    <span></span>
    <span>
        <button
            type="submit" class="btn btn-success btn-lg"
            value="login"
            name="form"
        >
            <i class="fa fa-check"></i>
            Speichern
        </button>
    </span>
</div>
```

</p>
</details> 

Also switching the language on an event page for a dual-language event has no effect on the button and UI labels: https://pretalx.allmende.io/agrikulturfestival-berlin-2024/

The application reports itself to be configured in `de`, but can't seem to be able to apply all language strings of a given locale, but only some?

```sh
$ curl -sSL https://pretalx.allmende.io | grep lang
<html lang="de">
```

In the pretalx shell:

```sh
>>> from pretalx.common.language import get_current_language_information
>>> get_current_language_information()
{'name': 'Deutsch', 'natural_name': 'Deutsch', 'official': True, 'percentage': 100, 'path': 'de_DE', 'code': 'de'}
```

### Expected behaviour

The UI is shown completely in the configured system locale and in the selected user locale.

### Steps to reproduce

1. Set up pretalx with `PRETALX_LANGUAGE_CODE=de`
2. Run the application
3. See the error on public and logged in pages.

### Screenshots

![grafik](https://github.com/pretalx/pretalx/assets/1645308/2fcde38f-6af1-4bb9-9e46-286dd0db6ccf)

Only "Neues Passwort" and "Speichern" are applied.

![grafik](https://github.com/pretalx/pretalx/assets/1645308/78736799-659f-4893-8fe9-81756c1afbef)

- Deutsch
  - Go to CfP
  - Contact Us
  - Imprint

### Link

https://pretalx.allmende.io/

### Browser (software, desktop or mobile?) and version

Firefox

### Operating system, dependency versions

as per - https://github.com/allmende/pretalx-docker/blob/next/context/default/Dockerfile.debian

### Version

2024.1.0

**Comment by almereyda** [comment]
The application is now running from main and reports itself as v2024.2.0.dev0.

Unfortunately the locale is still only applied partially.

Are there maybe other [commands to run after an upgrade](https://docs.pretalx.org/administrator/maintenance/#updates), other than:

```sh
python -m pretalx migrate
python -m pretalx rebuild --npm-install
python -m pretalx regenerate_css
```

In French, for example, a few more translation strings get through than in German:

![grafik](https://github.com/pretalx/pretalx/assets/1645308/693842ff-cf7f-48b3-916b-9aac8da73b73)

Is it possible to reproduce this issue somewhere else, or must it be a side-effect from using https://github.com/pretalx/pretalx-docker/pull/64?

**Comment by rixx** [comment]
Plugins should not skew translations. The documented rebuild commands should be taking care of all that's necessary.

In your example, an untranslated string is "Password (current)". This string is translated in `#: pretalx/person/forms.py:287`, where it is included with `gettext_lazy` (and has been for ages).

I cannot reproduce the issue – looking at the demo event at [pretalx.com](https://pretalx.com/democon), and in particular at the user/profile form, all form labels appear as the German / translated string upon locale switch.

**Comment by almereyda** [comment]
Will investigate.

**Comment by almereyda** [comment]
Please reopen for the time being, while investigating.
