### ISSUE TITLE
Ability to automate submitting talks

### ISSUE THREAD

**Issue by ekohilas** [pretalx/pretalx#1778]
### Problem and impact

When trying to submit multiple talks across multiple conferences, I need to copy and paste the same content manually. This is tiring and time intensive.

### Proposed solution / feature

Ideally, I could import a previously submitted talk from a different conference.
However understandably the data between conferences is separated.
Instead, if a talk submission API endpoint is created, one could write a tool to automate submitting talks given an API key for a given conference.

**Comment by rixx** [comment]
> Instead, if a talk submission API endpoint is created

There already is a submission endpoint; however, it is read-only. As such, this issue will be resolved once we have a writeable API, as per #1598.
