### ISSUE TITLE
CSS-Media-Files get  blocked due to MIME type

### ISSUE THREAD

**Issue by FFricke** [pretalx/pretalx#1783]
### Problem and impact

Firstly: Thanks a lot for all the work. I am a big pretalx-fan!

To the problem: I installed normal pretalx based on the documentation instructions with postgres, celery and python 3.1 on Ubuntu 22.04 with nginx as the web-server.

All css files from the static direcotry work fine. If I create a new event and don't alter the look of it too much it get's displayed normally (as I understand, that in such a case the css stylesheets from the static directory still get used. If I add an event-icon for example, the stylesheets get blocked with the error in firefox The resource from “https://myurl.com/var/pretalx/media/testerich-2024/cfp.f1fbfba20a6bc42d.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

I already tried to include mime.types in nginx and changed the location of the media directory back and forth and nothing worked. I'm quite cueless.

pretalx conf.
`[filesystem]
data = /var/pretalx/data/
static = /var/pretalx/static/
media = /var/pretalx/media/
logs = /var/pretalx/logs/

[site]
debug = FALSE
url = https://myurl.com
static = /var/pretalx/static/
media = /var/pretalx/media/

[database]
backend = postgresql
name = pretalx
user = pretalx
password = pretalx
host = localhost
port = 5432`

nginx.conf

`
user pretalx;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
`

and the the config file from sites-available

`
server {
        server_name pretalx;
        listen 81;
        charset utf-8;
        source_charset utf-8;   

        location / {
          proxy_pass          http://localhost:8345;
          proxy_set_header    Host $host;
          proxy_set_header    X-Forwarded-Proto $scheme;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /static/{
               autoindex on;
               alias /var/pretalx/static/;
               }

        location /media/{
               autoindex on;
               alias /var/pretalx/media/;
               }

}
`

### Steps to reproduce

1.
2.
3.
4.

### Link

https://event.archaeo-nerd.de/democon/

### Browser (software, desktop or mobile?) and version

Firefox, Chromium

### Operating system, dependency versions

Ubuntu 22.04. LXC

**Comment by jpoisso** [comment]
I'm having the same issue as well.

The files exist under /data/media/<talk>/*.css  and have the right permissions.

but when I load the Cfp page in any browser, it complains about the Mime Type but in my case, the size of the content is 0B (404) , which seems to be interpreted as HTML by the browser.

**Comment by rixx** [comment]
Your files aren't being rejected due to MIME type, they fail to load because the request, as @jpoisso points out, returns a 404.

In your case, this is because your configuration file is faulty. The configuration entries in the `site` section are meant to be site paths, not file system paths. Please refer to [the relevant documentation](https://docs.pretalx.org/administrator/configure/#id1) – you should not need to configure/change the `site.media` and `site.static` values at all.
