### ISSUE TITLE
Calendar export ignores filters

### ISSUE THREAD

**Issue by KeithWM** [pretalx/pretalx#1794]
### Problem and impact

When exporting a filtered view of talks to iCal, it exports _all_ the talks, not just those visible on screen.  I think it would be better to only export those shown, or at least present a warning that _all_ talks will be exported.

Not to labour the point, but just to make it clear why a warning might be in place: if you _do_ export all items and then import them into your own calendar application, it is a real nuisance to remove all the items again. At least MS Outlook was not designed for batch selection of calendar items. I managed by searching for all calendar items where the location was one of the rooms in the relevant event, but even this was quite some work.

### Expected behaviour

I would expect the export to only export what is shown on screen.

### Steps to reproduce

1. Remove some items from view using a filter in the calendar view
2. Click "export" at the top right
3. Import the .ical file into some application (probably best as a separate calendar for ease of undoing)
4. Behold the items in the calendar that had been filtered out

### Screenshots

I did not take any, but for 10 minutes my Outlook calendar was an absolute mess.

### Link

https://pretalx.com/juliacon2024/schedule/

**Comment by rixx** [comment]
I don't think we have a good place to show that warning, and we definitely do not have a way to provide an export filter like that. Given that, I wonder if we should remove or hide the ical export, limiting it to organisers. I can't imagine that it would be useful for attendees in most (or any) cases.

**Comment by rixx** [comment]
> Why is it not possible to use the same filter for the "stars" in the programme for the calendar export functionality?

I'm not sure what you mean by this. We currently do not have any filtered iCal export – neither for track / type filters, nor for starred talks. This issue is being tracked in #1002.

> Could that someone be implemented server-side?

Of course a filtered export could be implemented server-side, it's just that nobody has done that yet.

**Comment by rixx** [comment]
While the global iCal export is now gone (as in: restricted to organisers), there is now instead an export that is explicitly scoped to just your starred sessions.

**Comment by CarlSchwan** [comment]
We were using the global iCal export a lot in the [KDE Kongress app](https://apps.kde.org/kongress/). Importing the whole schedule was important for us to display an offline schedules of conferences. This is causing issue for example for adding the schedule of the "Grazer Linuxtage 2025" in Kongress https://invent.kde.org/websites/autoconfig-kde-org/-/merge_requests/52/diffs#note_1085126

**Comment by rixx** [comment]
Hmm, I see – I didn’t realise any apps used `ical` of all available formats as an API – a bit of an [xkcd#1172](https://xkcd.com/1172/), in that I only ever intended the iCal export to serve humans, as we have the API, JSON, XML, XCAL etc exports for automated consumers.

**Comment by rixx** [comment]
@CarlSchwan I added a way for exporters to be publicly available without showing up in the drop-down, so the iCal exporter should be available again, just not listed in order to avoid the confusion that led to this issue.

Hope this is a servicable solution for Kongress – thank you for pinging me about the problem!

**Comment by CarlSchwan** [comment]
Thank you!

**Comment by pspacek** [comment]
@rixx I can only confirm what @CarlSchwan said. We also use iCal as input for various tools. If it were meant for human consumption we could have stayed with TXT :-)

**Comment by pspacek** [comment]
I reacted because of the [xkcd#1172](https://xkcd.com/1172/) reference and wanted to make clear @CarlSchwan is not the only person on planet with this requirement. Plus I wanted to clarify that iCal is not only for humans to consume, that seems like misunderstanding purpose of iCal protocol. (BTW I found this issue only because the iCal export disappeared from an event page where it used to be.)

**Comment by pspacek** [comment]
I think we are in violent agreement then! No action needed. Thank you!

(FTR the reason why we use iCal with full feed is to generate meeting summaries. iCal allows us to use the same code for multiple events which run on three different scheduling systems - IETF's own Datatracker, Indico, and Pretalx. I hope it clarifies why common format is useful.)
