### ISSUE TITLE
Can't delete default "custom" mail template

### ISSUE THREAD

**Issue by tabascoeye** [pretalx/pretalx#180]
When trying to delete the "custom" mail template that is provided by the default installation, a protectedError Exception is raised.

## Expected Behavior
When pressing a red button labelled "delete" I expect something to be gone afterwards

## Current Behavior
an exception is raised and the "custom" mail template is still there.
I can however create a new "custom" mail template and delete that one flawlessly

## Possible Solution
dunno

## Steps to Reproduce (for bugs)
see above. Clean install, go to mail templates, click the "delete" on the bottom of the screen

## Your Environment
* Version used: trunk
* Operating System and version (desktop or mobile): macos sierra

## Trace
http://dpaste.com/3Y27XG9

**Comment by luto** [comment]
Thank you very much for you report! I pushed [a fix for this particular issue](https://github.com/pretalx/pretalx/commit/6614dc2fec8df4c2700a4024cc6d0f7e57f8fc39), which should get rid of that crash.

The code involved here could use a little cleanup to make it more robust, though, so I am leaving this issue open. In particular, the list of default templates exists in at least 4 places:
 [`event.py`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/event/models/event.py) (twice), [`mails.py`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/orga/views/mails.py) (twice), [`template_list.html`](https://github.com/pretalx/pretalx/blob/master/src/pretalx/orga/templates/orga/mails/template_list.html#L19). There shoud really only be one list in `event.py` in addition to the field definitions.
