### ISSUE TITLE
Limit reviewer's access to proposals by tag

### ISSUE THREAD

**Issue by OldhamMade** [pretalx/pretalx#1814]
### Problem and impact

For some events there may be different classifications of reviewers: event organisers, and subject matter experts. Organisers review incoming proposals for quality control, then SMEs review proposals for their specific area of expertise. Right now there is no way to separate this process.

### Proposed solution / feature

We would like to ensure that some reviewers (SMEs) can only review proposals that have first been tagged with a specific tag (a tag relating to the SME's area of expertise).

### Context or examples

For example, let's say that there is a new Python conference being hosted. The event organisers review proposals to ensure all basic information is provided and add tags such as `machine-learning`, `infrastructure`, `virtual-machine`, etc. The organisers do not have the expertise to decide which talks would be most interesting to attendees.

An SME with expertise in machine learning would then review the _contents_ of proposals tagged `machine-learning` to accept a number of proposals for the Main room on a 2hr Tuesday afternoon slot. This SME would not see any proposals other than those tagged with `machine-learning`.

A separate SME with expertise in Python virtual machine internals would then review the _contents_ of proposals tagged `virtual-machine` to accept a number of proposals for the Side room on a 1hr Friday morning slot. This SME would not see any proposals other than those tagged with `virtual-machine`.

**Comment by rixx** [comment]
I'm afraid this feature is not in scope right now. I'd be open to a discussion of an external contribution, but there are a bunch of complicating factors that the contributor would have to solve. I'm closing this as not planned for this reason.

To expand: Reviewers can currently be either individually assigned or limited based on **tracks** (not tags). This, already, leads to a bunch of confusion and makes people overwhelmed with how to manage their review teams and assignments. Additionally, reviewers can have the permission to change and create tags, which would interfere rather severely with also having permissions scoped by tag, and this contradiction would need to be resolved, and resolved in a way that makes it clear to organisers what is happening (i.e. with leading to absolutely no new support requests). If there is a proposal on how to implement all this without interfering with track-based and assignment-based reviewing, *and* with clear UI and guidance, I'd be open to discussing an external contribution of this feature.
