### ISSUE TITLE
Following documentation on FreeBSD leaves with in installation that will crash 

### ISSUE THREAD

**Issue by erdgeist** [pretalx/pretalx#1845]
### Problem and impact

When following the steps in [the install guide](https://github.com/pretalx/pretalx/blob/main/doc/administrator/installation.rst?plain=1#L155), in the end I will see an error:
`CommandError: Compressor is disabled. Set the COMPRESS_ENABLED setting or use --force to override.`

this is all fine in debug mode, but once I switch to release, the app will crash with an error like this:

```
Oct  8 04:00:47 cfp pretalx[88084]: compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "b489efdda5a5d50716bc8f035aa016054b121f3e0082b961bac653840d84284f" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:
```

also rending the error leads to another exception. After running `python -m pretalx compress`, all went fine. Should this go to the install documentation, or is something else off with my setup that disabled `COMPRESS_ENABLED`?

### Steps to reproduce

1.
2.
3.
4.

### Operating system, dependency versions

FreeBSD

**Comment by rixx** [comment]
You have to run the `rebuild` command with the same `debug` setting as the server runs as – if you run `rebuild` with `debug=true`, then switch to `debug=false` and start the server, it'll try to find compressed files – but for debug/development mode, files aren't compressed, hence the failure.
