### ISSUE TITLE
Links in orga feedback view are only referring to the page itself

### ISSUE THREAD

**Issue by oskar456** [pretalx/pretalx#1848]
### Problem and impact

When trying to review feedback on an URL like:
```https://pretalx.linuxdays.cz/orga/event/linuxdays-2024/submissions/feedback/```,
each submission title is a link that leads to the very same URL.

### Expected behaviour

I believe it should point to the submission page or to the submission feedback page.

### Steps to reproduce

1. get at least one feedback in your event
2. open Sessions -> Feedback in Orga interface
3. click on the link of a session
4. the page just reloads

### Browser (software, desktop or mobile?) and version

Chrome 129

### Operating system, dependency versions

macOS 15.0.1

**Comment by rixx** [comment]
This was fixed 12 days ago in 5a43f4c!
