### ISSUE TITLE
Copy link for drafts on submissions page not accessible

### ISSUE THREAD

**Issue by zivillian** [pretalx/pretalx#1854]
### Problem and impact

When trying to copy the link for a draft submission in Firefox the button cannot be clicked, because the tooltip is above.

### Expected behaviour

Being able to click the button.

### Steps to reproduce

1. save a draft submission
2. goto `/me/submissions/`
3. try to click the copy link button for the draft

### Screenshots

![grafik](https://github.com/user-attachments/assets/f8c26948-406e-431a-9737-45aa30b17142)

### Link

https://cfp.cccv.de/38c3/me/submissions/

### Browser (software, desktop or mobile?) and version

Firefox 131.0.2 on Windows Desktop

**Comment by zivillian** [comment]
duplicate of #1687

**Comment by rixx** [comment]
The entire tooltip system has been rewritten in the meantime, so please re-open once your instance is running the to-be-released-this-week v2024.3.0.
