### ISSUE TITLE
Add a "Back to schedule" button to the talk details page

### ISSUE THREAD

**Issue by g4b1nagy** [pretalx/pretalx#1855]
### Problem and impact

I visit the schedule page e.g:
https://pretalx.sifs0005.infs.ch/swiss-python-summit-2024/schedule/
I click on one of the talks.
I want to go back to the schedule page.
I have to use the browser's back button.

If, however, someone sends me a link to a talk e.g:
https://pretalx.sifs0005.infs.ch/swiss-python-summit-2024/talk/UX7SGC/
There is no way for me to navigate from there to the schedule page, outside of modifying the URL.

### Proposed solution / feature

Having a "Back to schedule" button on the talk details page would be super helpful.

**Comment by rixx** [comment]
You can also, instead, click the Event logo / title to go back to the event.

Indeed, on current pretalx, there is also a navigation menu listing "schedule", "sessions" and "speakers" as navigation options, [as you can see here](https://pretalx.com/democon/talk/KLJMEY/), which imo is better than a "back to  schedule" button, as the user may not have *come* from the schedule. They may have come from the speaker's page, or a related talk, etc.
