### ISSUE TITLE
The new info pop up about being in the organizer area

### ISSUE THREAD

**Issue by plaindocs** [pretalx/pretalx#1864]
### Problem and impact

I understand why it's there, but I'd like to be able to dismiss it (as someone who spends a lot more time in the org area than the submitted area).

I'd also like it to only show talks for current / public conferences not all, instead of all conferences. 

### Steps to reproduce

1.
2.
3.
4.

### Link

https://pretalx.com/orga/event/

**Comment by rixx** [comment]
We can probably just move this *below* the event list, right? This way, it won't be in the way for active organisers, but also will be immediately visible for people who don’t have any organiser events at all.

**Comment by plaindocs** [comment]
Yeah, that works. Danke!
