### ISSUE TITLE
track api is missing, or track_color information is missing in API

### ISSUE THREAD

**Issue by jmlich** [pretalx/pretalx#1866]
### Problem and impact

There is `track_id` and `track` in https://docs.pretalx.org/api/resources/talks/, but I would like to get color information. It could be shared directly in /talks/ as track_color or separately.

### Context or examples

I am trying to export schedule for printing and the information about track color is missing.

**Comment by rixx** [comment]
This feature request comes in the middle of the API rewrite, so I'm going to close it directly – I anticipate that the new API will expose all those fields under the `/tracks/` endpoint, where it actually belongs.
