### ISSUE TITLE
Schedule uses english localization instead of correct locale

### ISSUE THREAD

**Issue by fkusei** [pretalx/pretalx#1874]
### Problem and impact

When viewing a schedule for a german-only conference (like [Tools4AgileTeams 2024](https://pretalx.seibert.group/tools4agileteams-2024/schedule/)) the schedule uses english localization ("Wednesday" and AM/PM time) instead of the event locale.

If i remember correctly, 2023.2.x did this correctly.

### Expected behaviour

Schedule should use the event locale

### Steps to reproduce

1. Have Schedule
2. Set event language to "german" only
3. View Schedule
4. Schedule is english even when locale set to german

### Screenshots

![Screenshot 2024-10-29 at 08-24-04 Tools4AgileTeams 2024 pretalx](https://github.com/user-attachments/assets/1c9cfabc-951e-418a-acf4-2814a26334d5)

### Link

https://pretalx.seibert.group/tools4agileteams-2024/schedule/

### Browser (software, desktop or mobile?) and version

Firefox (Arch Linux, en_US); Chrome (Mac, de_DE)

### Version

103af4c00767a24b47f7a22ffdecd04393d78cb7 ("bump development version" after 2023.3.1)

**Comment by rixx** [comment]
Yup, this seems to have been a bug for the last months – we are not currently including moment locales in our schedule.js, because doing so with the new build tool is tricky / different from previously. It’s not the whole schedule that falls back to English, but it is anything concerning dates and times.

**Comment by rixx** [comment]
This seems to require us to switch from moment.js to something else. I spent the last 2.5 hours working on the switch to Luxon, and I at least have a rendering schedule again, but it’s still lacking

- timeslice collapse (making the schedule shorter where possible)
- locale use
- timezone switching

I'll try to find time in the coming days or during the weekend to get this done and released in another bugfix release.

**Comment by fkusei** [comment]
We just noticed this is now correct in pretalx and the widget, but not in venueless. I guess that should get reported to venueless then, am i right?

**Comment by rixx** [comment]
Yeah, the venueless schedule is a bit more involved than just an embedded widget.
