### ISSUE TITLE
Second submission of abstract not possible?

### ISSUE THREAD

**Issue by karttur** [pretalx/pretalx#1876]
### Problem and impact

I struggled for 1n hor to submit a 2nd abstract. Passing the 400 word count took 45 minutes and required logging in and out twice. When the word count came below 390 it worked. But then the last step in the (too) complex submission process reports and error - the second time that happened I write this. Now I give up.

Best

Thomas

### Steps to reproduce

1.
2.
3.
4.

**Comment by rixx** [comment]
I’m sorry to hear that you’ve had trouble with pretalx, but without further information, there’s no way I can help, I’m afraid. Some notes:

- You don’t mention which event this was for – many events host pretalx themselves, and often are behind on their updates.
- The word count limit as well as the current word count should be shown while you input your text, so you should have ample warning if you’ve been writing too many words. If that doesn’t happen, that’s either a bug or a problem in the instance’s update process.
- I’m not sure what you mean by "required logging in and out twice". It might be a bug, but without knowing what exactly happened (logged-in state should not affect your text length limitations at all), it’s hard to say.
- You mention a “too complex submission process” – please note that it’s the organisers’ decision how many fields to require and which fields/questions to show to you at all. At it’s simplest, the pretalx proposal process looks like "enter a title, log in, enter your name, done”, so I can’t treat this as a bug either.
