### ISSUE TITLE
Breaks should be part of /talks/ api

### ISSUE THREAD

**Issue by jmlich** [pretalx/pretalx#1878]
### Problem and impact

I am trying to export schedule into plain html, because I am not sure how to adjust it for printing better.

https://github.com/jmlich/pretalx_schedule

The "break" is not part of api `https://talks.openalt.cz/api/events/openalt-2024/talks/?limit=1000` and therefore I cannot easily render whole schedule.

### Expected behaviour

Breaks should be part of /talks/ api

### Steps to reproduce

1.
2.
3.
4.

### Screenshots

As you can see in the screenshot the 'intro' and 'lightning talk session are missing'
![screenshot](https://github.com/user-attachments/assets/177a6e93-2b3b-4eef-887b-ebc5c52d7313)
![screenshot2](https://github.com/user-attachments/assets/51c7d695-239d-49a8-8c15-13dcf67cb865)

### Link

https://www.openalt.cz/2024/program/

**Comment by rixx** [comment]
If you just want to render the same schedule data that the schedule widget is showing, you could consider using the schedule widget data endpoint instead.

**Comment by jmlich** [comment]
Schedule endpoint is not described in documentation, so I am not sure what to expect. Anyway, I have solved the issue for this year.

**Comment by rixx** [comment]
Yes, the widget data endpoint is not documented, as it may change at any point. I just wanted to offer you a pragmatic solution for your problem.

**Comment by jmlich** [comment]
thanks :+1:
