### ISSUE TITLE
Global search (typeahead) not working in firefox

### ISSUE THREAD

**Issue by johanvdw** [pretalx/pretalx#1895]
### Problem and impact

If I open the search box by clicking the event in organiser mode or typing alt+k, I can search when using chromium with the same setup (development server), but nothing happens in firefox.

This error appears in the console when I do so:
```
Uncaught ReferenceError: $ is not defined
    <anonymous> http://localhost:8000/static/orga/js/typeahead.js:2
```

no autocomplete is done, nor is anything happening when I press enter.

This was observed  in pretalx v2024.3.1

### Steps to reproduce

1.
2.
3.
4.

### Browser (software, desktop or mobile?) and version

Firefox 128.3.0esr

### Operating system, dependency versions

debian bookworm

### Version

2024.3.1

**Comment by rixx** [comment]
I’m afraid we (ie: I) can’t currently provide support to all versions of all browsers. I acknowledge that Firefox ESR exists and is distributed on some Linux versions as default browser, but the work required to keep pretalx fully compatible with such a (sorry!) niche browser is just out of scope for a project maintained by Just One Guy.

(FWIW, pretalx is regularly tested and works with *current* Firefox.)

**Comment by johanvdw** [comment]
Good you ddin't spend too much time on this, because the exact day I posted this issue firefox-esr on debian was updated and the issue was resolved.
