### ISSUE TITLE
Date tabs issues in the schedule

### ISSUE THREAD

**Issue by ogecece** [pretalx/pretalx#1898]
### Problem and impact

When scrolling the schedule in grid mode, the highlighted date tab doesn't change automatically. Also, the tabs aren't working on list mode when you click on the date.

I'm not sure if it is a bug related to our instance or with the project version, because I think it was working properly before. Could you help us out?

I believe it doesn't relate to #1722 since these bugs aren't found in their instance.

### Expected behaviour

When you scroll in grid mode, the highlighted date tab should automatically change when you reach new dates. In list mode, when you click on a date tab, the browser should scroll down to the first activities of that date.

### Steps to reproduce

**Grid**
1. Access the schedule in grid mode
2. Scroll down until you reach a date which isn't the first date of the event
3. Verify the highlighted date doesn't change at the top of the screen

**List**
1. Access the schedule in list mode
2. Click on a date tab
3. Verify the browser doesn't force-scroll to the desired date

### Screenshots

Grid mode, before scrolling
![image](https://github.com/user-attachments/assets/8ca78b2e-ecf7-4645-a09c-13dddad86273)

Grid mode, after scrolling
![image](https://github.com/user-attachments/assets/655c96f6-d9a9-448e-b67f-6a61e8b4351e)

### Link

https://atividades.americaaberta.org/2024/schedule/

### Browser (software, desktop or mobile?) and version

Tested in Chrome and Firefox, desktop and mobile

### Version

2024.3.1

**Comment by rixx** [comment]
This is fixed in the current pretalx build as you can see at [our demo event](https://pretalx.com/democon/schedule/). However, there are still other scrolling-bugs that we need to work out. We aim to have another release this year, and you should get the fix with that release or by upgrading to a [development version](https://docs.pretalx.org/administrator/maintenance/#installing-a-commit-or-a-branch-version).

**Comment by ogecece** [comment]
Thank you!
