### ISSUE TITLE
Can't log in on Firefox Android

### ISSUE THREAD

**Issue by HarHarLinks** [pretalx/pretalx#1905]
### Problem and impact

I'm trying to log into https://pretalx.fosdem.org on Firefox 132 for Android but can't.

### Expected behaviour

Can log in by clicking the green log in button or hitting virtual Enter.

### Steps to reproduce

1. go to https://pretalx.fosdem.org
2. enter email/pw
3. hit enter
4. hit the log in button

### Link

https://pretalx.fosdem.org

### Browser (software, desktop or mobile?) and version

Firefox 132 for Android

### Operating system, dependency versions

LineageOS 20

**Comment by rixx** [comment]
Cannot reproduce: Logging in on pretalx.com works perfectly fine on Firefox for Android 133, so this is either a problem with FF 132 (which would be surprising, as it’s a very standard form submit), or a problem with pretalx.fosdem.org.

**Comment by HarHarLinks** [comment]
Tried some more, deactivating plugins etc. It appears the android auto fill from keepass2android triggers the issue.
