### ISSUE TITLE
The Schedule's Editor module does not show the table

### ISSUE THREAD

**Issue by duongthuyle** [pretalx/pretalx#1916]
### Problem and impact

When I edit the schedule, no table shows up for me to edit sessions. 
<img width="1437" alt="Screenshot 2024-12-08 at 00 24 05" src="https://github.com/user-attachments/assets/f844dbaa-f291-4350-8973-260c852a8ba7">
<img width="1437" alt="Screenshot 2024-12-08 at 00 24 49" src="https://github.com/user-attachments/assets/575da51c-1ad1-4894-b0ce-7a1946c47b9c">
<img width="1437" alt="Screenshot 2024-12-08 at 00 24 14" src="https://github.com/user-attachments/assets/655a11ea-6534-4723-bdfd-683b66c93782">

![z6064172803284_ee75ecc5f46b22ab79edf01528a75397](https://github.com/user-attachments/assets/e13de1a0-f5f2-4940-80bf-ae94d5381f73)

### Expected behaviour

It should look like this.

![z6064182170875_8747141ad570cf9d37ab60c966454c39](https://github.com/user-attachments/assets/adb34222-d38c-4fff-8270-6f332123f45a)

### Steps to reproduce

1.
2.
3.
4.

### Link

https://pretalx.hoithaokhoahoc.vn/orga/event/vietnam-medical-english-conference-2024/schedule/

**Comment by rixx** [comment]
The pretalx schedule editor does work, so this is very likely not a bug, but rather a) you're using an unsupported browser, or b) something about your setup is not working in general. It’s very hard to say without further logs.

**Comment by duongthuyle** [comment]
I tried to fix the nginx configurations with AI assistance and it works now. Thank you anyway. I love pretalx.
