### ISSUE TITLE
Add breaks and similar events

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#242]
You may want to have non-talk events ("orga events"?) included in your schedule, such as a breakfast, a proper break, a party. You could do so by making a special submission, but that's a bit hacky.

(Data structure wise, this will of course be a submission, only with special treatment in the frontend.)

**Comment by rixx** [comment]
Since breaks can be relevant for all rooms, we could introduce a "blocks other rooms" flag for slots, in addition to the special event type.

**Comment by tabascoeye** [comment]
breaks could also be an attribute of rooms.
E.g. at conferences where complete rooms are getting "heralded/organized" by specific people, they might want to decide "lunch for my room/class/workshop is from 11:30 to 13:00"

The schedule arrangement/view would have to take those room attributes into account

**Comment by MacLemon** [comment]
Non-public events to be scheduled where everything else get scheduled would greatly help.

This includes pre- and post-conference days for buildup and teardown.
We're doing a morning-coffee-standup meeting and an after-day-retrospective and would love being able to schedule a room for that as well.

**Comment by rixx** [comment]
As a workaround, you can just never change those events to be confirmed (and leave them in "accepted" limbo) – you can schedule them and they will never show up on public schedules. Still, this is only a workaround until we get around to figure out non-public talks.

**Comment by MacLemon** [comment]
That is a nifty workaround we might (ab)use until this feature found time to get implemented.

**Comment by derpeter** [comment]
As an addition it would be nice to have a schedule.xml that does not include events like breaks or other placeholders that may be useful for the participants but not for machines / services

**Comment by meatballs** [comment]
I'd settle for a submission type that's only available to organisers and can have its own settings - that way I could flag it as being ok for multiple scheduling and have no abstract/notes without affecting the other types.

Then, I create a 'Lunch' submission and schedule it wherever I want.

**Comment by rixx** [comment]
Breaks are now a feature in pretalx (in the upcoming release after 1.0.4, so presumable 1.1.0 or 2.0). They ae always public, and get displayed differently than regular events. They are not included in any of the regular exports, for now. A [demo can be seen in this tweet](https://twitter.com/pretalx/status/1192817848470638594).
