### ISSUE TITLE
Add a button to activate/deactivate questions

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#246]
Since this is very relevant behaviour, a button might serve much better (and could be placed on the normal view as well as the edit view) than the current check box.

**Comment by rahmonov** [comment]
Hey @rixx, can I take up this issue?
Where should the button be located in the normal view and the edit view?
In the normal view, right beside edit and delete buttons? and in the edit view, beside the save button?

**Comment by rixx** [comment]
Either this, or put in an alert regarding the current state of the question, including the button to change it (similar to the orga backend's schedule view).
