### ISSUE TITLE
do not react to inviation links on GET

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#270]
The invitation links (e.g. into the orga or as a talk speaker) can currently be invoked via GET requests. Since those can happen without user interaction (e.g. automatic scanners or preloader browser plugins), we should switch them to listen for POST only. GET should cause the page to show a short information text as well as a button to cause the POST.

**Comment by rixx** [comment]
This issue is not too urgent since we only allow confirmation to logged in users.
