### ISSUE TITLE
Fix missing CSRF token in scheduling view

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#271]
Can't schedule talks atm, CSRF token is missing.

**Comment by rahmonov** [comment]
Hey there! I would like to contribute but can't reproduce this issue. How can I reproduce it?

**Comment by rixx** [comment]
Sorry, @rahmonov, I only saw your comment after fixing the issue. If you are interested, we have some other nice small issues to get to know this project, such as #246, #149, or #122. :)
