### ISSUE TITLE
i18n for HTML schedule export

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#279]
The schedule export currently always uses the events default language. Since many events offer content in multiple languages and expect visitors speaking different languages, there should be a way to export all languages, which are configured for each event.

- [ ] prefix all exported HTML paths by the language: `/de/event/schedule/index.html`
- [ ] option A: find a way to rewrite all links to `/en/..`, `/de/..`, and so on
- [ ] option B: provide a nginx config, which chooses the right sub-directory automatically based on browser headers

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx provides an HTML export of an event's schedule pages: the schedule itself, the speaker profiles, the talk detail pages, and all images, style sheets, etc. This export can be used to display the schedule somewhere else, to provide the speed and security associated with static HTML content.

Events, in pretalx, can choose to support multiple languages. The language of a page is not hardcoded in the URL, instead it is chosen based on the request cookie. As such, a static HTML page will not be able to replicate this behaviour. pretalx currently only provides the HTML export in a single language (the default event language).

A good first step would be to make the language of the HTML export an option (both in the export function and the User Interface part).

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

You can find the actual exporting code in `src/pretalx/agenda/management/commands/export_schedule_html.py`. This is a so-called Django admin command, which you can find out more about in the [Django documentation](https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/9). Add an optional `--language` flag to this command, and have a look at the language selection in `pretalx.common.middleware.event` (look at the `_select_locale` method).

For consistency, the default behaviour should remain as it is currently, with the special `--language all` flag to be used to get an export of all locales.

Once you have figured out how to make sure the correct language will be exported, have a look at the organiser interface for schedule exports, and allow users to select the language they'd like to use in the export.

The relevant view is in `pretalx.orga.views.schedule`.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rixx** [comment]
Since HTML exports are rarely used at this point, I'm closing this issue. If anybody wants to contribute it, I'll be happy to merge the contribution, but it won't be a priority in any way.
