### ISSUE TITLE
Schedule matching query does not exist when selecting the current draft after viewing another version

### ISSUE THREAD

**Issue by rahmonov** [pretalx/pretalx#282]
View some version of a schedule. Then, choose the current draft. It will raise `DoesNotExist` error.

## Possible Solution

Changing this:

    version = self.request.GET.get('version')

to this:

    version = self.request.GET.get('version') or None

Once you guys confirm, I can send a PR.

**Comment by rixx** [comment]
I can confirm the issue – you probably don't want to set `None` though (which is what `.get()` returns anyways on a miss), but set the `active_schedule` to `self.request.event.wip_schedule` in that case.

**Comment by rahmonov** [comment]
`.get()` would return an empty string because the key `version` is actually there. But I like what you suggested more :)

**Comment by rixx** [comment]
Ah, I see – using `or self.request.event.wip_schedule` would work regardless, as empty strings evaluate as `False` :)
