### ISSUE TITLE
Embed streaming player

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#293]
Streaming players for talks would be neat. There should be a `/live/` page, and it should also be linked from the currently running talks, and/or embedded there.

**Comment by MacLemon** [comment]
Maybe also link from the talk in the Fahrplan to the re-live URLs at [Media CCC](https://media.ccc.de) if their streaming is used.

**Comment by rixx** [comment]
VOC is not a fan of publishing/distributing reLive URLs after the fact. (We should definitely find the time and add a proper frontend to embedding the normal media.ccc.de players, as those are currently added via an arcane manage command.)

**Comment by MacLemon** [comment]
I didn't mean for long after the conference, but during the conference, and maybe a week after. When available the links should vanish or be replaced by their proper recording links.

**Comment by rixx** [comment]
This should be the task of the respective recording plugins, now that we have got those.
