### ISSUE TITLE
Allow to customize exports

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#313]
Build an export from available fields and formats, and provide it under a custom endpoint. Both HTML and JSON exports should be offered.

**Comment by StephanJanosch** [comment]
This would be nice. I exported submissions of an 2 language event via API and it took me 3 hours to get the right table in order to categorize the reviews.

**Comment by rixx** [comment]
As this is a fairly complex feature, I'm afraid it will have to wait until it comes up naturally or until somebody sponsors the development on it.

**Comment by rixx** [comment]
I'm closing this issue for now: Custom exports for specific use cases can be created via plugins. A general export builder like proposed in this issue would be neat, but also a lot of effort. It won't happen unless inspiration or funding strikes. (If you want to commission this feature, please get in touch!)

**Comment by rixx** [comment]
Part of this is now implemented with the new speaker exporter as of 402c30c4:
![DeepinScreenshot_select-area_20210630024516](https://user-images.githubusercontent.com/2657547/123887626-223e8380-d952-11eb-905b-2fc64ed92411.png)
