### ISSUE TITLE
Event creation

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#326]
Event creation should be made better with a wizard, that allows to either create an event in several steps only, or add an xml upload, or generate a demo event.

When creating an event:

- [x] ask about the language early on
- [x] emphasize that the slug cannot be changed later on
- [x] warn that slugs longer than X characters may be annoying
- [x] add flags next to language checkboxes
- [x] warn if an event is created to take place in the past
- [ ] explain how language fallbacks work
- [x] suggest a slug automatically
- [x] validate slugs for plausability, as they can't be changed later on

**Comment by MacLemon** [comment]
Side note on wording:
A wizard, does something magical I don't understand. Things happen and then I have some sort of result without an idea how it came to be. I'm left with the emotion of having no influence on what happens.

An assistant on the other hand clearly communicates that I, the user, am in charge to control the widgets and assists me in achieving *my goal*, not the mysterious aim of a wizard.
