### ISSUE TITLE
Can't change type of submission

### ISSUE THREAD

**Issue by fraxinas** [pretalx/pretalx#329]
I've created a submission for eh18 and selected Workshop (60 min).
When I reviewed my submission, I noticed the Type of submission was set to Talk (60 min)
An orga member tried modifying it too and said it looks correct for them now - however it's still Talk (60 min) to me, even after flushing all caches / using a different browser.
Other fields can be modified and will be saved and displayed properly.

Submission subject is "Gstreamer Fundamentals" (XREHJL).

**Comment by rixx** [comment]
Thank you for the report – this was a display issue that will be fixed in the upcoming (today or tomorrow) v0.4.0 release.
