### ISSUE TITLE
Can't remove accepted/rejected status

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#342]
It would be nice to be able to remove the accepted/rejected status in order to have get the proposal back in the to-review queue in case the button was clicked by mistake.

## Expected Behavior

Being ale to reset the state of a proposal.

## Current Behavior

You can either click on the accept/reject button and swap he status, but not remove it completely

## Context

Accepted/rejected the submission by mistake.

**Comment by rixx** [comment]
Yup, I've run into this one, too. I'm closing it as a duplicate of #319, since closing that issue will allow to change arbitrarily between states.
