### ISSUE TITLE
Add confidence of reviewer 

### ISSUE THREAD

**Issue by rommelfs** [pretalx/pretalx#345]
In larger evaluation scenarios, sometimes people are semi-randomly assigned to review talks.
While it is always good to have a review of intelligent people, it is usually pretty fair to self-assess one's capabilities in regards to the topic - in other words to mention the confidence of the topic.
Analogue to the score, the confidence could be self-assessed.

In an ideal world, I could imagine the following situation:

Talk A
Reviewer 1 score: 10
Reviewer 1 confidence: 1

Reviewer 2 score:  7
Reviewer 2 confidence: 10

Reviewer 3 score: 3
Reviewer 3 confidence: 5

As a very simple way of dealing with the two values, it could be the (sum of (score * confidence)) / (number of reviews * 10):
```
10*1 + 7*10 + 3*5      10 + 70 + 15     95  
------------------  = ------------ =  -------  = 3,16
       3 * 10           30               30
```
Cheers,
Sascha

**Comment by rommelfs** [comment]
Oh and because it's important: as you have sometimes reviewers who don't have the best ability for self-assessment, it would be great if the assessment score could be changed by admins :-)

**Comment by rixx** [comment]
I'm generally not very happy with the review system right now, and I'm planning to remodel it towards "review questions" that you configure as the organiser. So you could ask "What score would you give this submission?", and you could ask "How confident are you in your score?", but you could also ask questions like "Is this a beginner-level talk?", etc. This would be more adaptable than adding a fixed second field, and once we introduce plugins, adding calculated properties to submissions (such as "(sum of (score * confidence)) / (number of reviews * 10)") would also be easy.

**Comment by rixx** [comment]
Review questions have been implemented. You can't sort by answers yet, but I'd think this kind of feature would best be located in a plugin.

**Comment by rixx** [comment]
We're moving all plugin ideas from the issue tracker to [this page](https://github.com/pretalx/pretalx/wiki/Plugin-ideas/).
