### ISSUE TITLE
Add a second speaker while submitting the talk

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#364]
Currently you can add additional speakers once you have finished your submission (by email address or by giving an invitation link to them). It would be cool to allow to include additional speakers via email address while submitting, too. Emails should be sent out only after the submission has been completed.

**Comment by rahmonov** [comment]
Hey guys, some description would be great here

**Comment by rixx** [comment]
@rahmonov Oops, true, added one. :)
