### ISSUE TITLE
Timezone discrepancy in CfP view

### ISSUE THREAD

**Issue by derchrisuk** [pretalx/pretalx#372]
## Expected Behavior
Setting a deadline in CfP->Content, and checking 'Display deadline publicly'.
Previewing the CfP it should show the correct deadline according to the servers Timezone.

## Current Behavior
Previewing the CfP shows a date for the deadline off by 7 hours.
it does show the correct TZ though, which is 'Europe/Berlin'

## Possible Solution
Checking Django config, it takes 'Americas/Chicago' as a default timezone
https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-TIME_ZONE

## Steps to Reproduce (for bugs)
1. Set deadline in CfP->Content
2. Check 'Display deadline publicly'

## Your Environment
* Version used: 0.4.1
* Operating System and version (desktop or mobile): Ubuntu stretch/sid, TZ Europe/Berlin
* Link to your project: not public

**Comment by derchrisuk** [comment]
Tried adding this to settings.py did not help
`TIME_ZONE = 'Europe/Berlin'`

**Comment by rixx** [comment]
PR #373 fixes this issue for me, can you confirm the fix, @derchrisuk?

**Comment by derchrisuk** [comment]
What is the best way to test this using the pip install approach?

**Comment by derchrisuk** [comment]
@rixx I can confirm after copying over the changes.

**Comment by rixx** [comment]
Thank you!
