### ISSUE TITLE
Link to Contribution guidelines in the documentation is 404

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#382]
Link to Contribution guidelines at Read the Docs is 404.

## Expected Behavior

Link should return a 200 and a contributors guide.

## Current Behavior

404

## Possible Solution

Link URL looks reasonable, contributors guide likely really missing because `E_NOTIME`.

## Steps to Reproduce (for bugs)

1. Read [CONTRIBUTING.md](https://github.com/pretalx/pretalx/blob/master/.github/CONTRIBUTING.md)
2. Click on the Link in “We've got an contributors guide in [our documentation](https://pretalx.readthedocs.io/en/latest/contribute/index.html).”
3. 404

## Context

Contributing anyway. \o/

## Your Environment

* Version used: n/a, affects documentation
* Environment name and version (e.g. Chrome 39, node.js 5.4): Any browser
* Operating System and version (desktop or mobile): n/a

**Comment by luto** [comment]
Thanks! :)

**Comment by MacLemon** [comment]
Thanks for fixing this! Contributing intensifies!

**Comment by rixx** [comment]
Danke, @luto.

**Comment by MacLemon** [comment]
Danke, @luto!
