### ISSUE TITLE
Offer schedule export urls without queryparams

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#383]
Apparently giggity has problems parsing schedule exports when offered the ``?exporter=core-frab-xml`` style url, giving up saying ``java.net.malformedURLException: Protocol not found``. If it receives the ``schedule.xml`` style url it works, indicating a problem parsing queryparams. Let's just switch to ``/schedule/exporter/<id>``.

**Comment by luto** [comment]
Importing the schedule with queryparams worked for me in giggity 1.3.2.

**Comment by rixx** [comment]
Having non-queryparam urls might be nicer, nonetheless.
