### ISSUE TITLE
Datetimepicker niggles

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#386]
- [x] Add a placeholder suggesting typing in an ISO8601 date
- [x] When entering the event end date, put the focus on the start date, not on today
- [x] When entering the event end date, highlight the event start date
- [ ] Highlight weekend days
- [ ] When typing in a date, the picker should jump to that date
- [ ] Give a better error when the event end is positioned before the end start
- [ ] Time should default to 23:59:59 instead of ~now

**Comment by raphaelm** [comment]
> When entering the event end date, highlight the event start date

The event start date is already used as a "limiter", it's impossible to select things that happen before. I guess that's sufficient?

**Comment by rixx** [comment]
Ehh, I think for now the datetimepicker works well enough. Let's open new issues for specific pain points.
