### ISSUE TITLE
Allow to configure possible submission languages

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#392]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx is only available in very few languages (English, German, tentative French), and events can only be run in these languages, in terms of their display. Currently, only active event languages are available to be set as submission language, but that's not correct: An event could have a UI in English, but allow submission in English, French, or Russian, for instance.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

The [Event](https://docs.pretalx.org/en/latest/developer/interfaces/models.html#events-and-organisers) model should include a `submission_locales` field that should offer all locales we know about for selection in `pretalx/orga/forms/event.py`. These should then be offered in all forms relating to the `Submission` model.

(Note that currently the `locale` field is not shown in submission forms if only one submission locale is possible for selection, please keep that behaviour intact.)

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by Bjwebb** [comment]
I'll take a look at this issue.

**Comment by rixx** [comment]
As a first go, you can now disable the pretalx-inbuilt proposal language to replace it with a custom question.
