### ISSUE TITLE
Improve markdown support

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#402]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx allows many fields to be filled in with markdown support. It would be great to offer an editor with a preview tab. Bonus points for an editor like this one here at GitHub, supporting adding markup via buttons for people not familiar with markdown.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

You'll want to implement a custom widget in `pretalx/common/forms/widgets.py`, where you can also see examples. Please note that this should provide a safe fallback for users who block JavaScript execution.
Static files can be added  in `pretalx/static/common/`, but should only be included in views with forms in the `cfp` and `agenda` parts of pretalx. In the `orga` app, you can include these parts in the `pretalx/orga/templates/orga/base.html` parent template, as basically every page in this area contains forms.

A challenge will be the proper inclusion of multi-language forms, so please make sure to test with events with a single active language and multiple active languages.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by obilodeau** [comment]
I wanted to note here that there is a way to preview your submission, it's just that you need to complete it first and then you can use the `share submission` link also called `Copy Code for Review` in the "My Submissions" section. There the markdown is rendered like reviewers would see it.

**Comment by rixx** [comment]
![Screenshot_2019-05-17  foo](https://user-images.githubusercontent.com/2657547/57924671-0a0c6700-78a6-11e9-9ae1-741a1ece48f9.png)

**Comment by beedell-roke** [comment]
That interface does not appear to work everywhere, as [`ask.libreoffice.org/t/137595`](https://ask.libreoffice.org/t/why-does-libreoffices-pretalx-instance-not-appear-to-support-markup/137595?u=rokejulianlockhart) may demonstrate.

**Comment by rixx** [comment]
@beedell-roke 
This issue was closed seven years ago, and pretalx has changed and improved its Markdown rendering several times over since then. Please open a new issue for this.

In this particular case, I'd expect this to be a browser / JavaScript issue, as when I open the page linked in your LibreOffice discussion, the preview renders correctly for me in both current Firefox and Chrome.

**Comment by beedell-roke** [comment]
> This issue was closed seven years ago, and pretalx has changed and improved its Markdown rendering several times over since then. Please open a new issue for this.

@rixx, downstream, with TDF (at its Redmine instance), or upstream, with you (at GitHub)? I ask because I don't know of an official Pretalx instance, to verify reproduction at.

---

<p></p><details open><p></p>

> In this particular case, I'd expect this to be a browser / JavaScript issue, as when I open the page linked in your LibreOffice discussion, the preview renders correctly for me in both current Firefox and Chrome.

It reproduces in `chromium-0:152.0.7977.82-1.fc44`, too:

<img width="1275" height="1162" alt="Image" src="https://github.com/user-attachments/assets/9b6f7f49-6c84-4b78-8207-75674ff3eb66" />

**Comment by rixx** [comment]
@beedell-roke I managed to reproduce the problem, which is specific not to all of pretalx, but to just the feedback page. Fix will be part of the upcoming v2026.3.0 release. TDF is currently running v2025.2.2, so it might be some time before the fix gets there, though.

**Comment by beedell-roke** [comment]
> TDF is currently running `v2025.2.2`, so it might be some time before the fix gets there, though.

@rixx, I have filed [`redmine.documentfoundation.org/issues/3888`](https://redmine.documentfoundation.org/issues/3888). Thank you.
