### ISSUE TITLE
currently not working on mysql > 5.5

### ISSUE THREAD

**Issue by morisson** [pretalx/pretalx#407]
It seems "storage_engine" is deprecated on mysql >= 5.6.

I get the following error:
`django.db.utils.OperationalError: (1193, "Unknown system variable 'storage_engine'")`

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_default_storage_engine

This is due to commit 31f97da97d3ab70dcc0f31a7743f3b9399dad230

(I previously commented on the commit, but I guess this is a better place to do so :))

**Comment by rixx** [comment]
Both are fine – I'll definitely look into it before releasing v0.6.0 later this month. Thank you for the report! (Also tagging @raphaelm because he's much more fluent in MySQL than I am.)

**Comment by raphaelm** [comment]
Well, if that variable doesn't exist any more, we should stop using it/replace it. We can also remove it alltogether since InnoDB is default on all sensible systems nowadays.
