### ISSUE TITLE
Mail system: Send mails from templates

### ISSUE THREAD

**Issue by rommelfs** [pretalx/pretalx#412]
In  pretalx v0.5.0:

When trying to send out emails (Mails->Send E-mails), none of the defined templates from Mails->Templates is shown. 

Is that a bug or just a missing feature?

**Comment by rixx** [comment]
It's a missing feature, and an important one at that. I thought I had an issue open for it, but apparently I was mistaken, so this one's it now.

**Comment by rixx** [comment]
Mails can now be sent from templates, but variables will not yet be substituted (as I need to think some more on how/if this is to be done. If you send an email to somebody with several submissions, this means you can't just use {talk_title} or similar in your template etc.)

**Comment by fflorent** [comment]
Hi there,

First of all, thank you for the quality and the features of the application, this is very pleasant!

> but variables will not yet be substituted (as I need to think some more on how/if this is to be done

Is this something you consider to implement soon? Or could we propose you some ideas for the implementation and submit some patch?

Cheers,
Florent

/cc @sparunakian

**Comment by rixx** [comment]
Unless this feature gets commissioned, I'm not very likely to tackle it soon, so feel free to submit a patch.

**Comment by fflorent** [comment]
Do you have any clue on it could implement it? We would be glad to contribute!

Florent

**Comment by rixx** [comment]
Sorry, no. If I knew off the top of my head how to implement this, it would be done already.

**Comment by fflorent** [comment]
OK, thanks!

**Comment by orlando** [comment]
@rixx I just stumbled with this today. Just to confirm, does this mean Pretalx cannot send emails with variables/placeholders?

**Comment by rixx** [comment]
Not custom emails, no. In the regular, supported email types, variables will be substituted, e.g. when you accept or reject a talk, when you ask speakers to answer open questions, when you send them updates regarding their schedule slots, and so on.

Reworking the email system is scheduled to be the first big feature for 2020, so I *hope* this issue will be closed by summer (northern hemisphere).
