### ISSUE TITLE
Send password reset via team pages

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#415]
Not really an issue, but more a support question: I cannot figure out how to initiate a password reset for a user (either a speaker or a reviewer).

Am I missing something obvious?

**Comment by Rafiot** [comment]
Hmm ok. Is there a (even hackish) way to force-reset the password for a reviewer or an organiser?

**Comment by rixx** [comment]
They can use that same frontend login URL.

**Comment by RichiH** [comment]
As per IRC, please also add a reset button in the CFP login process.

**Comment by RichiH** [comment]
Sorry, didn't see this was closed; opened https://github.com/pretalx/pretalx/issues/461 instead
