### ISSUE TITLE
Save button missing on <url>/orga/event/<event>/settings

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#417]
Impossible to change the parameters on the event setting page (`url>/orga/event/<event>/settings`)

## Expected Behavior

Clickable save button.

## Current Behavior

No save button

## Possible Solution

Save button 

## Steps to Reproduce (for bugs)

1. Visit `url>/orga/event/<event>/settings`

## Context

I updated from HEAD, re-ran the following

```
python -m pretalx migrate
python -m pretalx rebuild --clear
```

And tried to make the event public.

## Your Environment

* Version used: HEAD (f6471253b84e74cc77deb32b4373b9cbfa85f992)
* Environment name and version: Firefox 59.0.2 - Chrome 65.0.3325.181

**Comment by rixx** [comment]
pretalx is currently undergoing lots of restructuring in preparation for the upcoming 1.0 release, so master may not be vrey stable (even though I try to keep it that way). Thank you for the bug report, I'll be looking into it.

**Comment by Rafiot** [comment]
Hmm, I see. 

Should I revert to the latest 0.5 instead?

**Comment by rixx** [comment]
Running a public intance off a project's master branch is generally only adviseable if you need features that are not in the latest release, imo.
