### ISSUE TITLE
Public link to submission

### ISSUE THREAD

**Issue by benjaminwand** [pretalx/pretalx#421]
As a potential speaker, it would be nice having a public link to my submission, so I can discuss it with people.

## Expected Behavior
It would be possible (not sure whether optionally, or for all talks, or on/off for one event) to see a submission without being logged in, if one has the link to it.

## Current Behavior
Only when logged in one can see one-selves submission.

## Context
I would like to discuss with online acquaintances (Twitter ...) whether they find my proposed talk useful/interesting/whatever.

## Your Environment
* Version used: the one that is used by GPN18
* Operating System and version (desktop or mobile): MacOS X, Safari, but that s probably not relevant

**Comment by rixx** [comment]
Good idea! A submission specific secret token that can be reset by the speakers sounds like it will fit the bill.

**Comment by benjaminwand** [comment]
Yes, that sounds good :)

**Comment by akoskaaa** [comment]
I'm checking out this issue
