### ISSUE TITLE
Allow organisers to upload slides

### ISSUE THREAD

**Issue by laf0rge** [pretalx/pretalx#422]
We've just completed our first pretalx-scheduled conference (OsmoDevCon 2018) and now we need to collect the Speakers slides for each of the talks.  This would be so much simpler if it was managed by pretalx, similar to how it used to  be in pentabarf or other earlier systems.

Ideally the files would then be served via pretalx as static pages (either automatically, or after manual approval by the conference organizer) and linked from the published schedule.

**Comment by rixx** [comment]
Do the Speaker Resources pretalx offer not work for you? When editing a submission/talk, speakers can upload a number of files which will be shown on the talk page. 
![screenshot-2018-4-25 foo testevent pretalx](https://user-images.githubusercontent.com/2657547/39231581-d83a5078-486a-11e8-892d-a87d2ea9c741.png)
![screenshot-2018-4-25 your submission testevent pretalx](https://user-images.githubusercontent.com/2657547/39231585-dafc3786-486a-11e8-9c61-a2c854689d41.png)

**Comment by laf0rge** [comment]
How can I as the "orga" add those? Under "submissions" the last item I can see is "Talk image" but no resources.

**Comment by rixx** [comment]
Currently not possible, but a good idea and not hard to add.
