### ISSUE TITLE
Programm link visible in speaker view even when talk not scheduled yet

### ISSUE THREAD

**Issue by Duckattack** [pretalx/pretalx#429]
My talk was accepted. Therefore a "Programm" link showed up next to the talk in the "Meine Einreichungen" section. Since the talk is not scheduled yet, the link results in a 404.

## Expected Behavior / Possible Solution
The link should either be not visible or deactivated while the talk is not scheduled.

## Current Behavior
Link resulting in a 404 page.

## Steps to Reproduce (for bugs)

I experienced the bug in the GPN18 pretalx.  

## Context

I am a speaker and do not wish to be confused by non-working links. ;)

**Comment by rixx** [comment]
Thank you for the report.
