### ISSUE TITLE
schedule.xml lacks talk slug

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#430]
Due to requests from VOC, pretalx has started to follow frab's slug scheme (event-id-title) instead of exposing a talk's code (the alphanumerical ID). Now, the schedule.xml export contains no reference to the talk's slug at all anymore, so that dependent apps can't link to a talk's page.

I'm currently not really sure how to solve this without breaking compatibility at some point. frab uses numerical ids and puts them in the id field, but the id field is validated (by our tests, and the VOC tests, etc) to be numerical, so we can't use that.

**Comment by raphaelm** [comment]
Could we have a view like ``/event/talk/by-slug/event-id-title/`` that redirects to the actual talk view?

**Comment by rixx** [comment]
Sure, but for that to have a non-horrible performance, we'd need to save the slug in the db, so we'll also have to update it with every save, etc. A redirect view would work for the numeric IDs though.

I'd much prefer to find a way to put the pretalx ID somewhere in that export – I'm not sure my dedication to frab compatibility is large enough to justify an extra db field and additional views.

**Comment by raphaelm** [comment]
> Sure, but for that to have a non-horrible performance, we'd need to save the slug in the db, so we'll also have to update it with every save, etc. A redirect view would work for the numeric IDs though.

Doesn't the slug always contain the submission ID between the first and the second dash? That should be enough to find the talk, no need to save the full slug to the DB. Or did I misunderstand how the slug is built?

**Comment by johnjohndoe** [comment]
I noticed that a few conferences use the `<links></links>` node of the _schedule.xml_ to link out the corresponding website of the event. As far as I know this is a manual process. Therefore, I have little trust in this workaround.
In [EventFahrplan](https://github.com/EventFahrplan/EventFahrplan) I used to deduce the link from the `<event id='5397'>` or in rate cases from the `<slug>C7WRZV</slug>` node.

**Comment by saerdnaer** [comment]
> dependent apps can't link to a talk's page.
Actually, frab's schedule xml introduced a new property for that url, c.f. https://github.com/frab/frab/issues/361
