### ISSUE TITLE
"Other talks by ..." lists talks that are not confirmed or scheduled!

### ISSUE THREAD

**Issue by laf0rge** [pretalx/pretalx#431]
Preconditions:
* a single speaker has multiple talks
* some of the talks are accepted/confirmed
* one talk is only accepted but not confirmed

In this situation, the public schedule lists *all* the talks, *even those not confirmed* in the "Other talks by this speaker" box.

Can be seen at https://pretalx.sysmocom.de/osmodevcon2018/talk/XPFFS9/  where the tal "SIMtrce2 with SAM3" is an "accepted" (but never confirmed or scheduled) talk.  If you click on it, you'll get a 404.

The expected behavior is that this "other talks" list only shows other talks that are confirmed (and scheduled?) rather than any submissions that never made it to that stage.

This problem has been observed with v0.5 and v0.6.

**Comment by rixx** [comment]
Thank you for the report. The issue is fixed in v0.6.1, released just now.
