### ISSUE TITLE
e-mail "remind all speakers who haven't yet uploaded their slides"

### ISSUE THREAD

**Issue by laf0rge** [pretalx/pretalx#432]
Right now the "resources" are quite flexible/free-form, so this request is probably hard to implement.  However, if there was a more formal type such as "Slides", then one could have the following feature:

* send e-mails to _all speakers who still haven't yet uploaded their slides_

I think this is a very typical problem for a conference organizer, and having assistance for this in pretalx (rather than manually checking each "submission" if there's a related resource attached) would greatly simplify this work.

Thanks for your consideration.

**Comment by rixx** [comment]
I received the feedback that "resources" isn't very intuitive anyways, so I was thinking about naming them "attachments". We could then add attachment categories ("slides", "paper", plus any the organiser wishes to add?), and use that as a filter. It's definitely something pretalx should support.

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx provides an interface to send emails to speakers. Adding a template for submissions without uploaded files, and a button to transform that template to emails and send them would be great.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

Add "speakers who have not uploaded files for their submissions" to the form used in the `ComposeMail` view in `pretalx/orga/views/mails.py`, and edit the `form_valid` method of that view accordingly.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.
