### ISSUE TITLE
Allow the orga team to see the reviews without reviewing

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#433]
It would be handy to let the orga team see the reviews without having to write a review themselves.

**Comment by adulau** [comment]
Indeed, this is indeed quite annoying.

**Comment by vmx** [comment]
This might be related. If you are in a team with review permission only and you log in, you have also and "Organisers" menu entry on the left. If you click it you get a 404. I think the menu entry should just be not displayed.

**Comment by rixx** [comment]
No, that's a separate issue. But thanks for reporting it, I just pushed a fix in e384da57.
