### ISSUE TITLE
Emails get linked to main domain, even if custom domain is set for a conference.

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#446]
## Expected Behavior
When a custom domain is set for a conference, I'd expect links in Emails to be using that custom domain.

## Current Behavior
Emails sent out are using the main domain instead of the custom one.

## Steps to Reproduce

1. Create a conference
2. Add a custom domain in settings
3. Send an Email (Invitation, etc.)
4. Inspect the links in the email you received.

## Context
Looks a little strange and some recipients may be confused by the different looks of the landing page. (Due to different branding or lack thereof.)

## Your Environment

* Version used: pretalx 0.6.1
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome 68, Firefox 60
* Operating System and version (desktop or mobile): macOS 10.12.6
* Link to your instance, if in production: https://conference.c3w.at/ (main domain of our pretalx instance) https://cfp.privacyweek.at/ (The custom domain we wanted emails to use for links)

**Comment by rixx** [comment]
I added a patch to a third-party library some time ago to make it possible for us to fix this, and then … I had a typo in the code that produced the custom url. Very clever.
