### ISSUE TITLE
Links sent in emails only work when logged in

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#447]
## Expected Behavior
Links sent in Emails should land the recipient on either
- the corresponding page provided the user is already logged into pretalx
- ask the user to login with their existing account and the get redirected to the corresponding page

## Current Behavior
Links sent in emails show a “this page ceased to be” page without any confirmation or easily understood call to action to login.

## Steps to Reproduce

1. Confirm a submission
2. Send out that email
3. as a logged out user, click that unsuspicously looking link
4. Wonder why that link doesn't work (from a recipients point of view)

## Context
Looks a little embarrassing when speakers are asked to confirm their talk and the enclosed links are not working (from their point of view). Also creates backscatter support tickets.

## Your Environment

* Version used: pretalx 0.6.1
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome 68, Firefox 60
* Operating System and version (desktop or mobile): macOS 10.12, Desktop
* Link to your instance, if in production: https://cfp.privacyweek.at/

**Comment by rixx** [comment]
This was fixed a few days ago, the fix will be available once 0.6.2 or 0.7.0 is released.

**Comment by luto** [comment]
for reference: https://github.com/pretalx/pretalx/issues/438, https://github.com/pretalx/pretalx/pull/439. That only mentions confirmations, but affects all cfp URLs.

**Comment by MacLemon** [comment]
I apologise! My search foo was weak and so was this bug report.

**Comment by luto** [comment]
nah, that's why we've got that fancy "close issue"-button ;) the PR wasn't properly titled anyway.

Please let us know if this is fixed for you after the next release.

**Comment by MacLemon** [comment]
I've updated yesterday, but after the emails got sent. So there may already be a fix from head in there, but it may affect only future links. I haven't looked at the code, and frankly, I most likely wouldn't be able to tell anyway. :-)
Thanks for caring!

**Comment by rixx** [comment]
Unless you have updated to `master`, you won't have the fix until the next release. But as the fix does not change the links themselves, and only changes how unauthenticated access to those pages is handled, once the new release is out and you've updated, all will be well.

**Comment by rixx** [comment]
(Closing as it's fixed. Expect the next release soon, sorry for the delay.)
