### ISSUE TITLE
Python db module not installed in install instructions

### ISSUE THREAD

**Issue by momorientes** [pretalx/pretalx#453]
`psycopg2` and whatever the mysql equivalent aren't mentioned in the install instructions, therefore the db migration will fail on a clean install.

I used the following manual:
https://pretalx.readthedocs.io/en/latest/administrator/installation.html#step-0-prerequisites

(Me being to blind is a valid option)

**Comment by rixx** [comment]
Oh, right! We have the useful table™ in [the configuration section](https://pretalx.readthedocs.io/en/latest/administrator/configure.html#the-database-section), but not in the actual setup.
