### ISSUE TITLE
Unexpected Login/Register behaviour with multiple form inputs

### ISSUE THREAD

**Issue by hettipeti** [pretalx/pretalx#455]
## Expected Behavior
Login procedure should work as intended (my personal opinion for procedure):
Login if login field credentials correct and ignore register form data, else procedure/output for failed login.

## Current Behavior
**Case A:** 
Login form data: existing Username or Email + correct PW 
AND
Register form data: Not existent Username + random Email + (random) PW (PW repeat field NOT filled)

----> User from Register Form will be created with the PW set in the register field and you will be logged in as this new user.

**Case B:**
Login form Data: existing Username or Email + correct PW 
AND
Register form data: Existing Username + random Email + (random) PW (PW repeat field NOT filled)

----> Triggers HTTP 500 Error

## Steps to Reproduce

1. Go to pretalx login Page
2. Fill data according to Current Behavior 
(Loginform: Username + PW, Register Form: Username+Mail+PW)
3. Trigger Case A or Case B after klicking on Login Button

## Context
Password Manager sometimes autofill form fields for websites.
In my Case the PW Manager filled out username, email and pw of register field.
I let it there and filled out login fields Username and passwort.
After Login I got the green background with Pretalx 500 Error Logo and in the HTTP Request Log Server gave me HTTP 500 back.
After reproducing this behavior for this bugreport I found out that you can register new users with behavior stated in the Current Behavior Section and found out why the HTTP 500 gets triggered.

## Your Environment

Tested successful on:
* Firefox 61.0 64-Bit and Chromium Version 67.0.3396.87

**Comment by rixx** [comment]
The error response should not happen, I agree. I'm not sure about preferring the login form to the registration form though, up until now the intended behaviour was to show a warning if both parts of the form were filled

**Comment by rixx** [comment]
The login form will now be evaluated if both fields are filled. Otherwise, the registration form will be evaluated.

**Comment by hettipeti** [comment]
Thanks for quite fast fix :heart:
