### ISSUE TITLE
pretalx 'forgets' talks in the frontend schedule

### ISSUE THREAD

**Issue by flashfingaz** [pretalx/pretalx#458]
I encountered a strange problem, while I entered talks and workshops into the schedule: all of a sudden the schedule was completely empty in the frontend.
After adding another talk and putting that one on the schedule as well I was able to see it in the schedule frontent all alone. After saving a new program version the new talk also vanished from the frontend.

In the schedule editor however all talks and workshops are visible and can be moved around.
Using the export function I get working files but without a trace of any talk as well:
```
<!-- Made with love by pretalx v0.7.1. -->
<schedule>
<version>2018071602</version>
<conference><acronym>bbq18</acronym>
<title>Chaos BBQ 2018</title>
<start>2018-07-20</start>
<end>2018-07-22</end>
<days>3</days>
<timeslot_duration>00:05</timeslot_duration>
</conference>
<day index="1" date="2018-07-20" start="2018-07-20T00:00:00+02:00" end="2018-07-21T00:00:00+02:00"></day>
<day index="2" date="2018-07-21" start="2018-07-21T00:00:00+02:00" end="2018-07-22T00:00:00+02:00"></day>
<day index="3" date="2018-07-22" start="2018-07-22T00:00:00+02:00" end="2018-07-23T00:00:00+02:00"></day>
</schedule>
```
The prefilled version number in the backend also was jumping around randomly and ended displaying an heart. Not sure if that is an inteded joke or actually an error with my installation.

Any suggestions on what might be the root cause for not having my schedule in the frontend are highly  appreciated! :)

**Comment by flashfingaz** [comment]
also the changelog for every version that i saved states that there have been no changes for multiple versions (used numeric versions as well as names to see if there is any difference):

```
Version 2018071602

No changes are visible in this version, but be assured we're working on cool new versions behind the scenes.
Version 2018071601

Nothing has changed, we just wanted to change the version name. It was going out of style.
Version v1.1

No changes are visible in this version, but be assured we're working on cool new versions behind the scenes.
Version v4.1

Nothing has changed, we just wanted to change the version name. It was going out of style.
Version open

No changes are visible in this version, but be assured we're working on cool new versions behind the scenes.
Version empty

No changes are visible in this version, but be assured we're working on cool new versions behind the scenes.
Version incognito

No changes are visible in this version, but be assured we're working on cool new versions behind the scenes.
Version 1

We released our first schedule!

```

**Comment by rixx** [comment]
Are the talks accepted or confirmed? Only confirmed talks will show up on a released schedule, as all others haven't been cleared by the speakers yet.

**Comment by flashfingaz** [comment]
that did the trick, thx!
