### ISSUE TITLE
Reviewer trying to review their own talk see a "this has ceased to exist" instead of an error stating they don't have permission to see this

### ISSUE THREAD

**Issue by RichiH** [pretalx/pretalx#463]
It's good that reviewers can't see detailed reviews by other reviewers, but pretalx should throw an actual error/403/whatever.

**Comment by rixx** [comment]
This is the standard 404 page of pretalx. We could try and redirect to the previous page, and the reviewer shouldn't ever be presented their own talk for review, so that's a bug in itself.

**Comment by RichiH** [comment]
Well, I see my submission in the overview (along with the ratings),
but not the detailed view.

IMO, the detailed view should print something along the lines of "no
permission, bad user!" instead of a 404.
