### ISSUE TITLE
Review: Show whether a speaker has submitted other content

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretalx/pretalx#467]
I understand that pretalx is focused on the content submission during reviews and therefore does not show submitter information directly on the review page. However it may be useful to some reviewers to see other submissions of a person and may be a history of that person with the event.

**Comment by rixx** [comment]
I can see adding the speakers' biographies and maybe even links to other submissions, even though this would probably serve to make the review page very long and unwieldy in some cases. A history of that person would definitely be overkill.

Would need to be optional to allow to go for anonymous review as per #346.
