### ISSUE TITLE
Make submissions / content groupable

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretalx/pretalx#468]
## Problem you are facing
Submissions that cover a similiar topic are not linked to each other. This makes it harder to 

## Possible Solution
There could be some kind of grouping implemented. One approach would be to group submissions by submitee, the other to group them under an arbitrary label (eg. "talks about an awesome conference planning tool")

**Comment by rixx** [comment]
Grouping submissions by free-text input is pretty hard to get right, especially for the people involved. Where would those groups then be displayed? In the review list? The submission list?

I think this would end up more like a cluttering anti-feature. I'd argue it would be better to implement tracks as per #234.
