### ISSUE TITLE
Overwriting votes option not available

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#473]
## Expected Behavior

Being able to configure and overwrite votes.

## Current Behavior

No option to configure the overwrite: the CFP config page says `Individual reviewers can be assigned a fixed amount of "override votes" (positive or negative vetos). You can configure override votes in the team settings.` but there is no such option.

## Steps to Reproduce

1. Enable `Allow override votes`
2. Go on the team setting page
3. No configuration option.

## Your Environment

* Version used: 0.7.1
* Link to your instance, if in production: https://cfp.hack.lu

**Comment by rixx** [comment]
Apparently the override votes were lost in the team settings refactoring, that's not good.

**Comment by Rafiot** [comment]
Thank you :)
