### ISSUE TITLE
Being able to independently review the diferent types of papers (workshop/talks)

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#474]
## Problem you are facing

We have a list of over 100 proposals and some are talks (long/short) workshops, keynotes, ... and there is no easy way to filter them.

## Possible Solution

Allowing to sort the submissions would be nice.

**Comment by rixx** [comment]
Sorting and filtering the submission list is possible in the submission list. At least filters for submission type and current submission status are present, as well as a search field. What is the problem with those filters?

**Comment by rixx** [comment]
While I'm starting to consider to merge the two views, I don't really want to incur the score calculation penalty on every submission list load, so let's stick with the two separated lists with the same search/filter options for now.

**Comment by Rafiot** [comment]
makes sense, thanks!
