### ISSUE TITLE
delete event

### ISSUE THREAD

**Issue by Adorfer** [pretalx/pretalx#476]
## event created "by accident"

if an admin had created an event accidently, it can not be removed any more.
you may change the title, date it back to the last century and make it invisible for normal users.
But it will stay in the list of events. 

## Possible Solution
feature request: make it possible to drop the record from the events. 
Perhaps only if there are not submissions yet. (has to be verified.)

## Context
if it happens multiple times, eg. if the proposed "shorte URL name" is not suitable, the "unused events" may pile up in the schedule in the administrative view.

**Comment by rixx** [comment]
Good point – although I think at least for now an action with this amount of potential destruction should be a management command.
