### ISSUE TITLE
Make Speaker Biography optional

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#481]
## Expected Behavior
Some speakers do not want to submit a (lengthy) biography. Some conferences do not (want to) require one.

## Current Behavior
When changing anything on the speaker profile, one must enter all fields, which includes Biography. This is quite annoying to speakers when they have no bio entered yet, you send out email to ask them to enter their availability and they can't set that without also entering a bio.

## Steps to Reproduce

1. Create submission as team member
2. log out, log back in again
3. Try to enter availability without adding a bio

## Context

Users complain about not being able to change their things we asked them to without overhead. This makes speakers unhappy. :-(

## Your Environment

* Version used: 0.7.1 (latest *release* version)
* Environment name and version Independent of Browser version, Python 3.6
* Operating System and version (desktop or mobile): User: Debian, Desktop
* Link to your instance, if in production: https://conference.c3w.at

**Comment by rixx** [comment]
This is already implemented in the current master.
