### ISSUE TITLE
Speakers and orga update speaker's availability due to required fields

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#482]
## Expected Behavior
Orga Team members should be able to update a speaker's availability regardless

## Current Behavior
Neither speakers nor orga can update speaker's availability when required fields (like Bio) are empty. This forces speakers to update data at inconvenient times.

At least orga should be able to always update a speaker's availability without being forced to enter a bio for a speaker.

## Steps to Reproduce

1. As orga create a dummy submission for a speaker.
2. Ask speaker to update their availability.
3. Speaker doesn't want to add a bio, or is not able to do it at that point in time.
4. Speaker cannot enter availability as asked for
5. Speaker sends unhappy email.

## Context

We already had multiple speakers being unable to add their availability due to this.
I've not found a way to make the speaker bio optional or at least being able to override this as orga person.

## Your Environment

* Version used: 0.7.1 (latest *release*)
* Environment name and version Browser independent, python 3.6
* Operating System and version (desktop or mobile): Debian Desktop
* Link to your instance, if in production: https://conference.c3w.at/

**Comment by rixx** [comment]
The speaker bio can be made optional in the current master. I'm not sure we want to introduce different settings for organisers though.

In the current master, the availability input will also be presented when confirming an attendance, thereby removing the need to enter a biography. Will the combination of these features be sufficient to solve your problem?

**Comment by MacLemon** [comment]
That sounds pretty close (without having tried on a test installation). I'll get this going and report back.

**Comment by luto** [comment]
please reopen in case the new feature does not meet you needs. Thanks! :)
