### ISSUE TITLE
Speaker's links to submissions seem to only work for that speaker.

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#484]
## Expected Behavior
When a speaker talks to orga about a submission they sometimes include a link to their submission in question. Looking something like: https://pretalx.example.com/slug/me/submissions/ABCDEF/

## Current Behavior
When clicking that link as another user I end up at a login page, though I'm currently logged in as an orga team member. It may be ambiguous which exact submission that speaker is referring to when no further context is given. 

## Steps to Reproduce

1. Have a speaker submit 2 or more events.
2. The speaker looks at the details of one of their submissions and sends that link to the orga team
3. Orga team clicks the link and is presented with a login form to login to pretalx as that speaker.

## Context
This may be related to using different domains for some conferences as a landing page.

## Your Environment

* Version used: 0.7.1 (current *release*)
* Environment name and version Browser independent, python 3.6
* Operating System and version (desktop or mobile): macOS Desktop
* Link to your instance, if in production: https://cfp.privacyweek.at/ and https://conference.c3w.at/

**Comment by rixx** [comment]
No, this is not related to different domains – at that URL, everybody can only access submissions they themselves have submitted.

**Comment by MacLemon** [comment]
Would it make sense that, when logged in with an orga team account, that I can see all submissions by using a link provided by a person? That's pretty much what this boils down to.

**Comment by rixx** [comment]
I'm not sure this would be good or correct. The proper way to do this would be an impersonation feature for organizers or at least administrators – a "browse page as …". But that is a lot of work to implement.

**Comment by MacLemon** [comment]
Disregarding the fact that I don't know how these links are implemented.

As I understand this, it's not necessary to do a complete impersonation of a speaker by admins.
The link is opened, pretalx knows which talk is meant.

If the talk is not public, a redirect to login is necessary.
Either the person logs in as the speaker of the talk, everything is fine and works as usual.

Or the person logs in as admin of the conference, then they should be able to see the talk as well, since they could manually navigate there anyway, but why not make it more comfortable by just redirecting them where they'd expect to end up?

Am I vastly mistaken or are my assumptions and perceptions how this should work a vast fallacy? If the latter, where have I taken a wrong turn? (Not directly talking about (hard|a lot of work) to implement.)

**Comment by rixx** [comment]
There is a difference between the links to the personal area (`/me/…`) and the public area (`/schedule/…`). The pages in the personal area are editable and strictly only accessible to speakers of that talk. Your assumption is incorrect at the "since they could manually navigate there anyway" stage, because the admin can only navigate to the public url of that talk, not the private, editable one.

**Comment by MacLemon** [comment]
I see, thanks for the details.
Would a redirect of a-logged-in-not-that-speakers to the schedule URL of that same talk make sense then?

**Comment by rixx** [comment]
It … might? It seems pretty brittle, and I'd have to override our usual "check access rights, 404 if no access" system, which I'm always cautious about.

**Comment by rixx** [comment]
Upon further reflection, I really don't feel comfortable doing this – I don't want to leak which submission codes are valid and which aren't. If somebody proposed a PR, I'd work with them to get it merged, but I'll close this issue until then.
