### ISSUE TITLE
Mark day rollovers more visibly in Schedule > Editor

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#485]
## Problem you are facing
The schedule editor can get quite crowded with rooms and it's easy to overlook the separate days.

![screen shot 2018-08-29 at 19 38 54](https://user-images.githubusercontent.com/90635/44805102-9a453780-abc3-11e8-8b6a-40a10d650af1.png)

## Possible Solution
Add an overlay across the editor for the day changes to make it more visible.
![schedule editor suggestion 1](https://user-images.githubusercontent.com/90635/44805343-3b33f280-abc4-11e8-8a18-a3facc08d1d2.png)

## Context
This should improve overview in the editor and reduce confusion over which day a talk is scheduled on without requiring a lot of inconvenient scrolling.

**Comment by luto** [comment]
Thanks for the suggestion :) I've implemented a very similar approach:
![image](https://user-images.githubusercontent.com/2158203/45257645-071db600-b3aa-11e8-946f-6698219348f3.png)
