### ISSUE TITLE
Pin date row and room names to the top in Schedule > Editor

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#486]
## Problem you are facing
The schedule editor can become convoluted with many talks and rooms spanning multiple days. It's easy to lose track of which day you're working on with the schedule since it's all a long list.

![screen shot 2018-08-29 at 19 48 38](https://user-images.githubusercontent.com/90635/44805789-7256d380-abc5-11e8-8120-90e8fab61122.png)
![screen shot 2018-08-29 at 19 48 54](https://user-images.githubusercontent.com/90635/44806294-da59e980-abc6-11e8-8de5-6807177e56e3.png)

## Possible Solution
Pinning a row with the current date to the top when scrolling would help to gain a better overview.
This would also include pinning the row with the room names to the top.

![date row pinning at the top](https://user-images.githubusercontent.com/90635/44806380-1e4cee80-abc7-11e8-823d-0a87c0163b88.png)

## Context
Conferences that go over more than a day will benefit from better overview in the schedule editor.

**Comment by rixx** [comment]
![Screenshot_2019-03-10 35c3 pretalx](https://user-images.githubusercontent.com/2657547/54089292-dbcf5000-4367-11e9-87b7-d1bd04de2cf9.png)
Here you go!
