### ISSUE TITLE
Checkbox broken if text is longer than one line

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#489]
## Expected Behavior

The green marker which appears inside a checkbox in the CfP form is located inside the checkbox if it is checked.

## Current Behavior

The marker appears outside.

## Steps to Reproduce

The question has to be longer than one line. See the following image:

![signup-broken](https://user-images.githubusercontent.com/3611273/44911409-07bda900-ad27-11e8-9cb2-9609dbc90f1c.png)

If the question is only one line long, the marker is located at the right location:

![signup-not-broken](https://user-images.githubusercontent.com/3611273/44911402-02605e80-ad27-11e8-9528-d9875c6e0da4.png)

## Your Environment

* Firefox 61.0.2, Arch Linux
* pretalx.com, used by FOSSGIS e.V.

**Comment by luto** [comment]
![image](https://user-images.githubusercontent.com/2158203/45368565-328be500-b5e4-11e8-97c4-c8c5d64905ed.png)

aand the fix broke something. Since the new breaking checkbox is in the orga backend, which has fewer users than the frontend, I am going to keep it in place for now..
