### ISSUE TITLE
Support HTTP Etags for frabxml/ical/... exports

### ISSUE THREAD

**Issue by johnjohndoe** [pretalx/pretalx#492]
## Problem you are facing
Client applications which retrieve the schedule data from an Pretalx instance do need to load the file everytime. This increases the traffic for both the server and the client.

## Possible Solution
The Pretalx API should be able to provide and consume [HTTP ETags](https://en.wikipedia.org/wiki/HTTP_ETag).

## Context
I am maintaining the [EventFahrplan project](https://github.com/EventFahrplan/EventFahrplan) which consumes schedule data from the Pretalx API.
The current EventFahrplan implementation [compares the old and the new schedule](https://github.com/EventFahrplan/EventFahrplan/issues/15) to find out whether it has changed. This could be done by the server using ETags.

**Comment by rixx** [comment]
I'm assuming you mean the exports, not the API?

**Comment by johnjohndoe** [comment]
Nice. Thank you for the quick action.
Just to clarify: this is not yet live for MRMCD 2018, correct?

**Comment by rixx** [comment]
Yeah, that is correct. You can be sure the change will be included in all instances running the upcoming 0.8 release and above, soon.
