### ISSUE TITLE
Email of the speakers in the API

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#493]
## Problem you are facing

I want to send unique registrations tokens to each speaker individually

## Possible Solution

1. Use the web interface to mail each speaker one after the other, copy/paste the template, change the token (time consuming)
2. Get the name and the email address from pretalx with the API, generate & send all the emails at once (faster, but the emails aren't exported in the API)

**Comment by derchrisuk** [comment]
I implemented this for another project

https://github.com/derchrisuk/pretalx/commit/d3e2099e20490b518568b1e93fa95e47dc36f34f

I guess if you only want the email in the results, then the changes in src/pretalx/api/serializers/speaker.py should be enough

**Comment by rixx** [comment]
Well, the changes you made expose the speaker emails publicly, as far as I can tell – that's not a good idea at all, since the speakers haven't agreed to a public display of their email address.

**Comment by derchrisuk** [comment]
They should not, as the change is done in the SpeakerOrgaSerializer, which should only be accessible by Orga members

**Comment by rixx** [comment]
Right, then the only thing it's missing is a Pull-Request with documentation and tests.

**Comment by derchrisuk** [comment]
If I find the time I will have a look at it.
Would need to look into tests though, never written one before.
