### ISSUE TITLE
Speakers with >2 talks displayed with the same event multiple times in event

### ISSUE THREAD

**Issue by oe1rfc** [pretalx/pretalx#501]
## Expected Behavior
In the details view of an event the "Speakers" box should show all speakers with other talks held by them under "Other talks by this speaker:", even if the speaker has more than 2 talks.

## Current Behavior
Under "Other talks by this speaker:" instead of other events, the same event is displayed several times:
![pretalks other talks](https://user-images.githubusercontent.com/892336/45380969-4a736100-b604-11e8-8835-fd780ddff855.png)
This is the same for the live preview and the HTML export but seems to be only the case for speakers with more than 2 talks.

## Steps to Reproduce

* go to detail view of event with speaker with multiple talks

## Your Environment

* Version used: 0.7.1
* example talk/instance: https://fahrplan.privacyweek.at/pw18/talk/LPNLNK/

**Comment by rixx** [comment]
The same can be seen in the organiser backend speaker list.

**Comment by rixx** [comment]
Actually, this was a separate issue from the speaker list – thank you for reporting it!
