### ISSUE TITLE
Hide history from the speakers / submission view

### ISSUE THREAD

**Issue by barbieauglend** [pretalx/pretalx#502]
## Expected Behavior

The same without the history on the right side.

## Current Behavior

Speakers are able to see the status logs and submission changes. 

## Context

Speakers seeing the history and status change isn't a good idea, making the history visible for reviewers only or orga only would be a better approach.

**Comment by rixx** [comment]
Could you expand on that, please? Why shouldn't a speaker see changes to their own submissions?

**Comment by Rafiot** [comment]
It is an issue if the conference organizer mistakenly accept a talk, change their mind, and switch back the talk to "submitted" (without sending a mail out).

The whole review process should not be in the logs seen by the speaker.

**Comment by rixx** [comment]
We might consider showing only some state changes to the user, I guess, but figuring out which ones to show is tricky.

**Comment by rixx** [comment]
Unless there is some suggestion of how to approach this, I'll close this issue as stale.

**Comment by rixx** [comment]
Closed as stale. Happy to revisit if there are new ideas/arguments/contributions.
