### ISSUE TITLE
Links to Mastodon User Profiles in Talk descriptions are not becoming HTML <a>.

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#503]
## Expected Behavior
Since Links in a talk description are becoming actual HTML links with `<a>` Tags, I expect this to work for all links.

## Current Behavior
Example Talk: https://talks.mrmcd.net/2018/talk/BRP77N/
This link `Fediverse/Mastodon: https://chaos.social/@MacLemon` is not becoming a link. Probably due to the `@` in the link text.

## Steps to Reproduce

1. Edit Talk description
2. Add link to your Mastodon user profile
3. Save
4. Check the talk page.

## Context
This could also be an upstream issue in Django.

## Your Environment

* Version used: Unknown, whatever revision MRMCD.net ist running as of 2018-09-12 14:00
* Environment name and version (e.g. Chrome 39, python 3.5): Browser independent
* Operating System and version (desktop or mobile): macOS Desktop (irrelevant, is a server side issue)
* Link to your instance, if in production: Observed at https://talks.mrmcd.net/

**Comment by MacLemon** [comment]
Caveat lector: I haven't yet tried URL encoding the `@` to `%40`.

**Comment by luto** [comment]
The problem seems to be the `.social`, not the `@`:

```
>>> import bleach
>>> bleach.linkify('Fediverse/Mastodon: https://chaos.social/@bla')
'Fediverse/Mastodon: https://chaos.social/@bla'
>>> bleach.linkify('Fediverse/Mastodon: https://chaos.de/@bla')
'Fediverse/Mastodon: <a href="https://chaos.de/@bla" rel="nofollow">https://chaos.de/@bla</a>'
```

**Comment by luto** [comment]
ah, yes. The TLD list of the underlying library is a litte short: [`bleach/linkifier.py#L14`](https://github.com/mozilla/bleach/blob/master/bleach/linkifier.py#L14).

**Comment by rixx** [comment]
Not maintaining a list of TLDs is a choice by the bleach project. We could substitute or expand by our own domain list, but I'm not sure that this poses a development overhead I'd like to maintain.

**Comment by luto** [comment]
good thing someone else already maintains that list as a python module: https://pypi.org/project/publicsuffixlist/ :)

**Comment by rixx** [comment]
Good point, thank you!

In the meantime, @MacLemon could of course also use markdown syntax to generate working links: ``[https://chaos.social/@MacLemon](https://chaos.social/@MacLemon)```

**Comment by MacLemon** [comment]
I had already though about using Markdown to try that, but haven't found the time to do so, yet. :-)
