### ISSUE TITLE
All day events blow up the schedule view and make it hard to read.

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#507]
## Expected Behavior
All-day events should be shown as starting with the first event, or at a configurable time and end with the last event or with a daily ending time.

## Current Behavior
All-day events are shown in the schedule as starting at 00:00 and ending at 24:00 for all the days, which blows up the schedule view.

## Steps to Reproduce

1. Create all-day event, like an Art Exhibition that's available during all the conference
2. Have a look at the schedule.
3. Schedule is blown up.
4.

## Context
Makes the schedule hard to read and unnecessarily long.

## Your Environment

* Version used: 0.8.0
* Environment name and version (e.g. Chrome 39, python 3.5): Chromium 71, Python 3.6, Browser independent
* Operating System and version (desktop or mobile): macOS 10.12.6 (OS independent)
* Link to your instance, if in production: https://fahrplan.privacyweek.at/ (Have a look at the Art exhibition tracks)

Since the room availability is known to pretalx, it should be possible to limit the display of an all-day event to the room-availability where that art-exhibition is located in.

**Comment by rixx** [comment]
I'm happy about any suggestions of both how to catch talks that are too long (or should we restrict the problem to all-day events for now?), and what a better display method would be, apart from not stretching the talk further than the room availability goes.

**Comment by s-light** [comment]
good idea to combine efforts with fixing #579 ?

first idea that came to my mind was:
adding a `event time-frame` - so we have an start and end time for every day.
then it would also be easier to setup rooms: if you don't need special times just use `all day`

to be backwards compatible this `event time-frame` would be unset and handled as `all day` default?

**Comment by rixx** [comment]
> good idea to combine efforts with fixing #579 ?

No, this is entirely separate from #579.

> adding a `event open-time-frame` - so we have an start and end time for every day.

Adding day lengths/event availability is generally a good idea, but it wouldn't fix this issue either – if your day goes from 8am till 5pm, all day events will still look terrible.

**Comment by s-light** [comment]
ok - so its better if i add this idea as separate feature-request?

by the way: is there any special way to create a all-day submission? 
i did not find a option to create a `submission type` explicitly as `all day` (i can calculate how many minutes my day lasts - but if my rooms / event availablilty is different on different days that would not fit well...)

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx provides a public event schedule page. On this page, all-day events are displayed in a very unwieldy fashion as described above.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

You'll have to work with the `pretalx/agenda/templates/agenda/schedule.html` file on this one. Play around with long and short talks at the same time, and see if you can make the interface less bloated.

Note: Please try not to introduce additional database lookups for this. Run the tests in `tests/agenda/views/test_agenda_schedule.py` to make sure of this, they include the expected query counts.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rixx** [comment]
Note for pretalx users: With the addition of our second schedule display mode (the list view), this is now at least a little alleviated, as there is a way to display schedules with long events that doesn't look absurd.
