### ISSUE TITLE
cannot create organiser

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#508]
## Expected Behavior

As an admin, I'd like to create new organizers.

## Current Behavior

![image](https://user-images.githubusercontent.com/2158203/46036518-f4bfae00-c105-11e8-9ffd-c20d61007e72.png)

## Steps to Reproduce

1. go to `/orga/organiser/new`
2. enter data into all non-disabled fields
3. press save
4. receive "This field is required." for the short form, which is disabled

## Your Environment

* Version used: v0.8.0
* Environment name and version (e.g. Chrome 39, python 3.5): N/A
* Operating System and version (desktop or mobile): N/A
* Link to your instance, if in production: conference.c3w.at

**Comment by luto** [comment]
:tada: thanks for the merge!

@MacLemon FYI

**Comment by MacLemon** [comment]
Danke luto! 🍪
Danke rixx! 🍪
