### ISSUE TITLE
Redirection loop with Gunicorn

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#516]
## Expected Behavior

I can run a Pretalx dev instance with Gunicorn

## Current Behavior

If Gunicorn is started, Pretalx can't really be accessed. On Firefox the error is`The page isn’t redirecting properly` on Chromium it's `ERR_TOO_MANY_REDIRECTS`. The output from curl is

```console
$ curl -X GET 'http://127.0.0.1:8345/orga' --verbose
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8345 (#0)
> GET /orga HTTP/1.1
> Host: 127.0.0.1:8345
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: gunicorn/19.9.0
< Date: Sun, 21 Oct 2018 21:26:30 GMT
< Connection: close
< Content-Type: text/html; charset=utf-8
< Location: /orga/
< Content-Length: 0
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< 
* Closing connection 0
```
If I add `--location`, it also ends up in a redirection loop

## Steps to Reproduce

1. Setup the dec environment as described in the documention
2. Go into the virtualenv: `source .env/bin/activate`
3. Install gunicorn: `pip install gunicorn`
4. Start Gunicorn: `gunicorn pretalx.wsgi --log-level=debug --bind=0.0.0.0:8345`
5. Go to `http://127.0.0.1:8345/orga`

## Context

I ran into this issue when I tried to deploy an instance on Uberspace. I had the same problem when trying it in Docker.

## Your Environment

I'm on Debian and tried it also on Centos6 (on Uberspace).

I think I'm really doing something fundamentally wrong. I hope someone can help.

**Comment by rixx** [comment]
I'm sorry, but I can't reproduce this at all. (I know that several pretalx instances use gunicorn in production without issues). If pretalx was correctly installed, the `/orga/` URL would redirect to a login page, so something is pretty broken here. There are a couple of things you can try for debugging, e.g. running pretalx without gunicorn (`python -m pretalx runserver`) to find the issue.

**Comment by vmx** [comment]
Thanks a lot for mentioning `python -m pretalx runserver`, that one work for me. For now that should be good enough and is is indeed a good way to dig deeper why it doesn't work for me with Gunicorn.

**Comment by MaticSulc** [comment]
I have an identical issue. Have you managed to find the problem?
It runs fine with python, but gunicorn makes a redirect loop.

I am using Pretalx 2024.1.0 on Docker.
