### ISSUE TITLE
On a new install without any languages compiled, "Einstellungen" is shown

### ISSUE THREAD

**Issue by tabascoeye** [pretalx/pretalx#517]
## Expected Behavior
All menu items are english

## Current Behavior
the only translated item is "Einstellungen" (my OS is set to english as well!)

## Your Environment
* Version used: current master
* Environment name and version: Firefox and Chrome, python 3.6
* Operating System and version: macos high sierra

<img width="240" alt="screen shot 2018-10-26 at 19 23 35" src="https://user-images.githubusercontent.com/111893/47582720-7ef17100-d955-11e8-9fcf-029b36cd2761.png">

**Comment by rixx** [comment]
I could not reproduce the issue and I can't imagine how this could occur except due to weird caching, as the string "Einstellungen" only occurs within the translation file.
