### ISSUE TITLE
It should be able to limit questions to one type of talks only

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#523]
## Problem you are facing

I would like to ask all speakers of one of our four types of talks at FOSSGIS 2019 to release their content under CC-BY. But I don't want to ask those how submit a workshop because their material will not be published.

## Possible Solution

The admin of a conference should be able to select which types of talks a questions should apply to.

**Comment by rixx** [comment]
"type of talk" is a pretty wide area. We could restrict by tracks (which not all events use) or submission types, or both.

**Comment by Nakaner** [comment]
The limitation to one or many submission types is implemented in the linked pull request which you are free to modify.

**Comment by rixx** [comment]
Since tracks work differently, a couple of additional considerations would have to take place. That's why I opened up the question of which restriction should be implemented. Your PR is of course noted and will be merged in time, as long as we don't determine that questions should be restricted by track only.

**Comment by rixx** [comment]
I think there is sufficient interest to warrant re-opening the issue.

**Comment by Nakaner** [comment]
> The limitation to one or many submission types is implemented in the linked pull request which you are free to modify.

I do not know why I did not link the pull request back then but that's the link: https://github.com/pretalx/pretalx/pull/582 (I don't know how easy it can be merged nowadays because I have not followed Pretalx development for the last few months in detail)

**Comment by rixx** [comment]
Yeah, I'll look into it – I changed a bunch of core CfP code recently which will probably require a couple of changes. Thank you!

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx provides a [Question](https://docs.pretalx.org/en/latest/developer/interfaces/models.html#questions-and-answers) model to get arbitrary information from speakers or reviewers.

pretalx also divides submissions by type, and (optionally) track. It would be useful to allow questions to be limited by certain submission types, just like they can already be limited to certain tracks.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

The Question model is in `pretalx/submission/models/question.py`, and the `submission_types` field should follow the `tracks` field pretty much exactly. Add it to `pretalx.orga.forms.cfp.QuestionForm`, too. Create a migration with the `makemigrations` command, and apply the migration with the `migrate` command.

Then have a look at the way the `track` restriction is implemented in `pretalx.submission.forms.question`, and do the same for the new submission type restriction. This is the form used to display all answer inputs for a given submission.

Please also have a look at the `pretalx.event.models.event.Event` model, and its `copy_data_from` field – it already copies questions and their tracks, and should now do the same for submission types.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rahmonov** [comment]
Hey @rixx. Can I take this one?

**Comment by rixx** [comment]
For sure!
