### ISSUE TITLE
review settings 'force data entry' unclear

### ISSUE THREAD

**Issue by knarrff** [pretalx/pretalx#524]
## Expected Behavior
In 'CfP / Content / Review settings' I see two checkboxes 'Force data entry' pretty close to the top of that section. There is no help displayed what these refer to. Due to experimentation, I think they belong to the score and text reviewers can/have to submit. I suggest to do two things: first, move those checkboxes closer to their respective other options (like the questions about the scores further down), and second, to label them more clearly. For example: 'Force score entry' and 'Force review text entry'.

## Current Behavior
See above.

## Steps to Reproduce
See above.

## Your Environment
pretalx v0.8.0
firefox 60.3.0esr
Debian testing (server instance)
Debian stable (client)

**Comment by rixx** [comment]
Ahh, this was introduced when the table for required/requested CfP entries was added. Thank you for reporting it!
