### ISSUE TITLE
Inviting a person who has an account to a team leads to invalid URLs in invitation email

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#528]
@rixx It's the bug I described you this morning but I have got new information since then.

## Expected Behavior

If I invite someone to a team who has an account alreday, he/she should get an email telling that new permissions have been granted.

## Current Behavior

The person gets an email with a link to `https://pretalx.com/orga/invitation/TOKEN` but calling this URL returns status code 404.

## Steps to Reproduce

1. Go to https://pretalx.com/orga/organiser/EVENT/teams/ID and add an email address of someone who has an account (as speaker) already.
2. The person gets an email with an invitation link.
3. He/she calls the URL and gets a status code 404.

## Your Environment

This bug can be reproduced at pretalx.com

**Comment by rixx** [comment]
The 404 issue should have been fixed. I'm in favor of not just adding people directly to a team if their email is known, because they might not want their accounts to be the same – the email address could be a collective one, for example.
