### ISSUE TITLE
Download reviews via API

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#530]
## Problem you are facing

I would like to download all submissions together with all reviews using the API.

## Possible Solution

The `/submissions` call should be extended by a query parameter `with_reviews={boolean}` which adds a field `reviews` which is a list of objects with the following properties:

* `name` (str): name of the reviewer
* `comment` (str): review comment
* `points` (number): number of points

Access should be limited to administrators of an event. If an non-admin adds `with_reviews=true` to the query string, he/she should get an error explaining that he/she is not allowed to see the reviews.

## Context

I want to print out small cards (A6 format using LaTeX) for the meeting of our programme selection committee. The cards should show the name of the speaker, the title and the number of reviews and the average number of points.

I am aware that admins can see all reviews if they are included in the API response even if they have submitted talks themselves. However, admins who don't act responsible are no good admins. :-)

**Comment by rixx** [comment]
That sounds like a further expansion of the submission object, which is growing quite a bit already, slowing down API responses. I'd say a `/reviews/` endpoint which can filter for submission would be more appropriate by far.
