### ISSUE TITLE
Documentation: Wrong directory in example config

### ISSUE THREAD

**Issue by gedsic** [pretalx/pretalx#535]
Step 5 of the installation manual instructs the reader to create a media directory:

`mkdir -p /var/pretalx/data/media`

This is also referenced in the nginx example config:

```
location /media/ {
        alias /var/pretalx/data/media/;
        expires 7d;
        access_log off;
    }
```

The example config for pretalx, to be put in `/etc/pretalx/pretalx.cfg`, however, uses another media directory:

```
[filesystem]
data = /var/pretalx/data
media = /var/pretalx/media
logs = /var/pretalx/data/logs
```

After setup, this leads to missing images and css files, as well as mails not being sent out.

**Comment by rixx** [comment]
Hmm, yes, I see your point. I'm a bit unhappy that the config file example seems to suggest that you *need* those paths there, because pretalx does have sensible defaults on directory locations, but you're right: the docs should be consistent.
