### ISSUE TITLE
Add weekday to /EVENT/schedule/v/VERSION/

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#537]
## Problem you are facing

Organisers of some conferences think in weekdays not calender days or offsets from the beginning. Therefore having weekdays in /EVENT/schedule/v/VERSION/ would help to orient oneself in a long and full schedule.

## Possible Solution

The format is defined in [agenda/templates/agenda/schedule.html](https://github.com/pretalx/pretalx/blob/master/src/pretalx/agenda/templates/agenda/schedule.html#L73). [`DATE_FORMAT`](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-DATE_FORMAT) provided by Django is used currently. However, it is not as simple as using `D d M Y` would not solve the issue good because all locales would be bound to one fix order of day, month and year. (Or do I understand something wrong?) That's why I did not submit a pull request.

**Comment by rixx** [comment]
You wouldn't need to change the global format, you can just change the one format by substituting something else in place of ``DATE_FORMAT``, which I think is a good idea.
