### ISSUE TITLE
Redirect after initial wizard doesn't use resolve

### ISSUE THREAD

**Issue by benjaoming** [pretalx/pretalx#540]
## Expected Behavior

If I include `pretalx.urls` in another Django project's URLs, the initial wizard will assume `/` after completing the wizard.

## Current Behavior

![image](https://user-images.githubusercontent.com/374612/49346389-f079b900-f691-11e8-887a-6479f948b34d.png)

## Steps to Reproduce

1. I think you can just try temporarily hacking `pretalx.urls` to include everything in non-root

## Context

DCEU2019

## Your Environment

https://github.com/djangocon/2019.djangocon.eu/pull/2

**Comment by benjaoming** [comment]
Oh it seems to be the same behavior for the main menu. I can reproduce my simply changing for instance `orga/` to `pretalx/orga/` in `pretalx.urls`.

![image](https://user-images.githubusercontent.com/374612/49346535-63842f00-f694-11e8-8969-a4c00f61dbb5.png)

**Comment by rixx** [comment]
Pretalx generally presumes / – it's not designed to run under a subpath at all.
