### ISSUE TITLE
Speaker Information Notes are instance global and not per conference

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#544]
## Expected Behavior
When adding “Speajer Information Notes” I'd expect them to be per-conference, as they likely will heavily depend on the conference itself and not make a lot of sense, if any, for a different conference.

## Current Behavior
Speaker information notes created within one conference show up on all conferences on the pretalx instance.

## Steps to Reproduce

1. Create *two* conferences.
2. Go to `/orga/event/slug/info` for the first conference and add a speaker note. Klick [Save].
3. Navigate to the other conference and check the existing speaker notes.

## Context
We're organising mulitple conferences and some infos we give the speakers for one conference absolutely do not make sense for speakers of the other conference. (Due to the different nature of the event and the different locations.)

As an organiser I would have expected Speaker Info notes to be per-conference, like the speaker-questions are per-conference.

## Your Environment

* Version used: 0.8.0
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome 72, Python 3.6
* Operating System and version (desktop or mobile): macOS, Desktop
* Link to your instance, if in production: https://conference.c3w.at/

**Comment by rixx** [comment]
This is a bug that thankfully only concerned the organiser backend: speakers only were shown bits of information created for their event, and organisers could only edit information bits for their own events, too, but they could see the titles (though not contents, so attachments were safe) for all events on a pretalx instance.
