### ISSUE TITLE
A "scaling" schedule that avoids overlaps of short talks

### ISSUE THREAD

**Issue by gedsic** [pretalx/pretalx#550]
## Problem you are facing
Talks with a short duration overlap each other visually in the schedule:

![screenshot from 2018-12-10 14-57-51](https://user-images.githubusercontent.com/592984/49737154-62eb2a00-fc8c-11e8-983f-b929c1d68631.png)

## Possible Solution
Maybe scale the talk height according to the total event length and number of talks?

## Context
Managing a lightning talk session, hence each talk is only 5 minutes long in a 2 hour session.

**Comment by gedsic** [comment]
I changed the timedelta to 20 minutes and tripled the talk and date heights in the schedule view and it looks good now. I guess in a special case like this you can't do without some manual work :)

**Comment by rixx** [comment]
It's pretty hard to find a way to work around this, yes. For events with only short talks or only long talks, the matter is simple, but what are we to do with events that have both? Your factor of 20 minutes would result in very long schedules for those events. :\
