### ISSUE TITLE
Consolidate login templates

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#551]
## Expected Behavior

As one of Django's design principles is DRY, it would make sense to have only a single login template.

## Current Behavior

There are currently four places that provide a login form. The current templates are:

 - [cfp/templates/cfp/event/login.html](https://github.com/pretalx/pretalx/blob/a28b49397cec7981bd130cd51aaa165343ee167a/src/pretalx/cfp/templates/cfp/event/login.html)
 - [cfp/templates/cfp/event/submission_user.html](https://github.com/pretalx/pretalx/blob/a28b49397cec7981bd130cd51aaa165343ee167a/src/pretalx/cfp/templates/cfp/event/submission_user.html)
 - [orga/templates/orga/invitation.html](https://github.com/pretalx/pretalx/blob/a28b49397cec7981bd130cd51aaa165343ee167a/src/pretalx/orga/templates/orga/invitation.html)
 - [orga/templates/orga/auth/login.html](https://github.com/pretalx/pretalx/blob/a28b49397cec7981bd130cd51aaa165343ee167a/src/pretalx/orga/templates/orga/auth/login.html)

## Steps to Reproduce

Look at the source :)

## Context

Having a single template would adding other authentication mechanisms easier.

## Your Environment

* Version used: 6b82f13a56d7020a109fb92453ead1c8946d4119

**Comment by rixx** [comment]
We now have a single template and a single form (and a re-used view in may places) for the login workflow!
