### ISSUE TITLE
Very long help text not possible

### ISSUE THREAD

**Issue by benjaoming** [pretalx/pretalx#552]
## Expected Behavior

 * Help text  cannot be this long:

   > If you get accepted, you will get a free ticket. You will also be asked all usual participant questions, like dietary needs or accessibility needs. However, if there is anything else, you would like to indicate, please feel free. Please also indicate if you need someone from the committee to reach out to you.

 * It is rejected without an error message

## Current Behavior

![image](https://user-images.githubusercontent.com/374612/50057659-c7672700-016d-11e9-8fc1-3f394510238c.png)

## Steps to Reproduce

1. Enter the above help text

## Context

Superbusy, tried to find another issue about this but couldn't -- sorry if I missed something :)

## Your Environment

0.8.0

**Comment by rixx** [comment]
I think this was due to me being nice about MySQL text field length or something.

**Comment by benjaoming** [comment]
@rixx the other issue would be that error message isn't showing.

Btw... this issue is super-minor, I am really impressed about how well PreTalx has worked :100:
