### ISSUE TITLE
Sign-up process for invited speakers

### ISSUE THREAD

**Issue by robbi5** [pretalx/pretalx#554]
## Problem you are facing
I've manually created most of the submissions in the orga area. (Happened because we've got submissions before we had a pretalx running)
This caused the creation of lots of "You have been added to a submission"-emails that contain password reset links for the speakers. 
Unfortunately, the timespan between the submission creation and the sending of the emails was larger than 24h, so all the password reset links in the emails were already broken. 
I've not yet found a way to recreate those emails with fresh reset links.

## Possible Solution
* Special invitation link for new accounts that isn't based on the password reset feature?
* Special link that allows one-time-password-change but without time limit?
* Feature to recreate invitation emails with fresh reset links?
* ...?

**Comment by rixx** [comment]
The reset links should also be sent out when you use the password reset form for that user, only not with the invite message. But yeah, a separate invitation feature would be good to have!

**Comment by rixx** [comment]
Merging into #1302 (I know this one is the original issue, but I already started writing up the next steps over there, so might as well).
