### ISSUE TITLE
Export Speaker-List as CSV

### ISSUE THREAD

**Issue by MaZderMind** [pretalx/pretalx#559]
## Problem you are facing
I would like to export the Speaker-List for further use in different application, for example for printing badges (until #206 is done).

## Possible Solution
CSV-Export of all Fields of the Speaker (esp. Mail, Name, HasScceptedSubmissions)

**Comment by luto** [comment]
We needed an ad-hoc solution during the last privacy week and ended up with dumping from the DB directly m) Sounds like a useful feature to me.

**Comment by rixx** [comment]
I'm still not sure how to handle export needs. For most special export requirements I'd suggest a separate plugin, as exporter plugins are easy to write, but a CSV export for speakers sounds so basic that it seems worth to include anyways.

**Comment by rixx** [comment]
The problematic part here is to decide:

- What should be included? Any submitter can have multiple submissions, for example, and adding them to the csv would be cumbersome (What would you add? The code? The title?)
- Who should be included? All accepted speakers? Or only people who have confirmed their participation?

**Comment by luto** [comment]
nice, thank you! :tada: @MacLemon
