### ISSUE TITLE
New Field for Speaker: Organisation

### ISSUE THREAD

**Issue by MaZderMind** [pretalx/pretalx#560]
## Problem you are facing
When using Pretalx in a commercial environment, the combination of Name and Organisation is used to identify Speakers. In non-commercial environment the Organisation is not used that often but might still be of interest.

## Possible Solution
Add a Organisation-Field to the Speaker.

**Comment by rixx** [comment]
Wouldn't a speaker-specific question for their organisation be sufficient here? Otherwise we'll have yet another field that only some conferences want to show, so we'll add this setting, plus a setting for showing/disabling this field.

**Comment by Nakaner** [comment]
In a commercial environment you want to show the organisation a speaker belongs to next to the name of the speaker. Is that possible with an ordinary question?

**Comment by rixx** [comment]
As pretalx currently does not print speaker badges, this wouldn't make any difference.

**Comment by rixx** [comment]
That is a separate issue, tracking at #403.

**Comment by rixx** [comment]
Speaker questions can now be made public, but for now they are only shown on the speaker page, not as in your screenshot on the talk page.

**Comment by rixx** [comment]
I'd consider this issue closed by advent of publishable questions, if that's alright by you?
