### ISSUE TITLE
Questions workflow is broken

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#565]
## Expected Behavior

 1. You can always go "Back" while answering questions.
 2. Already filled out answer are stored

## Current Behavior

1. You can't click on "Back" if not all required questions are filled out 
2. If you went back and continue again to the questions, your already answered questions are empty

## Steps to Reproduce

1. Add a required question to your submission process.
2. Go live.
3. Start to submit a talk, fill out required fields on the "General" page page, click on "Continue".
4. You are now on the "Questions" page. Click on "Back". You will get a "Please fill out this field." error and can't go back (Bug 1).
5. Fill out that field and click on "Back".
6. You are now on the "General" page. Click on "Continue".
7. You are now on the "Questions" page, but the answer is empty and doesn't contain your original answer (Bug 2).

## Context

It's not such a nice experience if you can't go back and lose user input.

## Your Environment

* Version used: current HEAD: 115563433e82bcff20da80e85bf4864149fd0c9f
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox, Python 3.7.2
* Operating System and version (desktop or mobile): desktop

**Comment by Anne-Victoria** [comment]
I experienced exactly the same issues, but in the flow for creating an event as an organiser. I entered something on the first page, then clicked next, then remembered, I wanted to change something on page one and clicked on previous step. But then I got the error that I needed to fill out the required fields first. After doing so I was allowed to go to the previous step, but when I then returned to step two after doing my changes in step 1, everything I had already filled out in step 2 was gone.

If I should add more information on this or create a separate issue, please let me know.

**Comment by rixx** [comment]
Within the submission workflow, I'm not quite sure how to solve bug 1 (bug 2 is fairly easy to solve, I think). Either you want your current data to be saved when going back – then it has to be validated when clicking the button. Or you want to discard it, then it will be gone when returning.

**Comment by rixx** [comment]
"Fairly easy" was overstating it, but I've fixed the bug. Within the CfP workflow, you can use the progress bar on top to jump around without filling in additional fields (losing data), and if you use the back button, data will be validated and saved instead. I'm inclined to call this good enough for now.
