### ISSUE TITLE
(Internal) Custom Field - similar to questions

### ISSUE THREAD

**Issue by s-light** [pretalx/pretalx#569]
## Problem you are facing
i would like to add custom fields to the Talk
- some are internal purpose 
- some should later be visible in the talk details

## Possible Solution
i think this could be a extension to the question concept - 
with a new question option so that the question is not shown to the presenter but 
for example to the reviewer - or only available in the talk details for organizers to fill in.
and it should have an option if its internal only or if it should be visible in the public details.

## Context
this would help to add information like a connected booth number.
(and this in an structured way.)

**Comment by rixx** [comment]
> -some are internal purpose […] for example to the reviewer

pretalx already features reviewer questions, which might be what you are looking for.

> - soem should later be visible in the talk details.

Issue #403 is tracking the proposal of making questions available publicly.

Other than that, I'd be fine with adding a "notes by the organiser" field, but I'm not sure about the merit of extending the questions model to yet another group.

**Comment by s-light** [comment]
hm i think you are right and i can represent all use cases i had in mind with the two options you mentioned !
thanks for the pointers!
