### ISSUE TITLE
Option to delete speakers

### ISSUE THREAD

**Issue by benjaoming** [pretalx/pretalx#572]
## Problem you are facing

In order to keep count of how many individual speakers have submitted, one needs to know how many of them are test accounts.

## Possible Solution

As with the option to delete submissions, speakers could also be deleted. I realize it means to cascade the deletion to all submissions.. but that would be nice, too :)

## Context

Depending on the size of the conference and the actual needs, a handful of test accounts can create a bit of uncertainty about the actual figures. It's not the biggest problem in the world.

Another issue would be if a speaker really has to be deleted, i.e. you don't want them in the system because of spam/sabotage/errors.

**Comment by rixx** [comment]
Yes, speakers who only have submissions that are set to "deleted" should not show up in the speaker list.

**Comment by benjaoming** [comment]
Awesome! Thanks :heart:
