### ISSUE TITLE
Move Review settings to a separate page

### ISSUE THREAD

**Issue by benjaoming** [pretalx/pretalx#575]
## Problem you are facing

 * Setting up the review process often doesn't happen until after publishing the CfP.
 * Because this form is very long and uses anchors, the status text from saving the form isn't seen when saving
 * Furthermore, I lost my changes a couple of times, presumably because the error messages aren't seen
 * Clicking "Settings" in the Review section takes one to the CfP section which is a bit confusing

## Possible Solution

Create a separate Review settings page.

## Context

In the review process of DjangoCon Europe, have very limited time to setup stuff and understand it :)

**Comment by rixx** [comment]
Closed in cd1b3376
