### ISSUE TITLE
Changing review settings has to be done twice

### ISSUE THREAD

**Issue by benjaoming** [pretalx/pretalx#576]
## Expected Behavior

Clicking "Save" would make new options for describing review scores appear.

## Current Behavior

Instead, nothing happens and the old settings appear again. One has to enter the range twice before it shows up.

## Steps to Reproduce

1. Go to Review => Settings
2. Enter a different score, i.e. Minimum: 0, Maximum: 2
3. Press Save
4. See that nothing has happened
5. Repeat Minimum: 0, Maximum: 2
6. Press Save
7. Now it works

This was reproducible.

## Context

In the review process of DjangoCon Europe, have very limited time to setup stuff and understand it :)

## Your Environment

 * 0.9.0
 * Self-contained Django project

**Comment by benjaoming** [comment]
I'm sensing that maybe the form fields or some formsets are generated not when rendering the view but during module load time?

**Comment by benjaoming** [comment]
Ah, this is a general issue with all the review settings. No matter what I change, I have to do it twice in order to see it show up in the form.

**Comment by rixx** [comment]
That's … very weird, and I cannot reproduce it on my end at all (and tests don't mirror this behaviour either). The review settings have been moved to their own page, now, though, so that might help?

**Comment by benjaoming** [comment]
Thanks for looking at this! I'll definitely notice if it's still an issue and come back to this! I might only have capacity to try using final releases though, being sensitive to the production environment :)

**Comment by rixx** [comment]
I expect a release will be done by the end of the month – we already have some bug fixes and a big feature (anonymous reviews) done, and are just waiting for one or two more, plus a big PR.

**Comment by benjaoming** [comment]
Thanks, that's awesome news @rixx :heart:
