### ISSUE TITLE
Move questions to first page or to speaker page

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#578]
Currently, we have a separate questions page in our submission worfklow. That's a bit silly, as we want questions to be integrated as well as we possibly can. Moving speaker questions to the speaker profile page and submission questions to the first page seems like a good idea.

**Comment by Nakaner** [comment]
This goal is partially in conflict with https://github.com/pretalx/pretalx/pull/582 where I allow questions to apply for some submission types only. Your idea requires either custom frontend JavaScript to hide the boxes or to show questions which don't apply for the talk to be submitted.

**Comment by rixx** [comment]
You are right. I'm generally against relying on JavaScript, so we should keep a separate questions page. We might consider moving speaker questions to the speaker profile page, but at that point it might not be worth the effort.
