### ISSUE TITLE
login e-mail address is case sensitive

### ISSUE THREAD

**Issue by s-light** [pretalx/pretalx#583]
## Expected Behavior
if i register with `TestUser@example.com`
i should be able to login with `TestUser@example.com`

## Current Behavior
if i register with `TestUser@example.com`
i can only login with `testuser@example.com`
otherwise i get the error message:

> No user account matches the entered credentials. Are you sure that you typed your password correctly? 

## Steps to Reproduce

1. register account with `TestUser@example.com` as email
2. logout
3. try to login with `TestUser@example.com`
4. see error message

## Context
seems the mail is internally stored as lower-case version (makes sens as mail addresses are not case-sensitive) - but than the login-form should also convert the input to lower-case.

## Your Environment

* Version used:  v0.9.0-59-g7bf2550a (current master / forked)
* Environment name and version: Firefox 64.0 (64-bit)
* Operating System and version: Kubuntu 18.10 64-bit

**Comment by rixx** [comment]
Technically our behaviour is incorrect as email addresses *are* potentially case sensitive. We just ignore this in favour of simplifying our world. Thanks for the report, logging in is now case-insensitive, too!

**Comment by s-light** [comment]
wow this was quick!

i did not know that there is a potentially case-sensitivity for mail addresses! 
just did a quick search - as one comment for this i found
https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive#comment29820108_9808332

> 'In short, you are safe to treat email addresses as case-insensitive.' I'd phrase it stronger: "you're unsafe to treat email-addresses as case-sensitive manner" Especially when checking for duplicates in user-databases, etc. – Geert-Jan Nov 16 '13 at 23:00
