### ISSUE TITLE
Requiring availability during submission prevents submissions due to deadlock.

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#594]
## Current Behavior
CfP Settings are configured to require availability, like in this screenshot.

![screen_shot_2019-02-14_at_14_38_10](https://user-images.githubusercontent.com/90635/52790631-522daa80-3067-11e9-8dda-c9d2dc20384a.png)

When a user wants to enter CfP with a submission, they're asked to fill in multiple forms. On the profile step, they're not asked to fill in their availability during the conference. The form validation enforces the filling of a non-displayed, and for the user non-existing field. 
This results in a dead-lock situation since the submitter cannot advance past this step.

## Expected Behavior
Display all required fields to the submitter so they can advance and complete their submission.
Alternatively, postpone the requirement for availability for the confirmation step, so they can only confirm their their talk when they also fill in the required availability.

## Steps to Reproduce

1. Configure CfP to require Availability
2. Start a submission, advance until the speaker's profile step
3. Hit a deadlock since pretalx is complaining about “This field must be filled out” where there is no marked field to give a hint *which* field is required. This is because the required availability field isn't displayed at all.
4.

## Context

A friendly speaker contacted us that they have a problem finishing their submission.

![wbvuixcvaeubacjntkacwgej-2](https://user-images.githubusercontent.com/90635/52791018-3f67a580-3068-11e9-9101-81657e5911de.png)

Current workaround: Remove the requirement for availability during submission. (Confirmed working, by said speaker.)

## Your Environment

* Version used: pretalx 0.9.0
* Environment name and version (e.g. Chrome 39, python 3.5): Browser independent
* Operating System and version (desktop or mobile): Speaker's Desktop OS is some Linux.
* Link to your instance, if in production: https://cfp.privacyweek.at/

**Comment by rixx** [comment]
Thank you for the report! Definitely a bug, and once it's closed, it might make a fine reason to release `v0.10.0`.
