### ISSUE TITLE
Info message on login screen

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#596]
I'm not sure if it's a bug or intended behaviour.

## Current Behavior

The error message on the login page appears left to the login, I think it should be above. I've made a screenshot.

![image](https://user-images.githubusercontent.com/42839/53300225-a1809180-3844-11e9-8a30-0952f6699589.png)

## Expected Behavior

I would expect the message to appear above the login form. 

## Steps to Reproduce

1. Create a new event
2. Go to `/<event>/login`
3. Create a new account with a too short passwort

## Context

I'd consider it an UX problem.

## Your Environment

* Version used: current HEAD (64608a8521d8945f8fad1ed0958271ad6cf040be)
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox
* Operating System and version (desktop or mobile): Linux

**Comment by rixx** [comment]
Thanks for reporting this! Seems it was introduced when we merged all our authentication templates.
