### ISSUE TITLE
Users can always edit their submission

### ISSUE THREAD

**Issue by meisterluk** [pretalx/pretalx#598]
## Problem you are facing

* The default accept-review-confirm model makes sense to me.
* But I still prefer the possibility of organizers to allow modifications to your submissions at any time.
* Why? Because I value quality of the submissions higher than organizer's control over user's submissions. If there is some sudden modification in the submission, this is little problem to me. If there are factual errors and submitters cannot edit them, this is a larger problem to me.

## Possible Solutions

* CfP, Content, Review settings: Introduce toggle button "Allow submitters to always modify their submission"
* CfP, Content, Review settings: Introduce settings class "Allow submitters to always modify the following submission data:" (checkboxes)

  * Title
  * Submission Type
  * Abstract
  * Description
  * Speakers
  * Notes for the organizer
  * Language

## Context

I think this model makes the review system even more flexible. I want to point out that in the long run some "submission modifications history" would be of interest, but this would require major changes to the database layout and software architecture. Thus, I want to limit this issue to the possibility to modifications at any time.

**Comment by rixx** [comment]
"Allow submitters to modify their submission even between CfP close and acceptance" could be a good option to introduce, agreed. (That is the only time when submitters can't edit their submission: they are frozen for review, and upon acceptance become editable again.)

I think introducing settings per field would be overkill – I'm hesitant to make pretalx settings even more stuffed than they are already.

Regarding the modifications history: We *do* want something like that, and it won't take the amount of changes you suggest. We're pretty close to that point already, it's just never been a priority so it keeps getting pushed back.

**Comment by meisterluk** [comment]
> I think introducing settings per field would be overkill – I'm hesitant to make pretalx settings even more stuffed than they are already.

I understand.

> Regarding the modifications history: We _do_ want something like that, and it won't take the amount of changes you suggest. We're pretty close to that point already, it's just never been a priority so it keeps getting pushed back.

Oh, really? Cool!

I think you have a good grasp on whether this feature is useful or not. I can live without it. I prefer to have it. Thanks for your work!

**Comment by rixx** [comment]
This can now be configured per review phase.
