### ISSUE TITLE
Allow organisers to provide example proposal

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#599]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

Public example submissions would be a great way to encourage organisers to clarify their expectations and priorities, making the submission process much easier, and raising the qualities of submissions received.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

This issue consists of two parts: First, the organisers will need to provide a sample submissions. They should need to fill all fields submitters have to fill, including questions. We could either store this data in a submission that we have to exclude (e.g. a deleted submission), and we'll store the reference to the submission in a separate ForeignKey or setting. Alternatively, the content could also be dumped into JSON and stored like that in the `event.settings`. In any case, all active event languages should be offered on all fields. In addition, there should be a possibility for organisers to annotate each fields with helpful hints ("remember not to write too much", or "please do not put personal information here").

In the second part, this information should be shown to users. As a first step, there should be a separate page where users can look at the example submission and its hints, which should be linked when starting the submission process. If we want to get fancy, though, we could also find a good way to include this information while users go through the submission workflow – although we'll have to take care not to be intrusive.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by garciadias** [comment]
I would like to try this one.

**Comment by rixx** [comment]
This can be done fairly well with the read-only sharing link for proposals.
