### ISSUE TITLE
Show more information on hover

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#601]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx shows a public schedule for events, where talks and speakers can be reached by following links. 
Following links is often an extra step people don't want to take. Showing additional information regarding talks/speakers when hovering on the relevant links would be good, helpful behaviour.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

Look at `pretalx/agenda/templates/agenda/schedule.html` and see what kind of additional information makes sense to you. Don't forget to test it as a mobile view, though!

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by s-light** [comment]
for mobile and a huge talk-list 'on-demand' would be better for page-size.

in my hacky embeddable list-view i did a pre-renderd version with the `details` html tag.
(so no javascript required to open close the details)
https://gitlab.com/s-light/pretalx/blob/more_embedding/src/pretalx/agenda/templates/agenda/schedule_list_days_inline.html#L13
iam planing to recreate this `list-view` as a clean pull-request ontop of the current master..

**Comment by rixx** [comment]
Those two aren't mutually exclusive though – if browsing on a laptop, I'll appreciate every link I don't have to click for minor added benefit, and if I'm on a mobile device, I don't have to worry about things I can't see.
