### ISSUE TITLE
Hide rooms from program

### ISSUE THREAD

**Issue by flowolf** [pretalx/pretalx#603]
## Problem you are facing

We plan Infodesks in pretalx too. Those are schedules in foyers for several hours. We want to show where Infodesks are in the program, but not when (because they are there all the time)

## Possible Solution

hide flag for rooms, to not show up in the program schedule.

## Context

the same goes for some events.
some events are internal, they take up room too. they should not be in the program, but should be planned to take up a room for a certain time.

**Comment by rixx** [comment]
You can leave events you do not wish to publish as "accepted", so they won't be shown publicly.

Internal events is something we'd like to have, but we're not sure yet how to implement them with a clean UI. The tracking issue is #242, so I'm closing this as a duplicate.
