### ISSUE TITLE
Time format not including "0" on dashboard

### ISSUE THREAD

**Issue by knarrff** [pretalx/pretalx#605]
## Current Behavior
I currently see there:

10:4h bis zum CfP-Ende

## Expected Behavior
I would expect to see

10:04h bis zum CfP-Ende

## Steps to Reproduce

1. Have a running CfP and a time including a leading 0.
2. Have a look at the dashboad
3.
4.

## Context

I wanted to know the remaining time of the CfP. It isn't a big problem, but it probably also doesn't take
a lot to fix.

## Your Environment

* Version used:
0.8
* Environment name and version (e.g. Chrome 39, python 3.5):
firefox, linux
* Operating System and version (desktop or mobile):
Debian stable
* Link to your instance, if in production:
https://derse19.uni-jena.de/orga/event/derse19/

**Comment by rixx** [comment]
This issue has been fixed in version 0.9.0 already.
