### ISSUE TITLE
Documentation about how to backup/restore

### ISSUE THREAD

**Issue by knarrff** [pretalx/pretalx#606]
## Problem you are facing
I would like to backup the current state, and am not sure how to find all 'state' of pretalx, nor how I would go about restoring from it.

## Possible Solution
Document this some place.

## Context

The current documentation states in multiple places that backups are a good idea (and they obviously are), e.g.:

"you should have a backup of the state before the command run", e.g.:
https://docs.pretalx.org/en/latest/administrator/commands.html

"While we try hard not to issue breaking updates, please perform a backup before every upgrade."
https://docs.pretalx.org/en/latest/administrator/installation.html

What I couldn't find is a description of how to do this, except maybe to backup the whole machine. I am a beginning pretalx user, not a developer. So while I installed pretalx and because of that know it uses a DB as backend, I do not know if a backup of the database would be sufficient, or if there is 'state' saved elsewhere as well, and where that all would be, and how to best backup that.

So, I think it would be a good idea to describe how to actually backup the data within a pretalx installation, and in the same document also, how to restore from such a backup.

**Comment by rixx** [comment]
I'm not going to document the **how**, as this is dependent on the database, OS, isolation, filesystem, etc. But I'll add a note in the docs about the **what** to include.
