### ISSUE TITLE
Localise quotation marks used throughout 

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#610]
## Problem you are facing

As a native English speaker, I'm not used to seeing Double Angle Bracket Quotation Marks (`»` and `«`) in text. If text is to be quoted, it's normally Double Quotes (`"`) (or sometimes Single Quotes (`'`), depending on the context)

## Possible Solution

Add a translation widget that allows the specification of start and end quotation marks (English: `"`, `"`; French: `»`, `«`; German: `„`, `“`) (at a guess, based on [Wikipedia](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table))

## Context

This issue is only very minor in an extremely well rounded and robust system, but as a native English speaker, it's glaringly obvious to see these marks out of context. It's not a blocking issue, just a possible feature to help smooth the experience between the major languages this application supports.

**Comment by rixx** [comment]
```
$ git diff | wc -l
791
```
:fearful:
