### ISSUE TITLE
Expose more review statistics

### ISSUE THREAD

**Issue by knarrff** [pretalx/pretalx#612]
## Current Behavior
For our current call, we have 127 submissions. None of these has reviews yet. In the review panel
https://derse19.uni-jena.de/orga/event/derse19/reviews
I do see the number 127 also on the bottom (Seite 1 von 6 (127 Elemente)).

However, on the top it says: "Reviewen Hier geht es lang, um mehr Reviews zu verfassen, es fehlen noch 126!"
Or in English: There are still 126 reviews pending.

## Expected Behavior
Since there are 127 submissions and none of them have a review yet, I would expect 127 reviews to be pending, not 126.

## Steps to Reproduce

probably (not going to mess with the installed version now):
1. create a call
2. submit something
3. take a look at the review panel and note the counts
4.

## Context

This is likely not a big deal, but in the current state it is of course quite noticeable. Depending on how this is coded, it might be a problem if there is only one review left, but I cannot check that now.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

Debian stable (server + client (firefox))
https://derse19.uni-jena.de/orga/event/derse19/reviews

**Comment by knarrff** [comment]
I just had a thought that this might be due to a submission of mine, which I obviously should not review myself. If this is the case, then please change the text to something that indicates that. When in the review panel, I see this with my orga-hat on. Then I do want to know the current number of todo-reviews, including my own submissions, to see if everything has already been done - not just my own todo, but all of the contributions.

**Comment by rixx** [comment]
The review panel is meant to be for the reviewer, and it tells them how many reviews they themselves still have to perform. The information you're looking for is probably "how many reviews haven't been reviewed at all yet" or "how many reviews haven't been reviewed by all reviewers yet". I'm not sure where to expose this information at this point.

**Comment by knarrff** [comment]
I see, thanks for the clarification. Maybe this could be made explicit in the panel by using some different wording.

Concerning your other comment "how many reviews haven't been reviewed by all reviewers yet" I actually have a question that just came up today: usually not all reviewers have to review all contributions. Often, a certain minimum number of reviews is targeted for each contribution. Is there a possibility in pretalx to set such a number and then get an overview of how much has already been done ect?

**Comment by knarrff** [comment]
Vielleicht als Vorschlag im Deutschen: "Hier geht es lang, Du hast noch 126 offene Reviews."

**Comment by rixx** [comment]
The review statistics have been removed since.
