### ISSUE TITLE
Add cancelled to talk status

### ISSUE THREAD

**Issue by toto** [pretalx/pretalx#613]
## Problem you are facing

When building clients that deal with sessions from pretalx (e.g. [the Congress iOS app](http://congress.bits.io) for 35C3) users would like to know if a talk was cancelled. To do this cancelling needs to be it's own status.

In addition to this adding a status that reflects the planning status of an issue for presenting it to the user. It might for example be useful to let users choose their favorite talks before they are scheduled with time and location since the favorite distribution might help the organizers perform the scheduling. 

## Possible Solution

Add a `status` property to all talks exposed via the API. The suggestion would be something like these states:

- `proposed` - CfP stage
- `accepted` - Post CfP
- `scheduled` - Has timeslot & room set
- `cancelled` - Was cancelled after beeing accepted. Instead of deleting a scheduled session it would be marked as cancelled. If could even be shown in the schedule marked as cancelled. 

Real deletion could of course still be done, but should be made explicitly as a last resort. 

## Context

Adding this would allow me to to add cancelling notifications to the app without relying on deletion as a trigger for this, which has proven unreliable in practice.

**Comment by rixx** [comment]
You mean, like the field `state` which can be any one of “submitted”, “accepted”, “rejected”, “confirmed”? Additionally, internally submissions can also be "cancelled" or "retracted" or "deleted". All states apart from "confirmed" will naturally only appear to authenticated users with appropriate permissions. Please refer to the [API documentation](https://docs.pretalx.org/en/latest/api/resources/talks.html) for further information.
