### ISSUE TITLE
Review Scoring ambiguous

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#616]
## Current Behavior
When a reviewer doesn't score any points for a given submission, the list of reviews shows a line of
“ø” which is ambiguous for reviewers and orga.

## Expected Behavior
If a reviewer hasn't given a score the symbol to represent “no score awarded”

## Steps to Reproduce

1. Have a conference
2. Have a submission
3. Review the submission but don't award any score
4. Check the reviews

## Context
The character used “ø” has the Unicode Name “ LATIN SMALL LETTER O WITH STROKE” (U+00F8) which has no inherent meaning for “none”.
With our review team the character was interpreted as the number zero (since some people strike our their zeroes to separate them from the letter oh.) Of course the reference wasn't zero points, but NULL points awarded.

This is a semantic issue. The character should be replaced by something else. Though I don't have a better idea than literally writing “none” there.

## Your Environment

* Version used: pretalx 0.9
* Environment name and version (e.g. Chrome 39, python 3.5): Browser independent
* Operating System and version (desktop or mobile): OS independent
* Link to your instance, if in production: https://conference.c3w.at

**Comment by rixx** [comment]
∅ is commonly used as a null sign in maths, but I agree that it's too ambiguous and out of context here. Other options I can think of:

- –
- ×

Even though we use a bin as symbol for removal everywhere, I'm against using a × in a circle, as this is too widely used as removal sign or error message indicator.

**Comment by MacLemon** [comment]
There's a difference between “∅” (math NULL) which you're referring to and “ø” (LATIN SMALL LETTER O WITH STROKE) which is currently used in pretalx. (Also there are øØ⊘⦰⦸⦵⦶𝝝𝝧𝞗𝞥ʘӨꙨ☉ꙪΘϴ which all look sufficiently ambiguous and people just don't notice the difference, let alone know of their meaning.)

I'd rather not use “-” because it's indicative of a negative value, or minus. It will likely be interpreted as a negative veto by someone.

Using × (Multiplication sign) does not have an inherent positive or negative connotation and I'd guess this is our best option at the moment. (Even though people will refer to this as “x” (the letter X) and when they have to type it, they'll use an x, because it's on their keyboard and it's close enough for most people to either not notice or not care.) Let's hope that most operating systems and browsers are capable of correctly displaying this character. :-)

I agree that Ⓧ or ⓧ will too easily be interpreted as either a tickmark, similar in meaning to what is used on ballots, or as a symbol that empties an input field.

**Comment by rixx** [comment]
I'll add it for now. Let me know if you come up with a better option, though!

**Comment by MacLemon** [comment]
I'll certainly let you know should we stumble about a better solution!
