### ISSUE TITLE
Assign submissions to people

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#619]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx allows all organisers access to all submissions, but there is no way to mark that somebody is the primary point of contact for any submission.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

You'll have to add a new relation between the [User](https://docs.pretalx.org/en/latest/developer/interfaces/models.html#users-and-profiles) model and the [Submission](https://docs.pretalx.org/en/latest/developer/interfaces/models.html#submissions) model.
The assignment of a submission to a person in one of the organiser teams would also contain that person's role. 

- Coordinators: Organisers might feel responsible for a set of submissions.
- Reviewers: Reviewers might receive a list of reviews they should definitely review / feel responsible for.

UI wise, submission lists should contain a filter by those roles, and the dashboard should also list how many submissions are assigned in which role for the user viewing it (e.g. "You are coordinator for 44 submissions", or "12 submissions are on your review list").

I'd say that all organisers should be able to assign coordinators and reviewers to submissions.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by ankitjavalkar** [comment]
Hello, I'd like to work on this issue.

**Comment by rixx** [comment]
Great! Let me know if you need any help.

**Comment by rixx** [comment]
@ankitjavalkar How's it going? Do you need any help, or do you have any questions?

**Comment by ankitjavalkar** [comment]
@rixx Thanks for checking in. I am making progress, albeit slowly. I'll drop a comment here in case I'm really stuck somewhere.

**Comment by ligi** [comment]
Hey @ankitjavalkar - did you get stuck somewhere? Is there a branch one could follow?

**Comment by rixx** [comment]
As of #1264, reviewers can now be assigned to proposals (and/or the other way around).
