### ISSUE TITLE
QRCode for exports

### ISSUE THREAD

**Issue by garfieldairlines** [pretalx/pretalx#62]
Hi there,

Just tried it on the MRMCD fahrplan and I found out that it misses a QRCode option for links for instance to export it on a android app.

Is it possible to add one ? Thank you.

**Comment by rixx** [comment]
Hmm, can you provide an example of what you are looking for? What would the QR codes link to? Which Android app are we talking about?

**Comment by garfieldairlines** [comment]
For instance with giggity I can enter the XML or JSON (I don't remember) URL ( like https://cfp.mrmcd.net/2017/schedule.json ) via QRCode and then I have the schedule synced on my phone.

**Comment by rixx** [comment]
I'd merge a PR that adds a QR code link to the drop down menu next to the JSON/XML link :)
