### ISSUE TITLE
Don't allow speakers to add other speakers once the CfP is over

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#620]
At that point, organisers should be informed about additional speakers, and can invite them themselves.

**Comment by vmx** [comment]
Invited speakers should still be able to accept the invitation after the CfP. That's important for last minute submissions.

**Comment by rixx** [comment]
We have no concept of open invitations, and I'm not sure adding it is worth it.

I'm go with "organisers have to add speakers after CfP closing", since knowing how many speakers will be present and who will come is relevant information that should be controllable by the organisers in the end. Last minute submissions will need to contact the organiser. Just knowing that "this talk will have three speakers and we know one of them" can be put in the notes to the organiser, but as somebody responsible for a conference, I'll want to know *who* those people are ahead of time.

**Comment by vmx** [comment]
Would this mean that if someone adds a speaker before the closing of the CfP, but the one who got invited doesn't accept the invitation before the CfP closes. That person won't be able to accept it after the CfP closed?

**Comment by rixx** [comment]
Yes, that is correct. Speakers who want to join a submission once it can't be edited any longer will have to talk to the organisers. Imagine a talk being submitted and reviewed under the premise of one speaker, and then it turns out that there will be three. It would complicate speaker checking, too – many events will check if their submitters had problems or were banned at previous conferences, so organisers definitely need to be aware of changes in speakers attending. Not to talk about booking a speakers' dinner, dealing with gifts and expenses, etc.

**Comment by vmx** [comment]
I agree that *adding* people later on would introduce those issues. But having someone invited would mean for me as an organiser "that person just hasn't created an account yet/clicked the link". I think this should be open at least until the review is done. Especially if you do blind review, you don't care about the speakers.

Once the talk is accepted I would think about speakers' dinner etc.

Organisers already have a lot to do. If there's more things that people can do themselves (like accepting an invitation) that sounds good to me.

**Comment by rixx** [comment]
Feel free to submit a MR to introduce this feature – adding invitations would conceptually be a good idea, but I won't have or make the time for it any time soon.

**Comment by vmx** [comment]
> We have no concept of open invitations, and I'm not sure adding it is worth it.

For me the link you get to invite someone as a speaker is an open invitation. I guess we are talking about different things then?

**Comment by rixx** [comment]
> For me the link you get to invite someone as a speaker is an open invitation. I guess we are talking about different things then?

Apparently we are. The link when inviting someone as a speaker is not personalized and can be handed out to any amount of people. I'd like to end this discussion here, as my decision for the point being stands: I'll pursue the easily doable feature, and I'll be happy to review and accept Merge Requests with more complex solutions. Sorry, but I have to prioritize issues in a project of this size.

**Comment by vmx** [comment]
> Sorry, but I have to prioritize issues in a project of this size.

Sure, you do a great job here (also on other issues). I just wanted to make sure I understand it correctly in case I want to implement it. If it turns out I do an I hit issues I'll come back to you.
