### ISSUE TITLE
Optionally add events for “Opening”, “Closing” and “Keynote” at event creation.

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#621]
## Problem you are facing
I assume that most conferences organized with pretalx follow a certain scheme which involves having a (probably short) introductory opening event, a longer keynote talk kicking off the event, and a closing event at the end of the conference.

Currently these events have to be created/submitted manually, though it's very likely they're required.

## Possible Solution
Upon creation of a new conference it would be great if these events could be instantly added as events to the submissions.

For example by adding a checkbox that asks to “Automatically add Opening, Closing and Keynote events” which, when ticked, will expand into a form field similar to the example given.

---
[x] Add an Opening event of 15 minutes at the beginning
[ ] Add a Keynote speech of 45 minutes after the Opening
[x] Add a Closing event of 30 minutes at the end

These events will take place in a room called <Main Event Hall>.
---

As for Defaults: Opening and Closing should be ticked, Keynote should not be. The duration should be an edit field accepting minutes. For example with the given values as guesstimates.

Creating the conference would then automatically add these events, automatically accept them and maybe even put them on the schedule. This would also implicitly create a room to host these events which can be given a name with a textfield.

- Beginning of the Event
- Opening
- Keynote
- <Conference>
- Closing
- End of the event

## Context
As we create and organize more and more Events using pretalx we see this pattern emerging which may or may not apply to other conference organisers. It might make creating a conference even faster and comfortable.

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx provides a multi-step process to create new events. Adding suggestions like described above would make sense for many events.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

Look at `pretalx/orga/views/event.py`. The `EventWizard` view is responible for generating the multi-step form. Adding these submissions would probably be done in the last step(?).

UI-wise, I'd imagine suggesting default titles and text fields, but allowing them to be edited in place.
Remember to first create the event, then create the submissions, and then call `confirm()` on them, to ensure that the schedule [slot](https://docs.pretalx.org/en/latest/developer/interfaces/models.html#pretalx.schedule.models.slot.TalkSlot) objects are created correctly.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rixx** [comment]
Since we now have Breaks/background events, which are sometimes preferable for administrative events, I'll close this issue for now.
