### ISSUE TITLE
Allow Reviewers to send emails to submitters

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#622]
## Problem you are facing
Reviewers are not allowed to send emails to submitters to ask for further details, missing parts, clarifying requirements, etc.

## Possible Solution
Optionally allow members of the group reviewers to also obtain the email privilege so they can send emails to submitters.

## Context
This problem has come up during our recent “check reviews and accept submissions” sprint of an event. It's the first time we tried to use a dedicated reviewing team. This worked quite well, and working through the ambiguous submissions was surprisingly fast in the end.

One issue we were facing was that reviewers would happily contact submitters to ask them for more details on their submission, or specific requirements for their event. This is great because it spreads the workload among the team. Also some reviewers seem to personally care for a specific topic or submission and would like to help submitters improve their entry. This is also great because it improves submissions, shows that people really care for (potential) speakers, and generally reduces delays.

It would make things a lot easier for reviewers if an admin could simply add the “allow sending emails” to a submitter privilege. It likely makes sense to limit the allowed recipients to the submitters of an event. As opposed to larger groups like all submitters, a larger selection of them or similar.

We had to raise our reviewers to fully privileged orga people to allow them to do work they were really eager to do. Luckily this is not a problem with our team, these people are wonderful! Stricter role separation may come in handy for larger teams though, so that shouldn't be an afterthought.

**Comment by rixx** [comment]
This is a good point, but sadly not this simple. To keep up with our offered anonymisation of speakers, we'll need to implement message sending between reviewers and submitters via pretalx, to make sure that speaker names are anonymised if required. (Allowing reviewers access to email if they can see speaker names seems like confusing if another messaging capability is also present).

This feature has already been requested in #339, so I'm closing this as a duplicate.
