### ISSUE TITLE
Search does not seem to like Umlauts

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#623]
## Current Behavior
Searching for Strings containing an Umlaut causes a crash.

## Expected Behavior
Finding events matching the search term, even when it contains Umlauts.

## Steps to Reproduce

1. Have a conference with a submission which contains an Umlaut in the title, like „Anonymität“.
2. Go to the list of submissions, and use the search field to search for „Anonymität“ (without quotes)
3. 500

## Context
We could work around this by shortening the search term, but it's unexpected and may be inconvenient to easily find the exact submission one is searching for.

It seems that if the search term contains anything but printable ASCII characters search crashes.
Tested with: ä, ö, ü, ß, é, 🥚, 日本語
They all lead to a 500. This also means that pretalx' search is unusable for some other scripts like japanese kana.

## Your Environment

* Version used: 0.9
* Environment name and version (e.g. Chrome 39, python 3.5): Chromium 73.0.3637.0
* Operating System and version (desktop or mobile): Client macOS 10.13.6, Server FreeBSD 11.2
* Link to your instance, if in production: https://conference.c3w.at/

---

Full stacktrace can be provided and is readily available to @luto if needed.
Head part of the crash log:

```log
UnicodeEncodeError at /orga/event/eh19/submissions/
'ascii' codec can't encode character '\xe4' in position 8: ordinal not in range(128)

Request Method: GET
Request URL: http://conference.c3w.at/orga/event/eh19/submissions/?q=anonymit%C3%A4t
Django Version: 2.1.7
Python Executable: /usr/local/bin/python3.6
Python Version: 3.6.8
Python Path: ['/root', '/usr/home/pretalx/.local/bin', '/usr/home/pretalx/.local/lib/python3.6/site-packages', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/root']
Server time: Do, 7 Mär 2019 21:30:39 +0100
Installed Applications:
['django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'bakery',
'compressor',
'djangoformsetjs',
'jquery',
'rest_framework',
'rest_framework.authtoken',
'rules',
'pretalx.api',
'pretalx.common',
'pretalx.event',
'pretalx.mail',
'pretalx.person',
'pretalx.schedule',
'pretalx.submission',
'pretalx.agenda',
'pretalx.cfp',
'pretalx.orga',
'bootstrap4',
'django.forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
'whitenoise.middleware.WhiteNoiseMiddleware',
'django.middleware.common.CommonMiddleware',
'pretalx.common.middleware.SessionMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'pretalx.common.auth.AuthenticationTokenMiddleware',
'pretalx.common.middleware.MultiDomainMiddleware',
'pretalx.common.middleware.EventPermissionMiddleware',
'pretalx.common.middleware.CsrfViewMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'csp.middleware.CSPMiddleware']
```

**Comment by rixx** [comment]
I'd definitely appreciate a stack trace, @luto, as I can't reproduce the issue on neither my development environment nor on pretalx.com.

**Comment by luto** [comment]
https://github.com/pretalx/pretalx/blob/master/src/pretalx/common/mixins/views.py#L128 :)

**Comment by rixx** [comment]
Oh god, I'm terribly sorry. Fix is pushed.

**Comment by MacLemon** [comment]
There's never a need to be sorry for giving us pretalx!
Thank YOU for creating an environment that makes those filing issues feel welcome! Much appreciated!
