### ISSUE TITLE
Viewing schedule sometimes causes a crash

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#624]
## Current Behavior
Sorry, this is kinda vague, as I'm not entirely sure what's causing this or what exactly is happening.
Looks like a simple GET to the live schedule can cause a crash in a string conversion.

## Expected Behavior
No crashes. :-)

## Steps to Reproduce

1. Unknown, sorry

## Your Environment

* Version used: 0.9
* Environment name and version (e.g. Chrome 39, python 3.5): Unknown, most likey not a frontend issue
* Operating System and version (desktop or mobile): Unknown
* Link to your instance, if in production: https://cfp.privacyweek.at/

---
Full crash report available to @luto or @MacLemon if needed or helpful.

```log
Internal Server Error: /pw18/schedule/

TypeError at /pw18/schedule/
'<' not supported between instances of 'int' and 'LazyI18nString'

Request Method: GET
Request URL: http://cfp.privacyweek.at/pw18/schedule/
Django Version: 2.1.7
Python Executable: /usr/local/bin/python3.6
Python Version: 3.6.8
Python Path: ['/root', '/usr/home/pretalx/.local/bin', '/usr/home/pretalx/.local/lib/python3.6/site-packages', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/root']
Server time: Tue, 26 Feb 2019 21:46:18 +0100
Installed Applications:
['django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'bakery',
'compressor',
'djangoformsetjs',
'jquery',
'rest_framework',
'rest_framework.authtoken',
'rules',
'pretalx.api',
'pretalx.common',
'pretalx.event',
'pretalx.mail',
'pretalx.person',
'pretalx.schedule',
'pretalx.submission',
'pretalx.agenda',
'pretalx.cfp',
'pretalx.orga',
'bootstrap4',
'django.forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
'whitenoise.middleware.WhiteNoiseMiddleware',
'django.middleware.common.CommonMiddleware',
'pretalx.common.middleware.SessionMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'pretalx.common.auth.AuthenticationTokenMiddleware',
'pretalx.common.middleware.MultiDomainMiddleware',
'pretalx.common.middleware.EventPermissionMiddleware',
'pretalx.common.middleware.CsrfViewMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'csp.middleware.CSPMiddleware']
```

**Comment by rixx** [comment]
This bug is known and fixed on `master` – it's an issue related to room ordering. If you don't want to upgrade right now, applying this change should fix the issue: e7f9949f.

**Edit**: But that line will change your room ordering in a weird way. If you touch that line, please change it to this instead:

```
                d['rooms'].values(), key=lambda room: room['position'] if room['position'] is None else room['id']
```

**Comment by knarrff** [comment]
What do you suggest a working installation to do right now? We are affected by this bug (https://derse19.uni-jena.de), and we did install pretalx via pip. Upgrading to the last development version seems a bit risky in a production environment, but with this our schedule is essentially broken at the moment.

**Comment by rixx** [comment]
I'm not quite sure on the fly – either reordering all rooms once, or removing the ordering from the rooms should do the trick. Try re-ordering them, and tell me if that doesn't help, in that case I can send you the query to remove room ordering.

**Comment by knarrff** [comment]
Reordering did not help (using the up/down buttons on https://derse19.uni-jena.de/orga/event/derse19/schedule/rooms; I tried making sure I changed each room at least once). I would not know how to remove room ordering entirely. Is that a setting I missed?

I guess an official version 0.9.1 is too much work? :)

**Comment by knarrff** [comment]
>   I guess an official version 0.9.1 is too much work? :)

Would you think a manual checkout of version 0.9, applying https://github.com/pretalx/pretalx/commit/7c5516015aa7cb83a0bdd9507c53bfec504efa96 and installing from there should do the trick?

**Comment by rixx** [comment]
What's your timeline right now? I think we could go for a 0.9.1 (even though I'm not happy with it, because it implies that all bug fixes ended up in there, and it's only going to be that one), but I'm not likely to get to it before tomorrow.

**Comment by knarrff** [comment]
I don't think we would need it over the weekend. I would otherwise update using a checkout of version 0.9 with the patch applied. I just thought that depending on your plans for the next release, it might be good to fix this for everyone, and a point-release sounded like the logical way to do that to prevent other more-critical changes from master out of 0.9.x versions.

**Comment by rixx** [comment]
Update: We're (hopefully) on the home stretch of the next release, with only three open points left to build/fix.
