### ISSUE TITLE
Assign submissions to reviewers

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#629]
## Problem you are facing

In the academic context, it seems usual to assign talks to reviewers. Pretalx cannot do that.

## Possible Solution

* Add a ManyToManyField pointing from Submission to Person for the assigned reviers.
* Add an extra tab "assigned reviewers" to `https://pretalx.com/orga/event/{event}/submissions/{slug}/` (URL would be `/orga/event/{event}/submission/{slug}/assigned_reviewers` which is a form with a multi select field of all people with review permissions.
* Add a checkbox "show submissions assigned to me only" to the SubmissionFilterForm (used by ReviewDashboard).

That's what I am currently implementing.

I have seen #619 but this looks different.

**Comment by rixx** [comment]
A few thoughts and questions:

Will reviewers still be able to see all submissions as they are now, and this adds only an additional filter? Could you make sure with your academic colleagues that this would be okay? I don't really want to add this feature only to then find out that we'll need to introduce additional access restrictions based on this. That's something I'd like to plan with beforehand.

I'd like to use the same data model as #619 for this, as both features would only add an assignment of a person to a submission, so please wait a bit with the implementation of this, until I've got the data model for assignments figured out.

**Comment by Nakaner** [comment]
> Will reviewers still be able to see all submissions as they are now, and this adds only an additional filter?

Yes, they will be able to see all submissions but can get a short list of their tasks using the checkbox in the filter form.

@yair-grinb @MarcoMinghini

**Comment by rixx** [comment]
Okay, that's a relief, thank you for clarifying. Let's merge this issue with #619 then, and I'll rephrase that a bit.
