### ISSUE TITLE
Programme editor is broken

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#630]
## Current Behavior

I cannot see any assigned talks in the programme editor.

The JavaScript console says: `TypeError: "this.talk.track is null"`

![Bildschirmfoto_2019-03-11_19-58-23](https://user-images.githubusercontent.com/3611273/54150128-0b4d8d80-4438-11e9-8e79-5dabca913694.png)

## Expected Behavior

There should be multiple talks in a darker green colour in all these rooms, not just light green tall boxes.

## Steps to Reproduce

1.  Go to https://pretalx.com/orga/event/fossgis2019/schedule/ (programme version does not matter, both WIP and latest public release are affected).

**Comment by rixx** [comment]
Apologies, this seems to be a bug related to talks without tracks. Fixed in 3aa0fbbd.
