### ISSUE TITLE
Getting 403 for an uploaded file

### ISSUE THREAD

**Issue by britiger** [pretalx/pretalx#632]
I've uploaded my slides of my last talk at fossgis. After upload the file I've check it. While try to download the file I get an 403 error from webserver. I've tried to delete and reupload the file. The first file seams to exists, because the second upload renamed my filename. I also get the 403 for my second upload.
I've tried out downloading the file as speaker as well as anonymous with another browser.

* Link: https://pretalx.com/fossgis2019/talk/GP8WDX/
* file: https://pretalx.com/media/Christopher_Lorenz_Fahrradknotenpunkte_eHrjZGd.pdf
* first upload (I removed from talk): https://pretalx.com/media/Christopher_Lorenz_Fahrradknotenpunkte.pdf

**Comment by rixx** [comment]
This wasn't a pretalx issue, but a deployment issue – apologies, it is fixed now.
