### ISSUE TITLE
CfP can be edited without "can change event settings" permission

### ISSUE THREAD

**Issue by zoff99** [pretalx/pretalx#633]
## Current Behavior
setting "Can change event settings" for team "xyz" is disabled.
yet any team member can change settings on "CfP -> Content" page.
like "Headline" for example.

## Expected Behavior
setting "Can change event settings" for team "xyz" is disabled.
team members can NOT change settings on "CfP -> Content" page.

maybe i am interpreting it wrong? i want the team members to only be able to edit and review submissions, but not change any global settings or texts for the event (and also the CfP itself of course)

## Your Environment

* Version used: v0.9.0
* Environment name and version (e.g. Chrome 39, python 3.5): python 3.6
* Operating System and version (desktop or mobile): debian 9

**Comment by rixx** [comment]
That's not quite intended, thank you. I'm about to push a fix.

> i want the team members to only be able to edit and review submissions

Interesting, I think this is the first time we've heard of this kind of separation of permissions. Usually reviewers are not supposed to edit submissions at all. Thank you for your report!

**Comment by zoff99** [comment]
@rixx wow that was fast :-) thanks for the reply
