### ISSUE TITLE
Show talk language on talk page

### ISSUE THREAD

**Issue by meisterluk** [pretalx/pretalx#635]
## Problem you are facing

The talk was accepted. The user entered a certain talk language, but the talk language is not communicated to the web user.

## Possible Solution

Add a UI element to visualize the talk language at the talk page.

## Example

The [talk “Web Frontend Testing”](https://pretalx.linuxtage.at/glt19/talk/ECW3JF/) will be held at Grazer Linuxtage (don't forget to add us as pretalx users 😉). The submission was done in English, but this does not necessarily reflect the talk's language.

**Comment by rixx** [comment]
Good point! Do you have a suggestion of where to include the language?

**Comment by senarclens** [comment]
@rixx thx for considering this request; in the detail view an obvious place would be right underneath the speaker... see this mockup:
![pretalx show language in detail view](https://user-images.githubusercontent.com/3088890/55567077-47090980-56fd-11e9-8a76-be4f5941206b.png)
In the overview I suppose a language shortcut would do just fine (eg. "en" for English); I can prepare a mockup if needed.

**Comment by rixx** [comment]
The talk language is now displayed if the event offers more than one language.
