### ISSUE TITLE
Allow accepting invitation when logged in

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#636]
## Current Behavior

You need to log in to accept an invitation to a team

## Expected Behavior

You can accept an invitation when you are already logged in

## Context

The background is that I'm running a pretalx instance which has login capabilities via GitHub. The problem is that such a third party authentication works via links and GETs. In order to accept an invitation, you need to follow the link and then do a login via POST in order to accept it.

This means that my users that have authenticated via GitHub can't accept invitations.

As this is a really special case on an unsupported version, I'd be happy to get some pointers on how I could fix that. Perhaps it can even be done in a way which improves pretalx in general.

## Your Environment

* Version used: master

**Comment by vmx** [comment]
It's not ideal, but kind of works. Add this to the `InvitationView()`

```python
    def get(self, request, code):
        if request.user.is_authenticated:
            invite = self.object
            self._accept_invitation(invite, self.request.user)
            return redirect('/orga')
        return render(request, self.template_name, self.get_context_data())

    def _accept_invitation(self, invite, user):
        invite.team.members.add(user)
        invite.team.save()

        invite.team.organiser.log_action(
            'pretalx.invite.orga.accept', person=user, orga=True
        )
        messages.info(self.request, _('You are now part of the team!'))
        invite.delete()
```

**Comment by rixx** [comment]
I probably wouldn't merge this, since I don't like taking actions on GET request in general, but especially not on links that email clients might just GET when seeing the invite email. (Believe me, it happens a lot).

**Comment by rixx** [comment]
I changed the invitation page so that it only offers a "Join the team!" button if the user is signed in.

**Comment by vmx** [comment]
I also didn't like the auto-subscribe mode, the solution with the "Join the team!" button is really a great idea, I really like it and it solved my problem. Thanks a lot for looking into this.
