### ISSUE TITLE
schedule layout is not optimal on high DPI displays

### ISSUE THREAD

**Issue by zoff99** [pretalx/pretalx#637]
## Expected Behavior
visit https://pretalx.linuxtage.at/glt19/schedule/ and look at the schedule
be able to read all talk headlines

## Steps to Reproduce

visit https://pretalx.linuxtage.at/glt19/schedule/ and look at the schedule
many talk headlines are cut or broken into multiple lines in a way that is not optimal to read.
(see image)

## Context

mybe the font can be smaller or condensed when the topic really does not fit in the bubble?

## Your Environment

* Version used: not sure
* Environment name and version (e.g. Chrome 39, python 3.5): windows firefox 4K display
* Operating System and version (desktop or mobile): windows

![image](https://user-images.githubusercontent.com/6833516/54808170-b7d11000-4c7f-11e9-852d-815d428e4ecd.png)

**Comment by rixx** [comment]
I don't think a smaller font would net you a full title with most of these talks, to be honest. I'm open for suggestions or pull requests, but I'm not sure that we have the option of fitting the complete title on screen without hovering for all talks, while maintaining a proportionate schedule view. A wider display would probably help, but other than that, I'm open for good ideas.

**Comment by zoff99** [comment]
sadly i do not have the answer.
i thought i will report it, maybe some other clever person has an idea how to solve it

**Comment by rixx** [comment]
pretalx will now resize to be as wide as possible if the schedule features six or more rooms, and will take up more room than it did so far if there are four or five rooms. Until better ideas come up, I'd consider this issue to be closed (but I'm very willing to re-open for new ideas).
