### ISSUE TITLE
Person unique ID missing in schedule export

### ISSUE THREAD

**Issue by Rufus125** [pretalx/pretalx#641]
## Current Behavior

URL to speaker is missing.

## Expected Behavior

URL to speaker is included in schedule.xml

## Steps to Reproduce

1. open https://pretalx.linuxtage.at/glt19/schedule/export/schedule.xml
2. Search for "<person " only ID and name is included in XML
3. Speaker URL: https://pretalx.linuxtage.at/glt19/speaker/ED97ZT/
4. Whole URL or ID (ED97ZT) is not found in schedule.xml

## Context

I am trying to add the link to the speaker to the Android app: https://github.com/linuxtage/glt-companion/issues/12

## Your Environment

* Version used: Made with love by pretalx v0.9.0.
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production: https://pretalx.linuxtage.at/glt19

**Comment by rixx** [comment]
We can't just add the speaker code to the schedule.xml export to retain frab compatibility and since that field expects a number, I can't just provide our code instead. I would probably merge a PR adding a URL that redirects from speaker ID to speaker code, if anybody wants to submit one!

**Comment by rixx** [comment]
Sidenote: The schedule.json does not undergo validation as rigid as the schedule.xml. Since I'm pretty sure that an additional field won't trip anybody up, I've added a ``"code"`` to speakers in the json export.

**Comment by rixx** [comment]
`/<event>/speaker/by-id/1234/` will now redirect if that ID is connected to a valid, viewable speaker of that event.
