### ISSUE TITLE
Having only one submission type shows all submission types

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#642]
## Current Behavior
If an event only uses one submission type, the submission form shows submission types for ALL events

## Expected Behavior
Only submission types for the current conference should populate the dropdown. 
Added bonus: if only one, the field should be read-only/text. 

## Steps to Reproduce

1. https://pretalx.com/orga/event/[YOUREVENT]/cfp/types/
2. Enter only one type
3. Navigate to https://pretalx.com/[YOUREVENT]/submit/
4. Click the dropdown for "Submission type"

<img width="801" alt="Screen Shot 2019-03-30 at 5 35 39 pm" src="https://user-images.githubusercontent.com/813732/55272568-53aeeb80-5312-11e9-8de9-e101aa53034f.png">

### Work around

Enter more than one submission type. 

## Your Environment

Pretalx hosted environment

**Comment by rixx** [comment]
Oops. That's what you get for trying to be clever and make a special case for "one submission type, no point of showing the field"! Thank you, @luto, for the timely fix.

**Comment by rixx** [comment]
The fix has been deployed on pretalx.com, too, so you should be good on that side, @glasnt.
