### ISSUE TITLE
Make team invitation link a login redirect page

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#644]
## Problem you are facing

The team invitation page has it's own form for login/registration.

## Possible Solution

Make the team invitation link a redirect to the login form. So instead of having a link like `/orga/invitation/vzrjezf1888s6pebzxcqcct2kifgxr25` it could be `orga/login?next=/orga/invitation/vzrjezf1888s6pebzxcqcct2kifgxr25`. This way you wouldn't need to provide a separate login/registration form.

## Context

There's currently several entry pages for login/registration. That makes it difficult for third party authentication as all those pages have different redirects on success. Unifying the login story would make that easier. I would also say that it makes the whole system cleaner.

In this case there's a problem though. Currently the orga login form doesn't provide a way to register, though the invitation link would need that.

Please take this as a proposition for solving a wider issue. I can see that this is not a major issue at the moment and given that we all have time constraints, feel free to close this issue. I just wanted to bring it up as it might be something to consider in the future.

**Comment by rixx** [comment]
I see your point, but I don't want to open registrations on a generic login page right now.

> There's currently several entry pages for login/registration.

While that's true, there is only one *template* and one *form* for these pages, making modifications still quite possible. In my mind, the real way forward would be to provide a couple of plugin hooks for oauth logins. I don't really have an overview right now what that would entail, but that's where I would want to head next. And I think if we put the logic in the login/registration form, and the presentation in the template, we don't need to mess with the invite workflow.

**Comment by vmx** [comment]
I'm closing this issue as "problem noted, we will tackle it once we have a proper oauth plugin" (which is on my todo list and I'll spend time one, once I'm done with the modifications for the FOSS4G conference.
