### ISSUE TITLE
"Full submission content" new lines lost in HTML email format

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#645]
## Current Behavior
If a person submits a talk, they receive an email with the "Acknowledge Mail" template, **but** the generated "Full submission content" is poorly formatted. 

## Expected Behavior

The receipt of the submission should read well in both text and HTML emails. 

## Steps to Reproduce

1. Submit a talk to any pretalx conference
2. Check email for a reply. 

## Context

Organisers can format their reply to CFP submissions with the "Acknowledge Mail" template. 

However, the formatted output is losing newlines. The code is correctly converting `**` to `<strong>` (where?) but newlines are being lost. 

![Screen Shot 2019-04-02 at 9 11 36 pm](https://user-images.githubusercontent.com/813732/55394832-f7ef9700-558b-11e9-91a3-f84d7368d1a2.png)

https://github.com/pretalx/pretalx/blob/master/src/pretalx/submission/models/submission.py#L535

Called in https://github.com/pretalx/pretalx/blob/master/src/pretalx/mail/models.py#L68

## Your Environment
 
Hosted pretalx v0.9.0

**Comment by rixx** [comment]
Thank you for the fix (and yay for your first pretalx PR)!
