### ISSUE TITLE
Make help texts for hard-coded CfP fields editable

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#648]
## Problem you are facing

Some fields of CfP are hard-coded and can only be enabled or disabled. They are useful but their description can be confusing to submitters or lack necessary information. There are two ugly workarounds at the moment:

* Disable the hard coded field and replace it by a custom field. This has the disadvantage of not being integrated in various exports and the programme.
* If running Pretalx yourself, edit the template and maintain your own fork.

## Possible Solution

Make help text editable.

## Context

For example, in Pretalx, an "abstract" is a short description one or two sentences long. A "description" is a longer text about the submission. In the academic context, an abstract is multiple hundreds of words long.

At FOSSGIS, the short text is printed in a booklet and both texts are shown in the online programme and the app. As an organiser, I would like to be able to edit the help text to explain that.

This feature request is a result of our experiences at FOSSGIS 2019.

**Comment by rixx** [comment]
I'd prefer to choose help texts that are no issue for anybody. Making all help texts for all fields in pretalx editable is quite a lot of settings, and settings fatigue in applications is a thing. I'd rather find a solution that works for everybody (and it may well be to remove the help texts entirely.

**Comment by vmx** [comment]
> Making all help texts for all fields in pretalx editable is quite a lot of settings, and settings fatigue in applications is a thing.

Agreed.

An alternative idea, not sure if I like it myself. Could there be a pretalx plugin that allows to upload custom templates? This way power users could override help texts from within the templates, but wouldn't need to run it themselves (in case it's installed on the hosted instance).

**Comment by Nakaner** [comment]
Custom templates also allow to add longer explanation texts. There could only be the issue of the loading content (images etc.) from third parties which is not coverd (but should mentioned) in the privacy policy of pretalx.com. In addition, one should check how safe it is to use Django templates submitted by users (or how powerful they are).

**Comment by rixx** [comment]
User uploaded Django templates are absolutely never going to happen – Django templates have access to the complete database, and while they can't quite execute arbitrary code, they're very close to that.

Plugins should already be able to provide custom templates just by adding them to their templates folders – have you checked that?

**Comment by rixx** [comment]
I've removed the help_text from the abstract and description fields, so that only the markdown note is left, and potential length restriction notifications. I'd say that any in-depth help in filling in the fields would be badly placed in our help text, since it's small and not great to read for longer texts, and should rather be placed elsewhere. Would you agree?
