### ISSUE TITLE
Dashboard History contains de-anonymised details of speakers

### ISSUE THREAD

**Issue by attacus** [pretalx/pretalx#649]
## Current Behavior

While running an anonymised CFP, where reviewers should not know anything about the submitters, this information is still visible in the "Dashboard" page inside the "History" section.

Speaker names are listed next to a link to the submission they have created. This de-identifies all speakers. It is especially troubling because the "Dashboard" is the first thing that a user sees when they log into the PreTalx organiser section.

## Expected Behavior

If a CFP is anonymous, reviewers should not be able to see any information about speakers/submitters _anywhere_ in the PreTalx interface.

(Ideally, reviewers should not be able to see the Dashboard at all, as it also contains a broken link to https://pretalx.com/orga/event/[event-slug]/mails/compose, which is not relevant for people who are only reviewing talks. Also, I do not think the "History" for the whole event's actions is really relevant information for reviewers.)

## Steps to Reproduce

1. Create a reviewer user on an event with an anonymous CFP, with some existing talk submissions
2. Limit reviewer permissions to "Is a reviewer" only
3. Log in as the reviewer
4. View "Dashboard"
5. You can see submitter names in the "History" section of the "Dashboard", with a link to the related submission

## Context

We are running an anonymised review process for PyCon AU. It is imperative that reviewers should not be able to see anything about the identities of the submitters anywhere in the interface, as this may bias their reviews.

This is a big problem for us, and will become a serious blocker once we begin inviting reviewers to the event.

## Your Environment

* Version used: pretalx v0.9.0
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome and Brave Browsers, latest versions at date of posting
* Operating System and version (desktop or mobile): MacOS, desktop
* Link to your instance, if in production: https://pretalx.com/pyconau2019/cfp

**Comment by attacus** [comment]
My suggestion is to remove the "Dashboard" from the reviewer role entirely, or at least to remove the "History" section from the dashboard if the user is a reviewer.

I'm not sure of the feasibility of this suggestion, but that would certainly solve the problem for us, at least.

**Comment by rixx** [comment]
> My suggestion is to remove the "Dashboard" from the reviewer role entirely, or at least to remove the "History" section from the dashboard if the user is a reviewer.

Definitely!

**Comment by rixx** [comment]
I added a fix for this, but deployment will have to wait for another ~12 hours: we currently have breaking tests that indicate I really should do some work before applying anything to pretalx.com – will that be alright for you?

**Comment by attacus** [comment]
Thanks for that! We can certainly wait 12 hours, no problem.

**Comment by rixx** [comment]
Ah, I forgot to notify you, but the fix has been running on pretalx.com for some time now.
