### ISSUE TITLE
Issues with gmail

### ISSUE THREAD

**Issue by momorientes** [pretalx/pretalx#653]
This is less of a pretalx bug, rather a strange behavior when working with gmail.

In summary gmail will report bad credentials when configured in pretalx.
To get this to work one has to enable access for "less secure" apps in gmail.
See: https://support.google.com/accounts/answer/6010255

I don't see any requirements for a change in pretalx, but maybe the docs/faq would benefit from knowing of this gmail setting.

**Comment by raphaelm** [comment]
Just FYI, Google will unexpectedly block your SMTP connection with unhelpful error messages if you use GMail to send out too many emails in bulk (think e.g. all rejections for a conference) even on GSuite, so using GMail for transactional email is a bad idea anyways.

**Comment by rixx** [comment]
Thank you @momorientes for reporting this (including a solution), and @raphaelm for sharing your experience – it's appreciated! I started a FAQ page in lieu of a proper user guide for now, and added your knowledge there.
