### ISSUE TITLE
email address with trailing space is possible

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#658]
## Current Behavior

You get invited to a talk and your email address has a trailing space at the end, e.g. `vmx@example.org `.

## Expected Behavior

Email addresses should be trimmed so that there are no whitespaces.

## Steps to Reproduce

The user where it happened reported that he got invited to a talk.

## Context

The system now had two accounts, one with the valid email address (when the user signed up himself) and one with the email address with the trailing space. The account looked the same, I only found this issue when I was looking on a database level.

## Your Environment

* Version used: https://github.com/vmx/pretalx/commit/80cb5c49053bda23a67714bca8ddc251102ebeab which is a https://github.com/pretalx/pretalx/commit/6b82f13a56d7020a109fb92453ead1c8946d4119 + minor changes
* Environment name and version (e.g. Chrome 39, python 3.5): Python 3.6.7

**Comment by rixx** [comment]
I'm not sure how this would have happened, and without further context it's hard to make out (e.g. who invited them, and how did they accept). I've added additional safeguards, which should prevent cases like this in the future.
