### ISSUE TITLE
Submission track counters include deleted talks

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#660]
## Current Behavior

If a talk is included in a track but has a state 'Deleted', then it is included in the counter, but is not returned in the search result. 

## Expected Behavior

Excluded states should be excluded from counters

## Steps to Reproduce

Assume 2 "ABC Track" talks, one Deleted, one Submitted

1. /submissions/
2. Filter by a track "ABC Track (2)"
3. One result shown

## Context

The expected filtered results should show in the helpful guide number. 

I understand that when you start having multiple filters active that having accurate guide numbers gets difficult, but this is an edge case that should be handled (e.g. full results for any state specifically exclude deleted talks, as should the guide number)

## Your Environment

Hosted pretalx

**Comment by glasnt** [comment]
This may also be yet another bug where Deleted talks are excluded from a number of views unless explicitly searched for, but featured in others where they are assumed to be hidden.

**Comment by rixx** [comment]
I thought we were ignoring deleted talks in all counts unless they were explicitly included. This is, like any solution reasoning about deleted objects, awkward. To my mind it's the most often useful one, as I typically don't want to consider deleted objects, unless to select them explicitly – but I'm open to suggestions for better behaviour.
