### ISSUE TITLE
Acceptance email and website does not show if submission type has been modified

### ISSUE THREAD

**Issue by ChrisRackauckas** [pretalx/pretalx#666]
## Problem you are facing

The acceptance email and website does not show if submission type has been modified. At many conferences, it is common to downgrade a submission to a shorter talk or poster instead of an outright rejection. However, the Pretalx system inform the participant that this has occurred in the acceptance email or the confirmation website. Thus, participants have no idea what kind of talk (or poster!) they have been accepted for!

## Possible Solution

When submission types are edited, this should be included in the acceptance email. Or at the very least, the submission type should be clearly displayed on the confirmation page, and the standard template should explain to participants that the type they were accepted for may not be that which they submitted.

**Comment by rixx** [comment]
Showing the submission track only if it has changed is a tricky thing, and unless somebody comes up with a proposal or PR, I don't think this is going to happen any time soon.

Showing the submission type and the track on the confirmation page is a good idea, though!

**Comment by ChrisRackauckas** [comment]
>Showing the submission track only if it has changed is a tricky thing, and unless somebody comes up with a proposal or PR, I don't think this is going to happen any time soon.

That's fine. I think as long as it shows up in the confirmation page we're good.

**Comment by ChrisRackauckas** [comment]
thanks!
