### ISSUE TITLE
Expose review endpoint 

### ISSUE THREAD

**Issue by vchuravy** [pretalx/pretalx#670]
## Problem you are facing

I would like to access the reviews through the API to collate review statistics and other metrics

## Context

In https://github.com/pretalx/pretalx/issues/656#issuecomment-485258439 we discussed several metrics to be calculated from review scores and so exposing the reviews through the API would allow me to do that kind of custom processing.

**Comment by rixx** [comment]
This is a great first issue for people to contribute, since adding an endpoint similar to the existing ones isn't particularly tricky – let me know if I can be of any help!

**Comment by rixx** [comment]
This is actually just a documentation issue, seeing as reviews are already exposed via the API.

**Comment by rixx** [comment]
Actually, it turns out, this endpoint was documented already, I had just forgotten about it. Can you clarify what your issue was asking for?
