### ISSUE TITLE
Allow to save submissions in a draft state

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#672]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

Submitters might not be ready to finish their proposal at submission time, or might want to pencil in details later. Offering a draft status would allow them to fill in what they can now.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).

## How to do this

Make yourself familiar with the `Submission` model. You'll have to add a new `SubmissionState` and exclude it in the default model manager and in the `all_objects` manager, to make sure it shows up nowhere except for the person creating the submission.

These are additional considerations you should think about – but if some of these seem like too much, do some of the work first, open a PR, and we'll take it from there!

### Clear UI

Switching to a draft status should be possible at any point during the workflow, so there needs to be a good and visible switch/button/… to do that. **Switching back cannot be as easy though**, since it requires form validation to run.

It must be very visible at all times if a proposal is edited in draft status.

### Form validation

It would be fair or even expected to disable form validation at this point – but part of the validation (particularly the length and format restrictions) take place client side via HTML attributes. We could remove those via JavaScript (but note that we have successfully avoided solutions requiring JavaScript so far).

All submission forms (including the already heavily meta-programmed question forms) would need to accept one more flag to turn validation on or off.

### Reminders

Submitters should be reminded about pending draft proposals at a (configurable? maybe not.) interval before the CfP closes. Note that different CfP deadlines for different submission types or tracks need to be respected here!

Submitters need to be able to opt out of the reminder, so this will need to be a per-permission flag. (Which is neat, since this can be useful on non-draft proposals, too.)

### Privacy

It needs to be clear that organisers will not be able to see, or review, or comment on draft proposals. Draft proposals should only be visible to the author(s) *and* on the review view, which allows the submission to be shared with people who do not have an account.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by Donnyvdm** [comment]
I'm interested in picking this up

**Comment by ligi** [comment]
@Donnyvdm hey - did you pick this up? Is there any branch to have a look at?
