### ISSUE TITLE
Add field for affiliation to speaker profile

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#673]
## Problem you are facing

There is no way to associate a speaker with a company/institution

## Possible Solution

Add a field to the speak profile called "affiliation" where you can add the information about the speaker.

## Context

For some conferences it is important which company/institution a speaker is affiliated with. Currently we have no way to add/display that information.

I'm happy to create a PR if I'm told how this could be implemented.

**Comment by rixx** [comment]
Isn't a speaker question sufficient for you? You can ask the speaker for their affiliation and choose if that information should be displayed publicly.

**Comment by vmx** [comment]
I didn't know that you can also have per speaker questions, I should've checked that. That should work for me.
