### ISSUE TITLE
HTTP 500 when trying to use rgb CSS for event color

### ISSUE THREAD

**Issue by kannes** [pretalx/pretalx#679]
## Current Behavior

i entered `rgb(76, 0, 255)` as color on `/orga/event/new/`

Then on "New event" "Step 5 of 5" after clicking "Next step" I got a HTTP 500 error. The log says:

```
ERROR 2019-04-26 11:18:46,485 django.request log Internal Server Error: /orga/event/new/
Traceback (most recent call last):
  File "/var/pretalx/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(7)
```

I am only guessing but I assume that somewhere there is a color column for 7 characters (`#234567`)? ;)

When I went back to step 4 and set "#5500ff" as color instead, I could finish event creation without any problems.

## Expected Behavior
Either an error or (which I would love) no error but support to declare colors in the rgb (or hsl or else) syntax, not just as hex. Might not be worth it though.

## Steps to Reproduce

1. Create a new event
2. Enter `rgb(76, 0, 255)` as its color on step 4

## Your Environment

Ubuntu 18-04, pretalx==0.9.0, psycopg2-binary==2.8.2, postgresql_10+190

**Comment by rixx** [comment]
Color declaration is indeed currently limited to hex syntax (as the help text below the field should have told you – for some reason this help text was only present in the event editing, not in the event creation).

I've added a validator that should provide more reasonable feedback. Thank you for the report!

**Comment by kannes** [comment]
Excellent!
