### ISSUE TITLE
Outgoing mails are not sent

### ISSUE THREAD

**Issue by kannes** [pretalx/pretalx#680]
I receive no mails on new submissions (I did configure it to send them) or if I send a mail to all authors (including me).

I checked the network traffic with tshark:
- When using the SMTP testing on `/orga/event/myevent/settings/mail` I do see communication between my host and the remote smtp server I configured.
- But when other normal actions should trigger outgoing mail nothing happens.

There are no explicitly related errors in `/var/pretalx/data/logs/*`, just lots of
```
...
WARNING 2019-04-26 12:18:00,865 django.request log Not Found: /api/values
WARNING 2019-04-26 12:18:00,865 django.request log Not Found: /api/values
WARNING 2019-04-26 12:19:07,134 django.request log Not Found: /api/values
WARNING 2019-04-26 12:19:07,134 django.request log Not Found: /api/values
WARNING 2019-04-26 12:24:11,455 django.request log Not Found: /api/values
WARNING 2019-04-26 12:24:11,455 django.request log Not Found: /api/values
WARNING 2019-04-26 12:29:15,568 django.request log Not Found: /api/values
WARNING 2019-04-26 12:29:15,568 django.request log Not Found: /api/values
```

## Your Environment

Ubuntu 18-04, pretalx==0.9.0

**Comment by kannes** [comment]
I just saw https://github.com/pretalx/pretalx/issues/419 and will look into that Celery stuff. I did not see that as being required during installation but maybe I overlooked some details...

**Comment by kannes** [comment]
Yeah, that fixed it. I will update the docs to indicate that celery is indeed a requirement, not an option.

**Comment by kannes** [comment]
On the upside, the previously unsent mails were all sent after I had the worker running. :)

**Comment by rixx** [comment]
Celery is a requirement, but running separate celery workers isn't one, if you configure your instance appropriately. If you have a celery section in your settings, celery workers will have to run.

**Comment by kannes** [comment]
So my mistake was "user configured `[celery]` in config but is not running workers". Should that result in a error or warning somewhere?

-----

Now I am confused...

I admit that I did *not* read https://pretalx.readthedocs.io/en/latest/administrator/configure.html#configure at all, I only followed https://pretalx.readthedocs.io/en/latest/administrator/installation.html

### Celery
So I could just leave out the `[celery]` part in `/etc/pretalx/pretalx.cfg` file and it would work without the workers?

https://pretalx.readthedocs.io/en/latest/administrator/configure.html#the-celery-section says: 

> Celery is not a requirement for pretalx.

which is contradicting your statement above. Am I right to assume that this should rather say that the `[celery]` part in the config is not requirement and is only used to configure settings for workers (if one decides to use them)?

### redis
Would this also mean that I would not need to run redis?

https://pretalx.readthedocs.io/en/latest/administrator/configure.html#the-redis-section suggests that redis is not actually a hard dependency:

> If you configure a redis server, pretalx can use it for locking, caching and session storage to speed up operations.

So that sounds like the only other use of redis apart from celery workers.

### Sensible defaults
Would it make more sense to have the installation guide default to redis and celery workers? If redis was running already, what reason would there be not to also use it for locking+caching+sessionstorage?

Or should the default installation rather do without redis and celery workers?

At what kind of size/scope would it be a very stupid(tm) idea to not use those things? Is there any drawback from running them even for a tiny installation?

-----

If we should move this discussion to a new issue, please just shout!

I will gladly update the docs in the end to help making the first-timer copy'n'paster's installation work out-of-the-box. ;)

**Comment by rixx** [comment]
>https://pretalx.readthedocs.io/en/latest/administrator/configure.html#the-celery-section says:
>>    Celery is not a requirement for pretalx.
>which is contradicting your statement above. Am I right to assume that this should rather say that the >[celery] part in the config is not requirement and is only used to configure settings for workers (if one >decides to use them)?

Yes, that wasn't phrased great, and what you inferred just now is correct.

> Would it make more sense to have the installation guide default to redis and celery workers? If redis was running already, what reason would there be not to also use it for locking+caching+sessionstorage?

I'd like to keep the installation guide as simple as possible. Having two additional services running that are not strictly necessary can be offputting to newcomers, as it makes the setup more complex, harder to debug, and makes pretalx seem more resource hungry than it is.

I'm not completely clear on how to handle this properly. It might be best to drop redis from the installation guide for consistency, and remove the celery/redis section from `pretalx.example.cfg`. This has the advantage of a simple first installation, but it will make it hard to discover the additional capabilities. (Although I guess that would be alright, really.)

**Comment by kannes** [comment]
I felt the installation was straightforward and easy enough. Powerful out of the box is good. The extra 100-200 MB for the celery worker is quite a bit though.
