### ISSUE TITLE
Provide Submission.created in API

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#682]
## Problem you are facing

I want to be able to see a graph of submissions over time, but in an exportable way

## Possible Solution

Pulling the`submission-timeline-data` div from https://pretalx.com/orga/event/eventID/submissions/statistics/ gives *all* submissions, but includes withdrawn talks. 

## Context

It doesn't look like submissions have timestamps on the objects, so we need to work from Activity. Being able to use whatever data is stored there and manipulate it would be useful.

**Comment by rixx** [comment]
Would it be sufficient (at least for now) to include a 'created' timestamp in the API?

Regarding the submission stats page – do you think it would make sense to make it more filterable? It like a clumsy UI addition to me, so I removed it when I played around with it, and left only the submissions vs talks filter.

**Comment by glasnt** [comment]
My use case is being able to compare our submission stats across years. 

If you can incorporate the 'created' timestamp in the API against a submission, that'd be cool. (Noting that it'd have to be a calculated field (whatever that's called in django), since I'm using existing data. Unless migrations can handle that. That'd be cool, too)

As for the UI; that section is extremely subjective, and personally I'd prefer to export the data to do it myself rather than having a muted calculated view (hence, this feature request)

**Comment by rixx** [comment]
I think introducing a `created` timestamp is the way to go here.

**Comment by rixx** [comment]
For authenticated users with organiser permissions, the submissions endpoint now includes a `created` field with an ISO8601 compliant string.
