### ISSUE TITLE
Emails send from pretalx are reported as unauthenticated

### ISSUE THREAD

**Issue by vchuravy** [pretalx/pretalx#685]
## Current Behavior

Rights now users can specify a send-as e-mail. These emails will show as unauthenticated to the recipient.

## Expected Behavior

Emails should be authenticated to reduce likely hood of emails being classified as spam. They should include at least a SPF header.

Alternatively instead of send-as, only reply-to should be set.

## Steps to Reproduce

1. Use a email address like GMail that has SPF and DKIM as a send-from email
2. Send email to user who verifies SPF/DKIM Gmail is again a provider that does this.

**Comment by rixx** [comment]
Reply-To should be explicitly set. All other issues depend on your email configuration – if your issue is with hosted pretalx, please contact support@pretalx.com. We had a report regarding email issues earlier today, that was resolved shortly afterwards.
