### ISSUE TITLE
Sharing submission during CFP shows blank page

### ISSUE THREAD

**Issue by MarkusH** [pretalx/pretalx#686]
## Current Behavior

After writing a proposal, while the CFP is still open, there's a link at the bottom for "Share submission" ("If you need a review from a colleague or a friend here's a link that you can send out for viewing your submission"). Opening this link in a private/incognito window will result in an "empty" page. The Conference's design is there but it seems like the object's attributes are simply not shown.

Example link (stripped of sensitive information): https://pretalx.com/:conf_slug/talk/review/:random_string

Here's the HTML for the `#main-card` element:
```html
<div class="card" id="main-card">
    <main>
        <article>
            <h3 class="talk-title">
                <div class="heading-with-buttons">
                    <div class="buttons" id="talk-buttons">
                        <a class="btn btn-outline-primary" href="">
                            <i class="fa fa-calendar"></i> .ical
                        </a>
                    </div>
                </div>
                <small></small>
            </h3>
            <div class="talk row">
                <div class="talk-content col-lg-8 col-md-6 col-xs-12">
                    <section class="abstract"></section>
                    <section class="description"></section>
                </div>
                <aside class="col-lg-4 col-md-6 col-xs-12"></aside>
            </div>
        </article>
    </main>
</div>
```

## Expected Behavior

I'd expect the title, abstract, description, etc to show up.

## Steps to Reproduce

1. Submit a talk during an open CFP
2. Open the "Share submission" link at the bottom of the proposal in a new, incognito window (or in a context of a not logged-in user).

## Context

I submitted a talk proposal and wanted a second person's opinion on it. So I figured I copy the "Share submission" link and sent it to them. Before sending it I had a look what they'd see and noticed the page the be "empty".

## Your Environment

* Version used: Hosted version on pretalx.com
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox Nightly 68.0a1 (2019-04-23) (64-bit)
* Operating System and version (desktop or mobile): Arch Linux
* Link to your instance, if in production: pretalx.com

**Comment by rixx** [comment]
Thank you for reporting this issue! This appears to have been introduced a week back during some refactoring. Our tests have been slightly improved to catch this in the future.

**Comment by MarkusH** [comment]
Thank you! :1st_place_medal:
