### ISSUE TITLE
Review page UI bug obscures Track drop-down

### ISSUE THREAD

**Issue by attacus** [pretalx/pretalx#687]
## Current Behavior

On the Reviews page (https://pretalx.com/orga/event/{$EVENTNAME}/reviews/), the list of tracks appears underneath the column heading, making it difficult to interact with. This is shown in the following screenshot (some information redacted for privacy):

<img width="357" alt="Screen Shot 2019-05-02 at 2 23 43 pm" src="https://user-images.githubusercontent.com/15101584/57056678-53c25280-6ce7-11e9-87cc-a596a212b0f7.png">

## Expected Behavior

The drop-down menu should render over the column headings.

## Steps to Reproduce

1. Log in as a user with Reviewer permissions, on an event that has two or more track tags
2. Visit the Reviews page (https://pretalx.com/orga/event/{$EVENTNAME}/reviews/)
3. Click the "Tracks" menu to trigger the drop-down

## Context

We will be opening reviews for our conference soon and discovered this UI bug during testing. We hope it can be resolved before reviewing begins.

## Your Environment

* Version used: PreTalx v0.9.0
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome Version 76.0.3776.0 (Official Build) canary (64-bit)
* Operating System and version (desktop or mobile): MacOS latest
* Link to your instance, if in production: https://pretalx.com/orga/event/pyconau2019/

**Comment by rixx** [comment]
This bug was introduced when we removed pagination from the review page – without pagination, the table is very long, so we decided to make the table header sticky, so it was pulled more towards the foreground (to make the table content disappear under it).

**Comment by attacus** [comment]
🤘You're the best!
