### ISSUE TITLE
reply_to field is empty 

### ISSUE THREAD

**Issue by vchuravy** [pretalx/pretalx#688]
## Current Behavior

With custom smtp server, the reply-to field by default is empty instead of being
the conference e-mail.

```
Return-Path: <******@gmail.com>
Received: from forge.localdomain (forge.pretalx.com. [78.47.248.22])
        by smtp.gmail.com with ESMTPSA id b124sm140165wmg.21.2019.05.02.13.10.00
        for <********@***.edu>
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Thu, 02 May 2019 13:10:00 -0700 (PDT)
Content-Type: multipart/alternative; boundary="===============5551116299634454064=="
MIME-Version: 1.0
Subject: [Conference] Test
From: Conference <organisers@conference.org>
To: ******@***.edu
Cc: 
Reply-To: 
Date: Thu, 02 May 2019 20:10:00 -0000
Message-ID: <155682780044.13086.9298517312597290913@forge.localdomain>
```

## Expected Behavior

Without a custom smtp server, pretalx does set the `reply-to` e-mail, but that
fails the SPF check. If I explicitly set the `reply-to` email things work as expected.

## Steps to Reproduce

1. Setup a custom smtp server
2. Check reply-to field

## Context

I was trying to get e-mails to be verified (we have googlegroups for the organisers that acts as a mailing list) 

## Your Environment

Hosted pretalx version

**Comment by rixx** [comment]
There was a bug/inconsistency in email handling. This has been corrected. pretalx now follows this logic:

- If only an event email address is set (which is mandatory), but no sender address in the mail settings, the instance-global sender address is used (e.g. "MyEvent <noreply@pretalx.com>). The Reply-To is set to the event email address.
- If a sender address is set, it is used as the sender and no further Reply-To is set. This naturally works best if the "custom mail server" option is checked, but it is not mandatory.

**Comment by rixx** [comment]
To address the Reply-To issue you opened this ticket for, a new separate reply-to setting was introduced. You can find it on the mail settings page.

**Comment by vchuravy** [comment]
Thanks!
