### ISSUE TITLE
Docs for installation not rendered correctly

### ISSUE THREAD

**Issue by kannes** [pretalx/pretalx#693]
## Current
https://docs.pretalx.org/en/latest/administrator/installation.html#step-4-configuration did not include the `pretalx.example.cfg` for some reason, it currently looks like

<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="o">..</span> <span class="n">literalinclude</span><span class="p">::</span> <span class="o">../../</span><span class="n">src</span><span class="o">/</span><span class="n">pretalx</span><span class="o">.</span><span class="n">example</span><span class="o">.</span><span class="n">cfg</span>
</pre></div>
</div>
<blockquote>
<div><table class="docutils field-list" frame="void" rules="none">
<colgroup><col class="field-name">
<col class="field-body">
</colgroup><tbody valign="top">
<tr class="field-odd field"><th class="field-name">language:</th><td class="field-body">ini</td>
</tr>
</tbody>
</table>
</div></blockquote>

## Expected Behavior

It should have included the actual contents of `pretalx.example.cfg` like it did correctly previously and in https://docs.pretalx.org/en/latest/administrator/configure.html

## Possible solution
The syntax of the actual includeliteral line seems identical in both files so I guess the double colon at the end of the block above broke this?

https://github.com/pretalx/pretalx/commit/f5a7adf99346667b66823d7bcfe582f26caaea0a#diff-13a4227e15ad8bbe3bcef840cb375608L90

**Comment by rixx** [comment]
Oh, yes, double colons have special meaning in .rst.

**Comment by rixx** [comment]
Thank you for the report!
