### ISSUE TITLE
Improve UX around assigning scores to individual talks

### ISSUE THREAD

**Issue by freakboy3742** [pretalx/pretalx#694]
## Problem you are facing

In the configuration for PyCon AU, individual talks are reviewed on a 3-level scale "No (-1)", "Maybe (0)", or "Yes (1)". 

The UX element used to select a score on a talk is a pulldown, with "No" automatically selected on unreviewed talks.

This means rejecting a talk requires no UX interaction, but accepting a talk requires interacting with the pulldown. It also obscures the available options (admittedly this is only really an issue on the first couple of reviews, but it's obscuring context for those first few)

## Possible Solution

* Using radio buttons (with no default selection) for the scores; this would result in all three scores being visible, with a single click (rather than click and select) for each selection. Keyboard shortcuts could also be an option.

* Adding an "blank" value as a default value for the pulldown, so that all three scoring options require the same UX interaction

## Context

This doesn't pose any major impediment or problem for me personally; it's more of a UX polish thing that would make reviewing a long submission list a little easier.

**Comment by rixx** [comment]
> Adding an "blank" value as a default value for the pulldown, so that all three scoring options require the same UX interaction

I think we do this if submitting a review score is optional, but we don't do it if it's mandatory.

> Using radio buttons (with no default selection) for the scores; this would result in all three scores being visible, with a single click (rather than click and select) for each selection.

I think this is the best way to handle this, yes. Even for events with a scale of 5-10 values (which is kind of nonsensical in any case), this wouldn't be too much visual clutter, even if it's not pretty.

> Keyboard shortcuts could also be an option.

Keyboard shortcuts would be cool, but also kind of awkward? Take your example: If you have scores from -1 to 1, and we map them to keyboard shortcuts from 1 to 3, that's pretty confusing, I'd say.

**Comment by rixx** [comment]
Have a look at it now – does work better for you?

**Comment by freakboy3742** [comment]
😍 Magnificent!
