### ISSUE TITLE
"XX submissions are waiting for your review" number incorrect

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#695]
## Current Behavior

"XX submissions are waiting for your review. Click here to get started!"

## Expected Behavior

For a person who has not submitted any reviews, `XX` should match the "submissions" number on the dashboard. It currently matches the "reviews" number on the same dashboard.

## Steps to Reproduce

Requires reviewing stage, and user to be a reviewer, and not having reviewed any submissions (yet)
1. Navigate to /event/eventname
2. Confirm the "submissions" and "reviews" numbers
3. Navigate to /event/eventname/reviews
4. Compare the "XX submissions are waiting for your review" number incorrect" number. 

Expected: XX == Submissions
Actual: XX == Reviews

I expect this bug will also occur when the review also starts reviewing, but the number will be Submissions - Personally Reviewed Submissions. 

## Context

The number of reviews in our CFP is currently larger than the total number submissions, so when this number was presented to a review, they were worried, and reached out to me. 

## Your Environment

Hosted pretalx 0.9.0

**Comment by rixx** [comment]
Confirmed, this is a bug. Apparently I managed to find a bug in Django where `queryset.count()` is not the same as `len(queryset)`. I'll work around this in pretalx and submit a ticket to Django once I manage to build a minimal example of this.

**Comment by rixx** [comment]
Could you check if the number displayed looks correct now?

**Comment by glasnt** [comment]
@rixx Yes, the number looks much better now!

**Comment by freakboy3742** [comment]
Number is now correct.

Don't know if this will help with the debugging - but when I saw this, my immediate guess was that one query set had a join on it, and as a result, some talks were being double counted. Django doesn't auto-distinct when doing counts, so joins can result in over-estimates of counts if they're joining 1-N on another table.

**Comment by rixx** [comment]
It is definitely related to joins, but it is at the same time definitely a bug in Django: I can reproduce a queryset where

```python
>>> result = Review.find_missing_reviews(event, user)
>>> result.count()
15
>>> len(result)
32
>>> result.count()
32
```

(Numbers fudged, but thereabouts). This part is just a Django bug: `qs.count()` should not change after running ``len(qs)``, and ``len(qs)`` should not be different in the first place.

The culprit is probably the part where pretalx runs ``queryset.order_by('review_count', '?')``, which produces a lovely

```sql
GROUP BY "submission_submission"."id", Random()
ORDER BY "review_count" ASC, Random() ASC  
```

**Comment by freakboy3742** [comment]
Well that's... entertaining. Someone is going to have fun debugging that one 😛

**Comment by glasnt** [comment]
> This part is just a Django bug: qs.count() should not change after running len(qs), and len(qs) should not be different in the first place.

That smells like lazy loading to me, but I would assume it would be the other way around (`len` primitive being wrong when `count()` is right)

I won't do any duplication work here debugging this, and wish you luck. 

But thank you for fixing this issue so promptly in hosted pretalx. ✨

**Comment by rixx** [comment]
For reference, I reproduced the issue on a *very* minimal example and opened a [Django issue](https://code.djangoproject.com/ticket/30473#ticket).
