### ISSUE TITLE
Radio box in submission review misaligned

### ISSUE THREAD

**Issue by MarkusH** [pretalx/pretalx#696]
## Current Behavior

![image](https://user-images.githubusercontent.com/475613/57580942-971f7c80-74b0-11e9-9253-d16e8ae18c76.png)

## Expected Behavior

To have the green dot be inside the right circle :wink: 

![image](https://user-images.githubusercontent.com/475613/57580988-144af180-74b1-11e9-94d0-8bc7a4483ae9.png)

## Steps to Reproduce

When the "Points" column is too narrow there's the `0 (“Maybe”)` text breaks between the `0` and the `(`, making it a two line string.

I think the problem is that the "grey circle" is defined in `:before` and the "green disk" in `:after`, causing them to be placed in two different logical locations. Both drawings are positioned with `absolute` but in relation to the current position.

## Your Environment

* Firefox Nightly 68.0a1 (2019-04-23) (64-bit)

**Comment by rixx** [comment]
That's what you get for spontaneous features (added today in 57df11eb). Thank you for reporting it.

**Comment by rixx** [comment]
Should look better now.

**Comment by MarkusH** [comment]
Yay, fixed!
