### ISSUE TITLE
Allow reviewers to abstain from reviewing a proposal

### ISSUE THREAD

**Issue by chrisjrn** [pretalx/pretalx#698]
## Problem you are facing

When I'm reviewing proposals, sometimes I can see proposals where I can identify the presenter, or I am unqualified to give a review. 

I would like to be able to permanently exclude that proposal from my review queue.

## Possible Solution

Add a "Permanently skip" or "Abstain" button to the review options, that permanently marks the proposal as unreviewed.

## Context

I'm reviewing for a conference with more than 300 proposals, using anonymous review. I can often tell the identity of the presenter, which means I should not review the proposal.

**Comment by rixx** [comment]
Hmm, up until now we have used the workaround of "submit an empty review" for this. Organisers can permit reviewers to submit an empty review (no text and no score) if they want to.

We could/should make this explicit with a separate button, and "skip permanently" is probably a good choice for the title, thank you for the suggestion. But I'm uncertain if we should offer this button always, or only if the organisers have already permitted empty reviews. Any input would be appreciated. (Cc: @glasnt, maybe?)

**Comment by glasnt** [comment]
Having this as an option would be amazing. But if the option is enabled, then yes, an abstain option would be extremely useful, and should count as "no score" rather than a 0 (if that is an option that has been configured).

**Comment by rixx** [comment]
So currently you can choose "require score" and "require text" in the review settings, and I'd say, if both are unchecked, we can definitely offer a "Skip permanently" button, which will just submit an empty review. (It's already handled as a "no score" value, not 0.)

The question is if we should offer this button even if either or both of these settings are turned on (i.e. the organisers have chosen to require a score or require a text. By default a score is required atm).

**Comment by glasnt** [comment]
I would want to have this button as a separate option, explicitly.

**Comment by rixx** [comment]
Ah, so a setting for organisers, "Allow reviewers to abstain"? That's totally doable, sure!

**Comment by chrisjrn** [comment]
@rixx The current "no review, no score" option isn't particularly clear: it looks like I have to choose between "-1", "0", and "+1". Perhaps having "do not score" as a radio button option could also work.

**Comment by rixx** [comment]
@chrisjrn That's exactly the way it is currently implemented: If your organiser permits reviews with no score, you will see a "no score" option in addition to the options in an integer range configured by the organizer. So if you only see "-1", "0", "+1", that means that your organizer has set the "Require a review score" option. They can adjust this in the /settings/review/ part of pretalx.

**Comment by rixx** [comment]
Example from my dev instance (disregard the test data 😉):
![Screenshot_2019-05-13 Test foo pretalx](https://user-images.githubusercontent.com/2657547/57629494-2c4b6f80-759c-11e9-883d-3148661568b5.png)

**Comment by rixx** [comment]
![Screenshot_2019-05-17 Test foo pretalx](https://user-images.githubusercontent.com/2657547/57893046-b700c880-7841-11e9-943c-36353884724c.png)
