### ISSUE TITLE
Limit lenfth of an abstract

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#703]
## Problem you are facing
Most submissions use nice short abstracts (Q3 length was about 500 characters, which i think is towards the upper end of fine.).
Some submissions though went a bit overboard.
I think the longest one was around 2000 characters, and the 2nd and 3rd longest were not much shorter.
Several of these did not fill in the description, and just put it all in the abstract.

Having a short abstract is useful, it means we can produce various lists of talks with abstracts that give people a better idea about what the talks are than just the title.
But when you can normally fit say 5 or 10 to a page, but 1 talk takes up a full page on its own, we have to  truncate them.

## Possible Solution
Having a character limit for the abstract would fix this,
It would be clear that the abstract is a short summary, and the full details can go in the description.
I suggest somewhere around 250-500 characters or so, though I guess it could be configurable.

## Context
To be precise I was generating a google form for people to suggest which talks they would like to attend.
This was so we can do things like schedule them to avoid clashes and make sure the most popular things have the biggest rooms.
Rather than just putting the title on the checkbox, I wanted to also include the abstract,
so people knew what some of the more "witty" titles were actually about.
But some of the abstracts were way too long, so I had to truncate them.

**Comment by rixx** [comment]
Organisers can choose to limit the length of an abstract in the CfP settings already.
![cfp_settings](https://user-images.githubusercontent.com/2657547/58476342-cb519900-8150-11e9-9f97-3d460abcd096.png)

**Comment by rixx** [comment]
Out of interest and for purposes of our UI improvements: where were you looking for this option?

**Comment by oxinabox** [comment]
I didn't setup the the CfP.
Who ever did should have set that I guess. So user error.
Possibly it should default to set?

**Comment by rixx** [comment]
I'm not sure finding a good default is possible here – pretalx is used by wildly different conferences, not all of which even ask for an abstract. But thank you for chipping in!
