### ISSUE TITLE
Tag a bugfix release

### ISSUE THREAD

**Issue by MEschenbacher** [pretalx/pretalx#704]
Hey,

I am also suffering from #623 which was fixed in commit  5a5ab54, but is not yet available in any tagged release. Are you planning on tagging one in near future or is the latest git master considered stable enough to just stick to it?

BR Max

**Comment by rixx** [comment]
We are planning to release a new version shortly, probably within the week.

**Comment by rixx** [comment]
Ah, regarding the second part of your question: I would not automatically run off `master`, no, but running a select commit with a green build status should work without problem (we do this for pretalx.com ourselves). The current commit, c3edcc7, should be a good candidate.
