### ISSUE TITLE
Add `{track_name}` as a template key for emails

### ISSUE THREAD

**Issue by glasnt** [pretalx/pretalx#705]
## Problem you are facing

I want to send acceptance emails to people across multiple tracks of my conference, and I want to ensure the email details which track they have been accepted for. 

## Possible Solution

Manually accepting waves based on tracks, but editing the template before each wave (🙅‍♀️ this could lead to many issues)

## Context

Users entered a track when they submitted, so I want to relay that information back to them in the accept email. 

Ideally this would be a template key that would be available for any email template, not just accepts.

**Comment by rixx** [comment]
Closed in ecc1c943, thank you!
