### ISSUE TITLE
Event-specific URLs are not resolving

### ISSUE THREAD

**Issue by sebastian-meier** [pretalx/pretalx#707]
## Current Behavior
If a custom colour is added and an event-specific css file is generated, the url to the css file generates an 404, while the file actually exists. The same problem exists for question-based file uploads. The file uploads work fine, but the urls for those files generate a 404.

## Expected Behavior
URLs should lead to corresponding files in the file system.

## Steps to Reproduce

1. Create Event
2. Change Colour
3. Open Event page

## Context

I would like to use a custom colour / css and i would like to let users upload abstracts.

## Your Environment

* python 3.6
* pretalx.technologiestiftung-berlin.de

**Comment by rixx** [comment]
This is an issue with your pretalx setup configuration, not with pretalx itself (we can confirm that custom CSS is working correctly). Please get in touch via support@pretalx.com if you require additional support.
