### ISSUE TITLE
API access to per-user answers

### ISSUE THREAD

**Issue by AmitAronovitch** [pretalx/pretalx#710]
## Problem you are facing

Currently, answers for submission-specific questions are available via the API using the submission resource (submission has `answers` entry)
However, I did not find any way to access per-person answers via the API (sample use case: speakers may specify a twitter handle on submission, and an app using the API should be able to show that information if available).

## Possible Solution

Either provide a "user" resource (the user model has FK in the answers model), or add a speaker-view containing that extra information.

## Context

Was trying to query the API for some answers that the speakers had provided via speaker-specific question. Since did not find how to do that, had to revert to django query via shell on the live server...

**Comment by rixx** [comment]
Yes, adding `questions`/`answers` to the speakers endpoint is the way to go here. We're happy to accept PRs on the matter. Anybody tackling this should look at how the submissions endpoints handle questions – feel free to ask if you have any questions!

**Comment by rahmonov** [comment]
@rixx can you please clarify this a little bit more? It looks like that the speakers endpoint already has `answers` property (`SpeakerOrgaSerializer`). What am I missing here?

**Comment by rixx** [comment]
You are correct – it appears I was overly quick in accepting this issue.

@AmitAronovitch As stated above, the API already exposes speaker answers for users with the appropriate permissions.
