### ISSUE TITLE
Toggle Sneak Peek

### ISSUE THREAD

**Issue by alanderex** [pretalx/pretalx#713]
## Current Behavior
https://pretalx.com/orga/event/the-event-slug/submissions/  
Click on _Sneak peek_

The request in the background returns a 404 
https://pretalx.com/orga/event/the-event-slug/**submissions/submissions**/ABCD1234/toggle_featured
returns a 404 

seems the url is errant, it should be
https://pretalx.com/orga/event/the-event-slug/**submissions**/ABCD1234/toggle_featured

## Expected Behavior
Toggle _Sneak peek_ for submission

## Steps to Reproduce

1. click 
2.reload
3. no change

## Context
Cannot update sneak peak 

## Your Environment

Safari, Chrome & Firefox on Mac

**Comment by rixx** [comment]
v1.0.1 is released, including the fix for this issue.
