### ISSUE TITLE
More expressive email addressee filters

### ISSUE THREAD

**Issue by alanderex** [pretalx/pretalx#715]
## Current Behavior

Having more *than one* filter selected in _All submissions of these types_ selected generates an email to all speakers.

## Expected Behavior
Generate Emails to subset selected in __All submissions of these types__

## Steps to Reproduce

1. Go to Mails, select _Compose E-mails_
2. Recipient groups, select one or more in _Everyone with submission(s) that have not been accepted/rejected yet_
3. Select something from _All submissions of these types_
4. Send

Note: in our case both 30 and 45 minute talks were labeled "Talks". It did work for the unique labels.

## Context

Keeping speakers speakers with submission(s) that have not been accepted/rejected yet_ 
up to date is important especially once word get around submissions have been accepted.

**Comment by rixx** [comment]
Yes, the filters you can select in the mail sending view are **or**'d with each other, not **and**ed, so this is working as intended. I'll keep this issue open as a UI issue regarding a better email sending interface, but not as a bug against the current system.
