### ISSUE TITLE
README.rst missing in latest release

### ISSUE THREAD

**Issue by hinnerkweiler** [pretalx/pretalx#718]
Hola, and many thanks for packing all the great new features into Pretalx now. I was just trying to upgrade from 0.9.0 according to the documentation on `https://docs.pretalx.org/en/latest/administrator/maintenance.html` but I keep hitting rocks. 

Apparently there is README.rst missing in the release's `tar.gz`

```
pretalx@event:~$ pip3.6 install --user -U pretalx
Collecting pretalx
  Using cached https://files.pythonhosted.org/packages/00/42/e4b7251a8b849181cee59378b4e0882fc199d0d72d24f1ece0139bed020a/pretalx-1.0.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o9fqi71g/pretalx/setup.py", line 32, in <module>
        with open(path.join(here, '../README.rst'), encoding='utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-o9fqi71g/pretalx/../README.rst'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-o9fqi71g/pretalx/
```

**Comment by sapran** [comment]
I am experiencing this issue in 1.0.0

**Comment by minusf** [comment]
the previous solution with the try/except was a bit suboptimal...

at some point `LICENSE` and `README.rst` was probably moved from `src/` one up...  `MANIFEST.in` still references these non-existing files.

**Comment by rixx** [comment]
Interesting to see who uses pretalx, maybe we should build breaking releases more often 😉

No, sorry – I'm currently running a couple of additional tests, and will then release v1.0.1

**Comment by rixx** [comment]
v1.0.1 is released, including the fix for this issue.
