### ISSUE TITLE
"lost file" for file uploaded at a Question in CfP process

### ISSUE THREAD

**Issue by kannes** [pretalx/pretalx#719]
## Current Behavior
File upload question ends with "lost file" during CfP process

## Expected Behavior
File upload question should properly store the file during CfP process

## Steps to Reproduce

1. Add a file upload question
2. Go through the CfP process
3. Browse for a file when the question comes
4. Continue

When looking at my submission (`/me/submissions/IDIDIDID`) afterwards, I see no file listed. If I browse for a file there and save, it gets uploaded and is subsequently shown.

## Context

We have a required, per submission, file upload question. If someone adds a file, it gets uploaded (according to sniffing browser traffic) but is not listed in the submission later on. In the admin view `/cfp/questions/1/` we see "filename (lost file)".

## Your Environment

v0.9.0-580-gc3edcc78

**Comment by rixx** [comment]
v1.0.1 is released, including the fix for this issue.

**Comment by kannes** [comment]
You rock, thanks!
