### ISSUE TITLE
Schedule: unassigned talks overlap with rooms

### ISSUE THREAD

**Issue by vmx** [pretalx/pretalx#729]
## Current Behavior

The "unassigned talks" bar overlaps the rooms.

![Screenshot_2019-06-18](https://user-images.githubusercontent.com/42839/59694289-abaa0f80-91e8-11e9-9a63-63b8dab4d8cd.png)

## Expected Behavior

The "unassgined talks bar doesn't overlap with rooms, so that you can drag on drop talks to all available rooms.

## Steps to Reproduce

1. Have a small screen
2. Have lots of rooms
3. Have talks to schedule
4. Try to schedule a talk to the most right room.

## Context

It makes the scheduling experience less nice if you can't drag talks into all the rooms.

## Your Environment

* Version used: c4fe92fe37ce1e433f9a3e1cf61c0567a3f88842 (+ one custom commit on top)
* Operating System and version (desktop or mobile): Desktop

**Comment by rixx** [comment]
This issue occurs if there are many rooms relative to the screen width of the visiting client, and should definitely be fixed.

As a side note, please note that you can click the header of the unassigned talk colum to minimize it and have more space available.

**Comment by rixx** [comment]
This issue is fixed in the 1.0.3 bugfix release.
