### ISSUE TITLE
Submission Type should be shown on Edit/View submission after acceptance

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#731]
## Problem you are facing
It is not easy to find out what submission type you made, after it has been accepted.

## Possible Solution
Show it on the Edit/View submission page. next to the speaker name
Or below the talk title.
As a noneditable value.
Could call it: accepted submission type at that stage.

See my great mockup:
![screenshot of what it could look like to have this shown](https://user-images.githubusercontent.com/5127634/59883099-e5774380-93ab-11e9-9dea-d4bbe335d21e.png)

## Context

While #666 solved speakers not knowing what they were accepted for
some speakers have forgotten, or not paid attention to that detail
on the confirmation page.
but it is not there.

**Comment by rixx** [comment]
Good point, thank you for your input.

If anybody needs guidance on how to add this information to the talk template, please let me know!
