### ISSUE TITLE
Include example XML file on Import page

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#733]
## Problem you are facing
I would like to use XML Import.
The Import says:

> Submit an XML file here to release a new schedule, containing exactly the talks specified in the XML file. The format is expected to be the same as the XML export provided. 

That is not enough detail for me to know what the format it.
So I though I would make an example by putting a few things in my schedule, then exporting it.
However, I can not do that without triggering a release first, which will email all my speakers.

## Possible Solution
Include an example file downloadable from the input page.
And maybe a link to the schema?

## Context
I have made a draft of my schedule in an external tool,
and I want to import in into Pretalx.
Since I can't do that via the API I need to go via XML import.

**Comment by oxinabox** [comment]
@vchuravy 
tells me that the following is the schema
https://raw.githubusercontent.com/wiki/frab/frab/images/schedule.xsd

**Comment by rixx** [comment]
You're making a good point here: We do support the frab schedule format as both an export and an import format, but it is not intuitive for the user.

We cannot provide stable documentation for this format, as it tends to change occasionally without notice ahead of time or any way to keep track of it. It would probably more honest and less jarring to relegate the import functionality to a shell command and remove it from the frontend.

**Comment by rixx** [comment]
As for other automated ways to handle this: We're still looking for funding and/or contributions to provide a writable API.

For importing the data manually, you can use the quick-schedule pages at /orga/event/<event>/schedule/quick/<submission-code>/ for more convenient import if the drag'n'drop interface does not work for you.

**Comment by oxinabox** [comment]
Ok, that seems useable.
I will create some nightmake AutoHotkey + Javascript monstrosity to use that to get my data in.
(I feel like it is saying something that this would not be the first time I have done data import into schedualling software that way.)

**Comment by oxinabox** [comment]
really, ideal for me right now would be to be able to just upload a CSV containing
```
<submissionid><roomid><start-date-time>
```

**Comment by oxinabox** [comment]
Hmm looking at the source for the frab
importer,
am I right in saying that to the fram abbreviation field, should match against the `submission_id`?


and also that if at all I do not match the expected format of frab,
it could absolutely destroy large parts of my program?

**Comment by oxinabox** [comment]
Ended up using Selenium to import everything.

**Comment by rixx** [comment]
We are very open for any and all contributions that help us build a safely writable API. But since this is a large endeavour, we cannot tackle it on our own right now, so the status quo can only be changed via community contributions.

I'm closing this issue by removing all references to the import functionality in the frontend. I had hoped that this could be useful for users, but apparently it's only harmful, so it should go.
