### ISSUE TITLE
Filter submissions by type ins schedule editor

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#735]
## Problem you are facing
Not all submissions need to be schedualled.

See how full things are on the right?
Those are mostly the pile of posters we have.
We want them in pretalx so they can go through review,
but we are not going to assign them actual place in the schedual

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/5127634/60373842-96f42580-99f9-11e9-9ff3-f0c5a46a5965.png">

## Possible Solution
 - Add an option to submission types to not have them show
 - Or; Add a filter to the unassigned talk list 

## Context

All those unassigned talks that I am not planning to assign make it hard to see the ones that I am

**Comment by rixx** [comment]
Good idea! I favor the filtering over an additional flag on the data model. This should be pretty easy to add, going off of the existing filter format UI-wise, and adding dynamic filters in the JavaScript part.

If anybody needs further guidance in implementing this, I'm happy to help.
