### ISSUE TITLE
Support short talks in schedule editor

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#736]
this was discussed but not fully resolved in https://github.com/pretalx/pretalx/issues/550

## Current Behavior
If one has items that are under an hour long, then do not display well in the scheduallinmg view,
it is infact so poor that it is hard to see the Red Alert triangle.

Once can mouse over them to see them but it is pretty difficult.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/5127634/60374498-b6d91880-99fc-11e9-9730-d06c1a1f7a33.png">

## Expected Behavior
Vertical space per hour should be doubled, possibly tripled.
I think that would strike a better balance.

Solving #734 would free up space for this.

## Steps to Reproduce

1. Add Item to Program that is <1 hour long
2. Go to schedule view

## Context
It is not practical to use the schedualling view,
I will likely  adjust my schedule in external tools and re-import.
(Nice that i have a work around for doing that related: #733)

## Your Environment

* Environment name and version: Firefox v67
* Operating System and version (desktop or mobile): Mac desktop
* Link to your instance, if in production: https://pretalx.com/orga/event/juliacon2019

**Comment by rixx** [comment]
I don't agree that tripling vertical space would be a good general approach. This would make many schedules unusably long.

**Comment by oxinabox** [comment]
Well if #734 is solved then there will be 3x as much space free, assuming a program is normally 8 hours long. 

I think even without that doubling the space is not unreasonable.

**Comment by rixx** [comment]
> Well if #734 is solved then there will be 3x as much space free, assuming a program is normally 8 hours long.

This assumption does not hold true for many conferences using pretalx, though. 14-15 hours are [not unheard of](https://pretalx.com/35c3/schedule/) for instance.

But I think from your issue phrasing that you are only refering to the backend part of talk scheduling. I guess in this case page length is less of an issue, so if anybody implements this, I'll be happy to review and discuss the solution.

**Comment by rixx** [comment]
(I think the better solution would be to offer different degrees of expansion, but as I said: I'll be happy to review and discuss any PR submitted on the topic.)

**Comment by oxinabox** [comment]
> you are only refering to the backend part of talk scheduling.
yes.

To be clear,
I've programmed conventions with  14 hour days in LiveCon and Grenadine,
Both of those platforms use over 4 times as much vertical space per hour as Pretalx.

Perhaps though a notable difference for those platforms 
is that they don't use a single long grid for the whole event,
but rather a page per day.
Which is also kinda nice for other reasons.

### LiveCon:

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/5127634/60375338-b93d7180-9a00-11e9-8a80-a2885274b4a8.png">


### Grenadine

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/5127634/60375397-face1c80-9a00-11e9-9dc8-76012e596ce8.png">

**Comment by rixx** [comment]
> Perhaps though a notable difference for those platforms
> is that they don't use a single long grid for the whole event,
> but rather a page per day.
> Which is also kinda nice for other reasons.

Oh, definitely agreed! I'd also happily work with PRs on this one, if anybody feels like providing one.

**Comment by oxinabox** [comment]
1 year later and again this has again rendered me unable to use the inbuilt scheduling software.
![image](https://user-images.githubusercontent.com/5127634/84086358-9e7cc680-a9df-11ea-8892-0df9d74625f1.png)

I am still using the API to dump everything into Trello,
then pulling it back in and doing some data mangling,
and then writing it back in by instrumenting the browser with Selenium.
The annoying part is though that i can't even do fine tuning in the Pretalx GUI, and indeed i can barely see where people have the ! conflic marker

**Comment by rixx** [comment]
I can see that this makes using pretalx frustrating for your particular use case, and I'm sorry that this is the case. Even though this is an area pretalx does not excel in, please keep in mind that this is an open source project, and we rely on community contributions for many features. If an issue remains open without a PR, that means it has not been worked on, and highlighting this frustration again will probably not help.

**Comment by oxinabox** [comment]
Yeah, I know.
I looked into changing it before.
Problem is that it is hardcoded in a few places to 1 (or maybe 2) pixels per minute.
And a lot of the rest of the display is similarly hard coded based on that assumption.
And I have no real skills in web-stuff, so it is beyond me.

I would say we would look into funding you to be able to work on this, but seems unlikely given we will be making nothing on ticket sales.
Maybe after next year.

By which point I will probably not be scheduling the program.
And so who ever comes after probably does not want to use my nightmare chest of tools to deal with this.
So maybe that's fine.
