### ISSUE TITLE
Offer to set "all day" when submitting availabilities on long availabilities

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#737]
## Problem you are facing
Some of my speakers set there availability to more or less the whole day,
e.g. setting 9am-5pm.
When a talk starts at 8:30 am or finishes at 5:15 pm,
this thus shows up as a warning on the settings page.

On the 3 times I have so far contacted a speaker asking about this,
they were completely fine with that.

I think the problem is they either:
 - Not thinking of this as a possibility
 - Or not understanding how to set all day

## Possible Solution
I see a few options:
 - Make it clearer about how to set "all day" with some kind better visual UX stuff.
 - Prompt users who select more than 6 continous hours if they mean to say "all day"
 - Give some kind of option that the conference can change what can be selected. (this seems the most work). So that rather than specifier per hour, speakers specify per Morning/Afternoon/Evening with boundries the conference specifies.

**Comment by rixx** [comment]
Thank you for your feedback. Most this ticket is not immediately actionable ("some kind better visual UX stuff" is not exactly helpful :) ).

I'm accepting it on the basis of asking users if they want to check the "all day" flag when submitting a long availability.

Side note: As an organiser, if a speaker did not input their availability to cover the very end of a day, I would probably schedule their talk regardless and adjust their availability to remove the warning.

**Comment by oxinabox** [comment]
> Most this ticket is not immediately actionable ("some kind better visual UX stuff" is not exactly helpful :) ).

Indeed

**Comment by rixx** [comment]
Having interacted with the calendar library some more, I'm declaring this out of scope for pretalx. Happy to merge a PR if anybody wants to tackle all that, but it's not something I'll be looking into adding myself.
