### ISSUE TITLE
Add a short-title field,

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#742]
## Problem you are facing
There is no bounds on the length of submission titles.

The peak-length talks at JuliaCon include:
 - “IVIVC.jl: In vitro – in vivo correlation module as part of an integrated pharmaceutical modeling and simulation platform”
 - “Heterogeneous Agent Dynamic Stochastic General Equilibrium (DSGE) Models in Julia at the Federal Reserve Bank of New York”

This makes it very hard to dislay them where there is limitted space.

(This is too late to help me now, but for next year)

## Possible Solution
Add an extra optional field for Short Title perhaps with (possibly configurable?) max length.
which is required if the main title is longer than that max length.

An alternative would be for conferences to ask it as a Question on the submission.
However, that would mean it could not be automatically used in the schedule editor/ view.

## Context

There are a number of places where a short title would be useful to display a shorter title.
 - Schedule editor  (re #736) 
 - Schedual view  (re  #550)
 - Exported PDF (#295) 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/5127634/60493210-51a75080-9ca4-11e9-89c4-f60752ebab45.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/5127634/60493318-7e5b6800-9ca4-11e9-9bbc-cf8bf57c0d17.png">

### Prior Art
 - Grenadine has this feature.
 - It is also comment in many LaTeX paper templates, wherre the short title will be displayed in the header.

**Comment by rixx** [comment]
I think it would be more in line with pretalx's existing configuration options to allow organisers to specify an upper limit on title length.

**Comment by oxinabox** [comment]
And then event organisers could add a long-title question.
(If e.g. it should match against a paper title,)
