### ISSUE TITLE
Sneak Preview and Schedule are mutually exclusive

### ISSUE THREAD

**Issue by MacLemon** [pretalx/pretalx#743]
## Problem you are facing
When a schedule `<slug>/schedule/` is activated, it's not possible to display the sneak preview `<slug>/sneak/` anymore.
When no schedule `<slug>/schedule/` is published, it's possible to view the sneak preview `<slug>/sneak/`.

Since we're using different URLs which match different cases, either one always delivers error pages which is inelegant.

## Possible Solution
While no schedule is published, a call to `<slug>/schedule/`, given any sneak preview data is available, could deliver `<slug>/sneak/` instead of an error page. This would be much more charming regarding visitors.

On the other hand, when a person visits `<slug>/sneak/`, but a sneak won't be delivered, because a schedule has already been published, a redirect to `<slug>/schedule/` seems more appropriate.

## Context
We're using `cfp.privacyweek.at` during the call for participation but, while the CfP is still active, we also publish a website `fahrplan.privacyweek.at` which is communicated to participants for finding the schedule.

Depending on orga progress currently either one will deliver an error.
This could be handled more friendly as described.

**Comment by rixx** [comment]
> While no schedule is published, a call to `<slug>/schedule/`, given any sneak preview data is available, could deliver `<slug>/sneak/` instead of an error page. This would be much more charming regarding visitors.

Agreed, this sounds like nice behaviour.

> On the other hand, when a person visits `<slug>/sneak/`, but a sneak won't be delivered, because a schedule has already been published, a redirect to `<slug>/schedule/` seems more appropriate.

This should already happen – we even have tests to show it does. Do you see different behaviour?
