### ISSUE TITLE
Files missing from distribution tarball

### ISSUE THREAD

**Issue by xanderio** [pretalx/pretalx#746]
## Current Behavior
The `LICENSE` and `README.rst`are missing for the distribution tarball.

## Steps to Reproduce

1. Download tarball from `https://pypi.org/project/pretalx/1.0.3/#files`
2. extract tarball
3. see files are missing

## Context

While building a FreeBSD port i notices that these file are missing.

**Comment by rixx** [comment]
Thanks for the report!
