### ISSUE TITLE
API: reviews endpoint contains duplicates

### ISSUE THREAD

**Issue by alanderex** [pretalx/pretalx#754]
## Current Behavior
GET /api/events/{event}/reviews  returns **some** reviews more than once.

## Expected Behavior
Each review should be only returned once.

## Steps to Reproduce

1. GET /api/events/{event}/reviews
2. continue with url from 'next' of result of 1. until 'next' is ''

The following calls all returned the review id 9519
https://pretalx.com/api/events/pyconde-pydata-berlin-2019/reviews/?limit=25&offset=125 
https://pretalx.com/api/events/pyconde-pydata-berlin-2019/reviews/?limit=25&offset=375 
 https://pretalx.com/api/events/pyconde-pydata-berlin-2019/reviews/?limit=25&offset=1300

## Context

We have to deduplicate the reviews, the issue is not obvious.  
We only found this bug coincidentally. 
Not too many reviews were affected.

## Your Environment

Requests via API calls with `requests`, shouldn't matter here anyway.

**Comment by rixx** [comment]
Thank you for reporting this issue! I pushed a fix, which is also rolled out on pretalx.com. It will be included in the next bugfix release (1.0.4), and the next minor release (1.1.0).
