### ISSUE TITLE
Display accepted speakers / talk count

### ISSUE THREAD

**Issue by alanderex** [pretalx/pretalx#757]
## Current Behavior

We have one talk accepted but 
https://pretalx.com/orga/event/pyconde-pydata-berlin-2019/speakers/?q=&role=true
returns 50 speakers

Narrowing down the search for the speaker with name
https://pretalx.com/orga/event/pyconde-pydata-berlin-2019/speakers/?q=mariatta&role=true
returns 1 result but Talks is displayed as 0 although the only talk by this person is accepted

## Expected Behavior

1. return only one speaker
2. talks column should display 1

## Steps to Reproduce

1. Go  to Speakers
2. Select "Speakers" from dropdown
2 (2nd case) add "mariatta" in search field
3. click "search" button

## Context

Keep track of how many speakers we have at the conference.

## Your Environment

Chrome / Mac (unlikely to be relevant)

**Comment by rixx** [comment]
I believe talks are only counted as talks once they have been confirmed by the speaker. I'm not sure we should change that behaviour, to be honest.

**Comment by alanderex** [comment]
Unfortunately I can't confirm this behavior, we have 'accepted' and 'confirmed' submissions, still Talks are all 0.

https://pretalx.com/orga/event/pyconde-pydata-berlin-2019/speakers/?q=&role=true
also includes speakers that have no accepted talk. 
AFAIR these speakers do have accepted submission at other conferences using Pretalx.

**Comment by rixx** [comment]
Thank you! 🐍
