### ISSUE TITLE
Review: make it more obvious that your comment is submitted

### ISSUE THREAD

**Issue by tabascoeye** [pretalx/pretalx#758]
## Problem you are facing
When in the review pane of a talk that nobody else has reviewed yet, even after submitting your point value and comment, there is still a sentence saying "nobody has reviewed this talk yet" in the place where comments form other reviewers would be.
This is pretty irritating and doesn't make it clear if your submission was accepted.
In the talk list, the number of reviews is correct however, showing a "1" if you're the only reviewer so far.

## Possible Solution
Either place the submitted comment in the spot where other review comments are placed so that it looks more consistent or at least change the text "nobody has reviewed" to something like "only you have reviewed so far"

**Comment by rixx** [comment]
The sentence says "Nobody **else** has submitted a review yet.". I'm not sure we need to change that.
