### ISSUE TITLE
Deal with changing time zones

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#766]
When organizers change the event timzone, we can either keep all talks at their configured time, which will move them in their time relative to the event time zone – or we can move all talks so that their relative time stays the same (e.g. 10am remains 10am).

Currently we do the first of these things, but I'm afraid the second would be more practical.

**Comment by vmx** [comment]
I needed exactly that and wrote a script to do that. This might help someone working on that feature: https://gist.github.com/vmx/842af29b8e40814720be4799f1ccad36

**Comment by insacuri** [comment]
I'll take a looksee
