### ISSUE TITLE
Per-speaker answers are duplicated and inconsistent in the API

### ISSUE THREAD

**Issue by oskar456** [pretalx/pretalx#770]
## Current Behavior
When a per-speaker question is asked during the CfP, it is actually stored in multiple instances – one for every submission. When querying for the answers via speaker API, multiple instances of the same answer is returned. What's worse, when the speaker changes the answer in their profile, not all answers get updated so two different answers are returned by the API. It is hard to tell which one of them is correct.

## Expected Behavior
Per-speaker answers should be visible only once.

## Steps to Reproduce

1. Setup an event with per-user question
2. Submit several submissions using one user accout
3. Query user's answers using the API endpoint `/api/events/{event}/speakers/{speaker}`
4. See number of duplicate answers
5. Try to change the answer in the user's profile
6. See how some answers changed and some not

## Context

I'm trying to get a simple sheet with speaker names and answers they answered (like T-shirt size). I didn't find any output like this in the app so I'm trying to get the data out of the API. It looks like it is not that easy.

## Your Environment

* Version used: 1.0.3 (with [minor patches](https://github.com/LinuxDays/pretalx))
* Link to your instance, if in production: https://pretalx.linuxdays.cz/

**Comment by rixx** [comment]
Absolutely a bug, thank you for reporting. We try in pretty much all places to deduplicate and make sure every speaker/question combination is stored once for speaker answers, so we must've introduced a regression somewhere.

**Comment by rixx** [comment]
It looks to me like this issue has to be fixed already – but I introduced a test that makes sure that a repeat submission does not introduce a second answer object. This should hopefully guard against regression.
