### ISSUE TITLE
Allow organisers to leave a public comment with a release

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#772]
This comment would then be shown next to the list of changes, probably before.

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx allows organisers to schedule events, and then release public versions of these schedules. It would be great to be able to leave a note on these schedule changes.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

The Schedule model is in `pretalx/schedule/models/schedule.py`. Add a new nullable field called `comment`, then create a migration with the `makemigrations` command, and apply it with the `migrate` command.

Next, you'll want to include this field in the organiser area when releasing a schedule. Add it to the `fields` list of `pretalx.orga.forms.schedule.ScheduleReleaseForm`, and include it in `pretalx/orga/templates/orga/schedule/release.html`.

Finally, make sure this text is shown in the public changelog (`pretalx/agenda/templates/agenda/changelog.html`) and RSS feed at `pretalx/agenda/templates/agenda/feed/description.html`.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by rahmonov** [comment]
Do you think it should be a `CharField` or a `TextField`?

I would think that comments should be a `TextField`. However the form kinda suggests that it should be a CharField because the form has an inline layout. Ignoring the styles, is the following something like you would expect?

![image](https://user-images.githubusercontent.com/9026972/77230852-927b2880-6b97-11ea-9e1c-845c61659917.png)

**Comment by rixx** [comment]
Hmm, you're right, I'd suggest using an I18nTextField, and offering the input above the submit bar.

**Comment by rahmonov** [comment]
@rixx could you please take a look? If this looks good, I will fix the unit tests. Quite a bit of them are broken because of the changes to `release_schedule` and `freeze` methods.
