### ISSUE TITLE
2 submissions from the same speaker at the same time (schedule interface)

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#777]
## Current Behavior

A speaker proposes two submissions, they are both accepted, the schedule interface doesn't display a warning if they are happening in parallel in two different rooms.

## Expected Behavior

Warning on the agenda that a speaker is expected to give two talks in parallel.

## Steps to Reproduce

1. Same speaker, two talks, accepted
2. Two rooms going on parallel
3. Set the two talks at the same time in the different rooms

I'd expect a warning the similar as when the talk is added at a time the speaker is unavailable.

## Your Environment

* Version used: v1.0.3

**Comment by rixx** [comment]
Absolutely, pretalx should check that. Happy to take a PR!

**Comment by DavidS48** [comment]
I'm happy to have a look at this.

**Comment by Rafiot** [comment]
\o/
