### ISSUE TITLE
Changing/Testing Custom SMTP Settings Fails

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#786]
## Current Behavior

Changing the STMP settings fails with:

>  An error occurred while contacting the SMTP server: __init__() missing 1 required positional argument: 'sender' 

![Bildschirmfoto_2019-09-26_01-49-17](https://user-images.githubusercontent.com/3611273/65647742-dd105380-dfff-11e9-83ed-85de3e7088d4.png)

This seems to be a Python issue, not something related to my email server.

## Expected Behavior

Change sender address, STMP server, username and password.

## Steps to Reproduce

* call https://pretalx.com/orga/event/sotm2019-at/settings/mail and try to change SMTP settings
* use custom STMP server
* set username and password
* click on "Save and test custom STMP connection"

## Your Environment

* pretalx.com, event sotm2019-at

**Comment by rixx** [comment]
Congratulations, you found a bug! I'll look into it tomorrow.
