### ISSUE TITLE
Expose URLs of resources via API

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#787]
## Problem you are facing

We (State of the Map 2019) use [our schedule renderer](https://github.com/fossgis/pretalx-scripts/tree/master/schedule_renderer) to build the programme for the website (table and detail pages) because we prefer a different layout than the one provided by Pretalx. The renderer uses various endpoints of the Pretalx API. Unfortunately, the API does not expose resources (the file uploads) which are useful to attach slides to the talks after the conference.

I would like to get URLs to download the resources using an API call.

## Possible Solution

There are two possible solutions. I prefer the first option because it is simpler but it does not matter whether I add another API call in my toolchain or not.

* extend `/talks` endpoint
* add new `/resources` endpoint

@rixx What do you prefer?

**Comment by rixx** [comment]
I'm always *very* hesitant to extend the `/talks/` endpoint – it's bloated and slow already, to my feeling. But I would agree that adding another endpoint wouldn't make a lot of sense here, and would only be frustrating to API clients.

**Comment by rixx** [comment]
For reference: The argument for the `/talks/` endpoint applies mostly because it is often used in its list form, or via the `/schedule` view even, and I'm torn between its convenience and it's speed.

**Comment by rixx** [comment]
✅ developed
✅ tested
✅ documented
✅ deployed on pretalx.com
