### ISSUE TITLE
password reset emails don't get sent

### ISSUE THREAD

**Issue by zoff99** [pretalx/pretalx#789]
## Current Behavior
on password reset emails do not get sent, and do not show up in the history of sent emails

## Expected Behavior
on password reset emails DO get sent, and show up in the history of sent emails

## Your Environment

* Version used: pretalx · v1.0.3 (using external SMTP server with authentication)
* Environment name and version (e.g. Chrome 39, python 3.5): any browset
* Operating System and version (desktop or mobile): any
* Link to your instance, if in production: https://pretalx.tox.zoff.cc/toxcon2019/cfp

**Comment by rixx** [comment]
Password reset emails do not show up in the history of sent emails for security reasons. They need to work via email alone.

Does your pretalx instance send email generally? Have you checked your email settings (the global ones, not the ones per event)?

**Comment by zoff99** [comment]
@rixx yes other emails get sent ok (like changed talk times, or speaker invites)

**Comment by zoff99** [comment]
password reset emails do not work. no matter if the user does it himself, or the admin does it

**Comment by rixx** [comment]
Password reset emails are not sent in an event context, so they will not show up in the email list. I think this is correct behaviour.

Password reset emails use the *global* email configuration, not that of any event (which is what your examples do, changed talk times, or speaker invites).

I have just confirmed that password resets work on pretalx.com, and the test suite confirms this, too, so this must be a configuraiton issue on your side. Please check your [email config section](https://docs.pretalx.org/administrator/configure.html#the-mail-section) for accuracy.

**Comment by zoff99** [comment]
```
Mails
Host: xxx.xxx.xxx
Port: 587
User:
Password: No email password has been set.
```

use and password never show up, yet they are set in /etc/pretalx/pretalx.cfg

**Comment by rixx** [comment]
Ah, it seems the administration interface is buggy and never shows user/password data. Fixed in e6fd9c4d.

**Comment by zoff99** [comment]
ah cool.
how can i test if it works?

**Comment by rixx** [comment]
This change was only visual and should not have changed the sending of password reset emails. I really don't know why they won't send for you, as I've never seen this issue either in tests or on pretalx.com.

**Comment by zoff99** [comment]
my username and password have special chars in them. do i need single quoutes or double quotes in the config file?

it is not clear from this doc:
https://docs.pretalx.org/administrator/configure.html#the-mail-section

**Comment by zoff99** [comment]
the info box is already sort of wrong. it says:
```
Settings have been loaded from: /etc/pretalx/pretalx.cfg
```

but the settings are not updated from the config file until the pretalx service is restarted

**Comment by rixx** [comment]
Settings are only loaded on startup. If you think this requires clarification, I'll happily merge a PR.

**Comment by zoff99** [comment]
ok. thanks for the help.
now i was able to have the config that email sending work.
