### ISSUE TITLE
Plugin Idea: Stagemanager tools

### ISSUE THREAD

**Issue by JanKoppe** [pretalx/pretalx#790]
## Problem you are facing

At the 35C3 chaos-west stage, we used pretalx for the CfP and talk scheduling process, which worked great. What did not work so great was on-site organisation of speakers and stagemanagers/heralds.

## Possible Solution

A plugin that provides
* configurable "checks" to each event. That way people can freely define checkboxes and notes like "speaker present", "technical requirements discussed", etc.
* A webinterface for on-site stagemanagers
  * view relevant information (upcoming events/speakers/contact information)
  * easily access/modify such these configurable checks/notes
  * needs a mobile-view! tabled/smartphone
  * some sort of low-friction authentication?
    * e.g.: stagemanagers scan a QR code that sends them to the pretalx-instance including some time-based token allowing them access to the required information.
* A webinterface for autonomous information display
  * Public information display for schedule at the stage
  * Remaining time, cues for speaker (screen at edge of stage)

## Context

Making sure that speakers checked in (are at event), are reminded/shown the location of the stage shortly before the talk, and possible technical requirements that are more individual are things that are important for a smooth operation.

Last year we had a huge scramble just before the talks started to check in with speakers and aquire information, no way to really "tick-off" those requirements and no clean way to relay this information to all the stagemanagers that changed regularly. In the end we kept a google spreadsheet for that and stagemanagers asked us again and again, because we (humans) became the only source of such information.

Also, at the event I've quickly cobbled together a small info-dash showing us upcoming speakers in realtime, sourced from the pretalx iCal export. Having this in a more accessible, reactive webinterface would be a great help as well. The audio/video/light people really loved this for a quick glance ("enough time to make a mate-run before the next speaker?") 

Code: https://gist.github.com/JanKoppe/a22f59f21b36b1a21e564021c0d3a28f

---

I now realize that the scope for this plugin is quite huge. This is a lot of work, and I'm not really involved in existing Pretalx development. Before I jump in head first and disregard any other development efforts that I have not yet noticed, I want to check in with you:

Is this interesting for pretalx? Do you think splitting this up into smaller modules makes more sense (I'm almost certain that the information displays for speaker and managers could/should be split out)? Is there any development already in such a direction that I could maybe help with? Anyone willing to participate?

I've started a repository for that at https://github.com/JanKoppe/pretalx-stagemanager and will start some work in the coming days.

**Comment by rixx** [comment]
I don't quite see why this should be a plugin and not core functionality. At the same time, I think much of this belongs to #197, doesn't it?

**Comment by JanKoppe** [comment]
Core functionality would be even better, yes :) Didn't see #197 before, there's a good overlap there, yes. The only thing missing there is the information display, but this should just be split out into a separate, standalone issue.

Will close this one, transfer the information display into a new issue and probably get to work on #197 this weekend!

**Comment by rixx** [comment]
Cool, that's great to hear! Feel free to get in touch here or via r@rixx.de if you want to discuss details.
