### ISSUE TITLE
Submissions made by orgas should not be constrained

### ISSUE THREAD

**Issue by oskar456** [pretalx/pretalx#793]
## Problem you are facing

As an orga, you would like to some content into the schedule which is actually not a talk (like Welcome, Farewell or a Social event). Such event should not need to have an abstract or a speaker even though such is required for other submissions.

Possibly related issues: #6 #621 

## Possible Solution

Submissions created by orga interface should allow not to fill even fields that are otherwise required. It should be also possible to have a talk without any speaker so orgas don't have to invent fake speaker accounts [like this](https://cfp.loadays.org/2019/speaker/FLCTJZ/).

## Context

We've used Pretalx for the first time for organising [LinuxDays](https://www.linuxdays.cz/2019/en/) in Prague. It worked pretty well but we've discovered a few rough edges.

**Comment by rixx** [comment]
I'm sorry, but I'll have to disagree with this issue. Submissions are there to handle actual content submissions. #621 will upon implementation provide a different way to add breaks, and I agree that it's unfortunate that this is not implemented yet. At the same time, we cannot use it to make the submission interface less consistent, sorry. Any help with this should go towards pushing #621 further along.

**Comment by rixx** [comment]
The problems of dealing with this would not be worth it: If you, as organiser, create an incomplete submission for a speaker, and they want to edit one part of it, they will find themself forced to edit all insufficient parts of it, which makes for very confusing experiences.
