### ISSUE TITLE
Add tool to monitor feedback

### ISSUE THREAD

**Issue by oskar456** [pretalx/pretalx#794]
## Problem you are facing

We've successfuly finished our first event using Pretalx. On the orga area dashboard, the last bullet is lit and its tooltip says that we should monitor incoming feedback.

Right now we have 80 talks. It is virtually impossible to monitor feedback in all the talks one by one. 

Instead, I look directly into the database like this:

    select review, title from submission_feedback f join submission_submission s on f.talk_id = s.id

## Possible Solution

There should be a page summarising all incoming reviews for all talks.

**Comment by rixx** [comment]
Sounds like a good contribution for first-time contributors (or anybody else, of course).

**Comment by michalpirchala** [comment]
Hello, I will grab this one. Can I have some additional info? What should it look like, what information sould be included etc.

**Comment by rixx** [comment]
I think the best thing to do would be to add a list of feedbacks received, as stated in the original ticket. It would be available to organisers in the same way the list of all submissions is available.

I'm not sure which level of information/guidance you are looking for, so feel free to ask for clarification!

**Comment by michalpirchala** [comment]
Is some demo database available? The system is pretty complex and as I need to go through complet event process, it would be nice to have already filled up data.

**Comment by rixx** [comment]
You can import another event's export by running the `import_schedule` command on their XML export. Any XML would do, for instance that of [PyCon UK](https://pretalx.com/pyconuk-2019/schedule.xml).

**Comment by michalpirchala** [comment]
Hello, so far I got this:
![Screenshot from 2019-10-17 18-53-01](https://user-images.githubusercontent.com/32014467/67030395-9e0d8380-f10f-11e9-9a68-46ca9b3baf30.png)

As I order feedbacks by talk.talk_id, they are "grouped" together and it is not necessary to have talk/submission title above every feedback. I would like to have the title just once and then all associated feedbacks to this talk. Normally I would do it in template cycle, comparing talk id to talk id in previous cycle. And if this changes, show new talk title. But this seems almost impossible in Django templating system, as it does not support assigning and changing variable values. Any tips?

You can check the commit [here](https://github.com/michalpirchala/pretalx/commit/b452c8d941f213a9cb5cc8f51e664a04295e92d6)

**Comment by michalpirchala** [comment]
And maybe it should be sorted by id, so you can still easily check the latest feedback.

**Comment by rixx** [comment]
You should be able to iterate over `talk.feedback.all` in the template if you base the view on the Submission objects instead of the Feedback objects.

**Comment by michalpirchala** [comment]
But I will not be able to paginate over them and it will not be easy to **monitor new feedback** - I think that's the main point of this issue. So maybe we should order just by id to show the latest feedback at the top.

**Comment by rixx** [comment]
You could still order by the latest feedback entry, if you'd like, that's somewhat independent of the other question. You'll have to decide between pagination and grouping usually goes hand in hand, though, so if you want to group by submission, you should also paginate by submission, imo. If you don't want to do that, you can of course first paginate by feedback, and then group by submission – it would be easiest to do that in the view, not in the template.

**Comment by rixx** [comment]
Closed via #798
