### ISSUE TITLE
Add greek translation

### ISSUE THREAD

**Issue by madonius** [pretalx/pretalx#799]
## Problem you are facing
There is no greek translation

## Possible Solution
Add greek translation

## Context
There is no greek translation. This makes the app inaccessible to humans who do speak greek and not german, french or english

**Comment by rixx** [comment]
I don't think opening an issue for every missing language is productive – but we definitely welcome PRs with new langauges for pretalx!

**Comment by madonius** [comment]
This was meant as an issue to reference in the PR. But makes sense :)
