### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2' when setting up development environment

### ISSUE THREAD

**Issue by orlando** [pretalx/pretalx#803]
## Current Behavior
When running `tox -e dev manage.py migrate` after configuring `pretalx.cfg` to use postgresql, it fails to find `psycopg2`

After installing psycopg2 with `pip install psycopg2-binary` it still fails

## Expected Behavior
When running `tox -e dev manage.py migrate` after configuring `pretalx.cfg` to use postgresql, it should complete without errors.

## Steps to Reproduce

1. Setup dev environment following https://pretalx.readthedocs.io/en/latest/developer/setup.html 
2. Configure `pretalx.cfg` to use postgresql as database
3. Run `tox -e dev manage.py migrate`

## Context

This is the first time trying to set up the development environment and couldn't find a solution searching in this repo issues. Anything that can set me in the right path is appreciated

## Your Environment

* Version used:
* Python 3.7.5
* OSX High Sierra

**Comment by rixx** [comment]
If you want to use PostgreSQL in your development setup, I'm afraid our tox.ini is not equipped to do that. It would be easiest if you created a virtual environment and used that instead of tox.

Why are you looking to set up the development environment with Postgres, out of curiosity?

**Comment by orlando** [comment]
Hello @rixx,

We are starting working on customizing Pretalx for an upcoming conference and the idea is to use the same stack for development as we do in production.

I'll do some research on how to set up a virtual environment for Pretalx. If you can point me to some resources on how to do this I'll really appreciate it.

Thanks!

**Comment by rixx** [comment]
Ah, that's good to hear – if you're free to share what your modifications are, I'm always interested!

For a virtualenv, you can use `python -m venv .env` to create a `.env` directory with the required isolation. You enter the environment by running `. .env/bin/activate` – all further `python` and `pip` invocations will run in that context and will not pollute your global system. (pretalx shows you your current python binary path on startup, so you can use that to check). `deactivate` lets you leave the context again.

Once you are in the virtualenv, go to the `src` directory, and run `pip install -e ".[dev]"`, which will install pretalx (as editable package, so changes will be picked up), and its regular dependencies plus dev dependencies.

Hope this helps!

**Comment by orlando** [comment]
@rixx Awesome thanks for the instructions, this is really helpful.

Our idea is to make all of our customizations available as plugins and release them on Github, I'll reach out when we have more to share since we are just starting with the work.

Thanks again!
