### ISSUE TITLE
Add optional icon to submission type

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx#807]
Currently, you cannot tell a talk's submission type by looking at the schedule. Often this is intentional, since submission types can be used to provide default lengths, and nobody needs to see if a talk was submitted as a long talk or a short talk.

It may be a problem, for example, when submission types are used for workshops or other presentation types that are different. Offering to display an icon next to the title might help here (and was requested by users.)

**Comment by karina-klinkeviciute** [comment]
hey, can I take this?

**Comment by rixx** [comment]
Absolutely! This has a bit less of a description than other issues, so just ping me if you have any questions.

**Comment by rixx** [comment]
Closed now that tracks are easier to use.
