### ISSUE TITLE
Filename of uploads cannot contain non-ASCII characters

### ISSUE THREAD

**Issue by hnzlmnn** [pretalx/pretalx#811]
## Current Behavior

When uploading a file that contains non-ASCII characters within a submition, a `UnicodeEncodeError` occurs as it cannot be converted to an ASCII string.

## Expected Behavior

The non-ASCII characters should either be replaced or just ignored.

## Steps to Reproduce

1. Create a CfP that allows uploading of resources
2.Try to upload a file whose filename contains non-ASCII characters "ä", "ö", "ü", "é", ...
3. Go to next step
4. Look at the error page

## Context

An attendee tried to upload a file that contained a "é"

## Your Environment

* Version used: v1.0.3
* Environment name and version (e.g. Chrome 39, python 3.5): python 3.6

## Stack Trace
```
[...]
File "[...]/python3.6/site-packages/pretalx/common/mixins/views.py", line 240, in post
  self.storage.set_step_files(self.steps.current, self.process_step_files(form))
File "[...]/python3.6/site-packages/formtools/wizard/storage/base.py", line 116, in set_step_files
  tmp_filename = self.file_storage.save(field_file.name, field_file)
File "[...]/python3.6/site-packages/django/core/files/storage.py", line 51, in save
  name = self.get_available_name(name, max_length=max_length)
File "[...]/python3.6/site-packages/django/core/files/storage.py", line 75, in get_available_name
  while self.exists(name) or (max_length and len(name) > max_length):
File "[...]/python3.6/site-packages/django/core/files/storage.py", line 310, in exists
  return os.path.exists(self.path(name))
File "[...]/python3.6/genericpath.py", line 19, in exists
  os.stat(path)
```

**Comment by rixx** [comment]
You have removed the interesting part of the stack trace, namely the actual exception!

Regardless, it's true that pretalx assumes that the underlying file system can handle UTF-8 filenames. Since the year is 2019, I'd say tht's not a bug, but I'll add a note to our administrator documentation to this regard.

**Comment by hnzlmnn** [comment]
I just added the full traceback. Also, we tested unicode support of the fs using the python env:
```
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> import os
>>> os.stat("/tmp/äöü")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/äöü'
```

Seems like python and the fs do not have a problem with the unicode filename... Any ideas?

**Comment by rixx** [comment]
Did you use a Python shell in the same environment as pretalx is running? Eg it may be that it's just the pretalx user's shell/locale config that is messing things up.

**Comment by MEschenbacher** [comment]
As it turns out, the pretalx user did not have set the correct locales although `sys.getdefaultencoding()` returned the correct `utf-8`. Thanks for the help!
