### ISSUE TITLE
I can't copy my old review comments

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#813]
# Current Behavior

Open the reviews tab of a talk after the end of the review and try to copy a review text you wrote back then. I cannot select the text in order to copy it.

![cannot-copy](https://user-images.githubusercontent.com/3611273/69248985-7f3a5b00-0bad-11ea-8865-8e4a423d7663.png)

## Expected Behavior

I should be able to select the text in order to copy it onto the clipboard.

## Steps to Reproduce

1. pretalx.com, fossgis2019 (a conference in spring, review ended in November 2018)
2. Go to https://pretalx.com/orga/event/fossgis2019/submissions/UFSQKT/reviews/ (logged in as Nakaner)
3. Try to copy my review text.

## Context

Sometimes talks are submitted a year later a second time. I would like to copy my review to reuse/cite it.

# Environment

Firefox 70.0.1, Linux amd64

**Comment by rixx** [comment]
Should be fixed and deployed, thank you for reporting it!
