### ISSUE TITLE
Yes/No question as a Radio button

### ISSUE THREAD

**Issue by orlando** [pretalx/pretalx#814]
## Problem you are facing
Right now Yes/No questions are rendered as a checkbox. If you need to require an answer for a question from users specifically answer No, we can't.

## Possible Solution

Instead of rendering these as Checkboxes, we should render them as Radio buttons. 
Ex
![image](https://user-images.githubusercontent.com/849872/69262942-f3fb9e00-0b89-11ea-861b-739ecc0834ed.png)

## Context

Have a Yes/No question rendered as a Radio button

Some questions we need for users to explicitly answer either Yes or No

**Comment by rixx** [comment]
Sorry, but that won't be useful for other cases, such as `[x] I accept the terms and conditions`.

Instead, please create a choice question with the options "Yes" and "No" if you want to permit both options. They will render as radio buttons.

**Comment by orlando** [comment]
@rixx I tried that but were rendered as a dropdown. I'll double-check to see if there's an option to make it as a radio button

**Comment by rixx** [comment]
Hm, my mistake, it seems you are right.

I think instead of an option, we could follow the pretix lead and introduce an additional question type that is a Yes/No question, with radio inputs.

**Comment by rixx** [comment]
My mistake, it seems you are right! I think offering Radio inputs is better UI in nearly all cases here, so let's do that by default on "Choose one from a list" questions.

**Comment by orlando** [comment]
Thanks!

**Comment by rixx** [comment]
That's a good point, but I still disagree on the additional setting. Settings fatigue is a thing, and I'd rather provide a sensible default than force users to configure a bunch of things like these. I think displaying up to three options as radio buttons, and anything over that as dropdown seems sensible.

**Comment by benabraham** [comment]
@rixx As a UX designer I agree, that sensible default is a great thing. But you have to be sure you’re making the right choice for the users. That is not easy. If you’re not sure, please let users decide what they want to show in their form and don’t force your opinion on them.

There is no rule in UI design that anything over 3 items should be a dropdown. Yes, there are situations when it’s the right choice but there are many more, when much more items can be shown and it’s a better design choice for the situation.

Google Forms for example has exactly that choice (and many others) and I don’t see it as a cause of `setting fatigue`. It‘s well designed, icons help with understanding, there are sections…

![image](https://github.com/pretalx/pretalx/assets/334494/352d429d-31cc-465e-9a26-f7d5cdf6a248)

As a developer I understand that your solution is much easier one. But that doesn’t necessarily mean the best one.

Just my 2 cents.

**Comment by rixx** [comment]
> I haven’t expected to change anything.

Ah right, sorry for the misinterpretation.

> I know how OSS works but I have a community conference to organize with CfP launching in days which means I don’t have time to take on more work and PR isn’t probably a way to change anything quick enough, so it would matter to our event.

Sure, when it's very urgent, I can't guarantee that a PR would make it in time. However, you can always choose to create a fork, where you have full creative control. :)
