### ISSUE TITLE
Reducing how often a talk is held causes orphan talks in "unassigned talks"  

### ISSUE THREAD

**Issue by hinnerkweiler** [pretalx/pretalx#816]
## Current Behavior
Reducing the amount of how often a talk can be held is not reflected in "unassigned talks" after a talk is confirmed for scheduling. Talks can be scheduled more often than available.

## Expected Behavior
Remove unassigned talks when number of assigned + unassigned talks is larger than possible number of talks.
(Or mark talks when number of assigned talks became larger than available talks like when a talk is scheduled at a time the speaker is not available))  

## Steps to Reproduce

1. create a talk with multiple occurrences (e.g. 5) and confirm for scheduling
2. schedule all occurrences in program editor 
3. reduce how often a talk can be held in talk's settings (to e.g. 3)
4. pull two scheduled talks back to "unassigned talks"

(steps 4 & 3 can be done in random order with same result)
## Context

I have a multiple day event and scheduled some talks possible on all days in the first Program draft. Now a speaker is not available at all days anymore and the number of possible talks was reduced accordingly. Removing two of the talks from the program they now clutter the "Unassigned Talks" panel and confuse co-workers and me probably in a few weeks too.

##Workaround: Setting the talk back to "submitted" removes it entirely from the program and "confirming" it again will make the right amount of talks available in the editor. However, this is causing canellation mails to the speaker.     

## Your Environment
* Version used: pretalx v1.0.4

**Comment by hinnerkweiler** [comment]
just saw related https://github.com/pretalx/pretalx/pull/580#issuecomment-460829939. looks like this is only called when the amount is increased and more talks become available.

**Comment by rixx** [comment]
Definitely a bug, I thought this was covered under [these lines](https://github.com/pretalx/pretalx/pull/591/files#diff-2581c8389b4980121e47668fb93a1f6bR318-R339).
