### ISSUE TITLE
How to install plugins on production?

### ISSUE THREAD

**Issue by orlando** [pretalx/pretalx#817]
## Problem you are facing
The documentation doesn't specify how to install plugins in a production environment. Another question that I have is what are the steps to deploy a custom fork to production. Sorry, I'm sure this is not the place to ask questions but I couldn't find a better place to do it.

We have this need now but I'm having a hard time to figure it out. I haven't deployed python apps directly to a VPS before.

## Possible Solution
I can open a PR adding this to the docs after defining the best approach to do this. The idea is to add how to:

- Install and enable a plugin in production
- Deploy a specific branch or a fork of Pretalx

## Context

Installation a plugin on production and deploying a fork or a specific branch of pretalx 

We need some customizations like adding extra steps to the CFP wizard.

**Comment by rixx** [comment]
Production-ready plugins should be installed using pip. E.g if you wanted to use [pretalx-media-ccc-de](https://pypi.org/projects/pretalx-media-ccc-de), you'd install it from PyPI using `pip install pretalx-media-ccc-de`.

Take care to run migrations and follow the other steps involved in an [update](https://docs.pretalx.org/administrator/maintenance.html#updates).
