### ISSUE TITLE
Incorrect count of talks which I need to review

### ISSUE THREAD

**Issue by britiger** [pretalx/pretalx#821]
## Current Behavior
In our FOSSGIS instance some reviewers have an incorrect number of talks which they have to review. The number of open reviews is shown on page Review on top. The number can also be lager than existing talks. If I review one talk the number of talks to review to made decreases by one or most more talks. If I reload the page sometimes the number of talks to review is increased.

## Expected Behavior
show correct count of unreviewed talks.

## Steps to Reproduce

I don't know.

## Context

At the beginning of my reviews everything was fine. The Problem starts after more and more reviewers made a review. I don't found a unreviewed talk I already reviewed so it seams to be only a wrong count in database. After a second person starts reviewing talks the number of open talks most decreased by two in the infobox. 
The Number of total talks and already reviewed talks on a detailed page is correct. After I finished all reviews, the Infobox on top of page Review shows correct that I don't need to review any more submissions (Du hast keine Einreichungen mehr zu bewerten!).

## Your Environment

* Version used: see instance 
* Environment name and version (e.g. Chrome 39, python 3.5): chrome/firefox no difference.
* Operating System and version (desktop or mobile): linux/windows no difference.
* Link to your instance, if in production: https://pretalx.com/orga/event/fossgis2020/

**Comment by rixx** [comment]
Definitely sounds like a bug. If anybody can come up with steps to reproduce it, that would help a lot in getting a fix in!

**Comment by thomersch** [comment]
I got the same issue. 
<img width="924" alt="Screenshot 2019-11-26 at 15 17 41" src="https://user-images.githubusercontent.com/948605/69641142-f1a0b480-105f-11ea-9d43-0e4b070ca015.png">

It says 227 to go, which is more than total submissions. In the single talk review view it displays the correct progress.
