### ISSUE TITLE
Cannot copy from input and textarea fields of sent emails

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#827]
## Current Behavior

A user cannot copy from input or textarea fields of sent emails, e.g. https://pretalx.com/orga/event/fossgis2020/mails/11616/

## Expected Behavior

Copying should be possible but editing not.

## Steps to Reproduce

1. Sent an email.
2. Go to "sent messages", open that email.
3. Try to select text in the message body or any header field (Subject, To, …).

## Context

See #813 

## Your Environment

* Firefox 70.0.1, Linux amd64
* pretalx.com

**Comment by rahmonov** [comment]
Hi @rixx. Can I take this? 

What do you think is the right way to approach this? Add a `read_only` to kwargs and based on that make the field editable, like in #813?  

Thanks!

**Comment by rixx** [comment]
Yup, feel free to take this one!

The read_only property should already be present, so you should be able to use it directly!
