### ISSUE TITLE
Typ "möglich" statt "nötig"

### ISSUE THREAD

**Issue by mseibert** [pretalx/pretalx#832]
## Current Behavior
Meldung (falsch): "Soll das Passwort dieser Person wirklich zurückgesetzt werden? Eine Anmeldung wird nicht mehr nötig sein, ohne ein neues Passwort zu vergeben. Die E-Mail wird an diese Adresse gehen: mail."

## Expected Behavior
Meldung (falsch): "Soll das Passwort dieser Person wirklich zurückgesetzt werden? Eine Anmeldung wird nicht mehr möglich sein, ohne ein neues Passwort zu vergeben. Die E-Mail wird an diese Adresse gehen: mail."

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: v0.9.0.2s
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome current
* Operating System and version (desktop or mobile): Mac OS
* Link to your instance, if in production: https://talks.seibert-media.net/orga/event/erpnext2020/speakers/24/

**Comment by rixx** [comment]
Ups, da hat der Übersetzer wohl geschlafen. Danke!
