### ISSUE TITLE
Add German locale in Höflichkeitsform

### ISSUE THREAD

**Issue by Nakaner** [pretalx/pretalx#842]
## Problem you are facing

While I can change all the templates to "Sie", Pretalx inserts a couple of "Du" or "Dein" in some fields, e.g. in the schedule update notification. This makes the message look unprofessional.

## Possible Solution

Add a second German locale for the Höflichkeitsform.

**Comment by rixx** [comment]
[German (de_FORMAL)](https://translate.pretalx.com/projects/pretalx/pretalx/de_FORMAL/).
