### ISSUE TITLE
placeholder {speakers} in update mail does not work

### ISSUE THREAD

**Issue by Kunsi** [pretalx/pretalx#863]
## Current Behavior
Template is saved without error, releasing a schedule fails with error 500

## Expected Behavior
Template creation fails (see #215)

## Steps to Reproduce

1. Add {speakers} somewhere in mail template for schedule update mail
2. Try to release a schedule

## Your Environment

* Version used: v1.1.1
* Link to your instance, if in production: https://talks.seibert-media.net/
* Error Log: https://gist.github.com/Kunsi/61c49937d2cddca34135122ffa8c3f8d

**Comment by rixx** [comment]
Thank you for the detailed report!

**Comment by rixx** [comment]
Do you need a bugfix release for this?

**Comment by Kunsi** [comment]
No, thanks for asking :)
