### ISSUE TITLE
Upgrade from 0.9.0 to current failed; redis is too old

### ISSUE THREAD

**Issue by mraugh** [pretalx/pretalx#864]
## Current Behavior
python3 -m pretalx regenerate_css fails with the error message: "kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 3.1.0"

## Expected Behavior
regenerate_css succeeds
upgrade is successful

## Steps to Reproduce

1.become root  (because that's the only way it works)
2.follow the steps in the Maintenance section (https://docs.pretalx.org/administrator/maintenance.html)
3.Everything works up until regenerate_css

## Context

My event is over, so I'm trying to upgrade to the current Pretalx build while nobody is expecting to use the system.  Right now my Pretalx is down -- all projects get an HTTP 500 error when accessing them.

Not sure what you mean here.

## Your Environment

* Version used:  0.9.0, trying to upgrade to current
* Environment name and version (e.g. Chrome 39, python 3.5):
  Chrome 79.0.3945.88, python 3.6.9
* Operating System and version (desktop or mobile):  Linux (Pop! OS 18.04), but mobile is affected too
* Link to your instance, if in production:   https://pretalx.charmedhypno.org

**Comment by rixx** [comment]
I'm not sure how you have installed redis, but `pretalx[redis]` pins redis at version 3.3, which would comply with the requirements. Either install `pretalx[redis]` or install `redis==3.3`.

**Comment by mraugh** [comment]
Huh.  That worked to upgrade redis (python -m install redis==3.3), but Pretalx is still broken although the upgrade now completes without error.  The main screen (choice of projects) still shows Pretalx v0.9.0, and any project I select goes to a 500 error.

I have no doubt that my python environment is frakked up, and I don't understand Python that well to be able to fix it.  I would like to retain the database, which I've backed up along with the secrets file.  But I've also noticed that Pretalx has moved toward PostgreSQL. Long-term, should I just junk the database and start over with a fresh Pretalx and PostgreSQL, or try wiping the box, reinstalling Pretalx 0.9.0 with the old database, and then doing the upgrade again?

<MR>

**Comment by rixx** [comment]
> The main screen (choice of projects) still shows Pretalx v0.9.0, and any project I select goes to a 500 error.

I suspect you have either forgotten to restart the pretalx service, of you have not done the upgrade in the same virtual environment pretalx is actually using. When you restart the service, the startup information includes which executable is used. It should point you in the right direction. It also tells you which database is in use, btw.

> But I've also noticed that Pretalx has moved toward PostgreSQL.

That's not the case. pretalx has always had compatibility with Postgres, MySQL, and sqlite. This is highly unlikely to change. I don't think there is any call for you to switch database systems or wipe anything – all you have to do is figure out the environment your pretalx is running in, and upgrade it :)

**Comment by mraugh** [comment]
Okay, that's good.  And it fits with my being still very much a novice with Python, too.  Can you recommend a good place to read up about different environments and how to change between them?  

<MR>

**Comment by rixx** [comment]
So basically, there are a couple of Python environments naturally:

- The global one
- The user one (if you run `pip install --user`, the installed packages are only available for the currently active user)
- Virtual environments (either created with `python -m venv` or `virtualenv` or other tools like `virtualenvwrapper`). These have to be activated manually, typically by executing the script located in the virtualenv's `bin/activate` location.

I don't know what you used to install pretalx initially, but if you run it as a service, you should be able to look it up, by checking how it was invoked when it was still working.

**Comment by mraugh** [comment]
I thought I followed the instructions for installing pretalx, although this was a year ago so what I actually followed isn't available anymore (it was at https://docs.pretalx.org/administrator/installation.html but back then 0.9.0 was current; now it shows a PostgreSQL database, which is why I thought there was a movement to PostgreSQL).  But I was also rock-bottom newbie, so I may have deviated without realizing.

What I get from the Pretalx service is:
Read from:  /etc/pretalx/pretalx.cfg
Database:  pretalx (mysql)
Logging:  /var/pretalks/data/logs

So that doesn't really tell me a whole lot about which *user* environment it belongs to.  There's also a bunch of error stuff in the logs ahead of that:

Jan 25 13:28:08 instance-1 gunicorn[16582]: [2020-01-25 18:28:08 +0000] [16610] [ERROR] Exception in worker process
Jan 25 13:28:08 instance-1 gunicorn[16582]: Traceback (most recent call last):
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/wsgi.py", line 17, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     from dj_static import Cling, MediaCling
Jan 25 13:28:08 instance-1 gunicorn[16582]: ModuleNotFoundError: No module named 'dj_static'
Jan 25 13:28:08 instance-1 gunicorn[16582]: During handling of the above exception, another exception occurred:
Jan 25 13:28:08 instance-1 gunicorn[16582]: Traceback (most recent call last):
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Jan 25 13:28:08 instance-1 gunicorn[16582]:     worker.init_process()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
Jan 25 13:28:08 instance-1 gunicorn[16582]:     self.load_wsgi()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
Jan 25 13:28:08 instance-1 gunicorn[16582]:     self.wsgi = self.app.wsgi()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Jan 25 13:28:08 instance-1 gunicorn[16582]:     self.callable = self.load()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
Jan 25 13:28:08 instance-1 gunicorn[16582]:     return self.load_wsgiapp()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
Jan 25 13:28:08 instance-1 gunicorn[16582]:     return util.import_app(self.app_uri)
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
Jan 25 13:28:08 instance-1 gunicorn[16582]:     __import__(module)
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/wsgi.py", line 20, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     application = get_wsgi_application()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
Jan 25 13:28:08 instance-1 gunicorn[16582]:     django.setup(set_prefix=False)
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
Jan 25 13:28:08 instance-1 gunicorn[16582]:     apps.populate(settings.INSTALLED_APPS)
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
Jan 25 13:28:08 instance-1 gunicorn[16582]:     app_config.import_models()
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
Jan 25 13:28:08 instance-1 gunicorn[16582]:     self.models_module = import_module(models_module_name)
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
Jan 25 13:28:08 instance-1 gunicorn[16582]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/common/models/__init__.py", line 1, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     from .log import ActivityLog
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/common/models/log.py", line 6, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     from pretalx.mail.models import MailTemplate, QueuedMail
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/mail/models.py", line 11, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     from pretalx.common.mail import SendMailException
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/common/mail.py", line 13, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     from pretalx.celery_app import app
Jan 25 13:28:08 instance-1 gunicorn[16582]:   File "/var/pretalx/.local/lib/python3.6/site-packages/pretalx/celery_app.py", line 3, in <module>
Jan 25 13:28:08 instance-1 gunicorn[16582]:     from celery import Celery
Jan 25 13:28:08 instance-1 gunicorn[16582]: ModuleNotFoundError: No module named 'celery'
Jan 25 13:28:08 instance-1 gunicorn[16582]: [2020-01-25 18:28:08 +0000] [16610] [INFO] Worker exiting (pid: 16610)

So I've noted that /var/pretalx is the home directory for the pretalx users, but it doesn't appear that the pretalx user has a valid python environment.  Something I've done -- I don't know what, but I've been flailing a bit now -- seems to have affected that, because before I would get "Unable to read name main" and after googling and trying things there I can now start to run the upgrade as pretalx, which probably means the right directory is getting touched.  I used the command line "pip3 install --user -U pretalx mysqlclient pretalx[redit] and that succeeded, but  'python3 -m pretalx migrate' get me somethng odd: 
pretalx@instance-1:~$ python3 -m pretalx migrate
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v1.1.2                                                       ┃
┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                                  ┃
┃ ┃  │  O │  ┃  Database:  pretalx (mysql)                                           ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /var/pretalx/data/logs                                    ┃
┃ ┃  └─┘     ┃  Root dir:  /var/pretalx/.local/lib/python3.6/site-packages/pretalx   ┃
┃ ┗━━━┯━┯━━━━┛  Python:    /usr/bin/python3                                          ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Operations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, schedule, sessions, submission
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

I figured manage.py was what get called with -m pretalx and ran 'python3 -m pretalk makemigrations' but that tells me no changes were detected and migrate still fails.  

Am I making it worse, or is it getting closer?  I don't know.

<MR>

**Comment by rixx** [comment]
> So that doesn't really tell me a whole lot about which user environment it belongs to.

No, but it tells you that it doesn't run in a separate virtual environment, due to the line 

> Python: /usr/bin/python3

pretalx doesn't output the user in this location, because we don't want to provide too much output, and also since *you* are starting the process, you already know which user is running it.

> I figured manage.py was what get called with -m pretalx and ran 'python3 -m pretalk makemigrations' but that tells me no changes were detected and migrate still fails.

Never run `makemigrations`, it will screw up your pretalx install! Your `migrate` does not fail, it has run correctly and does not need to take further action (hence the "No migrations to apply.").

But it looks to me like your pretalx user now executes pretalx correctly, so all you should have to do is to make sure that your *service* is started from this environment (i.e. as pretalx user, with the correct directory path), restart it, et voilà.

**Comment by mraugh** [comment]
Shit.  No, I finished the process and restarted and I now get a 500 error for everything.  :(

**Comment by mraugh** [comment]
ARRGH!   I'm getting 6 screens of error data, all of which appears to refer to something else, and the only discernable clue in all of it is:
Jan 25 16:59:23 instance-1 gunicorn[18405]: compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "62723ac4d34ac74c62025b1390028859c50123c3fa0a6add089ba5258741ba51" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:

which repeats a half-dozen or more times, but running "python3 -m compress" as pretalx only get me "Compressing... Invalid template /var/pretalx/.local/lib/python3.6/site-packages/django_filters/templates/django_filters/rest_framework/crispy_form.html: 'crispy_forms_tags' is not a registered tag library."  

This thing is fubarred.  I'm gonna revert back to snapshot and try fixing the python environment first.

<MR>

**Comment by rixx** [comment]
> This thing is fubarred. I'm gonna revert back to snapshot and try fixing the python environment first.

It doesn't seem to me like it is. The template compression error does not indicate that the `compress` command has failed completely, and you can ignore it.

Other than that: Sorry, but "500 for everything" is not actionable or sufficiently detailed to advise. Feel free to contact me via [Jabber or IRC](https://rixx.de/about/) for real-time communication, or support@pretalx.com. I'm locking this issue, since GitHub issues are not a support channel, and I feel that every useful piece of information has been exchanged.

**Comment by raphaelm** [comment]
For future people who stumble over this: I had the same experience as mentioned in the last comment here, and the reason was that after a Python version upgrade, I did not reinstall gunicorn in the new python version, so I was executing two different versions of pretalx in the gunicorn process and the command line.
