### ISSUE TITLE
Error on /2020/cfp

### ISSUE THREAD

**Issue by davearonson** [pretalx/pretalx#870]
## Current Behavior
PROPOSE link has URL https://cfp.devopsdays.amsterdam/2020/cfp which is 404

## Expected Behavior

Either https://cfp.devopsdays.amsterdam/2020/cfp exists, or the URL at the PROPOSE link is different (and works)

## Steps to Reproduce

1. Go to https://devopsdays.org/events/2020-amsterdam/welcome/
2. Click on PROPOSE
3. Observe 404 screen
4.

## Context

Trying to find a CfP for the event

## Your Environment

Irrevant AFAICT

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
I'm afraid that's not exactly a pretalx isseu and we can't help with that – it seems like the entire site is down, and every possible URL is throwing errors. Please get in contact with the organisers – they should be able to look into the syslogs and figure out what's happening.
