### ISSUE TITLE
Error on /cloud-native-rejekts-eu-2020/submit/ecnvEF/profile/ -- could not create account

### ISSUE THREAD

**Issue by jess-edwards** [pretalx/pretalx#872]
## Current Behavior
I tried to submit an abstract, and when I clicked "create account", it hung then gave me a 500 error (if I remember correctly).

## Expected Behavior
Login or account creation successful

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Mac OS Catalina - 10.15
* Link to your instance, if in production:

**Comment by rixx** [comment]
Could you please contact the organisers and ask them if they can provide details from their error logs? Cloud-native is not hosted by us / is running a self-hosted version of pretalx, so we have no way to look into it in more detail.

**Comment by jess-edwards** [comment]
I'll work with Cloud-Native on it. Their 500 error page had a "file an issue" link, which is what brought me to you.

**Comment by rixx** [comment]
Yeah, it's appreciated! It's just that we'll need their details/logs to work on a bugfix. They are running a fairly current version, so this is helpful to our project in any case, thank you!

**Comment by rixx** [comment]
Closing as stale, feel free to re-open with more details.
