### ISSUE TITLE
"Copy Configuration" for new event doesn't seem to do anything

### ISSUE THREAD

**Issue by jberkus** [pretalx/pretalx#873]
## Current Behavior

When you create your second event on Pretalx (at least, on the hosted version) one option you're given is to "copy prior event configuration".  I tried that out for one event, and it didn't seem to copy anything; settings, teams, questions, etc. were all Pretalx defaults.

## Expected Behavior

I'm not sure which things I expected it to copy, but at least the CfP "content", questions, and types.

## Steps to Reproduce

1. Create a new pretalx account.
2. Create an event with lots of customization (custom questions, text, tracks, etc.)
3. Create a second event and chose "copy ___other event___"
4. Nothing is copied.

## Context

Honestly this isn't a big problem for me and if the "copy prior" button went away I'm not sure I'd miss it.  But if it doesn't work, it probably should go away.

## Your Environment

Pretalx.com hosted version.

**Comment by rixx** [comment]
Hmm, it *should* work and we have tests to show for it. Thank you for reporting.

Anybody interested in debugging this should probably start with the `pretalx.event.models.event.Event.copy_data_from` method and see that it does the right thing, and that it is called from `pretalx.orga.views.event.EventWizard.done`.

**Comment by rahmonov** [comment]
I did some debugging and found out that the problem lies in `with scope(event=event)`. With this context manager on, `other_event.submission_types.all()` is returning an empty queryset. With `with scopes_disabled()` like in a unit test, it would return a correct queryset. I don't know how to fix this yet as I am not familiar with `django_scopes`. Any ideas @rixx?

**Comment by rixx** [comment]
Good catch! The specific section accessing the database will have to be wrapped in a `scopes_disabled` context manager – do you want to do that?

**Comment by rahmonov** [comment]
Yup, I will create a PR soon.

**Comment by rixx** [comment]
Due to an unforseen request I needed the fix right now, so I pushed it instead. Sorry for jumping in,  @rahmonov! I still appreciate that you looked into it :)

**Comment by rixx** [comment]
Fixed in 9aacd8d2
