### ISSUE TITLE
Preview page and review page treat line breaks differently

### ISSUE THREAD

**Issue by christianpeel** [pretalx/pretalx#877]
## Current Behavior

In the [JuliaCon](https://pretalx.com/juliacon2020/cfp) talk proposal site, the Preview pane for the "Abstract" and "Description" page ignore line breaks in the text pane. This is ok, yet the Review page for a submission does not ignore these line breaks.

## Expected Behavior

I expect the preview pane and review page to behave the same.

## Steps to Reproduce

1. Go to the [JuliaCon](https://pretalx.com/juliacon2020/cfp) talk proposal site, and make a dummy entry with a line break and check that the "Preview pane" ignores it. I guess other events on pretalx would behave the same.
2. After creating the talk entry, visit the "Review" page at the link that is shown and emailed to you.
3. Compare with the behavior in the Preview pane earlier

## Your Environment

* Version used: ??
* Environment: Chrome 79
* Operating System: MacOS 10.14.6
* Link to your instance, if in production: https://pretalx.com/juliacon2020/submit/7rDPkv/info/

cc @oxinabox

**Comment by rixx** [comment]
Thanks for reporting this!
