### ISSUE TITLE
Yes/no questions are not visible in submission display

### ISSUE THREAD

**Issue by jberkus** [pretalx/pretalx#878]
## Current Behavior

My event has 6 custom questions.  Four of those should be visible to reviewers; they were configured as visible to reviewers from the creation of the event.  However, only three of them are visible.

The invisible custom question is the only yes/no question, so maybe there is an issue with yes/no questions?

## Expected Behavior

All custom questions marked "visible to reviewers" should be visible when reviewing.

## Steps to Reproduce

1. Create an event
2. Create 5-7 custom questions for the event, including 3+ that are visible to reviewers.  One of the visible questions should be Y/N
3. Submit a proposal to the event
4. See if all custom questions that should be visible are visible, including the Y/N question

## Context

This is preventing us from completing talk review for our event.  Responses to speakers are due Thursday.

## Your Environment

* Version used: Pretalx.com hosted version.

**Comment by rixx** [comment]
Just to verify: The answer in question is visible to organisers with edit permisions, but not to reviewers?

**Comment by jberkus** [comment]
It's not visible to anyone.

**Comment by rixx** [comment]
I'm sorry, but I cannot reproduce this issue – all submission specific answers always show up for me. Speaker specific answers are not shown in the submission view, which may be the content you are missing? These answers are shown in the speaker profiles.

**Comment by jberkus** [comment]
aha, that's it', it's a speaker field.  thanks!
