### ISSUE TITLE
When submissions are deleted, number of submissions are not deleted in the track overview

### ISSUE THREAD

**Issue by darkmattercoder** [pretalx/pretalx#879]
## Current Behavior

When you delete a submission that belong to a certain track, you still see that submission counting in the tracks overview.

## Expected Behavior

Do not count deleted submissions in the tracks overview.

## Steps to Reproduce

1. Add a submission
2. Assign a track
3. Delete that submission
4. Note that the number in the tracks overview did not decrement

## Context

not sure what to say

## Your Environment

Hosted instance pretalx.com/haxogreen-2020

**Comment by rixx** [comment]
Good idea, thanks!

This shouldn't be too hard to do, so if anybody wants to take this up (looking at the `TrackList` in `pretalx.orga.views.cfp`), I'm happy to assist.
