### ISSUE TITLE
ask for confirmation before discarding all drafted mails

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#88]
On the outbox page (`/orga/event/foo/mails/outbox`) discarding all mail is very easy. Since the "Discard all" button is right next to the "Send all" button, I can imagine users clicking the wrong one by accident (e.g. on touch screens). Discarding all the emails can be quite disastrous after the user just confirmed 50 talks in one batch.
Think about adding a confirmation before sending or discarding all email to combat this.

**Comment by tabascoeye** [comment]
I would go as far as to have a default "safe mode" setting which asks for confirmation after **every** click on the "red"/dangerous buttons.
Users which dislike that extra confirmation can disable the "safe mode"
