### ISSUE TITLE
Add a possibility to delete the statistics

### ISSUE THREAD

**Issue by darkmattercoder** [pretalx/pretalx#880]
## Problem you are facing

Sometimes when playing around with the system, you will find yourself adding and deleting submissions. You then will have a not so realistic statistics view.

## Possible Solution

Add a button to clear the statistics.

## Context

hosted instance pretalx.com/haxogreen-2020

**Comment by rixx** [comment]
If I'm understanding this correctly, you want deleted submissions to be ignored in the timeline in the statistics view?

**Comment by darkmattercoder** [comment]
Well, as I am thinking it through, it might be probably better if you simply create a separate event after you are done with playing around and testing. So maybe the advantage of having a button to reset the statistics and let only submissions from then actually count might be not that big....

**Comment by rixx** [comment]
There is definitely no "resetting" of statistics – statistics are always calculated live, to avoid inconsistencies. But we can filter out deleted submissions, I suppose.
