### ISSUE TITLE
Use Google Tag Manager in Pretalx

### ISSUE THREAD

**Issue by mseibert** [pretalx/pretalx#881]
## Problem you are facing
I want to include a Google Tag Manager Container in Pretalks

## Possible Solution
Offer an option to add custom JS globally.

## Context

We're using a couple of services on our website for tracking (Google Analytics) and support (Intercom) that rely on Java Script snippets to be injected in the website. Is that possible with Pretalx today already? Is that something that is planned?

**Comment by rixx** [comment]
That's a good idea, I think, though it's not something we will be able to offer in the user interface. Instead, it will have to be added via custom templates, with some documentation as to how to use those. They will have to be installed by the system administrator.

**Comment by mseibert** [comment]
Is there a workaround as of today? Could we put the code in our custom templates already?

**Comment by rixx** [comment]
Technically there is a workaround, though it is not particularly clean or nice. The way pretalx works is that it iterates over a list of template paths, and it will use the first template it finds. These paths generally are the pretalx template paths followed by the plugin template paths (so a plugin can't just override the global paths). But before the pretalx paths are searched, pretalx looks into the `data` directory.

So if you create a `data/templates/common/base.html` (where `data` is your data directory as configured in your config file), pretalx will use that file as a base to all user/submitter facing pages, except error pages. The same would go for `data/templates/orga/base.html` if you want analytics for the organiser backend.

The file should look more or less like [the original](https://github.com/pretalx/pretalx/blob/master/src/pretalx/common/templates/common/base.html).

To include a script, you'll have to put the script itself into a file and put that in the pretalx static directory, and use the `{% static ` inclusion like you can see in other parts of the template file. (And run `rebuild` again, so that the static file is available.)

This is off the top of my head, so the details may not be completely accurate. And I know, this is far from ideal – for our next release, I'll figure out a way to make it easier for administrators to add custom js.

**Comment by mseibert** [comment]
Cool. Thanks a lot.

**Comment by MaZderMind** [comment]
@rixx would you accept an PR that, similar to the current "Custom CSS" option, would allow per-conference "custom HTML" which would be literally inserted to the end of each page where the "Custom CSS" is currently?

**Comment by rixx** [comment]
I would accept such a PR, but since we do not allow execution of inline scripts on most pages, and because we'd need to sanitise the included HTML for security reasons, this wouldn't actually help in this case.

A workaround could be to only allow the addition of script content to superusers/administrators, but that wouldn't change the fact that we don't allow inline scripts. I really think the correct solution to this would be a better documentation of how to include custom scripts.

What would you think instead of a "google tag manager" plugin for pretalx? I'd need to add a couple of templates and plugin hooks, but that'd be the best way to get a per-event, safe way to handle this, imo.

**Comment by MaZderMind** [comment]
@rixx Then it would probably be simpler to have a Custom JS option in parallel to the Custom CSS option. That would solve the "no inline js" issue and follow already preprared paths.

**Comment by MaZderMind** [comment]
I tried copying the base.html but got a 500 error:
```
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]: ValueError: Missing staticfiles manifest entry for 'vendored/popper.js'
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/storage.py", line 420, in stored_name
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     hashed_name = hashed_name_func(*args)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/storage.py", line 132, in _url
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self._url(self.stored_name, name, force)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/contrib/staticfiles/storage.py", line 153, in url
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return staticfiles_storage.url(path)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/templatetags/static.py", line 118, in handle_simple
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.handle_simple(path)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/templatetags/static.py", line 103, in url
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     url = self.url(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/templatetags/static.py", line 106, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     bit = node.render_annotated(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.nodelist.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/compressor/templatetags/compress.py", line 134, in get_original_content
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     original_content = self.get_original_content(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/compressor/templatetags/compress.py", line 65, in render_offline
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.render_offline(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/compressor/templatetags/compress.py", line 96, in render_compressed
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.render_compressed(context, self.kind, self.mode, forced=forced)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/compressor/templatetags/compress.py", line 142, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     bit = node.render_annotated(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.nodelist.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return compiled_parent._render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     bit = node.render_annotated(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.nodelist.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return compiled_parent._render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     bit = node.render_annotated(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.nodelist.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self._render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 171, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     return self.template.render(context)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     content = template.render(context, self._request)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 83, in rendered_content
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     self.content = self.rendered_content
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 106, in render
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     response = response.render()
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 143, in _get_response
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     response = self.process_exception_by_middleware(e, request)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 145, in _get_response
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:     response = get_response(request)
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]:   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]: Traceback (most recent call last):
Feb 25 14:23:34 pretalx.smedia.pb-8.smhss.de gunicorn[23605]: ERROR 2020-02-25 14:23:34,774 django.request log Internal Server Error: /infosession20/
```

I think it would be better to implement this the correct way ;)

**Comment by rixx** [comment]
That error looks like you haven't run rebuild/collectstatic afterwards?

**Comment by rixx** [comment]
> @rixx Then it would probably be simpler to have a Custom JS option in parallel to the Custom CSS option. That would solve the "no inline js" issue and follow already preprared paths.

As I mentioned earlier – it will not be possible to provide this in the user interface, since granting organisers of *one* event access to JavaScript means that they can access data relevant to other events, aswell, since they all share a domain. We can put it in plugins (which would provide pre-defined javascript and need to be installed by the administrator) or by way of template manipulation by administrators, but I can't see a way to offer any organiser to add custom JavaScript to their event.

I'm really sorry, and I see how this would be useful to event organisers, and I'm very much open to discuss solutions – but only so far they safeguard access to user data.

**Comment by MaZderMind** [comment]
@rixx Ich versuche das grade über ein eigenes Plugin zu lösen; in dem ich für unsere Installation CSP abschalte* und das ganze Tracking Geraffel in den Header lade. Mir gefällt das auch nicht sonderlich gut.

Weißt du einen Weg, als Plugin JS in die Seite zu integrieren? Derzeit benutze ich einen Context Processor, muss dafür aber sowas in die `base.html` schreiben:
```
    {% for script in extra_scripts %}
            <script>{{ script | safe }}</script>
    {% endfor %}
```

*) Angeblich kann der Google Tag Manager CSP mit Nonce, aber meinen Tests hat das nicht für alle Tracking Codes funktioniert. Es ist wirklich unglaublich wie viele Teqcking Codes da eingebunden werden sollen *sigh*

**Comment by rixx** [comment]
Ich hab auch noch mal mit den pretix-Leuten geredet – da gibt es auch keine Integration für Google Tag Manager, weil das zu übel umzusetzen ist. Google Analytics geht wohl deutlich besser.

**Comment by rixx** [comment]
In summary, this is probably not something we can add at this point. I added the ``pretalx.cfp.signals.html_head`` signal in 15088396, though, to make it easier to add custom JS/CSS to the HTML header from a plugin without working around templates.

**Comment by MaZderMind** [comment]
@rixx Thank you very much, this is as much as we can ask for.
