### ISSUE TITLE
Feature Request: Search by Custom Questions

### ISSUE THREAD

**Issue by jberkus** [pretalx/pretalx#882]
## Problem you are facing

Currently, you cannot search, sort, or filter by custom questions, either for speakers or for submissions.  Since these custom questions are frequently more important to the organization than the built-in questions, this is an obstacle to using Pretalx for many events.  Right now, the only way to do this is to pull data exports and use an external program.

## Possible Solution

Add a custom-question drop down, with "question" and "value" to the search interfaces for both submissions and speakers.  Ideally, this would be part of an "add criteria" interface, where you could add several different criteria.  But even allowing filtering by one custom question would be helpful.

## Context

Some examples:

For selecting talks for an upcoming event, we require a higher rating for submissions where the speaker requires travel funding.  However, we have no way to filter our list to either those that do or don't need travel funding so that we can select talks this way.  Once we've selected the talks, we'll also want to extract a list of speakers who need travel funds so that we can have accounting contact them.

Many conferences need to check how they are doing on selection of under-represented minority speakers.  For this, they'd want to filter a list of speakers with the URM-related custom questions to see if they've picked enough.

**Comment by rixx** [comment]
Absolutely agreed, that would be a nice feature to have. It's rather big in scope, so I can't say when it will be implemented – our roadmap for non-sponsored features for 2020 is pretty much set already, but perhaps somebody will want to pick this issue up – I'll be happy to advise in that case!

**Comment by eriktews** [comment]
Hi, that sounds like a great idea and it would be cool to see it for the Email composer as well. For example you might have a custom box "would like to attend the conference dinner", and when there are changes to the conference dinner, you could then send emails to everyone who had this box checked.

**Comment by rixx** [comment]
Linking between search filters and email adressees would be extremely good UI, thank you for the suggestion! I'll try to push the changes in email handling forward soon, and after that it'll be easier for new/old/any contributors to take up ideas like this.

**Comment by eriktews** [comment]
Great, and the existing selectors for the email composer could then become persistent search filters. Maybe you could add a feature that allows you to persist a custom search, such as "all vegetarians" and then have it visible in the email composer as well.

**Comment by rixx** [comment]
You can now go to a list of submissions with a specific answer from the question statistics page, by following the link in the line of the statistics table you're looking at.
