### ISSUE TITLE
Feature Request: Resend Invite

### ISSUE THREAD

**Issue by jberkus** [pretalx/pretalx#885]
## Problem you are facing

Sometimes team members do not get their initial invitation.  The UI path to re-invite them is cumbersome.

## Possible Solution

Add a "resend invite" button to Pending team member listing, in the same place that the "reset password" button is for confirmed team members.

**Comment by jberkus** [comment]
This seem like it would be a good first issue for someone.

**Comment by rixx** [comment]
This is an issue that is well-suited for external contributors – let me know if I can be of any help, either via this issue or via support@pretalx.com.

## What this is about

pretalx allows groups organisers of an event in teams, and organisers with sufficient access rights can invite new team members. There is currently no easy way to re-send an invitation, which would be useful.

## How to get started

First of all, leave a comment on this issue to make sure nobody else starts working on this issue at the same time!

Next, you need pretalx running locally on your machine. First, [fork](https://github.com/pretalx/pretalx/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier)

Follow the [developer setup guide](https://docs.pretalx.org/en/latest/developer/setup.html), and then play around with pretalx a bit.
Have a look at the places impacting this issue. Look at the code responsible for the issues (searching for relevant words or files should help you find your way around). We have an explanation of our [code structure](https://docs.pretalx.org/en/latest/developer/concepts.html) and the actual [data models](https://docs.pretalx.org/en/latest/developer/interfaces/models.html).


## How to do this

The interface currently looks like this: 

![DeepinScreenshot_select-area_20200308163702](https://user-images.githubusercontent.com/2657547/76165929-27733000-615b-11ea-85b0-cd790b646f03.png)

Add button to the line with the pending invitations, titled "Resend invite". Then add the functionality to a new view.

You're looking for the template in ``pretalx/orga/templates/orga/settings/team_detail.html``, and the view code is in ``pretalx.orga.views.organiser.TeamDetail``. You can look at the ``TeamUninvite`` view to see how to an individual action can be implemented. The ``TeamInvite`` class has a ``send`` method that you should call to re-send the email in question.

## Submit the PR

There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Remember to provide documentation and tests, if applicable. Run the tests before opening your PR, including style checks. We have a [contribution guide](https://docs.pretalx.org/en/latest/developer/contributing.html), which ought to prove helpful at this stage.

**Comment by koebi** [comment]
I'd like to take a look at that :)

**Comment by rixx** [comment]
Cool, go for it!
