### ISSUE TITLE
Feature Request: communicate all talk data in submission process

### ISSUE THREAD

**Issue by orithena** [pretalx/pretalx#889]
## Problem you are facing
We've had a misunderstanding in the submission process which could've been prevented by communicating more data in the process.

Story: I submitted a workshop to HIP2020, commenting that I need a 4h slot instead of the biggest available 2h slot. Workshop was accepted and scheduled and confirmed and rescheduled and reconfirmed, but the fact that there was a 4h requirement got lost on the way to the last reschedule (even though we communicated in person about that before the submission). This duration problem only gained attention when I reviewed the whole schedule, because nowhere in the process of accepting the schedule is a hint about the actually alotted duration of the slot.

## Possible Solution
Improve the email and web templates to always show the speaker all meta data as alotted by the orga.

**Comment by rixx** [comment]
This is a very good idea, though it won't be trivial to do with the way our templating system works currently (and even less easy in a backwards-compatible fashion.)
