### ISSUE TITLE
HTTP ETag ignored at pretalx.com (v1.2.0.dev0)

### ISSUE THREAD

**Issue by johnjohndoe** [pretalx/pretalx#892]
## Current Behavior
Requesting data from `https://pretalx.com/fossgis2020/schedule/export/schedule.xml` with a valid `ETag` header always results in HTTP 200.

## Expected Behavior
Requesting data from `https://pretalx.com/fossgis2020/schedule/export/schedule.xml` with a valid `ETag` header results in HTTP 304 if data has not been modified meanwhile.

## Steps to Reproduce

1. Execute `curl -v -s https://pretalx.com/fossgis2020/schedule/export/schedule.xml >1 /dev/null`. The response contains a `ETag` header, e.g `8b0e9d86ea1f4730d052855481bf5566ae736212`. HTTP status code 200.
2. Execute `curl -v -s -H "ETag: 8b0e9d86ea1f4730d052855481bf5566ae736212" https://pretalx.com/fossgis2020/schedule/export/schedule.xml >1 /dev/null`.
The response contains the same `ETag` header value as before. HTTP status code 200.
3. Execute `curl -v -s -H "ETag: 8b0e9d86ea1f4730d052855481bf5566ae736212" -H "If-None-Match: ETag: 8b0e9d86ea1f4730d052855481bf5566ae736212" https://pretalx.com/fossgis2020/schedule/export/schedule.xml >1 /dev/null`.
The response contains the same `ETag` header value as before. HTTP status code 200.

## Context

The behavior currently hinders me from publishing the Android app for the [FOSSGIS conference](https://fossgis-konferenz.de/2020/) taking place from March 11, 2020. I appreciate any advice how to circumvent the behavior or a fix deployed at the instance.

I was able to reproduce the **expected behavior** with a different Pretalx instance running on _nginx/1.10.3_. Here is the _schedule.xml_ URL for your to try: `https://cfp.chaoszone.cz/36c3/schedule/export/schedule.xml`.

## Related
- [Issue #492: Support HTTP Etags for frabxml/ical/... exports](https://github.com/pretalx/pretalx/issues/492)

## Your Environment

* Webserver: [openresty](https://openresty.org)
* Version used: pretalx.com, v1.2.0.dev0
* Environment name and version (e.g. Chrome 39, python 3.5): zsh
* curl: 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3, Release-Date: 2018-01-24
* Operating System and version (desktop or mobile): Ubuntu 18.04.4
* Link to your instance, if in production: https://pretalx.com/fossgis2020

**Comment by johnjohndoe** [comment]
@rixx, can you please state **if** you will have time to work on this issue at all before March 11?
I like to know if I have to start working on a client-side workaround. Thanks. /cc @raphaelm

**Comment by rixx** [comment]
Since you stated that this behaviour only occurs on a single pretalx instance, and it can't be reproduced on other instances, this seems to be a configuration problem, not a pretalx bug. This issue tracker is only meant for pretalx bugs and feature requests, so please get in touch via support@pretalx.com instead.

**Comment by johnjohndoe** [comment]
I am not sure if my comparison of https://cfp.chaoszone.cz/36c3 `<!--  Made with love by pretalx v1.0.4.  -->` and https://pretalx.com/fossgis2020 `<!--  Made with love by pretalx v1.2.0.dev0.  -->` makes sense. I cannot tell if other `pretalx.com` reproduce the behavior since I don't know any other instances.

**Comment by johnjohndoe** [comment]
My mistake. 

> curl -v -s -H "ETag: 8b0e9d86ea1f4730d052855481bf5566ae736212" -H "If-None-Match: ETag: 8b0e9d86ea1f4730d052855481bf5566ae736212" https://pretalx.com/fossgis2020/schedule/export/schedule.xml >1 /dev/null

must be

> curl -v -s -H "ETag: 8b0e9d86ea1f4730d052855481bf5566ae736212" -H "If-None-Match:  8b0e9d86ea1f4730d052855481bf5566ae736212" https://pretalx.com/fossgis2020/schedule/export/schedule.xml >1 /dev/null

Thanks to @rixx for spotting this.
