### ISSUE TITLE
easy automatic updated code deployment

### ISSUE THREAD

**Issue by ThomasWaldmann** [pretalx/pretalx#901]
There are some instructions there:

https://docs.pretalx.org/administrator/maintenance.html

But they require that a server admin is available to do that.
Some stuff needs to be run as user pretalx, some as root.

It would be nice if one could trigger an update via a http request (e.g. with a github webhook, so that a merged pull request automatically would get deployed).

As it is quite a hassle to add some extra cgi script (running as correct uid/gid), it would be nice if pretalx could handle that internally, especially since pretalx should be terminated, then upgraded and then re-started anyway.

Just an idea, not sure how to implement that best.

**Comment by rixx** [comment]
I don't think we can or want to do that, at least at the moment. I have no idea how to do this in a fashion that is *safe*, seeing as pretalx is Python (impossible to sandbox) and that there are multitudes of possible ways of deployment. Permitting a web interface to update system code would also mean allowing it to execute near-arbitrary code. 

Stopping and restarting is highly deployment specific, and I can't see a way to do this with reasonable effort and security.

You could, of course, write a plugin that can do this with little effort, if you just tailor it to your existing installation.

I'm closing the issue for now. I'm willing to re-visit this decision if there's a proposal or PR demonstrating a safe and deployment-independent approach to this.

**Comment by ThomasWaldmann** [comment]
A github webhook only sends a trigger, it does not send you code.

I guess the app could react to the trigger by exiting with some specific `i want to upgrade` exit code that is dealt with by a minimal wrapper that then calls another script which implements the upgrade.
I that script terminates, it would start the pretalx app again (then using the upgraded code).

The upgrade script would pull the code from a trusted location (e.g. the project's gh repo).

**Comment by rixx** [comment]
Upgrades also include third-party code, though, and plugin upgrades, and database migrations. Triggering these things from a web interface is not something I plan to support from within pretalx at this time, especially given that I don't see how this would be doable in a deployment- and platform independent way.

Implementing this in a way that supports your specific installation method should be pretty easy in a plugin, even though I would not recommend it.
