### ISSUE TITLE
In documentation properly explain relationship between celery and mail sending

### ISSUE THREAD

**Issue by pedrogk** [pretalx/pretalx#902]
After running pretalx for a few days and not receiving any mails from it, I realized that celery needs to be running for mails to be sent. If that is the desired behaviour, it is ok but probably it should state so in the documentation. 

At the moment, Documentation gives the feeling that celery is optional (``If you decide to use Celery (giving you asynchronous execution for long-running tasks)``) but it should state that it is needed for sending mails, which is quite important.

**Comment by rixx** [comment]
No, that's not the case (and when it is, it is a bug and we need to find how it happens). All mails are, in the end, sent via ``pretalx.common.mail.mail_send_task``. This is a method marked as a Celery task, but Celery runs synchronously if no workers are present.

For some reason Celery must have assumed that workers were present, and tried to schedule the tasks, which were then not retrieved. pretalx assumes that Celery is present if-and-only-if there is a celery broker configured in your settings. Please double-check your settings to make sure no celery configuration is present.

(If this was not the issue, please also get back to this and I'll re-open the issue.)

**Comment by pedrogk** [comment]
Oh. That was it. My conf file had entries for celery (I figured it wouldn't harm).
Anyway, I still think it would be a good idea to modify the docs to mention this. Something like: "If you don't plan to use celery omit these entries from your configuration file, otherwise some tasks like email sending will not work".

**Comment by rixx** [comment]
If I remember correctly this isn't the first time this has happened, so I've removed the celery section from the example configuration file.
