### ISSUE TITLE
404 for the cfp / agenda css

### ISSUE THREAD

**Issue by ThomasWaldmann** [pretalx/pretalx#903]
does that ring any bells?
```
WARNING 2020-03-27 18:16:24,288 django.request log Not Found: /media/democon/agenda.5fc07c8e3641cb01.css
WARNING 2020-03-27 18:16:24,294 django.request log Not Found: /media/democon/cfp.60d621a29d974a77.css
```

having that in 2 different installations now, done by 2 different admins.

in mine, i did a gunicorn based install into a virtual env.

the files are there in data/media and strace says that the python process does not even try to open them.

also, there are no permission issues, all stuff is owned by `pretalx` and has appropriate permissions.

**Comment by ThomasWaldmann** [comment]
also, there are no permission issues, all stuff is owned by `pretalx` and has appropriate permissions.

**Comment by ThomasWaldmann** [comment]
Works with `debug = True`, breaks with `= False`.

**Comment by rixx** [comment]
You may have forgotten to run ``regenerate_css`` after an update, and/or have a problem with your celery configuration. It doesn't appear to be a general bug with pretalx.

**Comment by rixx** [comment]
Ah, wait, I misread – if the files are there, you'll have to deliver them to the browser. In development mode, pretalx does this for you, but in production mode, you'll have to deliver them via the web server of your choice, just like the static files.

**Comment by ThomasWaldmann** [comment]
I tried regenerate_css, it did not change behaviour.

There is no celery configuration.

**Comment by ThomasWaldmann** [comment]
Considering that it looks like a lot of people fall into that trap and that this somehow counteracts running with debug = False, maybe just pretalx should always serve these files?

One can still catch the request before it reaches pretalx to optimize then, but at least it does not break in mysterious ways.

**Comment by ThomasWaldmann** [comment]
As the minimum, there could be a comment in `pretalx.cfg` right above `debug = False` that this implicates media and static not being served by the python code.

**Comment by rixx** [comment]
> As the minimum,

The documentation outlines how to serve static files in [step 7 of the installation guide](https://docs.pretalx.org/administrator/installation.html#step-7-ssl). If you think that additional hints are needed there, we'll happily take a look at your pull request.
