### ISSUE TITLE
Have a multiple file upload question type

### ISSUE THREAD

**Issue by eriktews** [pretalx/pretalx#911]
## Problem you are facing

There is currently a file upload type for questions so that users can upload a single file. However for some questions, uploading multiple files would be a good way to answer them. Currently this can only be done by uploading a zip file, but that's not very convenient.

## Possible Solution

Have a multiple file upload type for the questions as well. Users may then decide to add additional files to their answer or delete some of the files they uploaded.

## Context

This could be interesting for questions such as "additional reading material as PDF" for the submission or something similar.

**Comment by rixx** [comment]
Off the top of my head: This would be quite an annoying change to make in several tricky areas. At the same time, I'm not opposed to it, and I can see how it makes sense.

I'd be happy to help/guide a PR on this feature, but I won't prioritise development on it myself. If anybody wants to take this up and/or has further questions, just leave a comment!

**Comment by rixx** [comment]
I've thought about it some more, and I think at this point, this would be better suited for a plugin or some sponsored development.

If you really just want multiple files uploaded for a given talk/session, pretalx already has the "resources" part of a proposal.
