### ISSUE TITLE
DOMException while loading event schedule in pretalx instance

### ISSUE THREAD

**Issue by pl4st3** [pretalx/pretalx#912]
## Current Behavior
Rendering of event schedule fails due to a DOMException after update from pretalx v1.0.3 to >v 1.1.x.  Pretalx instance serves different events, each with its own event domain. 

`offline.js:4 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The origin of the provided scope ('https://_<pretalx_eventtitle>_') does not match the current origin ('https://_<event_URL>_').`

## Expected Behavior
correct loading and rendering of event agenda/program for end-user without DOMExecptions.

## Steps to Reproduce

1. go to https://pretalx.freifunktag.de
2.  try to view agenda / program of past events (also occurs with upcoming events)

#### reproduce it in own env.
1. build pretalx stable from git repo
2. create pretalx instance and an event with it's own event URL, which differs from pretalx installation domains.
## Your Environment
* Version used: v1.1.2 
* Pretalx is installed as docker image with an nginx reverse proxy.  Configuration due to recommendations for reverse proxy, docker build via https://github.com/pretalx/pretalx-docker. 
* Error occurs in versions stable pretalx versions >v1.0.3. Tested with v1.0.9, v1.1.2 and current master (v1.2.0 dev0);  only tested with different pretalx versions in docker container, python 3.6 - 3.7.7 tested as well as different versions of redis.

* Clients: Windows 10 Firefox and Edge , MacOS 10.15.4, Safari, Chrome (80.0.3987.163) , iOS 13
* Domains are all CNAME's for pretalx instance domain.
* Link to your instance, if in production:
https://pretalx.freifunktag.de -> see reproduction

**Comment by rixx** [comment]
It looks to me like you have either not run `regenerate_css`, not run `rebuild`, or not restarted all services required. Could you please check or repeat those steps and make sure they have been done?

For reference, it does not seem to be a pretalx bug, since [our demo event](https://democon.pretalx.com/democon/schedule/) runs fine on a custom domain.
