### ISSUE TITLE
If use cfp?track=XXX URL can not go to the Questions view

### ISSUE THREAD

**Issue by victorbuild** [pretalx/pretalx#913]
## Current Behavior
use   cfp?track=XXX  URL atuo select Track

## Expected Behavior

use   cfp?track=XXX  URL can't go to Question view after info view is completed

It seems that the value of the ‘submission_type’ variable is missing

## Steps to Reproduce

1. cfp?track=XXX
2.  info view is completed Continue
3. Can't go to Question view

## Context

Can't Submit a proposal

## Your Environment

Google Chrome 81.0.4044.113

**Comment by rixx** [comment]
Can you link an example of where this occurs?

**Comment by victorbuild** [comment]
Can't go to Question view
https://pretalx.com/coscup2020/cfp?track=277-postgresql

OK but not atuo select Track
https://pretalx.com/coscup2020/cfp
