### ISSUE TITLE
Feature Request: Track Descriptions

### ISSUE THREAD

**Issue by MaZderMind** [pretalx/pretalx#915]
## Problem you are facing
We have [a Conference with Tracks](https://talks.seibert-media.net/tools4agileteams2020/submit/cBrgkI/info/) which are not necessarily self explanatory to submitters.

## Possible Solution
We would like to add a Description-Texts to the Tracks which, when entered, are displayed below the Track-Select-Field when a Track is selected. Also we would like to have a clickable Question Mark icon on the Track Field which would maybe open a Flyout with all Tracks and their Descriptions.

Both Functionalities would only be activated, when Track Descriptions are used and thus be backwards compatible.

## Context
After discussion this feature we would sponsor the development by implementing it into pretalx master and opening a PR for it.

**Comment by rixx** [comment]
This sounds like an excellent idea! Thank you for offering to sponsor/provide the feature – I'm looking forward to the PR. Let me know if you need anything while working on it 🙂
