### ISSUE TITLE
Feature Request: Let reviewers edit and see their own reviews

### ISSUE THREAD

**Issue by blinry** [pretalx/pretalx#923]
## Problem you are facing

We did reviewing for our event, and we configured it in a way that reviewers can't see other's reviews. It's also important to us to keep identities of submitters of rejected talks secret, so we don't have a phase where we reveal the reviews to everyone.

When reviewing, we found that reviewers can't edit their reviews, and needed to just "keep in mind" any changes they wanted to do.

When discussing the results together, we found that reviewers can't see their notes, which would've been useful.

## Possible Solution

Let reviewers to see and edit their own reviews. :)

**Comment by rixx** [comment]
This should absolutely possible, was possible in the past, and shouldn't be hard to fix. I'm confused that this isn't covered by our tests, tbh. Thank you for reporting this bug!
