### ISSUE TITLE
iCalendar export: uniqueness of UIDs for every VEVENT entry

### ISSUE THREAD

**Issue by Calendify** [pretalx/pretalx#925]
## Current Behavior

Talks with multiple appointments/slots get the same UID for each VEVENT entry. This violates the intent of [UID according to RFC5545](https://tools.ietf.org/html/rfc5545#section-3.8.4.7). For calendar applications it is important to have a unique ID for each VEVENT entry in order to match requests with later replies, modifications, or deletion requests.

See related issue: https://github.com/pretalx/pretalx/issues/762

## Expected Behavior

Each VEVENT entry should have its own UID.

## Steps to Reproduce

1. Call https://talks.oio.social/36c3-oio/schedule/export/schedule.ics
2. Search for UID pretalx-36c3-oio-FU3ZZE@talks.oio.social
3. Get two VEVENT entries with the same UID but different appointments.

## Context

Observed this issue when trying to import the schedule into https://calendify.com

**Comment by rixx** [comment]
Definitely a bug in line with #762, as you noted. Thank you for reporting!
