### ISSUE TITLE
Document placeholders for email templates

### ISSUE THREAD

**Issue by blinry** [pretalx/pretalx#926]
## Problem you are facing

We want to make rejection mails more personal, and add the submitters' names to them. I found [this file](https://github.com/pretalx/pretalx/blob/86b3ad07209dde213aa6b0faf3c2b5b08c06b630/src/pretalx/mail/context.py), that looks like there is `{speakers}`? Which is close to what we want. But I'm not sure whether this will work, and there doesn't seem a good way to test this (the "compose new mails" dialog explains that it doesn't allow templates).

## Possible Solution

Document all available placeholders right there on the email template page.

**Comment by blinry** [comment]
I just saw that you get a list of placeholders as soon as you start editing the templates. We didn't find it there because we drafted the template together in an external tool.

So I'd still suggest including that documentation at the top of the email template overview, with a qualification that they will only work for "default templates".

**Comment by rixx** [comment]
Good suggestion, thank you!
