### ISSUE TITLE
Logged in user is not redirected to the organization top page

### ISSUE THREAD

**Issue by CYBAI** [pretalx/pretalx#927]
## Current Behavior

While checking my proposal to COSCUP 2020, I opened 2 tabs in the login page.
I logged in successfully in one tab; then, I go back to another one and reload. It still showed me the login page.

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/6782666/82114562-757a6480-9798-11ea-9e13-0553e473240c.png">

## Expected Behavior

Because I've logged in, I will expect to be redirected to the top page of the organization (in my case, I would expect to be redirected to `https://pretalx.com/coscup2020/` instead of staying at `https://pretalx.com/coscup2020/login/` after logged in)

## Steps to Reproduce

1. Open 2 tabs in login page
2. Login successfully in A tab
3. Go back to B tab and then reload

## Context

N/A

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 76.0.1
* Operating System and version (desktop or mobile): macOS 10.14.6
* Link to your instance, if in production: https://pretalx.com/coscup2020/

**Comment by rixx** [comment]
Thank you for reporting this behaviour, that definitely looks like a bug.
