### ISSUE TITLE
Allow placing talks in the schedule with minute-accuracy

### ISSUE THREAD

**Issue by blinry** [pretalx/pretalx#933]
## Problem you are facing

We want to build a schedule that has 10-minute blocks, with 2 minutes in between every two. But pretalx only allows placing the talks in 5-minute intervals.

## Possible Solution

A similar UI as for changing breaks: when you click on a talk, open a window that asks for the precise start time.

**Comment by rixx** [comment]
I was never sure how to balance the need of most users for at-most 5-minute level accuracy with the freedom of selecting any starting time you want. I like your idea with a separate modal – That seems like a good UI choice!

The modal could also be used to display further information and go into detail about warnings, and offer a link to the talk and the speakers, so you won't accidentally open them anymore.

**Comment by blinry** [comment]
Yay, thanks so much for implementing this! <3
