### ISSUE TITLE
Order talks in the "Talks" tab of the schedule alphabetically or chronologically

### ISSUE THREAD

**Issue by blinry** [pretalx/pretalx#934]
## Problem you are facing

In the "Talks" tab of the schedule, the talks currently seem to be ordered by the timestamp of the submission. This seems confusing.

## Possible Solution

Order them alphabetically (this seems most consistent) or chronologically.

**Comment by rixx** [comment]
Oh, yes, that's definitely confusing. Thank you for bringing it up! I think alphabetical ordering would be good here.
