### ISSUE TITLE
API Docs are Incorrect

### ISSUE THREAD

**Issue by travigd** [pretalx/pretalx#936]
I'm just going to give an example of a talk from JuliaCon 2019.

The documented type for `submission_type` is `string, but it's (apparently?) an object with translations based on locales.
```
  "submission_type": {
    "en": "Lightning Talk"
  }
```

Duration is documented to be a number, but it's actually a time-string.
```
  "duration": "00:10"
```

Additionally, which fields are optional is not well documented (a few fields mention in the description that they're _Available if XYZ_, but it would be nice to include that in the type (e.g. `?string`) as well).

**Comment by rixx** [comment]
Thank you for the feedback! I adjusted the documentation so that multi-lingual strings are marked as such.

The incorrect duration field is a bug that I will also fix, to be included in the next release.
