### ISSUE TITLE
Link on CfP landing page

### ISSUE THREAD

**Issue by Rafiot** [pretalx/pretalx#938]
## Current Behavior

If I write `hack.lu` in the `Landing page text`, it is automatically converted to a link.

## Expected Behavior

No conversion to a link, unless we use the markdown syntax for a link

## Steps to Reproduce

1. Create an event
2. Enter `something.something` in the `Landing page text`
3. Save
4. It is link to `something.something` on the landing page.

The CfP page working as expected (no link)

**Comment by rixx** [comment]
First off, I cannot reproduce a linkification of `something.something`. As far as I can tell, only `a.b` patterns are linkified where `b` is a valid TLD. This is generally intended behaviour.

I'm afraid that's not something I can see a solution for – we use [linkify from the bleach library](https://bleach.readthedocs.io/en/latest/linkify.html), and it seems they have no way of restrict linkifying to patterns leading with `https?://` unless we build and maintain our own URL parsing regex, which does not seem like a good idea.

**Comment by Rafiot** [comment]
Oh yeah, sorry, only `something.validtld` is turned into a link.

In my case, I had `hack.lu` in the title, and the CSS turned the link to white on white, so it was quite confusing. 

```
# Hack.lu 2020 CfP
```
I just find it weird that it is turned into a link even if we aren't using the default markdown format `[this](https://pretalx.com)`

But yes, maintaining your own URL parsing library sounds like a terrible idea.
