### ISSUE TITLE
UserStep and ProfileStep are both named "Account"

### ISSUE THREAD

**Issue by Astranox** [pretalx/pretalx#944]
Profile step should probably be named "Profile", it is already available as that in the translations, but it seems not used yet.

https://github.com/pretalx/pretalx/blob/891a34474e2f2b263b533197eb53306cde11858f/src/pretalx/cfp/flow.py#L451

**Comment by rixx** [comment]
Brought to you by highly professional copy'n'paste development practices, I'm afraid. Thank you for reporting!
