### ISSUE TITLE
Talk submission type is not always localized in API

### ISSUE THREAD

**Issue by travigd** [pretalx/pretalx#945]
## Current Behavior
Currently, querying talks from the API results in either an object with text for various localizations **or** a plain string (in my experience, using JuliaCon 2019, only the `"talk"` type is a plain string, everything else is an object with an `"en"` key).

## Expected Behavior
The type of `submission_type` should be consistent.

## Steps to Reproduce
```bash
# Real, publicly available data
curl https://pretalx.com/api/events/juliacon2019/talks?offset=25
```

```js
{
    "count": 156,
    "next": "https://pretalx.com/api/events/juliacon2019/talks/?limit=25&offset=50",
    "previous": "https://pretalx.com/api/events/juliacon2019/talks/?limit=25",
    "results": [
        {
            "code": "YZPSDK",
            ...
            "submission_type": {
                "en": "Lightning Talk"
            },
            ...
        },
        ...
        {
            "code": "8AM9JC",
            ...
            "submission_type": "Talk",
            ...
        },
        ...
    ]
}
```

**Comment by rixx** [comment]
Thank you for bringing this up! This is definitely unexpected/buggy behaviour.

This is due to the behaviour of the library `django-i18nfield` that we use for internationalisation. We're looking to get a fix for this issue worked into the library, and will then pull it into pretalx.

**Comment by oxinabox** [comment]
@travigd this is one of the things that Pretalx.jl does; normalize that field.

**Comment by rixx** [comment]
@oxinabox If you encounter bugs in pretalx like that, it would be very helpful to the project if we knew about them, so that we can fix them – bug reports are welcome.

**Comment by oxinabox** [comment]
I didn't really click that it was a bug.
Thought it was a feature I was using wrong
