### ISSUE TITLE
Dead link in the paragraph "Allow override votes" under "Review settings" 

### ISSUE THREAD

**Issue by markmail** [pretalx/pretalx#951]
## Current Behavior
when clicked on link [in the team settings], a 404 not found is displayed

## Expected Behavior
when clicked on link [in the team settings], it should take user to team setting page

## Steps to Reproduce

1. Goto: Organiser backend > Settings > Review
2. Scroll down to "Allow override votes" and click <ins>in the team settings</ins> link
3.
4.

## Context
Go to team setting to make change suggested

## Your Environment

* Version used: The online version hosted by Pretalx

**Comment by rixx** [comment]
Oops, thank you for reporting!
