### ISSUE TITLE
Need help upgrading to current, possibly screwed-up Python environment

### ISSUE THREAD

**Issue by mraugh** [pretalx/pretalx#955]
I am finally having another try at upgrading from 0.9.0 to the latest Pretalx.  The immediately presenting problem is that pip3 fails to built wheel:
<quote>
Building wheels for collected packages: pretalx, rules, urlman
  Building wheel for pretalx (setup.py) ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vewfnjmr/pretalx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-9kmnykdh --python-tag cp36:
  running bdist_wheel
  running build
  ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
  ┃ ┏━━━━━━━━━━┓  pretalx v1.1.2                                         ┃
  ┃ ┃  ┌─·──╮  ┃  Settings:  /etc/pretalx/pretalx.cfg                    ┃
  ┃ ┃  │  O │  ┃  Database:  pretalx (mysql)                             ┃
  ┃ ┃  │ ┌──╯  ┃  Logging:   /var/pretalx/data/logs                      ┃
  ┃ ┃  └─┘     ┃  Root dir:  /tmp/pip-install-vewfnjmr/pretalx/pretalx   ┃
  ┃ ┗━━━┯━┯━━━━┛  Python:    /usr/bin/python3                            ┃
  ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vewfnjmr/pretalx/setup.py", line 155, in <module>
      cmdclass={"build": CustomBuild},
    File "/var/pretalx/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/var/pretalx/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-vewfnjmr/pretalx/setup.py", line 50, in run
      django.setup()
    File "/var/pretalx/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
      apps.populate(settings.INSTALLED_APPS)
    File "/var/pretalx/.local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
      app_config.import_models()
    File "/var/pretalx/.local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
      self.models_module = import_module(models_module_name)
    File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/tmp/pip-install-vewfnjmr/pretalx/pretalx/common/models/__init__.py", line 1, in <module>
      from .log import ActivityLog
    File "/tmp/pip-install-vewfnjmr/pretalx/pretalx/common/models/log.py", line 5, in <module>
      from django_scopes import ScopedManager
  ModuleNotFoundError: No module named 'django_scopes'
  
  ----------------------------------------
  Failed building wheel for pretalx
  Running setup.py clean for pretalx
  Building wheel for rules (setup.py) ... done
  Stored in directory: /var/pretalx/.cache/pip/wheels/c5/9f/fc/cbf9eff602ec470e1443d68957f9488fa30e30aa5c1a12736b
  Building wheel for urlman (setup.py) ... done
  Stored in directory: /var/pretalx/.cache/pip/wheels/c5/00/9b/83e7d525c82a024d0d44cc6a6953bdac6310e59780b372f3cb
Successfully built rules urlman
Failed to build pretalx
<end quote>

To get there I had to use python3 -m pip install --user -U pretalx, because just "pip3 install --user -U pretalx" only got me:
pretalx@pretalx:~$ pip3 install --user -U pretalx
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

I assume that my Python environment is wrong and that's why the wheel build is failing, but I don't know enough about Python to recognize what's wrong and fix it.  I tried this some time ago and gave it up, but now my event is getting ready to ramp up so I have to deal with it.  I would prefer not to throw away my existing data if I don't have to.

Help?

<MR>

**Comment by rixx** [comment]
Have you made sure that you're using the exact same Python environment that pretalx is currently installed in (same virtualenv etc), and that your Python version matches the pretalx requirements of 3.6+?

**Comment by mraugh** [comment]
Hmm.   It's 3.6.9, which meets the floor for Pretalx.  I don't know if that's the same version that was there last January but it's Ubuntu 18.04, so it's probably not a major revision off.  Nobody has touched the server, so only the normal updates in Ubuntu would have been applied.

**Comment by rixx** [comment]
This is extremely confusing, since the error message implies that `django-scopes` is not getting installed. If you have not used any virtual environment before, I'm not sure what's going on. You could install django-scopes manually to make sure it exists, of course. The fact that your pip installation fails on its own points to a deeper problem, though, and I'm not sure where it came from. Maybe a (very) outdated pip?

**Comment by mraugh** [comment]
Hmm ... pip is version 19.0.1.  
Running 'python3 -m pip install django-scopes' get me: 
  Requirement already satisfied: django-scopes in ./.local/lib/python3.6/site-packages (1.2.0)
  You are using pip version 19.0.1, however version 20.2b1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.

So I'm a little behind on pip, but not massively.  And django-scopes is installed, at least for user pretalx not using any virtual environments.  But that fact that I have to call pip in that longer way kinda suggests something is broken at the system level, doesn't it?

**Comment by rixx** [comment]
It looks that way, yes. Is there anything keeping you from re-installing completely, possibly directly choosing an installation either as a `--user` or in a virtualenv? That would seem to me the best course of action.

**Comment by mraugh** [comment]
Only the desire to keep last year's database.  Which, frankly, is less of a deterrent by the day.

**Comment by rixx** [comment]
The database should have nothing to do with this at all. Depending on your setup, the database will either be a file (if you use SQLite) or a MySQl or PostgreSQL database, neither have anything to do with the Python environment. You can back them up individually, and any new or updated pretalx instance can be pointed at this database without problems.

If you want to make very sure, take a look at the [backup section of the maintenance documentation](https://docs.pretalx.org/administrator/maintenance.html#backups) which also details which parts of the filesystem you should update.
