### ISSUE TITLE
Markdown preview is blank on CFP submission screen in Firefox

### ISSUE THREAD

**Issue by excitedleigh** [pretalx/pretalx#957]
## Current Behavior

When I type content into the Markdown fields in a CFP and switch to the Preview tab, the content is blank.

## Expected Behavior

The Preview tab contains a rendered Markdown copy of the content I've entered.

## Steps to Reproduce

1. Go to the PyConline AU CFP
2. Start a new submission
3. Type text in the Description field
4. Switch to the Preview tab

## Context

This issue was reported to me by a prospective speaker, but I've also reproduced it on my own machine.

They were (understandably!) worried that if the preview tab being blank might mean their submission would be blank on the server once it was saved.

In the Console, I see five Content Security Policy violations (the bottom-most one is repeated twice), as well as a SyntaxError, which could be related.

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content-hooks-frames.js:59:42
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). injectGlobalHook.js:1:1760
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). pagewrap.bundle.js:1:1151
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
SyntaxError: nothing to repeat output.becc30abae0e.js:1:1
```

## Your Environment

* Version used: pretalx.com hosted version
* Environment name and version (e.g. Chrome 39, python 3.5): Firefox 77.0.1 (64-bit)
* Operating System and version (desktop or mobile): macOS Catalina 10.15.5 (19F101)
* Link to your instance, if in production: https://pretalx.com/pycon-au-2020/

In Google Chrome version 83.0.4103.116 (Official Build) (64-bit), it works as expected and the above messages do not appear in the Console.

**Comment by rixx** [comment]
Oh no. This problem does *not* occur in development mode, but it does occur in production mode with just `runserver` in local development.

So it is probably some sort of compression relic, I think?

**Comment by rixx** [comment]
Looks like it's working again now, and the fix is deployed to pretalx.com, too. Apologies for the confusion caused.

**Comment by excitedleigh** [comment]
Thanks Tobi!
