### ISSUE TITLE
iCal not generated with break & general error handling

### ISSUE THREAD

**Issue by martinheidegger** [pretalx/pretalx#961]
## Current Behavior

When the schedule contains a break the iCal files are not generated by pretalx.

## Expected Behavior

Generate the .ical link.

Extension: Show that an error happened.

## Steps to Reproduce

1. Create schedule 
2. Add a break
3. Click on iCal link
4. 404 error

## Context

_(Note: I am used to write Python which is why I hesitated to turn this into a Pull Request)_

I noticed the error when trying to test the iCal integration for a conference site and only a 404 error occurred.
The error lead me to look into issues but I havn't found any similar problems.

I noticed that the docker version I am running is behind this repo (1.1.2). so the code in question is quite different.

To fix it I first tried to figure out what error happened: https://github.com/martinheidegger/pretalx/commit/702fbfc61723e73175272e1bb9f2143c1cfd3252 - this code only shows a 404 error message if indeed no exporter happens and else shows a 500 error with the error written to the log. _(as I would have expected it to happen)_

Once I got the error message, I noticed that the calender entries submission may be [`blank`](https://github.com/pretalx/pretalx/blob/d812e665c1c5ce29df3eafc1985af08e4d986fef/src/pretalx/schedule/models/slot.py#L40) thus causing an error when trying to retreive the timezone on [`L242`](https://github.com/pretalx/pretalx/blob/d812e665c1c5ce29df3eafc1985af08e4d986fef/src/pretalx/schedule/models/slot.py#L242)

I fixed this for me by adding a None check: https://github.com/martinheidegger/pretalx/commit/702fbfc61723e73175272e1bb9f2143c1cfd3252

## Your Environment

Running the latest pretalx docker on a ubuntu server.

**Comment by rixx** [comment]
Thank you for both the report and the fix! I opened a Pull Request with your changes in #962 – with your permission, I'd like to merge them as-is (I'll just add changelog notes and the like).

**Comment by martinheidegger** [comment]
@rixx If you are confident that my fix is proper then gladly! _(Python noob 😅 )_ Thank you for the quick response.
