### ISSUE TITLE
New Plugin Hook: public event data update

### ISSUE THREAD

**Issue by martinheidegger** [pretalx/pretalx#964]
## Problem you are facing

I would like to trigger a static site generation based on pretalx where the site should be updated when data that is accessible through the API changes. 

## Possible Solution

Add a hook for plugins to pretalx that gets triggered when one (or any) public data changes.

**Comment by rixx** [comment]
Restricting this to public data would be somewhat hard, but adding a hook on any change of the events settings page would be pretty easy and reasonable, I think. Happy to take/guide PRs.

**Comment by rixx** [comment]
Tentatively closing via c0c2465b – introducing a plugin hook that fires when a new schedule is released.

**Comment by wslyvh** [comment]
I have a similar situation as OP and looking to update a static generated site if the Pretalx schedule changes.
And trying to understand the solution a little bit better..

It seems like the linked change from @rixx just adds the signal for when the schedule gets updated.
I'd still need to write a plugin to actually trigger, correct?

**Comment by rixx** [comment]
Yes, we currently don't have generic webhooks in pretalx, as those can be somewhat painful to do well (i.e. with authentication, checksums and so on). It's planned in the future, and I'd be happy to collaborate on the feature or merge a PR, but until then, a separate plugin is the way to go.
