### ISSUE TITLE
Emails with multibyte characters

### ISSUE THREAD

**Issue by martinheidegger** [pretalx/pretalx#965]
## Current Behavior

Entering multi-byte characters in Email Text or Subject field will result in 500 Error message.

```
  File "/pretalx/src/pretalx/common/views.py", line 42, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/pretalx/src/pretalx/orga/views/mails.py", line 193, in form_valid
    result = super().form_valid(form)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/pretalx/src/pretalx/orga/forms/mails.py", line 65, in save
    obj = super().save(*args, **kwargs)
...
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE2......' for column 'text' at row 1")
```

## Expected Behavior

Unicode characters should just work.

## Steps to Reproduce

1. Create an email
2. Enter text that includes a unicode character like "😫" or "↓" in the text or subject field
3. Save

## Context

This is crucial for east-asian language support, but also for supporting millenials as they love emoji: 🌈 🦄 

## Your Environment

pretalx: 1.1.2
mysql: 5

**Comment by rixx** [comment]
Can you enter emoji in any other field, like talk descriptions or the event title? If not, I would assume that you ahve not configured mysql to deal with utf8 correctly, which is something of a pain. pretalx itself leaves all of the encoding to the underlying database.

Our docs mention

```mysql > CREATE DATABASE pretalx DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci```

Is this how you created the database?

**Comment by martinheidegger** [comment]
I went back and tested many fields. Most worked (including event description and name). But I noticed that its also not possible to enter multibyte strings in the speaker name and biography.

For the database I used the pretalx docker database setup as-is.

**Comment by rixx** [comment]
Sorry, I can't help you with that. I have confirmed that this works both in our development and production setup. Please note that the pretalx docker setup is not officially supported and provided as a community effort.

**Comment by martinheidegger** [comment]
Using a mysql client I noticed that the collation of all tables is cp1252 western european, changing the collation will fix this issue, I opened an issue in pretalx-docker but I am not sure how/why this happens.
