### ISSUE TITLE
List Team members in speakers list if they have presentations.

### ISSUE THREAD

**Issue by martinheidegger** [pretalx/pretalx#966]
## Current Behavior

The Speakers list in the `orga` section doesn't show team members of an event that have submitted a schedule.

The schedule can be reached by **guessing(!)** the team members id and adding it in the URL like: `/orga/event/my-event/speakers/1/`.

## Expected Behavior

The Speakers lists shows also team members and maybe adds a `*`-mark to distinguish the speaker as a team-member when displaying.

## Steps to Reproduce

1. Fill out the CfP as owner of the event.
2. Go to speakers list.
3. See that you are not listed as speaker

## Context

Most of events that we organize are events where the organizers have one or more talks during the event as well - this is because we are bigger groups and while all get access to the `orga` interface, not all need to know how to use it.

## Your Environment

pretalx: 1.1.2

**Comment by rixx** [comment]
I can't seem to reproduce the issue – either it is solved in the development version or there is something else going on. Reproduction [here](https://share.cutebit.de/pretalx-issue-966.mkv).

Context: We've run plenty of events where team members were also speakers, to the degree of having extra precaution to keep speakers from seeing or writing reviews of their own talks even if they are reviewers. I'm not sure what's going on here, but this isn't it.
