### ISSUE TITLE
Confirmation dialog when deleting emails

### ISSUE THREAD

**Issue by martinheidegger** [pretalx/pretalx#967]
## Problem you are facing

I am not sure which email I clicked on deleting. It just happened.

## Possible Solution

- Add a dialog showing what email is going to be deleted and then press okay. - Give warning that this process is irreversible
- Add undo option somehow
- Add "Trash" that contains list of deleted emails.

## Context

Through automation we generated a bunch of emails double and when  deleting one of the extra mails I wasn't sure if I clicked the right one, I was rather surprised when it was just gone without a dialog.

Further reading:
[article on confirmation design](https://medium.com/nextux/designing-confirmation-278d159723e)
[undo versus confirm](https://ux.stackexchange.com/questions/71960/deletion-confirm-or-undo-which-is-the-better-option-and-why)

**Comment by rixx** [comment]
I'll happily merge a PR providing undo functionality for pretalx, but I'll warn any contributor taking this up that generic undo capability is a giant can of worms and that I'm sceptical that we'll manage to introduce this.

We already have confirmation dialogues for submission state changes and email bulk actions, so adding confirmation pages for individual email actions (as much as I would dislike it from a flow perspective) would be easier and I'd also be willing to review a PR introducing this functionality.
