### ISSUE TITLE
Error on /ptt/login/

### ISSUE THREAD

**Issue by ajuvo** [pretalx/pretalx#971]
## Current Behavior

error 500
## Expected Behavior

login
## Steps to Reproduce

1. try to login with existing credentials 
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, python 3.5):
* Operating System and version (desktop or mobile):
* Link to your instance, if in production:

**Comment by rixx** [comment]
Sorry, this is not a place to register problems with specific instances. In pretalx generally, logging in works – for broken instances, please talk to the specific instance administrators instead of the bug tracker.
