### ISSUE TITLE
Calendar links are hidden behind header on agenda

### ISSUE THREAD

**Issue by oxinabox** [pretalx/pretalx#973]
## Current Behavior

![image](https://user-images.githubusercontent.com/5127634/88235198-44c01b00-cc72-11ea-9454-7c70857611a2.png)

## Expected Behavior

<img width="365" alt="image" src="https://user-images.githubusercontent.com/5127634/88235327-8c46a700-cc72-11ea-8599-1a40122c79a9.png">

## Steps to Reproduce

1. Go to a user facing schedule page e.g. https://pretalx.com/juliacon2020/schedule/
2. Click the `</>` links button
3. Notice how it is hidden hehind the day/date

## Context

Someone wanted the `.ical` caledar link.
we knew it existed but no one could find it.
It was hidden behind wednesday.

I think it just needs the CSS z-index set to a large number.
That is how I made the expected screenshot work

## Your Environment

* Version used:
* Environment name and version: Firefox 78
* Operating System and version (desktop or mobile): Mac OS X 10.15.5
* Link to your instance, if in production: pretalx.com/juliacon2020

**Comment by rixx** [comment]
Closed in 848ddbcf.
