### ISSUE TITLE
Tag submissions for ad hoc filtering

### ISSUE THREAD

**Issue by jpwarren** [pretalx/pretalx#976]
## Problem you are facing

I wanted to flag some submissions to find them later in a way that doesn't seem available in current interface.

## Possible Solution

#882 might provide a solution, but seems a heavyweight way to achieve it, and (I think?) would limit what can be searched to the existing database schema.

Being able to add arbitrary tags to talk submissions (and other things?) might provide a flexible way for people to find them later without having to write complex filter queries, adaptable to individual user desires that may not matter to other users.

Tags are a well-known mechanism that people are likely to be already familiar with, which would make it easier for new users, and probably also more advanced users who don't need to context switch as hard. "Which filter syntax/DSL does this system use?" is… tiring.

I suspect that tags could also provide a useful "does this need to be a dedicated feature?" clearinghouse. If people use tags a lot for a specific purpose, that specific purpose could become a dedicated field item now that it's proven to be a thing people want.

## Context

As a track lead, I was reviewing talk submissions to the CFP during the anonymous review period and saw talks that were not for my track but that I thought might be good candidates. I made a review comment saying as much, but then couldn't search for my track name in the text of my review comments to find them again. I needed admin intervention to do a database query and extract for me.

Being able to flag talks by adding an arbitrary tag that I could then filter/search on would have enabled me to find this list of talks more easily later on. I suspect there are other use-cases that tags might also be a solution for.

I suspect per-user tags and global tags might be needed, as some people might want to use tags for reasons that shouldn't leak to be seen by everyone else. I can foresee RBAC challenges, so perhaps better to start with per-user tags and then add global tags and/or permissioning after that, in the interests of privacy/safety.

**Comment by Delawen** [comment]
Also, this could be viewed as assigning keywords to talks so reviewers can find them easier. When having huge amounts of submissions and reviewers specialized on topics, having a search by tag/keyword/topic is extremely useful.

**Comment by rixx** [comment]
Agreed: some sort of tagging would be nice to ahve, but: This comment shows pretty much the problem with the idea of adding tags. "tags" are very versatile and people have a wide range of conflicting expectations – eg, a reviewer tagging a talk for grouping within the talk selection would not expect their tag to be public.

(It looks like I will add a tagging feature to pretalx this year, I just want to explain why a) it took this long and b) it's not as trivial as it looks and I'm very cautious about it.)

**Comment by rixx** [comment]
There is now rudimentary tagging in pretalx, including these capabilities:

- Organisers and reviewers can create (update, delete) tags
- They can add and remove these predefined tags to proposals
- They can filter proposals by tags

Notably, there is a long list of improvements, to be added soon(ish?), documented here:

- A better tagging interface for organisers and reviewers (currently you just toggle checkboxes, that's obviously not a permanent solution)
- Allowing the creation of new tags for organisers and reviewers without going to a new page
