### ISSUE TITLE
lengthy speaker biographies can dominate talk pages

### ISSUE THREAD

**Issue by luto** [pretalx/pretalx#99]
![image](https://user-images.githubusercontent.com/2158203/29829903-edb660ae-8ce0-11e7-97b3-23f76fd5ef79.png)

The only place the speakers bio is currently shown is the talk page. For some longer biographies, the text can dominate the speakers box, as shown above. Information like additional speakers or other talks (as part of #53) will be pushed to the very bottom of the page, sometimes even out of the view.

We want to show the full bio for each speaker somewhere, as it contains useful and interesting background information. But we can't, in my opinion, give it as much space as it currently has. A couple of suggestions:

* limit the bio to ~80 words, add an ellipses after that and expand it on click
* show the bio as part of a popup/modal dialog (yuck?)
* do not show the bio at all on talk pages, add a dedicated speakers page to give that information the space it needs (see #76)

What do you think?

**Comment by rixx** [comment]
You'd really like to see that speaker page, wouldn't you? XD

I've been considering – a speaker's URL should be as stable as possible (which means we can't really use their name) without giving away their login credentials … would a unique code per speaker (in the same format as the submission codes) be a horrible idea? It's not very readable, URL wise …

For now, a simple shortening seems adequate, but the talk page isn't going to get shorter – sooner or later we need to allow speakers to add links or even files, provide a feedback interface (or at least link) … So decluttering probably needs to happen.
